[quote.epigraph, , Acts 18:24]
____
...an eloquent man and mighty in the Scriptures.
____

[quote.epigraph, , Jer. 15:19]
____
Therefore thus says the LORD: "`If you return, then I will bring you back;
you shall stand before Me; If you take out the precious from the vile,
you shall be as My mouth.
____

== The Life of John Crook

I have often been pressed in spirit to write this following history of my life,
so that the world, as well as my friends and acquaintances,
might know the Lord`'s dealings with me from my tender years,
both for the comforting of the saints,
and the information and instruction of all into whose hands this account may come.
But above all, my desire is that the God of my life be feared and exalted in the hearts,
and by the holy lives, of all the sons and daughters of men forever.

I was born in the north country,
of parents that were for the common religion of the times in which they lived.
I was brought up with them, and instructed in their way,
until about ten or eleven years of age.
Within this time, I had many exercises in my inward man,
and often prayed in hidden places as words sprang in my mind,
and as I learned prayers without a book.
Yet many strong combats remained within me, which continued haunting me for many months.
One time, above all the rest, I was almost overcome,
and I nearly consented to the devil urging me (by a mighty,
violent striving) to give up all my resistance and withstanding of him.
But on a sudden, there arose in me a power and life that opposed and denied the enemy,
making my spirit say within me, with much boldness and courage, "`I will not serve you,
O Satan, but I will serve the Lord God of heaven and earth, whatever I suffer,
or whatever becomes of me.`"
This, I do remember, my tongue uttered pretty loudly,
and with much vehemence and resolution,
in full consent to what was spoken inwardly in my heart,
and in opposition and contradiction to the evil spirit that
strongly tempted me to give up myself to wickedness.
After this,
I was frightened when I came to consider these two opposite strivings in my spirit,
what they could mean, for I had never heard anyone speak of such things.
And I was especially amazed when I considered what that voice
should be which spoke with such an authority in me,
and commanded my tongue to speak so boldly in compliance with it,
and against the other which had almost forced me
to consent to its evil motions and suggestions.
But by the ease and relief I felt in my inward parts,
I concluded it was the Lord who had helped me in so great a trial.

I remember after this, when I was tempted or troubled in my mind,
I would go into some corner or secret place and pray unto God.
And when I had committed sin and evil, and was troubled afterwards,
I would then pray to God for His strength against them.
And I found that when I was alone, I was sure to hear from Him of all my doings,
for my sins would come fresh in my remembrance,
and be so set before me that I could not get them out of my sight.
Then I would endeavor to get into some private place to pray and weep,
and would promise and covenant in secret with God that if He would forgive these,
and help me for the time to come, I would never do the like again.
But despite all this, evils prevailed in me, and I could not keep my promises with God.
So trouble came upon my spirit, and I often mourned and went about heavily.
I took no delight in play or in the pastimes which I saw other children enjoy,
which made me often conclude in my mind that they were in a better condition than I,
and that surely God was angry with me, which made Him so correct me.
For I saw that other children were merry and cheerful, but I had no peace.
Yet sometimes I found ease, and was cheerful,
but it seldom held long without some intermixture of trouble.
I also had many openings in my mind about heaven and hell, and wicked men and good men,
which did sometimes much amaze me.
And I saw that many of the priests were profane in those parts,
giving themselves up to various kinds of wickedness.

When about ten or eleven years of age I went to London,
and there attended several schools until I was about seventeen years of age,
during which time I had much trouble and exercise in my mind.
But though I lived in a wicked family,
and among those who scoffed at all strictness in religion,
yet I would often get into some hidden place and pray
or weep bitterly from the sense of my own sins,
and would often reprove my schoolmates and companions for their wickedness.
I often walked alone by myself in some secret place
when all the rest were busy at play and pastimes.
In this way I passed away my youthful days,
in reading and in frequent prayers when trouble was upon me,
from which I was seldom free whole weeks, either in the night or in the day.
But all this time I did not much listen to sermons,
being little acquainted with any who frequented such exercises,
until I went to be an apprentice, about the seventeenth year of my age.

About this time I was placed in a parish in London
where there was a minister who was called a Puritan.
Here I became acquainted with a group of young people that frequented
sermons and lectures as often as we had any liberty from our apprenticeship.
Yet as I grew in knowledge and understanding of the things of God,
still trouble grew upon me more and more.
I applied myself to reading the bible and other good books, and prayed often,
insomuch that even the family where I was then an apprentice took much notice of it,
and would sometimes stand in secret places to hear me pray, though I then knew it not.

But I remember when I was most fervent in my devotion,
something in me would still be pulling me back,
so that I should not yet wholly leave off the evils I knew myself to be guilty of.
I would gladly have had them pardoned and forgiven, and yet I desired to continue in them.
I found such a thing within myself, opposing my earnest cries and petitions,
desiring both to have peace with God,
and yet to continue in those things which I prayed against.
This at last made me conclude that I was but a hypocrite,
and did not belong to the election of grace,
but instead was to become an eminent spectacle of God`'s displeasure.
And I further concluded that that which opposed my earnest cries to God was the devil,
and that I was therefore possessed with the devil.
So, as often as I had occasion,
I would inquire of other professing Christians how it was with them,
and what they understood of the condition of
those who were possessed with unclean spirits.
But all that I could get from any could not remove the
idea from my mind that I was possessed with the devil.
Indeed, I thought I felt in myself something sensibly and manifestly
opposing the good motions and desires that were in me,
as if two had been striving in me for victory.
And when I was so tired out with resisting and fighting in myself,
I could get no relief or sensible ease except by
going to prayer--either secretly within myself,
or down upon my knees in some secret place.

Often times, when I was at prayer,
I was so possessed with fear that I stopped and looked behind me,
lest the devil stood there ready to take me as soon as I rose up.
And then I was troubled for giving way so far to my fears as to look behind me.
But for all of this, I dared not leave off praying.
And what troubled me even more was that those who heard me admired my gift in prayer,
and believed me to be a child of God,
when I concluded nothing less of myself than that I should deceive them,
and cause God`'s name to be blasphemed by my falling away at last.
For I thought it impossible for me to continue long in that condition
before I should fall and be made an example to all hypocrites.

Thus I continued professing, praying, hearing, and reading,
and yet I could not perceive any true improvement in myself;
but still the same youthful vanities drew my mind away whenever opportunities offered.
I never gave myself to outward, gross profaneness,
but only to idle talk and vain company, mis-spending my time,
taking pride in my apparel and such things,
for all which I was condemned--as also for wearing long hair,
and spending my money in vain,
which would have been better employed if used to buy good books, or to give to the poor.
All that I did was condemned, and myself for doing it,
yet I dared not leave off my religious duties,
for then I thought the devil would prevail over me to make me destroy myself.
Oh, I was afraid to see a knife if I was alone,
or to have any in the room all night where I lay.

Thus I continued,
running to hear lectures whenever I had any time allowed me by my master,
which I endeavored to get by doubling my diligence in the day time,
and abstaining from sleep in the night time.
I sought out private meetings and lectures, going to hear any eminent speaker I heard of,
which, by this time,
I had obtained a great knowledge of through much acquaintance with hearers of sermons,
and frequenters of private fasts and meetings.

Sometimes, when hearing sermons,
I had much ado to forbear crying out in the midst of the assembly,
"`I am damned! I am damned!`" which I never did,
but would go away full of horror and misery in my mind.
The ministers in those days commonly preached how a man
might know himself to be an elect child of God,
by certain marks and signs if it were so, and other signs if it were not so.
This, at times, made me conclude I had saving grace,
and at other times to conclude I was but a hypocrite.
Thus I was tossed up and down, from hope to despair;
and from a sign of grace in me one time, to a sign of a hypocrite and a reprobate again.
I could not tell what to do with myself, or whether it was best to go to church,
or to stay at home,
for I found no rest or lasting peace by all my hearing and running here and there.
And I felt no freedom to go to any of these ministers
in private to acquaint them with my condition,
partly because I thought they could not help me, and partly for fear,
lest they should discourage me and tell me I was a hypocrite,
and then Satan should prevail to force me to destroy myself.
Indeed, I was afraid of anything that might confirm my own thoughts of my miserable state.
For my own thoughts were bad enough,
but I was exceedingly afraid to have my thoughts seconded by the judgment of any other.
So I never went to any ministers to acquaint them with my condition,
but rather bore it secretly in my own bosom, few knowing how it was with me.

Then one day when I was an apprentice, being full of trouble,
I resolved on a first-day afternoon (called then the Lord`'s day) to go whatever way
I should feel moved or inclined in my spirit--whether it was up street,
or down street, east or west, north or south,
without any predetermination or forethought, but only as the staff should fall,
so to speak, or as I should be led.
Accordingly I walked,
as I was led by something within me which I believed in and followed,
until it brought me into a parish church (so called).
I went in and sat down, and within a small space of time,
a young man went up into the pulpit and preached out of this text, Isaiah 50:10;
"`He that walks in darkness, and has no light, let him trust in the name of the Lord,
and stay upon His God.`"
Upon this text he had preached before,
and purposed at this time to show who that man was that
feared the Lord and yet walked in darkness.
This he performed as if he had known my condition and spoke to me in particular,
which did greatly relieve me, and at that time greatly comforted me,
having been so providentially brought there, where I never was before.

I went away much gladdened, and continued so for some time.
But trouble soon came upon me again, through some negligence and coldness,
which brought about distrust and unbelief.
So the old enemy, the tempter, got in again, and tore me worse than before in my mind,
so that I questioned all that had ever been given to refresh me as being but a delusion,
with no truth in it.
Then I began to be full of horror, so that my sleep was much taken from me,
and anguish and intolerable tribulation dwelt in my flesh.
And when I heard any of the lowest, poor people crying out in the streets of London,
I even wished that I were in their condition,
for I thought every man or woman was in a better condition than myself.
Truly, I thought myself the only miserable man in the world.
Had I been made the most contemptible creature in the whole creation,
I would have been happy in comparison to my most intolerable misery.
And all of this was heightened by Francis Spira`'s book,^
footnote:[Francis Spira (1502-1548) was an
Italian lawyer who converted to Protestantism,
but under pressure from the Catholic Inquisition denied
his own convictions and publicly recanted his faith.
The book referenced by Crook is called _A Relation of the Fearful Estate of Francis Spira,_
which relates the terror that immediately seized Spira upon his recantation,
and the subsequent guilt, horror, and mental anguish that soon ended his life.]
which came into my hand, but when I had read but a little,
I cast it from me and dared not look on it anymore,
for I thought it so resembled my present condition.

In this extreme misery I continued, keeping it to myself and mourning in secret,
until one morning, as I was sitting alone, lamenting my present state,
on a sudden there sprang in me a voice saying, "`Fear not,
O tossed as with a tempest and not comforted; I will help you,
and although I have hidden My face from you for a moment,
yet with everlasting lovingkindness I will visit you, and you shall be Mine.
Fear not, for I am pacified towards you, and will never leave you nor forsake you,
says the Lord, the mighty God.`"

Then, suddenly, all was hushed and quieted within me,
so that I wondered what had become of the many vexations,
tormenting fears and thoughts that just before attended me.
There was such a calm and stillness in my mind for a space of time,
that it came to my mind how there was silence in heaven for half an hour.
I was filled with peace and joy, like one entirely overcome,
and there shone such an inward light within me,
that for the space of seven or eight day`'s time, I walked as one taken from the earth.
I was so caught up in my mind, that it was as if I walked above the world,
not taking notice (as it seemed to me) of any persons
or things as I walked up and down the London streets,
being so gathered up in the marvelous light of the Lord and
filled with a joyful dominion over all things in this world.
In this time,
I saw plainly (and to my great comfort and satisfaction) that
whatever the Lord would communicate and make known of Himself,
and of the mysteries of His kingdom, He would do it in a way of purity and holiness.
Yes, I saw then such a brightness in holiness, and such a beauty in an upright and pure,
righteous life, and in a close, circumspect walking with God in holy conduct.
Although I had before obeyed to the utmost that I could,
yet I could not thereby find peace,
nor find and feel any of the acceptance and
justification before God that I did at this time,
when it sprang up freely in me.
So I saw that all true religion lay in this communion,
and that all profession of religion without this was as nothing in comparison.
And I well remember,
that while I abode and walked in that light and glory
which shone so clearly in my mind and spirit,
there was not a wrong thought that appeared or stirred within me
which did not quickly vanish upon being given no entertainment.
Indeed, my whole mind and soul was so taken up with, and swallowed up in,
that glorious light and satisfactory presence of the Lord thus manifested in me.

During this time, when I was filled with joy and peace,
I found I could not perform religious duties as formally as I used to do,
but instead did them with much more life and zeal, faith and confidence than before,
which caused many of my acquaintance to admire my gift in prayer,
and upon occasions to set me upon that duty.
But after this time, I perceived an abatement of the glory,
and I began to read and perform duties much as I had done before.
About this time, I began to follow some ministers that came out of Holland,
and some others who were for separation from the parish assemblies; and indeed,
I disliked those mixed assemblies, and much thirsted after, and longed for,
a pure communion with those who were most spiritual.
Having seen something of the beauty of holiness,
I longed to walk with those who knew a fellowship with God in holiness,
and who were watchful one over another for good, and for the increase of a holy life.

I walked with a company of young men who met
together as often as our occasions would permit,
and prayed and conferred together about the things of God.
And I remember, when several would be speaking out of the Scriptures,
by way of exposition, I had very little to say,
not having then much acquaintance with the Bible,
for I was brought up in such families and under such
tutors as did not much regard the Scriptures.
But I would speak forth my own experiences, and I delighted in, and loved most,
those who could speak from experience.
Yes, my heart was most warmed and enlivened by those
experiential discourses and conversations,
so that those who were most spiritual delighted to be with me, and I with them.
They would often tell me that I spoke from experience,
and that I could speak to many conditions and things as though
I had had a volume of all subjects written within me,
while most gathered their discourses from the Scriptures outside of them.

But in two or three years time, I began to gather Scriptures into my mind and memory,
both from hearing others and from my own studies,
which occasioned me to dwell more without, and less within.
So by degrees,
the knowledge in my natural understanding and judgment began
to outgrow and overhang the sense of my inward experiences.
At last,
having little more than the remembrance (now a great way off)
of those things which once were alive and fresh and growing in
me as though it had been spring time in my heart and mind,
my inward parts became like a winter.
The inward life retired out of sight, as though into a hidden root,
and then many questions about the way of worship,
and the ordinances of the New Testament, began to arise in my mind.

Since the Lord had done so much for me,
I judged I could not help but be guilty of unthankfulness
before Him if I did not now seek out the purest way of worship.
So, after I had gone among several sorts of professing Christians of diverse judgments,
seeking with whom my spirit could sit down and unite,
at last I met with a group of Independents with whom I joined in communion.
We had many refreshing times together, so long as we were kept watchful and tender,
with our minds inwardly retired, and our words few and savory.
And we were preserved in this spirit by communicating our experiences to each other,
as to whether our hearts had been kept towards the Lord all the week,
and what had passed between God and our souls from the beginning of the week to the end.

This continued some years, until it grew formal.
Then we began to consider our state,
whether we were in the right order of the gospel according to the primitive pattern,
and in the proper administration of baptism, etc.
And so we began to be divided and scattered in our minds about these things,
and many questions arose about various subjects which were not at all questioned before,
all of which tended to much uncertainty and instability.
We then began not only to be careless about our meetings,
but also confused in our preaching and services when assembled.
So at last we did not meet at all, but by degrees grew estranged from one another,
and into carelessness, con­sulting principles of liberty and ease to the flesh,
and from there fell to encouraging and justifying our
present carelessness and coldness in religion.
Nevertheless,
I was not so given over to ease that I was
wholly without checks and reproofs for so doing;
and oftentimes the inward distress and trouble of my
spirit roused me up again to religious duties,
such as prayer and reading.

When I was oppressed in my judgment and natural understanding about doctrines and tenets,
(which would present themselves to me in my weak and shattered state),
I then found my mind drawn into carelessness about all religion,
and into a slighting of my former strictness against sin and evil.
I saw how many doctrines and principles would have forced me
into a belief that my former apprehensions about wickedness,
and the great danger thereof, arose from mere emotion or tradition,
and not from grounded reason or true judgment.
I was often exercised day and night, and tempted (both by inward suggestions,
and outward allurements) to embrace such principles.
And sometimes others, who had been as religious as myself,
and no less acquainted with inward experiences of like kind,
sought to draw me off from the sense and deep impression of truth which remained
upon my spirit after the great troubles and consolations I had tasted.
But the sensible remembrance of former days did stick upon me,
and kept me from the principles of Ranterism^
footnote:[Ranters were a somewhat odd,
non-conformist group that sprung up in the mid 1600s. They
denied the authority of both the church and the Scripture,
and instead promoted a sort of pantheism, insisting that God was in every creature,
and that sin was nothing more than the product of human imagination.
Ranters would often interrupt established religious gatherings with shouting (ranting),
singing, playing instruments, or making other loud noises.]
and Atheism which were prevalent and much stirring in those times.

Through faith in what I had tasted, I was supported under many a bitter combat,
and under deep waves and billows,
and was made to conclude in my heart and mind that
"`the righteous was more excellent than his neighbor,`" (Prov. 12:26)
and that there was a far better condition to be known and enjoyed in this
world by walking with God in holiness and purity,
than by all licentious and voluptuous living,
or covetous gathering of riches together to obtain a name in the earth.
This I knew from the sweetness I myself had once enjoyed therein,
and it continued underneath all the reasonings and dry observations I could make,
and lay more deeply lodged in my inward part
than all the floating apprehensions in my mind.
So I found there was a continued cry and sound in my
inward ears which called for watchfulness over my ways,
and obedience unto what was made manifest to be the will of God in my conscience,
and this I saw was more likely to afford me rest and peace, than all my notions,
observations, beliefs, or sacrifices, whatsoever.

But the true meaning of these things was unknown to me,
and not understood distinctly until it pleased the Lord to send one of His servants,
called a Quaker, to minister to me, even as Philip did unto the eunuch in the chariot.
For the eunuch did not understand what he read, but afterwards,
by Philip`'s expounding the Scripture to him,
he then believed what he had been ignorant of.
So it was with me,
through the servant and instrument of the most high God opening my eyes,
and speaking plainly, and not in parables or dark sayings,
whereby I came to see what it was that had so long cried out in me
upon every occasion of serious inward retiring in my own spirit.
Then, I could at last say of Christ,
"`A greater than Solomon was here`"--He who
divided aright between the living and the dead,
and manifested plainly to whom the living child belonged.
Yes, He it was who revealed the true woman, or church,
which is in God the Father of our Lord Jesus Christ;
and also made known who was the harlot, or false church and synagogue of Satan,
regardless what she could say to justify herself as the true mother-church.

When I first heard this kind of preaching, by the fore-mentioned Quaker (so called),
it appeared to me as if the old apostles had risen from
the dead and begun to preach again in the same power,
life, and authority in which they first ministered and
published the new covenant of Jesus Christ.
And I could truly say with Jonathan,
after I had heard and tasted the honey and sweet ministration of the blessed gospel,
that my eyes were opened,
and my strength was renewed from that same power
by which the gospel was preached at first;
for this gospel was free from the dregs and residue of man`'s wit and inventions,
by which man had long darkened counsel by words without knowledge.
I speak the truth, and lie not.
After I had heard and tasted of the honey of Canaan which flowed freely,
without the forced inventions of man`'s brain,
my eyes were opened and my strength was renewed.
Then I obtained victory, through that grace of the gospel,
over those lusts and corrupt desires which rose up against the little
stirrings and movings in my heart after the living God (which I had
at times felt working even from my youth).

When the glad tidings of the gospel thus came to be sounded in my ears,
and to reach my heart and conscience,
it did not make void my former experiences of the love and mercy of God to my poor soul,
nor in the least bring my mind into a contempt of His
sweet refreshings during my wearied pilgrimage,
which were like streams of that brook from which
Israel drank by the way in their travels.
On the contrary,
it brought fresh to my remembrance the many ways
the Lord had revived me in my sore bondage,
and manifested my manifold rebellions against His wooings,
and my ingratitude for His tender dealings and frequent visits to me;
and this occasioned a true subjection from me,
as what was most due unto this tender God and Father.
And I was made to cry out,
"`What? Was God in this place, and I knew it not?`" (Gen. 28:16)
So I found my heart broken and overcome with His love and mercy to me,
and I became more tender before Him.

Thus all things were brought to my remembrance,
and I came to know Him not only as the One who
"`told me all that ever I had done`" against Him,
but also all that ever He had done for me.
This rendered the truth even more lovely and acceptable in my heart,
in that it should bring old things into new remembrance,
and restore an old acquaintance with my long-provoked God.
Thus it was with me as it was with Nathaniel,
who confessed to Christ just as soon as He told him that He saw him under the fig-tree.
In just the same way,
I could not withhold my soul`'s immediate subjection to
the Truth when I saw how it thoroughly searched me,
and plainly told me where I now was,
and how God had several times seen and visited my poor soul.
So I have found Christ`'s promise to Nathaniel also
fulfilled in me--for since that day of visitation,
I have seen greater things than ever I saw before.

Then I saw that my former condition (before truth fully conquered me,
and manifested itself distinctly) was like unto Hagar,
who had bread and a skin of water given to her by Abraham,
when she was sent into the wilderness for her son`'s mocking of Isaac.
When this bread and skin of water were spent,
her condition with her son was most miserable, and she knew no way to fill it again,
nor could she see it, though it was not far from her.
But her necessity pierced God`'s ears, and He then opened her eyes,
and she saw "`Lahai-roi,`" that is, "`the well of Him that lives and sees me.`"
So it was with me when the bread and water of relief (which
God often gave me to maintain me in the wilderness) was spent;
I was likely to perish, not seeing any well, or way of supply.
But the Lord sent the angel of His presence to open my eyes,
and I saw my Lahai-roi--which was there before, but I could not see it,
until my eyes had been opened.

Thus for lack of understanding, I (with many others) did pine away many of our days,
like Hagar in the wilderness, as a punishment of our lightness,
and for joining with Ishmael in despising weaned Isaac,
the weighty Seed in our own hearts, who is the heir of all spiritual blessings,
and the one with whom God establishes His covenant forever.

So I was convinced of the Truth towards the end of the year 1654 (as I remember),
through the servant of the Lord before-mentioned, named William Dewsbury.
I did not know of what persuasion he was when I went to hear him,
for if I had known he was a Quaker, I think I would not have heard him,
being afraid of strange opinions, lest I should be deceived.
But being providentially cast where he was declaring, I heard his words,
which were both like spears that pierced and wounded my heart,
and also like balm that healed and comforted me.
I remember the very words that took the deepest impression upon me at that moment.
Speaking of several states and conditions of men and women,
he described the miserable life of such who,
notwithstanding their religious duties or performances,
had no peace and quietness in their spirits; for,
through lack of understanding where to find a stay to
their minds at all times and in all places,
these were like children tossed to and fro,
and frightened with the cunning craftiness of men,
who promoted their own opinions and ways.
This I knew was my own condition at that time, as well as the state of many more poor,
shattered people, who
"`compassed ourselves about with the sparks of our own kindling`" (Isa. 50:11).
And indeed,
this brought us nothing but sorrow whenever we came to lie down and be still,
and to commune with our own hearts;
for we had nothing inwardly to feed upon and to stay our hearts,
besides either formal duties which perished with the using,
or disputable opinions about doctrinal things, in the natural understanding and memory.
This I came to know and behold afterward,
in the appearance of the tried cornerstone laid in Zion,
most elect and precious unto them that believed in Him.
And in His light I understood certainly, that it is not an opinion,
but rather Christ Jesus the power and arm of God who is the Savior.
And when He is felt in the heart, and is kept dwelling there by faith,
He differs as much from all notions in the brain,
as the living substance differs from a picture or image of it.

The reception of the Word of life in my soul was like
unto the little book that John was commanded to eat,
which proved sweet in his mouth but bitter in his belly.
So was the Truth unto me, most sweet and delightful unto my taste,
even like Jonathan`'s honey,
by which my eyes were opened and my strength renewed with great joy and clearness.
So it continued for some months after my first hearing,
whereby my judgment was so enlarged and fortified against all
batteries and assaults from the disputers of this world,
that I doubtless could have maintained the principles of truth against all opposers.
But all this while, I little regarded the outward form or expression of the truth,
until I heard the same person declare the word of truth again.
Then I began to see that all knowledge was nothing
without true practice and conformity to what I knew.
And then the truth began (like the little book) to be bitter in my inward parts,
because I did not yield obedience to what I was convinced was
my duty--as to lay aside all superfluity in apparel,
words, and conduct, which was hard for me to do,
being then in commission as a Justice of the Peace.
But by degrees, I was brought through all consultations and reasonings in this respect,
by sore and sharp terrors in my conscience.
I came to see all my sins and evils (both outward and great,
as well as secret and hidden) by the light in my own conscience;
and I knew that all my sins were but as fuel,
which the wrath and indignation of the Lord must consume.

I saw that now the axe was to be laid to the root of the tree,
and that there was an evil nature to be consumed in me which had long borne sway,
notwithstanding my profession of religion.
And I saw that my superfluity in apparel, words, and many other things,
did but feed and keep alive that nature, and so prolong the fire, to my own great misery.
And among many other things, I saw plainly that speaking "`you`" to a single person,
and putting off my hat after the customs and fashions of the world,
must all be left and put away, before that fleshly,
worldly nature in me could wholly die, and I be perfectly delivered from it.
I clearly saw that these things, together with using many words out of God`'s fear,
were but as food to nourish and feed and keep alive the wrong nature and part in me.

But oh how strongly the reasoning part withstood
me in my parting with these and other things!
None knows, but those who have been exercised in the like manner,
neither can I express the multitude of ways and arguments which the devil
used to keep me in those formalities and observances--and so much the more
because of my many great acquaintances and public employment.
And yet the greatest tribulation I passed through (before I could enter into
the kingdom of God) was to part with my own wisdom and knowledge,
by which I had profited beyond many of my equals.
I found I needed to be beheaded (so to speak) for the testimony of Jesus;
for I found by certain experience that, until man be truly crucified with Christ,
he cannot bear a true testimony for Christ.
Prior to this death, man can but bear witness to himself, which witness is not true;
but after he is truly crucified with Christ, and risen with Christ,
then if he bears witness of Christ, his witness is true.
In this is that faithful saying understood aright,
"`For the testimony of Jesus is the spirit of prophecy.`" (Rev. 19:10)

After a long and sharp fight of afflictions and
deep exercises in my heart and conscience,
I at last gave up to be a fool for Christ,
and as one "`beside myself for the Lord.`" (2 Cor. 5:13)
This was not effected without deep agony,
for indeed I thought I might lose my mind because of
the terrors of God that were upon my soul.
But at last, by His grace, He subjected the spirit of my mind unto Himself, so that,
through His prevalence, I was made to yield and be still,
that He might do with me what He Himself pleased.
Then I was enabled to give up to the death of the fleshly man, mind, and wisdom also,
which I saw was like unto the slaying of the first-born in Egypt.
And then it was said unto me,
"`Out of Egypt have I called my son,`" who was before as one slain,
but is now made to live as one born of God in His everlasting covenant forever.

Thus I came to know the One in whom there is no occasion of stumbling.
And I saw Him indeed to be the One who silences the disputer and wise of this world,
answering fully and most satisfactorily the deep inward cry and need that was in my soul.
Yes, He became to me like a most sweet shower that reached unto the root in me,
and I saw that all His former revivings were but as summer
drops that ushered in a greater drought afterwards,
or like a traveling man who stayed but a night.
And as I continued on my spiritual journey,
I saw the fulfilling of these and many more sayings of Scripture,
which were like a brook by the way,
which most sweetly gladdened my soul as the Lord made me drink of them.
A cup He put into my hand, of which He Himself was my portion.

I must not forget to relate in my journeying, how that after I came to Mount Sinai,
I felt the burnings of that fire which burned up
all my own righteousness like stubble and straw,
and I saw that it was not able to afford me any
shelter or preservation from those flames.
Then I thought to rely upon the knowledge I had
acquired of Christ by reading the Scriptures--such as,
that He was my surety, and that God accepted Him in my stead,
He having satisfied divine justice.
These concepts,
together with the sweet experiences I formerly had of Christ before I came into this way,
made me say within myself, "`Shall I let go all these things?`"
Unto which question (and to many more reasonings of the like nature) it was said in me,
"`Was it a bare remembrance of Christ, and His merits and surety mustered up,
or applied in your own time, or by your own natural understanding,
that did save you or help you in your distress?
Or was it My free revealing of Him, as My arm and power within you,
as really felt by you to comfort you within,
even as sin and the devil were truly felt within to torment you?`"
So I came to know how, when Christ appears,
the Seed of the woman does reach to the weak state that man is found in, even when Satan,
the old serpent, is most busy, lifting up his head to rule and torment the creature.
This Seed is also known to be the Seed of God, which, by the Spirit,
does bruise the head of the serpent, putting down all rule,
that Christ may be a Prince and a Savior forever.

Thus I came to the saving knowledge of Christ,
which did confirm my former experience of His appearance in me and to me,
even when I was weak in my understanding, and had but fleshly apprehensions of Him.
Nevertheless, the true saving Christ of God is indeed life, power, and virtue,
and those who know Him as such, have the knowledge of the truth as it is in Jesus;
for the opinion or concept of Christ in the natural understanding comes too short.
But when that Seed within, which wars against sin and evil, is minded and followed,
it does rectify the understanding according to the true and right acknowledgment of Him,
who is the true God and eternal life, the very Savior of all that believe in Him.
Many come only to be dwarfs in experience by giving way to their will,
and not to the light in the conscience to
command and steer the understanding and judgment.
These refuse the light, saying it is natural and insufficient; and yet,
at the same time (by the subtlety of the old serpent),
they follow their will and understanding, which are indeed both natural and insufficient.

So I passed from Mount Sinai to Mount Zion;
from the ministration of condemnation to the ministration of the Spirit;
because of which I could, and truly did, give thanks to God, through Jesus Christ.
He freed me from that condemnation under which I lay,
notwithstanding all my duties and beliefs,
and brought me to Him who is the sum and substance of all,
and who was now my rule and guide.
He was the guide of my youth in many things, though I knew it not then.
But now He is to me the Spirit which gives true liberty from every yoke of bondage.
For the ministration of the Spirit does war against the flesh, and is contrary to it,
and the soul that walks after the Spirit enjoys life abundantly.
But if the spirit of this world prevails, then death and condemnation come again.
As it is written, so I found it to be--
that "`He that is in the flesh cannot please God,`"
and "`He that walks after the flesh shall die.`"

After this, I felt the Spirit of truth to rule in me,
and my spirit to be really in union therewith,
though before I was in union with the spirit of this world.
And from that time forward,
the Spirit of Truth became the true rule by
which I walked and was led unto peace and rest,
even as before, when the old man ruled, I was led into trouble and sorrow.
So it was verified plainly in me,
that "`the stability of your times are righteousness and peace;`" and also,
this other scripture was fulfilled in me,
"`Neither circumcision, nor uncircumcision avails anything, but a new creature,`"
and only those who are accounted for the seed, the Israel of God,
and who walk according to this rule, do inherit true peace.

When I thus felt the immortal birth raised up in my inward parts,
like a most pleasant plant,
I often felt it put forth many sweet and heavenly breathings after God,
which were frequently answered by Him, so that I never sought His face in vain,
nor asked without a satisfactory return.
I found also that praises and thanksgivings did
naturally arise and spring up to God from the holy root,
even as I had before known a wicked, wrathful nature to cast up mire and dirt,
and to send forth fear, horror, trouble, and distrust.

Now my joy was full,
and often a cry arose in me unto God to keep me poor and needy in the daily cross;
to be nothing in self, but rather free from all self-willing and self-working,
in a daily dependence upon the Lord in this pure birth,
finding Him to be a treasury and storehouse of all supplies.
Both alone, and in meetings, I often felt Him to arise in great power and glory,
constraining me to sound out, like a trumpet, living praises to my God.
Out of the mouth of this Seed of eternal life,
words would proceed within me as I sat in meetings with God`'s people, and at other times,
which I was moved to utter with my tongue.
Oftentimes I spoke in the cross to my own will,
for the words seemed to my earthly wisdom to be void of wisdom,
and most contemptible to my natural understanding,
and I knew not the end for which I should speak such words.
Yet I was charged with disobedience and was deeply afflicted and
troubled in my spirit whenever I neglected to speak them forth.
And sometimes, while I was doubting and reasoning about them,
others have spoken forth the same words, which greatly exercised me,
knowing that the words were taken from me and given to another that was faithful.

The Lord having thus been pleased to reveal His Son in me,
He then showed me the deceitful workings of the "`man of sin`" in myself,
(in the "`mystery of iniquity,`" 2 Thess. 2:7)
and his exaltation in the temple of God,
where he is worshipped as God, above all that is called God.
And I saw that, though God deserves all worship, yet in this temple He is little known,
or little taken notice of by the creature,
because of the exaltation and rule of another thing which has appeared as God,
but is not.
All this I saw in the light of the Lord.
And not only so, but I also felt by experience how God raised up the younger,
and so made the elder in me to serve the younger,
which the Lord had now raised up as a beggar from the dunghill.
Then I came to know Him who is both Prince and Savior,
and the Minister of the true tabernacle which God had pitched, and not man.
And this I did not know in myself while the first tabernacle was standing,
nor did I know the holiest of all while the veil was still over my heart,
which veil I found to be done away in Christ,
and a new and living way opened thereby into the Holy of Holies.

Of this new and living way, the Lord made me a minister,
and commanded me to make known what I had seen, felt, handled, and passed through,
of the word and work of God.
At first this was hard to give up to do,
having many reasonings and consultations in my mind,
lest I be thought forward in my own will by those I ministered amongst,
or that I should go and appoint meetings, gather people together,
and then sit as a fool among them, having nothing to say.
These and many other reasonings
(being too numerous to mention particularly)
did assail me.
But being followed with daily stirrings and motions of life,
and a command to go to such-and-such a place by name (signified to me
by God`'s Spirit in my inward parts) I found a blessed result,
and many were at that time converted, who at this day abide in the truth,
and others have died in the faith.
The circuit and compass of counties where I should mostly labor in
the work of the Lord was shown to me by the Spirit of the Lord,
though I traveled in other parts as well when required by the motion of the same Spirit.
And I found I was not able to contain myself,
but that words would proceed from me in meetings where I was ordered
to go among God`'s people--both at my own habitation and elsewhere.
Many places were opened unto me where I was required to go;
and having suffered deeply by God`'s judgment for disobedience in this kind,
I gave up freely to go.
And indeed, I always found Him to be greater in His goodness than I could expect,
and more abundant in the pouring out of His Holy Spirit than my faith could
reach--even to the breaking of my heart many a time before Him in secret,
when no eye has seen me.

I will omit all the hardships and losses, as to my family and all outward concerns,
through which I was obliged to pass as the Lord led me on, both by the melting,
heart-breaking sense of His tender mercy to my soul,
and by the close pursuit of His anger and displeasure if I disobeyed.
So I was constrained to obey the Lord, in my going up and down, according as He sent me,
taking no thought what I should say, but often crying out to Him in my spirit,
"`Keep me poor and needy, believing in You, and then I shall speak from You, and for You!`"
Oh, I have an engraven sense of God`'s mercy upon my soul,
that He sent His servants from far away to come and seek me,
and to preach the everlasting gospel unto my poor, lost soul.
So then, why should I refuse to go and seek others, whose souls are lost,
as mine once was?
Shall I not love my neighbor as myself?
And I, knowing God`'s terrors,
shall I refuse to persuade men in Christ`'s stead (in obedience
to His motions in my soul) to be reconciled to God,
knowing Him to be a consuming fire?
Such were the workings of my mind, and the thoughts of my heart,
when I gave up to go where the Lord directed me, and I never lacked His assistance.
But sometimes I felt myself to be the weakest in all the meeting,
like an empty vessel without one drop to relieve any,
and I wondered what had become of all my knowledge,
and why I should now sit as one in poverty, in a posture fitter to be ministered unto,
than to minister to others.
But though I sometimes had nothing to give, yet I had no lack as to my own condition,
only I felt that others expected something from me, which was a trial to my mind.
But by degrees I learned to die to all but the will of God,
and whether in silence or speaking, to be content.

I began to minister about the year 1656,
after I had been some months in Northampton
prison for being at a meeting with God`'s people.
There I came to learn divinity through deep outward sufferings,
as well as inward exercises,
witnessing the opening of the sealed mysteries of God through the passing of woes;
for after the first and second woes were passed,
new seals were opened into the mysteries of God.
Thus God made prisons to be as schools for the true prophets,
or nurseries for true ministers of the gospel.
And then, having learned to remain in much fear and awe of God,
from the deep sense I had of His majesty and purity in my heart,
I spoke of Him as I felt He required it of me.
His rewards were in my bosom as a most sweet and comforting liquor,
that did lift up my spirit above all discomfort, both from enemies within and without.
And though trials did often sorely beset me, even like bees on every side,
yet God`'s blessed power and presence in me and with me did furnish my heart
and tongue with words suitable to the conditions of my listeners,
above all fear of any thing or person present.
I might fill a volume with this subject,
but this is spoken to the glory of the Almighty God,
and for the comfort and encouragement of His ministers that abide in His counsel,
and for the abasing of all flesh.
May the all-sufficiency of His Holy Spirit be trusted in, and relied upon,
as the only supplier of all ministers and people that go forth in His name.
Amen.

This Holy Spirit has been to me both meat and drink,
even as the Rock of old that followed the Israelites.
Ten times (as I remember) I have been in bonds,
and not only incurred the sentence of premunire^
footnote:[_Premunire_ was a legal judgment designed to disenfranchise
those who refused to formally swear allegiance to the King of England.
Those under a sentence of premunire were considered traitors to their country.
They lost all rights to property and possessions,
were removed from under the kings protection, and were often imprisoned for life.]
with my brethren at London, but also have been tried for my life in the country,
and all for the sake of a good conscience before my God.
But this Holy Spirit never left me, but many times has caused me to sing in prisons,
and often brought fresh courage before my accusers.
Indeed, by its virtue cruel judges have been bound,
and envious witnesses have been confounded who sought to destroy the innocent.
Yes, by this Holy Spirit all has turned to my joy.
My help is in it, my comfort flows from it,
and my daily request to my God is that all His people may be guided by it in all things.
Oh may God forever be worshipped in His own Spirit,
and may His blessed truth be preached through it, that neither wit nor skill,
outward learning nor gifts, persons nor forms, be ever set or esteemed above it.
But may we who have been baptized in it,
be forever found drinking of it while still in the body,
so that when we come to lay down the body,
we may do so with joy--both to the praise of the riches of His grace,
and the comfort of those who survive us in the same truth.
Amen.

[.asterism]
'''

[.emphasized]
John Crook was a wise merchant in the Lord`'s house,
selling all that he had to buy the Pearl of great price.
Though he was born into a wealthy family,
and by education and natural gifting became a prominent public figure,
he came to count all as dung in view of the excellency of the knowledge of Jesus Christ.
Throughout much ill-treatment, ten imprisonments, and several prolonged illnesses,
his spirit was kept sweet, humble, and in a true fear of the Lord,
so much so that after his death, a friend of more than forty years said,
"`I do not remember that ever I heard him utter an unsavory word, or impatiently cry out.`"

[.emphasized]
Shortly before his death, at 82 years of age,
he wrote an epistle to his children and grandchildren,
offering them weighty counsel from a life abounding with deep experience.
The letter begins thus: "`Dear children, I must leave you in a wicked age,
but commend you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ.
As you love it, and mind the teachings of it,
you will find it a counselor to instruct you in the way everlasting,
and to preserve you out of the ways of the ungodly.
I have seen much in my days,
and I always observed that the fear of the Lord God proved the best portion,
and those that walked in it, were the only happy people,
both in this life (while they continued faithful) and when they come to die.`"
