[quote.epigraph, , Acts 18:24]
____
An eloquent man, mighty in the Scriptures.
____

[quote.epigraph, , Jer. 15:19]
____
Therefore thus saith the Lord, If thou return, then will I bring thee again,
and thou shall stand before me: and if thou take forth the precious from the vile,
thou shalt be as my mouth.
____

== Introduction.

Various and manifold have been the methods in religious affairs in England,
within the memory of man; as may appear by these few short observations, or instances,
amongst many others that might be shown: viz; as by preaching,
and proving their doctrine, out of the volumes of ancient fathers, as they call them,
which was much used in the bishops times, etc.

Others preached by doctrine, and uses from their text,
which they endeavoured to prove out of the Scriptures.
Others preaching by marks and signs, showing by them, how a man might know,
whether he was a child of God or not, etc.
Which made way for independency of churches, living stones,
as they thought by this preaching, being already prepared for their building;
which begat that angry book, called, Edwards`'s Gangrena,
written by a zealous Presbyterian,
raking up all the miscarriages he could hear of the Independents, etc.

Others preached up water-baptism, as belonging only to those of riper years,
that could give an account of their faith, as an initiating ordinance,
thereby not only unchurching, but also unchristianing those that opposed it:
some of them preaching, that except men were baptized they could not be saved.

About this time Dr. Crisp, and some others appeared, preaching up free-grace,
and that God sees no sin in his people, accounting themselves evangelical, and others,
as legal preachers; these they called Antinomians.

After these appeared a people they called Seekers,
of these there was said to be two sorts; one sort they called Notionists,
who were said to be above all ordinances:
preaching up God and the Spirit to be beyond all.
The other sort called Seekers, denied that there was visibly to be found,
either true church or ministry in England, that they knew of, rightly constituted,
for want of an administrator, qualified with gifts,
and manifesting their sending by miracles: these, as was said,
waiting for both church and ministry to be restored, as was in the apostles time, etc.

After these, as I remember, appeared those they called Ranters;
some of them having been strict professors of religion;
these preached up one power to act and do all; of whom there were two sorts also;
the one sort they called Civil Ranters,
who kept themselves out of those gross debaucheries the others ran into:
the last affirmed, there was no sin but to them that thought so, etc.

Soon after appeared a people in the north, whom they called Quakers,
from their trembling at the word of the Lord.
These bore testimony to the light of Christ Jesus within, in the conscience,
to throw down all the former buildings;
yet owning the former true inward experiences witnessed
to be wrought in any by the Spirit of God,
proclaiming the day of the Lord to come, and coming,
that should throw down their fenced cities and their high towers,
and spoil all their pleasant pictures.
Some of these first preachers being sons of thunder,
awakening many that were sleeping in security;
but being thoroughly awakened by their testimony, they found their beds were too short,
and their covering too narrow: to such it was as a midnight cry,
unexpectedly coming upon them.

Others of this people`'s first preachers, were as sons of consolation,
trampling upon the mountains of opposition,
to bring glad tidings to the hungering and thirsting souls,
who readily received their testimony amongst all the former sorts of professors.
This being taken notice of, some cried out, the everlasting gospel is preached again;
observing, that amidst so many opinions, guarded with so much knowledge,
and outward learning, as both their leaders, and many of themselves were armed withal,
together with the countenance of the magistrates, which many of them had on their side,
the Quakers should so prevail, by their testimony to the light of Christ Jesus within;
and that published by poor contemptible and illiterate instruments at the beginning,
depending only upon the sufficiency of God`'s Holy Spirit,
without taking thought what they should speak, till God opened their mouths,
according to the scriptures and the doctrines therein recorded by the Holy Ghost,
retaining still their belief of the birth, life, death, resurrection, etc.,
of Christ Jesus the Son of God, who died, and shed his precious blood for them,
witnessing salvation, not for the merit of good works, as works,
though wrought in them by the Spirit of God; but for the sake of Christ Jesus,
the author both of their faith and good works, that flowed therefrom.

Finding, by experience, that generally all professors of religion in England,
continued in a belief of the death and sufferings of Christ,
it was required of these first preachers of the light of Christ within,
to continue their testimony to the same; witnessing in themselves,
that by waiting in the light,
they were instructed to distinguish between the living and the dead faith,
and between the saving and historical knowledge.
They found, by good experience,
that the understanding between some professors of religion,
and these first preachers of the light of Christ within, about the man Christ,
his death and sufferings,
etc. did not much arise about the things known and generally believed,
as about the nature and kind of the faith and knowledge,
whereby they were generally known and believed.

The tree being known by its fruit,
and many beholding the brightness of the Quakers`' lives and conversations,
at the beginning, behooved their doctrine, according to Christ`'s promise,
viz. He that doeth my will, shall know my doctrine; concluding their way,
as people called it, was "`The good old way,`" and ancient path,
prophesied of in Holy Scripture,
but had been long over-grown by the weeds of men`'s imaginations, traditions,
and inventions, being a way too narrow for corrupt flesh and blood to walk in.

But it being given to the faithful sincere professors of the truth amongst this people,
not only to believe it to be the truth, but also to suffer for the same,
they were enabled to withstand all opposition from others without,
as also the gain-sayings of the fleshly part within themselves.

Their innocent sufferings so tendered the hearts of many beholders,
that many were prepared to receive their testimony.
So mightily grew the truth and prospered,
the word of the Lord being precious in those days; when, for a time,
there had been no open vision, but the vision of all was become dark, like a sealed book.

The gospel day, as it were, being now proclaimed; many of the people,
sensible of their inward wants and necessities, came flocking to meetings,
where they met with spiritual supplies, answering their inward states and conditions,
as if themselves had told them to the preacher.
The kingdom of heaven, as it were, suffered violence, and the violent took it by force,
as in the days of John the Baptist: those that were eye-witnesses from the beginning,
may remember these things.

When this people, called Quakers, were but few in number, being low, contemptible,
and poor in their own eyes, and had but few public preachers amongst them,
the harvest being great, and the labourers few,
their first preachers commended and left them to the Spirit and word of God,
to be their teacher in their own particulars; unto which they did retire,
in deep inward silence, waiting to hear what the Lord would speak in them; which he did,
by his Spirit, according to his own good pleasure, to their souls refreshment.
Many times their hearts affected their eyes, to the amazement of the beholders;
observing tears to trickle down their cheeks, and not one word, outwardly, spoken to,
or amongst them.

In this pure silence they witnessed the outward testimonies
of truth to be inwardly sealed to their hearts;
whereby their spiritual love was so endeared to the truth, that the called, chosen,
and faithful, loved not their lives unto the death for its sake.
This caused them to be so watchful over their own hearts,
as to keep them with all diligence, lest that fearful example of the church of Ephesus,
should befall them, whose abatement of the zeal of her first love,
made way to the removal of her golden candlestick;
and so to the bringing in of that fearful darkness,
whereby her former shining light might be extinguished.
This hath befallen most, if not all, the church reformations we read of in history.
Yet how few can endure this sound doctrine,
of the danger of departing from their first love to God,
and to his light and truth in their inward parts.
On the contrary they are apt to say, as lukewarm Laodicea did, they are rich, and full,
wanting nothing, not fearing to say of their first estate and condition,
as some have said of the primitive Christians and churches,
viz. "`they were but in their infancy,`" etc.
"`But now,`" say some, "`that grain of mustard seed is become a great tree,
because of the multitudes that sit down under the profession of it,`" etc.
And in some respects, such speak truer than they are aware of;
for most people having only a form of godliness,
sit down under the bare form and profession of it, without the life and power of it.

But there are some others, more to be lamented than the former;
for they have in some measure, tasted of the good word of God,
and have been partakers of the Holy Ghost, and of the powers of the world to come,
beyond the former, as the Scripture speaks, and some of these also,
not liking to retain God in their knowledge, have left their first estate,
and first love to true godliness, as it is in Christ Jesus,
and are become wanton in their behaviour, and vain in their imaginations,
whereby darkness is come upon them; and yet say, with Babylonish confidence,
"`They sit as a queen, reigning in the power as much as ever; and are no widows,
their first love being still alive in them, and they shall see no sorrow.`"

When Zion remembers their state, she mourns for the darkness that is come over them,
and prays for their return, as in the day of their espousals.
Then she knows she shall sing again, as in the days of her youth,
as when she came out of the land of darkness, and spiritual Egypt;
she shall sing that new song, which none can learn but the redeemed out of the earth,
into the region of heavenly glory, etc.

It hath hitherto been the great unhappiness of all administrations,
that the professors of the same, have caused them to be evilly spoken of,
by not living up to the height of the administration they had been under;
for which cause God forsook such persons, and left them desolate,
by withdrawing that presence and power, which at first appeared among them.

I shall conclude with the apostle`'s prayer for the Thessalonians, 1 Thess. 5:23;
"`And the very God of peace,`" saith Paul, "`sanctify you wholly:`" that is,
all those which are in God the Father, and in the Lord Jesus Christ,
as it is at the beginning of the epistle, etc.
"`And I pray God,`" saith he, "`your whole spirit, and soul, and body,
be preserved blameless unto the coming of our Lord Jesus Christ.`"
Amen, Amen.

I find upon the margin of the old Bible, printed about the year 1599, this note, viz.

"`When the mind thinketh nothing; when the soul coveteth nothing;
and when the body acteth nothing contrary to the will of God;
this is perfect sanctification.`"

[.signed-section-signature]
John Crook.
