== Chapter 1. A Short History of the Life of John Crook.

I HAVE often been pressed in spirit, to write this following history of my life,
that so the world, as well as my friends and acquaintance,
might know the Lord`'s dealings with me from my tender years;
both for the comforting of the saints,
and the information and instruction of all into whose hands this account may come.
But above all, that the God of my life might be feared and exalted in the hearts,
and by the conversations in holiness before him,
of all the sons and daughters of men forever.

I was born in the north country,
of parents that were for religion of the common profession
of the times in which they lived,
with whom I was brought up, and instructed in their way.
Until I was about ten or eleven years of age, within which time,
I had many exercises in my inward man, and often prayed in by-corners,
as words sprang in my mind, and as I learned prayers without book;
yet many strong combatings remained within me, which continued haunting me many months;
until one time, above all the rest, I was almost overcome to consent,
the devil urging me thereunto by a mighty violent striving,
to run down all my resistance and withstanding of him.
But on a sudden, there arose in me,
a power and life that did oppose and gainsay the enemy, making my spirit say within me,
with much boldness and courage, I will not serve thee, O Satan,
but I will serve the Lord God of heaven and earth, whatsoever I suffer,
or becometh of me therefor.
Which, I do remember, my tongue also uttered pretty loud,
with much vehemency and resolution,
in full consent to what was spoken inwardly in my heart,
in opposition and contradiction to the evil spirit that
strongly tempted me to give up myself to wickedness.
After this,
I was affrighted when I came to consider those opposite strivings in my spirit,
what they should mean, having never heard any body speak of any such thing:
but especially I was amazed, when I considered what that voice should be,
which spake with such an authority in me,
that it commanded my tongue to speak so boldly in compliance with it,
and against the other,
which had almost forced me to consent unto its evil motions and suggestions;
yet by the ease and relief I found in my inward parts,
I concluded it was the Lord who helped me in so great a strait.

I remember after this, when I was tempted or troubled in my mind,
I would go into some corner or secret place, and pray unto God;
and when I had committed sin and evil, I was still troubled afterwards,
and then I would pray to God for his strength against them: and when I was alone,
I was sure to hear of all my doings, they would come fresh in my remembrance,
and be so set before me, that I could not get them out of my sight,
but endeavoured to get into some private place to pray and weep;
and then would promise and covenant in secret with God, that if he would forgive these,
and help me for the time to come, I would never do the like again: but for all this,
evils prevailed against me, and I could not keep my promise with God.
So that trouble came upon my spirit, and I often mourned and went heavily,
not taking that delight in play and pastime which I saw
other children took which made me often conclude in my mind,
that they were in a better condition than I, and that surely God was angry with me,
which made him so correct me, that I could have no peace,
whereas I saw other children merry and cheerful, and not at all as I was.
Yet sometimes I had ease, and was cheerful, but it seldom held long,
without some intermixture of trouble.
I had also many openings in my mind, which, did sometimes much amaze me;
about heaven and hell, and wicked men and good men;
and also I saw many of the priests profane in those parts,
giving up themselves to divers kinds of wickedness.

About ten or eleven years of age I went to London, and there went to several schools,
until I was about seventeen years of age; in all which time,
I was not without much trouble and exercises in my mind:
notwithstanding I lived in a wicked family,
and amongst those that scoffed at all strictness in religion,
yet I would get into some by-corner, and pray and weep bitterly,
from the sense of my own sins,
and would often reprove my school-fellows and companions for their wickedness;
I often walking alone by myself in some secret place,
when they would be at play and pastime.
Thus I passed away my youthful days,
in reading and praying oft-times when trouble was upon me,
which I was seldom free from whole weeks, more or less, either in the night or day time;
but all this time I did not mind hearing of sermons,
being little acquainted with any that frequented such exercises,
until I went to be an apprentice, about the seventeenth year of my age.

About this time I was placed in a parish in London, where was a minister,
who was in those days called a Puritan,
where I came acquainted with those young people that frequented sermons and lectures,
so often as we had any liberty from our occasions, being apprentices;
yet trouble grew upon me more and more,
as I grew in knowledge and understanding of the things of God;
and still I applied myself to reading the bible, and other good books, and prayed often,
insomuch that those in the family where I was an apprentice, took much notice of it,
and would stand in secret places to hear me, though I then knew it not.

But I remember when I was most fervent in my devotion,
something in me would be still pulling me back, as it were,
as if I would not wholly yet leave those evils I knew myself guilty of,
but would gladly have them pardoned and forgiven, and yet would I continue in them.
Such a thing I found within myself, gainsaying my earnest cries and petitions,
as if I would have had peace with God,
and yet also have continued still in those things I prayed against;
which at last made me conclude, I was but an hypocrite,
and did not belong to the election of grace,
but was to become some eminent spectacle of God`'s displeasure,
and that that which gainsayed my earnest cries was the devil;
and therefore concluded I was possessed with the devil; and would often,
as I had occasion, be enquiring of professors how it was with them,
and how they understood the condition of those to be,
that were possessed with unclean spirits in Christ`'s time;
but all that I could get from any, could not remove this out of my mind,
but that I was possessed with the devil.
I thought I felt in myself something sensibly and
manifestly opposing those good motions and desires,
that were in me, as if two had been striving in me for victory:
and when I was so tired out with resistings and fightings in myself,
I could get no relief or sensible ease, but by going to prayer,
either secretly within myself, or down upon my knees in some secret place.
And oft-times, when I was at prayer,
I was so possessed with fear that I looked behind me,
lest the devil stood there ready to take me so soon as I rose up;
and then I was troubled for giving way so far, as to look behind me;
yet I durst not leave praying for all this.
And that which troubled me often times, was, that those which heard me pray,
admired my gift in prayer, and believed me to be a child of God,
when I concluded nothing less of myself, than that I should deceive them,
and cause God`'s name to be blasphemed by my miscarriage at last,
which I concluded must needs be at one time or other;
for I thought it impossible for me to continue in that condition long,
but I should be made an example to all hypocrites.

Thus I continued professing, and praying, and hearing, and reading,
and yet I could not perceive any amendment in myself;
but the same youthful vanities drew away my mind when opportunities offered, as before;
which was never much to outward gross profaneness,
but only to idle talk and vain company, in misspending my time,
and minding pride too much in my apparel, and such things, for all which I was condemned;
as also for wearing long hair, and spending my money in vain,
which I thought might have been better employed, if I had bought some good books,
or been charitable to the poor; all that I did was condemned,
and myself for doing of it also; yet I durst not leave off my duties,
for then I thought the devil would prevail over me, to make me destroy myself;
for I was afraid to see a knife if I was alone,
or to have any in the room all night where I lay.
Thus I continued,
running to lectures when I had any time allowed me by my master from my occasions,
which I endeavoured to get, by doubling my diligence in the day time,
and also from my sleep in the night time,
that so I might the more easily gain opportunities of my master;
all which I employed in private meetings and lectures,
going after any eminent man I heard of,
which by this time I had obtained the knowledge of,
by much acquaintance with constant hearers of sermons,
and frequenters of private fasts and meetings.

I have often been in congregations, hearing sermons,
when I have had much ado to forbear crying out in the midst of the assembly, I am damned,
I am damned; but did not, though I went often away full of horror and misery in my mind.
The ministers then. commonly preaching by marks and signs,
how a man might know himself to be a child of God, if he were so;
and how it would be with him if he were not so;
which made me sometime to conclude I had saving grace,
and by and by to conclude I was but an hypocrite.
Thus I was tossed up and down, from hope to despair;
and from a sign of grace in me one while,
and then presently to a sign of an hypocrite and reprobate again;
so that I could not tell what to do with myself, or whether it were best to go to church,
or stay at home; for I could get no rest, or lasting peace,
by all my hearing and running up and down.
Yet I had no freedom in myself, to go to any of those ministers, in private,
to acquaint them with my condition; partly, because I thought they could not help me;
and partly out of fear, lest they should discourage me, and tell me I was an hypocrite,
and then Satan, should prevail to force me to destroy myself;
for I was afraid of any thing that might confirm my own thoughts of my miserable state,
which I believed to be bad enough,
but was exceedingly afraid to have my thoughts seconded
by the sentence and judgment of any other:
so that I remember not that ever I went to any ministers to acquaint them with my condition,
but bore it secretly in my own bosom, few knowing how it was with me.

Then I resolved one first-day afternoon (called then
the Lord`'s day) being full of trouble,
when I was an apprentice,
to go that time which way I should be moved or inclined in my spirit,
whether it was up street, or down street, east or west, north or south,
without any predetermination or forecast, or so much as forethinking,
either of any man or place to go to, or hear that day, but only as the staff should fall,
as it were, or as I should be led.
Accordingly I came downstairs, and went, as I was led by something within me,
which I believed in and followed, until it brought me into a parish church, so called,
where I went in and sat down, and within a small season of time,
a young man went up into the pulpit, and preached out of this text, Isa.
1.10; "`He that walketh in darkness, and hath no light,
let him trust in the name of the Lord, and stay upon his God.`"
Upon which text he had preached before, and was at that time to pick out, or discover,
who that man was that feared the Lord, and yet walked in darkness;
the which he performed, as if he had known my condition and aimed at,
and spake to me in particular; which did much relieve me,
and at that time much comfort me, being so providentially brought thither,
where I never was before, neither heard of any such man, that I remember.

I went away much gladdened, and continued so for some time;
but trouble came upon me again afterwards, through some negligence and coldness,
which gendered to distrust and unbelief; so that the old enemy, the tempter,
got in again, and tore me worse than before in my mind;
so that I questioned all that ever I had at any time given me to refresh me,
as being but a delusion, and no truth in it; for I was a castaway,
and all these things were but to leave me without excuse.
Then I began to be full of horror, so that my sleep was much taken from me,
and anguish and intolerable tribulation dwelt in my flesh;
so that when I heard any of the meanest poor people cry any thing about London streets,
I even wished and desired that I were in their condition;
for I thought every man or woman to be in a better condition than myself; nay,
I thought myself the only miserable man in the world.
Had I been made the most contemptible creature in the whole creation,
I had been happy in comparison of my most intolerable misery;
all which was heightened by Francis Spira`'s book,^
footnote:[Francis Spira (1502 - 1548) was an Italian lawyer who converted to Protestantism,
but under pressure from the Catholic Inquisition denied
his own convictions and publicly recanted his faith.
The book referenced by Crook is called A Relation of the Fearful Estate of Francis Spira,
which relates the terror that immediately seized Spira upon his recantation,
and the subsequent guilt, horror, and mental anguish that soon ended his life.]
which came to my hand, but I would not read it over,
I thought it so to resemble my present condition; for when I had read but a little,
I cast it from me, and durst not look on it any more.

In this extreme misery I continued, keeping it to myself, mourning in secret,
until one morning, as I was solitarily sitting, lamenting my present state; on a sudden,
there sprang in me a voice, saying, "`Fear not, O thou tossed, as with a tempest,
and not comforted, I will help thee;
and although I have hid my face from thee for a moment,
yet with everlasting lovingkindness will I visit thee, and thou shalt be mine; fear not,
for I am pacified towards thee, and will never leave thee nor forsake thee,
saith I the Lord, the mighty God.`"

Whereupon all was hushed and quieted within me,
so that I wondered what was become of the many vexations,
tormenting fears and thoughts that just before attended me.
Here was such a calm and stillness in my mind for a pretty time,
so that it was brought to my mind, that there Was silence in heaven for half an hour;
and I was filled With peace and joy,
like one overcome--and there shone such an inward light within me,
that for the space of seven or eight days time, I walked as one taken from the earth:
I was so taken up in my mind, as if I walked above the world, not taking notice,
as it seemed to me, of any persons or things as I walked up and down London streets,
I was so gathered up in the marvellous light of the Lord,
and filled with a joyful dominion over all things in this world.
In which time, I saw plainly, and to my great comfort and satisfaction,
that whatever the Lord would communicate and make known of himself,
and the mysteries of his kingdom, he would do it in a way of purity and holiness;
for I saw then such a brightness in holiness,
and such a beauty in an upright and pure righteous conversation,
and close circumspect walking with God in an holy life,
although I had before obeyed to the uttermost that I could,
yet I could not set peace thereby,
nor find and feel that acceptance and justification before God, as I did at this time,
when it sprang freely in me, that, as it were, all religion lay in it truly so,
and all profession besides, or without it,
were as nothing in comparison of this communion.
For I remember,
while I abode and walked in that light and glory which shone
so clearly in my mind and spirit within me,
there was not a wrong thought appearing or stirring within me, but it vanished presently,
finding no entertainment; my whole mind and soul was so taken up with,
and swallowed up of,
that glorious light and satisfactory presence of the Lord thus manifested in me.

After this, I perceived an abatement of the glory,
and I began to read and perform duties as I had done before,
which for about eight days time, I could not perform so formally as I did use to do,
before I was filled with joy and peace, but with much more livingness and zeal,
faith and confidence than before,
which caused many of my acquaintance to admire my gift in prayer,
and upon all occasions to put me upon that duty.
I began about this time much to follow those ministers that came out of Holland,
and some others that were more for the way of separation from the parish assemblies,
disliking in my mind those mixed communions; much thirsting after,
and longing for a pure communion with such as were most spiritual,
and walked in the closest fellowship with God in holiness,
and watchfulness one over another, for good and increase in a holy life,
which I much longed for, since I had seen the beauty of it.

I walked with a company of young men,
who met together as often as our occasions would permit,
and prayed and conferred together about the things of God; and I remember,
when several would be speaking out of the scriptures, by way of exposition, etc.,
I had little to say from thence, not having much acquaintance with them,
being brought up, mostly in my young days, under such tutors, and such families,
as did not much regard the scriptures,
accounting them Puritans and sectaries that addicted themselves that way.
But I would be speaking forth my own experiences, delighting in,
and loving those most who could speak from experience,
my heart being most warmed and enlivened in those experimental discourses and conferences;
so that those who were most spiritual, delighted to be with me, and I with them;
they would tell me, that I spake from experience;
for I thought that I could speak to most conditions and things by experience,
as if I had had a volume of all subjects within me,
while most gathered their discourses from the scriptures without them.

In two or three years time after this,
I began to gather scriptures into my mind and memory, what from hearing of others,
and my own studies, which occasioned me to dwell more without, and less within;
so that by degrees,
the knowledge in my natural understanding and judgment began
to outgrow and overtop the sense of my inward experiences.
At last, having little besides the remembrance, now a great way off,
of those things which once were lively and fresh, growing up in me,
as if it had always been spring time in my heart and mind:
my inward parts were like a winter, all retired out of sight, as into a hidden root;
and many questionings`' about the way of worship,
and ordinances of the New Testament began to arise in my mind, judging myself,
that now the Lord had done so much for me,
I could not but be chargeable with unthankfulness before the Lord for his mercies,
if I did not now seek out the purest way of worship,
that I might enjoy all his ordinances in the purity of them.

Wherefore, after I had gone amongst several sorts of professors, of divers judgments,
trying with whom my spirit could sit down and close with; at last,
I met with some particular persons, with whom I joined in communion,
in the way of independency; and at times, we had many refreshings together,
while we were kept watchful and tender, with our minds inwardly retired,
and our words few and savoury; which frame of spirit we were preserved in,
by communicating our experiences to each other; as,
how our hearts had been kept towards the Lord all the week;
with an account of most days passages between God and our souls,
from the beginning of the week unto the end.

This continued some years, until it grew formal;
and then we began to consider our church state,
whether we were in the right order of the gospel, according to the primitive patterns;
and in the consultation of the proper administrator of baptism,
and the right subject thereof,
we began to be divided and shattered in our minds about it;
from whence arose many questionings about divers things not at all questioned before,
which gendered unto much uncertainty and instability.
Afterwards, we began not only to be remiss in our meetings,
but also confused in our preachings and services, when we were assembled;
so that at last we did not meet at all,
but grew by degrees into estrangedness one from another, and into carelessness,
consulting principles of liberty, and ease to the flesh, and from thence,
to encourage and justify our present remissness and coldness in religious performances.
But I was not so given up, or devoted to remissness and ease,
as that I was wholly without checks and reproofs for my so doing;
and oftentimes the inward distress and trouble of
my spirit roused me up again to religious duties,
as prayers, and reading.

I found also by experience,
that when I was overborne in my judgment and natural understanding,
by principles and tenets, which were offered me in my shattered state,
to draw my mind into carelessness about all religion,
and to a slighting of my former strictness (as well as others now);
and as for sin and evil, those principles would have forced me into a belief,
that my former apprehensions of the wickedness and danger thereof,
were more from a sudden fright, together '`with a traditional belief of the thing,
than from any grounded certainty from reason,
or deliberate consideration thereof in true judgment.
But against all this, and much more of like nature,
which I was exercised with day and night, and often tempted to embrace,
both by inward suggestions, and outward allurements,
from those that sometimes had been as religious as myself,
and no less acquainted with inward experiences of like kind with my own:
yet from a sense and deep impression, which remained upon my spirit,
both of great troubles, in being delivered from them all,
and sweet consolation I had tasted; I say,
the sensible remembrance of the former days did stick upon me so,
as to keep me from those principles of Ranterism and Atheism,
which were rife and much stirring in those times.

Through faith in what I tasted, I was supported under many a bitter combat,
and deep wave and billow, and made to say and conclude in my heart and mind,
that the righteous was more excellent than his neighbour;
and that there was a far better state and condition
to be known and enjoyed in this world,
by walking with God in holiness and purity, than by all licentious and voluptuous living,
or covetous gathering of riches together, to get a name in the earth.
This I knew from what sweetness I myself had once enjoyed therein.
The result of all which, together with an inward cry,
that was still continued underneath all reasonings and observations I could make,
and lay deeper lodged in my inward parts,
than all floating apprehensions and wanderings to obtain relief and satisfaction--I say,
this continued cry and sound in my ears inwardly, called for watchfulness over my ways,
and obedience unto what was made manifest to be the will of God in my conscience,
as being more available to afford me rest and peace, than either all my notions,
observations, beliefs, or sacrifices, whatsoever.
The meaning thereof, to know them distinctly, was unknown to me,
until it pleased the Lord to send one of his servants,
called a Quaker to join himself unto my condition, in his ministering,
as Philip did unto the chariot of the eunuch, who before understood not what he read;
but afterwards, by Philip`'s expounding the scripture to him,
believed what before he was ignorant of.
So it was with me, through that servant and instrument of the most high God,
opening my eyes, and speaking plainly, and hot in parables, nor in dark sayings;
whereby I came to see what it was that had so long cried in me, upon every occasion,
of serious inward retiring in my own spirit: that I could say of Christ,
a greater than Solomon was here,
and one that divided aright between the living and the dead,
and manifested plainly to whom the living child belonged, and what was the true woman,
or church, in God the Father of our Lord Jesus Christ; and what was the harlot,
or false church and synagogue of Satan; whatever she could say to justify herself,
as the true mother-church.

And indeed this kind of preaching by the fore-mentioned Quaker, so called,
appeared unto me, at the first hearing thereof,
like as if the old apostles were risen from the dead,
and began to preach again in the same power, life, and authority,
in which they ministered when they gave forth,
and first wrote and published the gospel and New Testament of Jesus Christ.

I could truly say with Jonathan,
after I had heard and tasted of the honey and sweet ministration of the blessed gospel,
that my eyes were opened, and strength renewed from the same power again,
by which it was preached at first,
as free from the dregs and lees of man`'s wit and inventions,
by which they had darkened counsel by words without knowledge.
I say the truth, and lie not; after I had heard and tasted of that honey of Canaan,
that flowed freely, without the forced inventions of man`'s brain, my eyes were opened,
and my strength was renewed, and I obtained victory, through that grace of the gospel,
over those lusts and corrupt desires which rose against
those little stirrings and movings after the living God,
which I had felt working at times in my heart, even from my youth,
until the time of my being born again of the incorruptible seed,
and received the earnest of the inheritance and seal of the covenant, etc.

When the glad tidings of the gospel came thus to be sounded in my ears,
and reaching my heart and conscience,
they did not make void my former experiences of the
love and mercy of God to my poor soul,
nor in the least begat my mind into a contempt of
his sweet refreshings in my wearied pilgrimage,
all along as streams of that brook which Israel drank of by the way in their travels;
but on the contrary,
brought all my former revivings that he gave me in my sore bondage fresh to my remembrance,
and set in order before me my manifold rebellions against his wooings,
also my ill-requitings of him for his tender dealings,
often visits and long-suffering towards me; all which challenged a subjection from me,
as most due unto this tender dealing God and Father towards me, and made me cry out,
"`What, was God so near me in a place I was not aware of,
that I found my heart to be broken and overcome with his love and mercy to me?

And the more was my heart tendered before him,
in that all things were brought to my remembrance,
as one that not only told me all that ever I had done against him,
but also all that ever he had done for me;
and this rendered the truth more lovely and acceptable in my heart,
that it should bring old things into new remembrance,
and restore my old acquaintance with my long provoked God again.
Thus it was with me in spirit, as with Nathaniel, who confessed to Christ,
as soon as Christ told him, he saw him under the fig-tree;
so I could not withhold my soul`'s subjection unto the truth,
when it so thoroughly searched me, and plainly told me where I now was,
and the several times that God had seen and visited my poor soul.
And Christ`'s promise hath as really been fulfilled in me,
as ever he spake it to Nathaniel; for since that day of visiting me again,
I have seen greater things than ever I saw before,
although I was sweetly comforted for a time, as I have expressed,
yet not with that distinct plain understanding as after.

My condition before truth conquered me fully, and manifested itself distinctly,
so as to make me lay down all my weapons and crowns,
and give up myself to be on its side wholly, was like unto Hagar,
who had her bag and bottle given to her by Abraham, when she went into the wilderness,
for her son`'s lightness in mocking Isaac; which bag and bottle being spent,
her condition with her son, was most miserable,
in that she knew not a well to recruit her again; neither could see it,
though it was not far from her, until her necessity pierced God`'s ears,
and then he soon opened her eyes, and she saw Lahai-roi,
i+++.+++ e. the well of him that liveth and seeth me.
So it was with me, when my bread and water of relief,
which God often gave me to maintain me in the wilderness, was spent,
and I likely to perish, I could not see any well, or way of supply,
until the Lord sent the angel of his presence to open my eyes,
and then I saw my Lahai-roi, which was there before, but I could not see it,
until he had opened mine eyes.

And thus, for want of an understanding, did I, with many more,
pine away many of our days, like Hagar, in the wilderness,
as a punishment of our lightness, joining with it in ourselves, to slight weaned Isaac,
the weighty Seed in our own hearts, which is the heir of all spiritual blessings,
and with it God establisheth his covenant forever.

=== A Relation of the Working of Truth in my Heart Since I was called a Quaker, Until Near the Time of My Departure.

I WAS convinced of the Truth towards the end of the year 1654, as I remember,
through the servant of the Lord, before mentioned, called William Dewsbury,
not knowing of what judgment he was when I went to him.

For if I had known he had been a Quaker, I think I should not have heard him,
being afraid of strange opinions, lest I should be deceived;
but being providentially cast where he was declaring, I heard him; and his words,
like spears, pierced and wounded my very heart; yet they seemed unto me, as balm also,
healing and comforting, as well as searching and piercing,
I remember the very words that took the deepest impression upon me at that present,
speaking of several stales and conditions of men and women; such words passed from him,
as implied the miserable life of such,
who notwithstanding their religious "`duties or performances,
had not peace and quietness in their spirits; who through the want of an understanding,
where to know and find a stay to their minds, to exercise them at all times,
and in all places, were like children tossed to and fro,
and frightened with every cunning craftiness of men,
to promote their own opinions and ways.
This I knew was my own condition at that time,
as well as the state of many more poor shattered people,
compassing ourselves about with the sparks of our own kindling,
which did but procure us sorrow, when we came to lie down and be still,
and commune with our own hearts, having nothing inwardly to feed and stay upon,
but either formal duties which perished with the using,
or disputable opinions about Christ and doctrinal things,
in the natural understanding and memory;
but wanted a spiritual understanding of that which
might then have been known of God within.
This I came to know and behold afterward,
as the appearance of the tried corner stone laid in Zion,
most elect and precious unto them that believed in him; whereby I understood certainly,
that it is not an opinion, but Christ Jesus the power and arm of God, who is the Saviour,
and being felt in the heart, and kept dwelling their by faith.
He differs as much from all notions in the head and brain,
as the living substance differeth from the picture or image of it.

The reception of the word of life in my soul, was like unto the little book,
which John in the Revelations was commanded to eat, which proved sweet in his mouth,
but bitter in his belly.
So was the truth unto me, most sweet and delightful unto my taste,
even like unto Jonathan`'s honey, by which mine eyes were opened,
and my strength renewed with great joy and clearness;
which continued for some months after my first hearing,
whereby my judgment was so enlarged and fortified against ail batteries
and assaults from any of the disputers of this world,
that I doubted not,
but at that time I could have maintained the principle of truth against all opposers.
But all this while, there was little of the outward form of truth regarded by me,
until I heard the same person declare the word of truth again.
Then I began to see that all knowledge was nothing,
without practice and conformity to what I knew.
Then began the truth, like the little book, to be bitter in my inward parts,
because I did not yield obedience unto what I was convinced to be my duty;
as to lay aside all superfluities in apparel, words and carriage,
which was hard for me to do, being then in commission as justice of the peace;
but by degrees, I was brought out of all consultations in this respect,
by sore and sharp terrors in my conscience; for all my sins and`" evils,
which I saw to be many and great, as well as secret and hidden, which,
by the light in my own conscience,
I came to see more and more through the exercise of my mind;
for all my sins were but as fuel,
which the wrath and indignation of the Lord took hold of.

I saw that now the axe was to be laid to the root of the tree,
and that there was an evil nature to be consumed in me, which had borne sway long,
notwithstanding my profession of religion, and that my superfluity in apparel, words,
and many other things, did but feed and keep alive that nature,
and so prolong the fire to my own misery therein.
And of this sort I saw plainly was speaking you to a single person,
and putting off my hat after the customs and fashions of the world, etc.
I reasoned, must all be left and put away,
before that fleshly worldly nature and part in me could wholly die,
and I be perfectly delivered from it?
Because I saw that these things, together with using many words out of God`'s fear,
were but as food, to nourish and feed, and keep alive that nature and part in me.

But how strongly the reasoning part withstood me,
in the parting with these and other things, none knows,
but those that have been exercised in the like manner;
neither can I express the multitude of ways and arguments which the devil used,
to keep me in those formalities and observances; and so much the more,
because of my great acquaintance, through some public employment, and other occasions.
And yet the difficulty to part with my wisdom and knowledge,
in which I had profited beyond many my equals,
I found to be the greatest of tribulations that I passed through,
before I could enter into the kingdom of God, viz. to be, as it were,
beheaded for the testimony of Jesus: for I found by certain experience,
that until man be truly crucified with Christ,
he cannot bear a true testimony for Christ; for it is but a bearing witness to himself,
which is not true; but after he is truly crucified with Christ, and risen with Christ,
then if he bears witness of Christ, his witness is true:
hence is understood aright that faithful saying,
viz. For the testimony of Jesus is the spirit of prophecy.
After a long and sharp fight of afflictions,
and deep exercise in my heart and conscience, I at last gave up to be a fool for Christ,
and as one beside myself for the Lord.
This was not effected without deep agonies; for I thought I should have been distracted,
because of God`'s terrors that were upon my soul; but when, by his grace,
he had subjected the spirit of my mind unto himself,
that I was made through its prevalency to yield, and be still,
that so he might do with me what himself pleased,
giving up to the death of the fleshly man, mind, and wisdom also; through which,
as the slaying of the first-born in Egypt, it was then said unto me,
"`out of Egypt have I called my son,`" which was before as one slain,
by whom I am now made to live as one born of God, into his everlasting covenant forever;
which being thus known to be his own, having loved it, he loves it unto the end.

Thus I came to know him, in whom is no occasion of stumbling,
to be him indeed that silenceth the disputer and wise of this world, answering fully,
and most satisfactorily, the deep inward cry and want that was in my soul,
and was as a most sweet shower, that reached unto the root of the matter in me,
while the former revivings were but as summer drops,
ushering in a greater drought afterwards: or like a wayfaring man,
that tarries but a night; and as I passed on my spiritual journey,
the bringing fresh into my soul, the fulfilling of these,
and many more sayings of scripture, like a brook by the way,
most sweetly gladdened my soul, when the Lord made me drink of them,
as a cup he put into my hand, and himself was the portion of.

I may not forget to relate in my journeying, how that after I came to Mount Sinai,
I felt the burnings of that fire,
burning up all my own righteousness like stubble and straw,
as not being able to afford me any shelter or preservation from those flames.
Then I thought to rely upon the knowledge I had of Christ, by reading the scriptures; as,
that he was my surety, and God accepted him, as in my stead,
he having satisfied divine justice,
together with the sweet experiences that I formerly had of Christ,
before I came into this way, or did believe in his light in my own conscience;
and I said within myself.
Shall I let go all these things for an uncertainty?
Unto all which, and many more reasonings of the like nature, it was said in me,
to my great relief at that time, Was it a bare remembrance of Christ,
and his merits and suretyship, mustered up, or in thy own time applied, or +++[+++by thy]
own natural understanding, that did save thee, or helped thee in thy distress?
Or, was it my free revealing of him, as my arm and power within thee,
as really felt by thee, to comfort thee within; as sin and the devil were felt within,
to torment thee?
So that the seed of the woman, reaching to the weak estate man is found in,
when Christ appears to save him, even when Satan, the old serpent, is most busy,
lifting up his head to rule and torment the creature,
this seed is also known to be the seed of God, according to the spirit,
bruising the head of the serpent, and putting down all rule,
that he may be a Prince and a Saviour forever.

Thus I came to the saving knowledge of Christ,
which did confirm my former experience of his appearance in me, and to me,
even when I was weak in my understanding, and had but fleshly apprehensions of Christ.
Nevertheless, the true saving Christ of God, is indeed life, power, and virtue,
whom to know as such, is the knowledge of the truth, as it is in Jesus:
for the opinion or conception of Christ in the natural understanding, is too short:
but while that within, which warreth against sin and evil, is minded and followed,
it will rectify the understanding, to the true and right acknowledgment of him,
who is the true God and eternal life, the very Saviour of all them that believe in him.
Many come to be dwarfs in experience, by giving way to the will,
and not to the light in the conscience,
to command and steer the understanding and judgment, refusing the light,
as natural and insufficient; and yet at the same time, follow the will and understanding,
which are both natural and insufficient; but understand it not,
through the subtlety of the old serpent.

And thus I passed from Mount Sinai, to Mount Zion; from the ministration of condemnation,
to the ministration of the Spirit; through which I could, and in heart did,
give thanks to God, through Jesus Christ,
freeing me from that condemnation which I lay under,
notwithstanding all my duties and beliefs, as the sum and substance of all,
being now my rule and guide.
He was the guide of my youth in many things, although I knew it not then;
and now is that spirit, which gives true liberty from every yoke of bondage,
as being now known to be that ministration of the Spirit,
which doth war against the flesh, and contrary to it,
whereby that soul that walks after the Spirit, enjoys life abundantly;
but if the spirit of this world prevail, then death and condemnation come again;
as it is written, so I found it to be true, he that is in the flesh cannot please God,
and he that walks after the flesh shall die.

After this, I felt the Spirit of truth to rule in me,
and my spirit to be really in union therewith,
as before I was in union with the spirit of this world; which was from that time forward,
as really a true rule to me to walk by, leading unto peace and rest, as before,
when the old man ruled, in following of him I had trouble and sorrow.
So that it was verified plainly in me,
the stability of thy times are righteousness and peace; and also,
that other scripture was fulfilled in me, viz. Neither circumcision,
nor uncircumcision availeth any thing, but a new creature;
and those only are accounted for the seed, the Israel of God, that do inherit true peace,
who walk according to this rule.

When thus I felt the birth immortal raised up in my inward parts,
like a most pleasant plant;
I felt it often put forth many sweet and heavenly breathings after God,
with a frequent answer from God: so that k never sought his face in vain,
or asked without a satisfactory return.
I found also, as naturally praises and thanksgivings to arise and spring to God,
from the holy root,
as ever before I had known a wicked wrathful nature to cast up mire and dirt,
and to send forth fear, horror, trouble, and distrust.
Now my joy was full, and often a cry arose in me unto God,
to keep me poor and needy in the daily cross; nothing in self,
but out of self-willing and working,
in the daily dependence upon the Lord in this pure birth,
finding him to be a treasury and storehouse of all supplies; whereby both alone,
and in meetings, I felt him often to arise in great power and glory,
to the constraining me to sound out like a trumpet, living praises unto my God.
Out of the mouth of this seed of eternal life,
would words proceed within me as I sat in meetings with God`'s people,
and at other times,
which I was moved to utter with my tongue often times in the cross to my own will,
as seeming to my earthly wisdom to be void of wisdom,
and most contemptible to my natural understanding,
not knowing the end why I should keep such words: yet I was charged with disobedience,
and deeply afflicted and troubled in my spirit, when I neglected to speak them forth;
and sometimes some others have spoken the same words,
while I was doubting in the reasoning about them; and then I was much exercised,
that it should be taken from me, and given to another that was faithful.

=== How I Came By My Ministry.

The Lord having thus pleased to reveal his Son in me, showed me in myself,
the deceitful workings of the man of sin, in the mystery of iniquity,
and his exaltation in the temple of God, being worshipped as God,
above all that is called God, and rightly deserves that name, although little known,
or taken notice of by the creature,
because of the exaltation and rule of another thing which appeared as God, but was not.
All this I saw in the light of the Lord; and not only so, but felt by experience,
how God raised up the younger, and made the elder, in possession in me,
to serve the younger, which the Lord had now raised up, as the beggar from the dunghill,
and to know him who is both Prince and Saviour,
and Minister also of the true tabernacle which God had pitched, and not man;
which I did not know in myself, while the first tabernacle was standing,
neither the holiest of all, while the veil was over my heart,
which veil I found to be done away in Christ,
and the new and living way thereby set open into the holiest of all.
Of this way, the Lord made me a minister, and commanded me to publish what I had seen,
felt, and handled, and passed through, of the word and work of God; the which,
I gave up to do, being thereby fired out of all my reasonings and consultations,
lest my own wisdom would either get up again, and so I should lose my own condition,
and be judged as forward in my own will, by those I went to minister amongst;
or I should go and appoint meetings, and gather people together,
and should sit as a fool amongst them, having nothing to say unto them;
with many other reasonings, too numerous to mention particularly.
But being followed with daily stirrings and motions of life,
and a command to go to such a place by name,
signified to me by God`'s Spirit in my inward parts; which I obeying,
I found a blessed effect; and many were at that time converted,
who to this day abide in the truth, and others died in the faith.
The circuit and compass of counties, was showed me by the Spirit of the Lord,
where mostly I should labour in the work of the Lord;
though not restrained from travelling elsewhere,
when required thereunto by the motion of the same Spirit:
so that I could not contain myself,
but words would proceed from me in meetings where I was ordered among God`'s people,
both at my own habitation, and elsewhere; and many places were opened unto me,
where I was to go; and having smarted so deeply by God`'s judgment upon my soul,
for disobedience in this kind, I gave up to God;
and I found him always to be larger in his goodness than I could expect,
and more abundant in pouring out of his Holy Spirit, than my faith could reach,
even to the breaking of my heart many a time before him in secret, when no eye hath seen.

To omit all the hardships and losses, as to my family, and all outward concerns,
through which I was obliged by a close pursuit of
God`'s anger and displeasure if I disobeyed,
as well as by the sweet continuance of the melting and heart
breaking sense of God`'s tender mercy to my soul,
in bearing so long with me, and at last doing so much for me;
as not only to free me from all my foes, but also from my fears of death,
which all my life time I had been subject to at times;
until I felt Christ come to deliver me; praises to God forever.
But also, I was constrained to obey the Lord, in going up and down, as he sent me,
about his message; taking no thought what I should say,
but cried to him often in my spirit.
Keep me poor and needy, believing in thee, and then I shall speak from thee,
and for thee; yea, from the engraven sense of God`'s mercy upon my soul,
that he sent his servants from`' far to seek me,
and to preach the everlasting gospel unto my poor lost soul;
and why shall I refuse to go to seek others, whose souls are lost, as mine once was;
and shall I not love my neighbour as myself?
And I knowing God`'s terrors, shall I refuse to persuade men in Christ`'s stead,
in obedience to his motions in my soul, to be reconciled to God,
knowing him to be a consuming fire?
After this manner were the workings of my mind, and the thoughts of my heart;
and when I gave up to go as before, when, and where the Lord directed me,
and to come again when he called me, I never failed of his assistance.
But when to my own sense, I was the weakest in all the meeting,
and was as an empty vessel without one drop to relieve any,
wondering what was become of all my knowledge, and now I should sit as one in poverty,
but in a posture fitter to be ministered unto, than to minister to others;
and yet as I had sometimes nothing to give, so I had no wants as to my own condition,
only for the sake of others that expected something from me, I was exercised in my mind;
but by degrees learned to die unto the will of God, whether by silence, or speaking,
to be content.

I began to minister about the year 1656,
after I had been some months in Northampton prison,
for being at a meeting with God`'s people,
where I came to learn divinity through deep outward sufferings,
as well as inward exercises,
witnessing the opening of the sealed mysteries of God through the woes;
for after the first and second woes were past,
new seals were opened into the mysteries of God.

And thus hath God made prisons to be as the schools for the true prophets,
or nurseries for true divines:
and then being preserved in much fear and awfulness of God,
from the deep sense I had of his majesty and purity in my heart;
I spoke of him as I felt his requirings thereunto,
and his rewards were in my bosom as a most sweet and comforting cordial,
that did lift up my spirit above all discomfortings, both from the enemies within,
and without; although both oft-times sorely beset me, even like bees on every side;
yet God`'s blessed power and presence in me, and with me,
furnished my heart and tongue with suitable matter to the conditions of the auditory,
above all fear of any thing or person present.
I might swell a volume with this subject,
but this is spoken to the glory of the Almighty God,
the comfort and encouragement of his ministers that abide in his counsel,
and the abasing of all flesh,
that the all-sufficiency of his Holy Spirit may be trusted in, and relied upon,
as the only supplier of his ministers and people, that go forth in his name.
Amen.

This Holy Spirit hath been to me both meat and drink,
as the Rock of old that followed the Israelites: yea, ten times, as I remember,
have I been in bonds,
and not only incurred the sentence of premunire with my brethren at London,
but also have been tried for my life in the country,
and all for a good conscience to my God: but this Holy Spirit never left me,
but many times hath made me to sing in prisons,
and often at the bar did bring fresh courage; who by its virtue hath bound judges,
and quite confounded envious witnesses, that thought to destroy the innocent;
but by this Holy Spirit all turned to my joy: my help is in it,
and my comfort flows from it, and my daily request is to my God,
that all his people may in all things be guided by it,
that he forever may be worshipped in it,
and his blessed truth may be preached through it, that neither wit nor parts,
outward learning nor gifts, persons, nor forms, may ever be set or esteemed above it;
but that we all, who have been baptized in it, may forever be found drinking into it,
while in the body; that when we all come to lay down the body, we may do it with joy,
both to the praise of the riches of his grace,
and the comfort of those that shall survive us in the same truth.
Amen.

[.asterism]
'''

In giving an account of the doctrines which he preached, and in a belief of which,
says he, "`I die in full assurance of a resurrection unto eternal life,`" he declares,
viz.: "`That God only is to be worshipped, and not any image or likeness,
either of God the Father, or of his Son Jesus Christ, or of the Holy Spirit,
proceeding from the Father and the Son; nor the Virgin Mary,
nor any image or likeness of the Virgin Mary; or any other saint departed, or yet alive,
ought to be worshipped or prayed unto, etc.
I always believed and taught, that neither the Pope, nor his Papists,
or any other man or men, have power to pardon sins, past, present, or to come,
or to give indulgences for sin; or that their doctrine of purgatory,
or prayers for the dead, were according to truth,
but quite contrary to the Holy Scriptures of the Old and New Testament,
and contrary to the doctrine of Christ and his apostles.

"`And I do not, nor ever did believe, that the church of Rome, or the papal church,
is the true church, out of which there is no salvation; or that the Pope, or see of Rome,
hath any authority derived from Christ Jesus, or any of his apostles,
to be head of the true Catholic church; or that he, or the see of Rome, jointly,
or severally,
have any jurisdiction or supremacy over the said Catholic church in general,
or myself in particular; or that it belongs to the Pope,
or authority of the church or see of Rome, to be sole judge touching matters of religion,
or sense of Holy Scriptures;
or to command the least tittle of doctrine or discipline merely from his,
or their own power and authority, without warrant or license from the Holy Scripture.
He or they in their so commanding, are not only tyrannical, but anti christian,
and repugnant to the royal office of Christ;
and such I believe to be his and their doctrines of transubstantiation and elevation,
and worshipping of the host or wafer after consecration,
with the using of their cream and spittle,
and their penances upon their confession to a priest;
and all the rest of his and their inventions whatsoever; I ever did,
and still do deny and abhor the same, as false and contrary to true Christian religion.

"`I believed and preached that the worship of God is spiritual, and not carnal,
in all its parts and ordinances, and ought not to be imposed by any outward force,
but performed by the inward leadings of God`'s Spirit;
and he that thus worships God in the Spirit,
his faith carries him beyond his performances, with righteous Abel, and preserves him,
that he is not lost or drowned in the form, like Cain;
neither falls he short of the glory of God, nor of his assurance of acceptance with him.

"`I believed and preached the truth of the Holy Scriptures of the Old and New Testament,
beginning my declaration most times with scripture sentences,
as moved by the Holy Spirit; not daring to open my mouth, until I was inwardly satisfied,
and believed, that these were the words, given me of God, to speak to the people, where,
by his providence, he ordered me to preach the everlasting gospel,
according to the assistance of his Holy Spirit; which was sometimes longer,
and sometimes shorter, as the Spirit of God enabled me, and gave me utterance.

"`I never wanted assistance suitable to the service God called me unto,
as my will and mind was subjected to the orderings of this Spirit,
freed from all forethinkings, or forecastings how to begin, or what to say,
or how to go on when I was begun; but the more passive I was,
the greater enlargements I had, with the sweetest inward contentment of soul,
and yet in deepest abhorrency of myself at the same time;
finding it always safest and best, both for my own preservation,
and blessed success and effect upon the auditory; not daring to give way,
or yield to the least tickling applause, praise, or commendation, either arising in,
or from myself, or from any others: but still felt an inward cry to my God,
to keep me poor and humble;
and mostly when I was poorest in spirit at the beginning of the meeting,
as I thought none so poor and empty as myself, then I was most assisted,
and the meeting most refreshed; and in my spirit, at that time,
I was commonly as poor and empty when the meeting was ended, as I was before it began.

"`I believed and taught, that there are those in our days,
that do speak and write from a measure of the same
spirit which the prophets and apostles had;
yet neither believed, nor taught, that either myself, or any other,
were to be equalized unto them, either in our speaking, or writings;
either in the same degrees, discoveries, or attainments:
as it pleased God to make them his instruments,
in delivering those holy records and oracles of his mind and will,
contained in the Holy Bible, for an universal service unto the children of men; so far,
as by the providence of God, their writings came to be spread abroad in the world.

"`I believe the Holy Scriptures to be the best outward rule in the world,
yet cannot rightly and truly be understood but by the Holy Spirit that gave them forth;
and that the Spirit of God can and may give the inward
virtual knowledge of Christ unto salvation,
where the Scriptures, outwardly, never came to give the historical knowledge of him;
and in a sober sense what Chrysostom saith, to the godly and faithful,
the Scriptures are not necessary; for so saith the apostle.
There is no law provided for the just.
And again, it behoveth us to have no need of the Scriptures,
but in all things to show ourselves so pure and clean, that instead of books,
we might use the grace of the Holy Spirit.`"

"`Nevertheless,
I believe that the Holy Scriptures ought to be received upon the authority of the Spirit,
evidencing the truth thereof unto the conscience,
and not only upon the bare authority of any church or council whatsoever:
Theodoret, Hist. lib. 2. chap. 7. saith,
"`The evangelical, apostolical, and prophetical oracles,
do plainly instruct us by a touch or feeling of their majesty or divine power.`"

"`Neither any visible church, so called, or any outward councils,
have authority or dominion over true believers`' faith towards God;
because this doctrine, that they have authority over other men`'s faith,
is not only contrary to Scripture,
which testifies the apostles had no such authority or dominion, 2 Cor. 1:24.
1 Pet. 5:3, but also being a dangerous influence upon our belief,
to subject our faith to human resolutions.

"`I believe that without supernatural grace there is no salvation:
for although that which is called good nature, be as it were,
an excellency of the first creation,
and hath such a delightful union with itself in others,
which is as like to the union of the measure of grace as may be;
yet it being but of the first creation, cannot of itself,
bring man or woman into the happiness and bliss that appertain to the new creation,
or world to come; yet its worth is such, that a little grace easily commands it,
while that which is commonly called ill nature,
will hardly be ruled by a far greater measure.

"`That nature and grace are of different natures or kinds;
for that good nature seldom alters,
except by some great outward trial or inward conflict;
whereas supernatural grace often causes inward disturbances,
by reason of its opposition to everything of a contrary nature to itself:
but it is greatly to be feared, that this good nature, I have been speaking of,
is too much taken for, and believed to be, the supernatural grace;
especially where this Divine grace is not arisen in the heart, or come into dominion,
to bear some rule in the understanding, and authority in the inward parts.

"`That the new creature, or new creation, spoken of in the Scripture,
partakes of the divine nature, which is Christ the image of God,
also called Christ formed in us by the divine power, 2 Pet. 1:3-4,
compared with Gal. 4:19, which is something substantially in the regenerate,
whereby they cry and call in their hearts after God,
and after all those things that are well pleasing in his sight,
the life or spirit of his Son in them being plainly and frequently heard within them,
leading and guiding this new man, as it were, by the rule of its own nature,
according to Gal. 6:16,
which the truly regenerate experimentally find to
be much more than mere qualities or habits,
as some imagine; for by faith in its divine power,
they do enter into that rest which remains for the people of God, spoken of, Heb. 4:9.
Such as are entered into this rest, have also teased from their own works,
as God did from his, when he rested from the creation on the seventh day,
and sanctified it.
So by following the guide and rule of the new creature,
the regenerate labour against all that would hinder their entrance into this gospel-rest,
as not to do their own works, nor to speak their own words,
nor think their own thoughts on this sabbath day, but still remember to keep it holy,
lest they fall short by unbelief; for the Word of God within them,
is quick and powerful to make it manifest,
when any distrust or negligence is given way to; and that Word pierces,
to the dividing asunder of the soul and spirit, etc.,
and is a discerner of the thoughts and intents of the heart.
All things are manifest in his sight,
and open and bare before his eyes with whom we have to do.`"
