== Chapter 2

=== An Epistle of Love to All That Are in Present Sufferings, Whether Inwardly or Outwardly.

Upon the first day of the fourth month, 1660, as I was travelling upon the way,
there came upon my heart a deep sense of your conditions;
whereupon I was pressed in spirit to write these following lines.

Many have been the warnings, counsel and advice,
which have been given unto you from the Lord, out of the love that he bears unto you,
who would not have you to perish, but rather that you might repent,
and do your first works, and live; and therefore hath he sent unto you of his servants,
early and late, to forewarn you of the evils and dangers that were coming upon you.
But your hearts were so hardened, through the deceitfulness of sin,
and you choked with the cares of this life,
and your minds so filled and taken up with the present enjoyments of worldly delights,
and fleshly ease, that there was no room or entrance for any thing that came unto you,
though delivered in never so much tenderness and bowels of affection,
from a true sight and deep sense of what must unavoidably overtake you.
Like Jeshurun, you were grown fat, and kicked against what could be said unto you;
looking upon yourselves as so enriched with worldly glory and delights,
and so decked therewith, that you sat as queens,
as if none could pluck you from your throne, or seats,
because of the sureness and firmness of your standing,
as you thought and concluded in yourselves.
And your work was, how to climb up higher, and to soar aloft in your glory,
beyond any that had been before you; that so your families might be great,
and your names renowned to posterity,
and your children enriched with your gettings and possessions;
so that you were just like the wild ass colt upon the mountains and high hills,
snuffing up the wind, and kicking the heel, and laughing at, and having in derision,
all those that came unto you in the name of the Lord, with the word of the Lord;
concluding it to be but the fancy of a drunken brain,
or the offspring of a precipitate zeal, without a true understanding.
So you made light of it, and made no doubt in yourselves, to shake off those things,
like Paul`'s shaking off the viper from his hand,
and like Samson to go forth as at other times; but knew not how,
by that fleshly confidence, and carnal security, and worldly delights and pleasures,
which had made you, like drunken men, not only fearless and careless,
but also senseless of what could be said unto you, or done against you.

So high had you made your nests, that you feared not the hand that could pluck you down;
and therefore it was your manner, in that light, elevated and transported spirit,
with scorn and disdain,
wholly to reject and refuse either the hearing of
such counsels as were tendered unto you,
by message in words or in writing, or otherwise to receive them in feigned humility,
and a complimentary spirit; putting off the more serious hearing or reading thereof,
with Felix, until a more convenient season;
satisfying yourselves with this imaginary conceit,
that you had pleased and given content unto the persons that so spake or wrote to you;
this being your utmost end and design, if by all you could but procure popular applause,
and ingratiate yourselves into any party or interest,
thereby to corroborate and strengthen your seat and standing.
All your confessions, professions, and acknowledgments,
were but like Absalom in the day of his advance, saying with him in your hearts,
"`O that all men would come unto us,`" that there might be none to oppose you,
or disquiet your ease,
and "`we would do them justice!`" but this was to palliate your worldly interests,
that you were with so much eagerness seeking to exalt.
But now is your month come upon you, and the day that was threatened,
and you forewarned of it, hath overtaken you; and it is a day of gloominess and darkness,
and thick clouds; so that it appears to be night, rather than day,
and the sun to be set and gone down, and the shadow of death approaches,
and fears and amazements seem to compass you about as a mighty host,
and your names and posterities to be blotted out,
and ignominy and reproach to be cast upon you, and to be your portion,
from the basest of men.
Instead of crisping-pins, and gorgeous attires and apparel, and mincing with your feet,
and sweet fumes, and odours and smells, shall be stenches;
and that which shall be an abhorring and a loathing unto them,
that you have trampled upon, and thought too mean to converse with.
That conformity to the world, and the greatness and glory thereof,
and that fellowship and communion which you are increasing apace,
with those who have their portion in this life,
even unto them also shall you be a disdain and an hissing; so that you are become,
like Israel of old, as the vines amongst the trees of the forest,
which when it hath left its bearing, and bringeth forth no fruit, is good for nothing,
not so much as to make a pin of, so as to hang a vessel thereon,
but is only become as fuel for the fire.

Woe is me, woe is me for you! What will become of you?
For I am pained, because of the utter desolation that is coming upon you,
even to the utmost!
And then shall those that you have scorned, laugh at your calamity,
and mock when your fear comes, which shall come upon you as an armed man;
and you shall not be able to withstand his dread, because of the load of guilt,
and the weight of sin, that lies upon your consciences, and presseth you down,
and plunges you into the utter darkness, even thick darkness, that may be felt.
For your time of working is over,
and the night in which no man can work is come upon you;
and though you seek to fly as upon dromedaries, and to make a league with death and hell,
and by your compliances with, and your calling to the rocks, the hills,
and the mountains; yet shall they not be able to hide you from the wrath of the Lamb,
nor to shelter you from the indignation of him that is too strong for you.

And though you fly upon the swift, a swifter shall overtake;
for you shall not be able to escape his fury,
though you fly to the uttermost parts of the earth,
yet there shall his hands find you out.
You have numbered him amongst transgressors,
and hardened your necks against his reproof in your own hearts and consciences,
and have had them in derision that have directed you thereunto,
to take heed and to obey his counsel, lest you perished in the gainsaying,
and the spirit of grace ceased striving with you; and then, he that hath suffered long,
and borne the iniquity, withdraws his shoulder, and the word of his power,
whereby he upholds all things: and then you shall bear your own iniquity,
and feel the weight and burden thereof; and then shall you know by woful experience,
and drink of the cup of his fury, without mixture of mercy, or support.
And who is able then to abide or stand,
when thus he ministers pure wrath and displeasure in the fierceness of his indignation,
against and upon the rebellious, who would not hearken in the day of their prosperity,
but were grown rich, and full, and wise, and strong, and said in themselves,
"`We have need of nothing; our tongues are our own, who shall control us?
We know what it is to be religious, and to profess God and Christ, and the Scriptures.
These things we have professed and known, and were once zealous in them, and for them,
and were tender-hearted, and broken in our spirits, and then could we weep and mourn,
and pray and fast, and tell of our experiences, and durst not commit sin,
nor do anything that we knew to be evil, because of a fear that was upon us.

"`Now we are past those things, and mind not the feeling of them;
but account those as possessed with a fanatic spirit,
that say they are moved by the Spirit of the Lord,
to remind us of our former days of tenderness,
and speak so much to us of feeling that broken heart, and contrite spirit,
and true thirst and hunger after the living God, which sometimes we felt;
and condemn and cry against all knowledge and speculative notions,
above and beyond the feelings, as that which will not avail,
nor stand in stead in the day of the Lord.
And these in ourselves we condemned, and the spirit by which they spake to us,
we judged to be fanatical; and therefore it is justly come upon us,
to have that name given unto us by our enemies, which we gave unto our friends:
for if we had not so looked upon them, we would have taken their counsel.
But we looked upon those former times of tenderness in religion,
to be the days of our minority and infancy; and we are now come beyond those things,
and some of us grown past feeling, into a belief, that there is nothing sin,
but what a man imagines so to be; and so are soared aloft,
and mounted up upon the wings of reason and state policy,
looking upon that to be religion, wherein self-security is most preserved and promoted.
And so have concluded within ourselves, that the ground of our former trouble inwardly,
and of the like trouble that is upon others now,
did and doth arise from the distrust of our reason;
and so have concluded all inward feeling and possessing of the presence of God,
and the light of his countenance, to be but the strength of fancy or imagination.
This apprehension and belief hath been strengthened in us by the many experiences
and examples that in our observations we have taken notice of;
namely, what a general and universal defection there hath been in all sorts of persons,
of various judgments and opinions, that have sprung up,
and the respective confidence that they have had of their ways and opinions,
and their proneness to be taken with the glory and riches of this present world,
and equally with a zeal to pursue after them,
when they have had an opportunity to enrich themselves thereby.
And when they have been tried with such opportunities, they have been found too light,
and lost their zeal and tenderness in religion: and therefore from these observations,
we have been strengthened in our belief, that to get wealth and live at ease,
and secure our places, and to comply to any man, or with any thing, in order to this end,
hath been goodness enough, and the very religion of our hearts;
though with our lips we have spoken and professed otherwise.`"

O thou exalted above the stars, who art climbed up another way,
and hast set up thy nest on high, and fenced it about, as with impregnable walls,
whose searedness and confidence is all thy safety;
the Lord is undermining thy foundation,
and he is bringing thee down as with a mighty hand.
He is causing thy fall to be as a mill stone into the sea,
and he is making thine enemies to rule over thee;
even thou that hast been in thy jollity, and making merry,
and sending and receiving the gifts,
in this way wherein the witnesses have lain slain in the streets of this great city.
The Spirit of life from the Lord is entering into them again,
and they shall stand upon their feet, and fire shall come down from heaven,
and consume their enemies, and they shall torment all that dwell upon the earth.
Therefore, hear the word of the Lord, O ye stout-hearted and stiff-necked,
whose hearts are become as an iron sinew,
and whose sins are written as with the point of a diamond.
O tremble, tremble at the word of the Lord, which saith, "`He gave you space to repent,
but you repented not!`"
Wherefore a bed of torment is preparing for you,
and the cup which you gave to others shall you drink,
and you shall squeeze out the dregs thereof.
Woe and misery is coming upon you, and languishing and distress shall cover you;
and because you will not hear the voice of the rod in the day of your fulness,
you shall hear the voice of wrath and desolation,
and flood upon flood shall come upon you, and billow upon billow shall overflow you;
so that you shall not be able to escape, nor fly from his presence.

O hear, hear the word of the Lord, and hearken, that yet, notwithstanding,
your souls may live; and if it be possible, may be redeemed out of the land of darkness,
and the deep captivity in which they are plunged.
Do not fly, nor make a league with thine enemies;
neither let despair and unbelief swallow thee up; but bear the indignation,
because thou hast sinned.
Lay down thy back, that the plowers may plow deep furrows; lay thy mouth in the dust,
and say, "`I have sinned, I have sinned;
and for my iniquity are these things come upon me, and because of the weight thereof,
am I pressed down; and if the Lord arise not, I must perish under them.`"
Think not upon revenge "`for vengeance is the Lord`'s, and he will repay it.`"
For thy rising up, and thy restoration, and thy recovery, must not be by an arm of flesh,
nor by a bow of steel, but by the revealed arm of the Lord,
that must bring salvation to thee; and therefore must thou be patient, and still,
and quiet, and ascribe righteousness to the Lord, until he arise.
For through sore judgment must thou be delivered,
and all thy ways must be hedged up with thorns,
that thou mayest not be able to pass from under his hand,
nor from the smart of his stroke.
For this is the day of the recovery, not only of thy soul out of the pit,
that waits in the patience and long suffering, and out of the mire and the clay,
wherein thy feet have stuck fast,
so that thou hast not been able to run in the ways of righteousness; but also,
of the recovery of the corn, and the wine, and the oil, which he gave unto thee,
and thou hadst forgotten that he gave it thee, that thou mayest return unto him,
from whom thou art fallen by thine iniquity.
For was it not better with thee in the day of thy meanness and poverty,
not only of spirit, but outwardly,
when thou hadst not those possessions in the earth as now thou hast,
nor faredst so deliciously as now thou dost?
Was it not better with thee then, than it is now?
Let the witness of God answer.
And therefore like a bull in the net must thou be cast,
who hast been seeking liberty and largeness for thyself,
but hast not cared how much others were in straightness and captivity;
and therefore is the day come upon thee, wherein the same measure,
thou measuredst to others, is measured to thyself.

Therefore thou must bear in patience, that the seed thou mayest know,
which the Lord`'s love is unto, and feel it in thyself; that which hath suffered long,
even all this time of thy wantonness.
For this is the seed which cries unto God, though thou regardest not the cry thereof,
because of thy fulness, and because of the noise that hath been in thy heart,
both about keeping what thou hast already gotten,
and how to enlarge thy barns to hold more;
but the cry of the poor hath not been regarded, even that seed in thee,
which hath groaned for deliverance; and sometimes, because of the anguish thereof,
thy soul cried out for distress; though, through the variety of thy pleasures,
thou endeavourest to murder it, and to stop its cry.

Is it not now an acceptable time, to speak a word in due season to thee,
from one that is sensible of thy burden, and travails with thee for thy deliverance?
O that thou wouldst hear, that thy soul might live!
And even now, when the Lord is as one retired into his place,
and all thy comforts and lovers seem to stand at a distance from thee,
and thou art as one termed desolate and forsaken,
and the wrath of the enemy is ready to swallow thee up, in telling thee,
there is no hope for thee, and that the day of thy visitation is over,
and that the pit will open its mouth,
and swallow thee up in the sight of all thine enemies.
Arise, arise, thou captive, thou exile, thou outcast of Israel,
thou that art termed forsaken, both in thine own eyes,
and in the eyes of all that behold thee; this is the day of thy deep visitation,
hear the voice of the rod, and know the hand of him that smites with it,
that through the chastisings and the rebukings, thy soul may be recovered.
O cease from man, and from all revengeful thoughts,
and hearken not to the counsel of thine own heart, neither lend an ear to the wicked,
and lean not to thy own understanding.
For God`'s thoughts are not as thy thoughts, neither his ways like thine;
thine are thoughts and ways of evil, his of good:
therefore judge the disquietness of thy mind with that grace and light,
that gives thee the sight and the sense of it, and say not,
"`He hath shut up his lovingkindness in forgetful ness, or will be merciful no more.`"
Fear not thou, worm Jacob, though all tread upon thee, be thou still;
for thy deliverance must be from the Lord: and that is the seed, that lies low under all,
that is dumb, and opens not his mouth in revenge; that lies down in his will,
and drinks the cup, because it is the Father`'s good pleasure.
This is the seed, to which the blessings belong;
and it is that which must hear the word of the Lord, and come out of Egypt,
to worship God in his own land, that it may be set free;
from which he cannot withhold his bowels, nor the strength of his love;
but that it might be set free, that he might render double unto it,
beyond whatever entered into thy heart to conceive.
And this is the seed that the Lord hath blessed, and that can be content both to abound,
and to suffer want; and to be abased, and how to receive at the hand of the Lord,
and give it again with the same freedom that it was received:
and though it hath nothing in the world, as to the enjoyments of the world,
yet it possesseth all things, in that its kingdom is not of this world.
Neither is it a seed of so low a descent, and so ignoble an offspring,
as to have its delight or, joy in this world: but though it hath lain amongst the pots,
and been as in the manger, yet must it have the wings of a dove,
and in the simplicity and innocency thereof, must it mount up over the world,
and have its rest with its father Abraham.
And this is the seed that follows his steps, and forsakes all,
to go to the land that the Lord shows it; and believes in the hope, against the hope,
and staggers not through the weakness of faith,
by considering the reasonings of the earthly birth, or fleshly spirit;
but is strong in the faith, and gives glory unto God and submits unto him,
to let him do what seemeth good in his sight.

O Friends! had you hearkened unto this, and let it gone free,
then had not this day come upon you, nor this hour of darkness overtaken you;
and therefore now be wise, and receive the instructions of the Almighty,
who speaks unto you in the secret of your hearts, that you may hear his voice, and live.
For he is saying to you, as once he did to Adam, in the cool of the day,
now the heats are over.
Where are ye?
And what have ye been doing?
Have ye not sinned, in eating that which was forbidden,
and in feeding upon that which was likely to make wise, and was beautiful to the eye,
and pleasant to the taste, but is become as gall and wormwood in the belly?
In this day of adversity, when you come to consider where you are,
and what you have been doing, are you not indeed naked?
And are you not flying, as he was, to the bushes,
and for shelter to every imagination that springs up in your minds,
and counsel that is given to you from the earthly spirit, either in yourselves or others?
And are you not sewing fig-leaves, and making coverings for yourselves,
to mitigate the offence, as he did, by saying, "`The woman that thou gavest me,
deceived me?`"
And so you are covering and hiding by excuses and pretences,
that which in the day of your simplicity and tenderness
you would not have been ashamed of,
and since, in the day of your prosperity, have gloried in as your crown.
O do not so, for the Lord will not be mocked; for such as you have sown,
such shall you reap.
Be not like Israel of old, to add evil to evil, not only in forsaking the fountain,
but hewing out inventions and excuses, which will not hold in this day of your distress;
but be upright-hearted and single to God, seeking out no covers, nor sinful compliance,
lest you lose this day of visitation also,
and the little glimmering of hope that yet remains for you,
if you persist not in your wickedness, but on the contrary, if you do,
ye shall go down to the pit, where there is no Remembrance of him.

=== To You that are Called Public Preachers, or Ministers of the Gospel, and are under present sufferings, or possessed with fear, that you shall suffer either in relation to your places or consciences.

Why are you afraid?
And wherefore are your hearts disquieted?
If you have preached the gospel in season, and out of season,
will not that keep you in peace?
Or is not your gospel, the gospel of peace?
Or are you afraid, because you made use of the gospel, to preach up war?
If you have discharged your duties faithfully, and sought no man`'s goods,
but their good; if so, will not the good overcome the evil?
And if you suffer for righteousness sake, are you not blessed?
And if you can live upon the gospel, will not that maintain you, and save you?
Why are you then troubled?

If another generation, more righteous than you, spring up;
and those that have been long humbling, and under a sharp rebuke,
be restored to their places again, and you put out; and if they preach better,
and live better, that their moderation may be known unto all men;
and that they are not so greedy of filthy lucre, as you were; nor use that rigor,
and severity, and inhumanity, which some of you have done,
in casting poor people into prison, and separating man and wife,
until they have died in a jail, and that for a thing of naught, as for smoke-penny,
and a garden-penny, and such like trifles as should not be named amongst Christians,
much less amongst those who call themselves the ministers of the gospel; and all this,
because for conscience sake they could not let them gather that had not scattered,
nor him reap that had not sown,
nor his ox feed in that corn which he had not trodden out,
nor pay him wages whom he never hired, neither did any work for him: if those ministers,
that come after you, shall not do these things,
nor make shipwreck of faith and a good conscience, by serving the times,
and complying with worldly interests, to enrich themselves, and fare deliciously thereby;
but shall at all seasons preach freely, giving good example both in life and doctrine;
oppressing no man`'s conscience, but giving freely, and freely receiving;
not following your steps, but the steps of Christ and his apostles,
who chose to obey God rather than man; and not to comply for self-safety and advantage,
who spake as the spirit gave them utterance; and not what men commanded,
contrary thereto; will not the Lord bless them?

But if these, that come in your places, shall follow your steps,
in all or any of the things aforesaid, will not the Lord drive them out,
and cast them off, for their rebellion and unfaithfulness, as he hath done,
and is doing of you before them?
And therefore why should you be troubled, except for the load of guilt,
and weight of oppression, and merciless cruelty, that lies upon you?
And for these things you ought to be humbled,
that if it be possible you may be recovered out of the gall of bitterness,
and bond of iniquity; that so your souls may be saved,
in this day of your visitation and sore chastisement that is coming upon you,
and you restored to your former integrity, and uprightness of heart,
which sometimes some of you were acquainted with, before you walked in the way of Balaam,
to attempt to curse Israel, or to run greedily for gifts and rewards.
O that there were an ear open, to hear the voice of this chastisement,
that your souls might be recovered out of the snare of the enemy.

=== To all those that are in present sufferings in their hearts and minds, because they do not understand the end of the Lord in these late transactions.

Know ye the seed of God, even Abraham`'s seed; and as that comes to be raised,
and brought forth, and bear rule in your hearts,
so shall ye understand the mind of the Lord,
and he will not hide from you the thing that he doth.
Are you strangers in Israel,
that you know not the causes and provocations that the Lord hath had from day to day,
from a gainsaying and disobedient people, who draw near him with their lips,
but their hearts were far from him; and who said, "`Is not the Lord amongst us?
No evil shall come unto us:`" who had provoked him to jealousy from day to day;
and after many a warning given unto them by the servants of the Lord,
and his overturning time after time, yet would they not hearken,
but rebelled more and more, and continued to oppress the innocent,
and for their own ends gratified the ungodly,
and cried up those whom the Lord by his word cried against?
And not only so, but what wickedness was there found within their gates,
and injustice in their courts, and pride and fulness of bread within their palaces,
exceeding any that had been before them; besides, their profession of religion,
made subservient to state policy; brother betraying brother,
and one friend undermining another, and all to promote self,
which the Lord had thrown down in others, and they, in an eminent way,
were setting it up in themselves?

How could the Lord but reckon for these things?
Was not his suffering long, and his patience stretched out to the uttermost,
and the measure of their iniquities full?
And was it not then righteous with the Lord,
to give them up into the hands of the treacherous dealer,
who themselves had dealt treacherously one with another, and to others?
And so hath he repaid them with that which they requited others withal.
Therefore say not you, Why hath the Lord done this?
Nor busy your minds or thoughts about the cause of his dealings;
but mind that in your own hearts, that accuseth you for your treachery against the Lord,
who hath showed thee, O man, what is good, "`to deal justly, to walk uprightly,
to show mercy, and to walk humbly with thy God.`"
Keep thou to that in thine own heart; for it is that which may be known of God,
which is manifested in thee: and by that he shows thee, O man, what is good;
and to that must thou take heed, lest thou drop into the same snare with those,
whose fall thou art admiring, and so their case become thy case.
If thou standest by faith, yet except thou believest in that within thyself,
that shows thee what is good, thou canst not avoid falling likewise: neither canst thou,
by beating thy brain, or musing in thine understanding,
understand the end of these things; for they are too hard for thee to find out;
until thou return into the sanctuary, which is the grace of God manifested in thee;
and thereby shalt thou learn the fear of the Lord, whereby the heart shall be kept clean,
and thou kept out of their snares.

=== To you who are in present power, who are raised up by the fall and overthrow of those that went before you.

Do not you boast yourselves in your own strength,
nor glory over those who are under your feet,
but consider the end of the Lord in these things.
For, not for your sakes hath he wrought this change,
that you might glory in the arm of flesh, or exalt yourselves, because the day is yours;
but know assuredly,
that it was to be avenged of an hypocritical and gainsaying generation, who said,
and did not.
And therefore is he arisen in righteousness to plead with them, and that those,
whom they have ruled over, might once more rule over them;
that you by their fall might take warning,
and not lust after that which they lusted after, nor oppress that which they oppressed,
both in themselves and others; but that you might undo the heavy burdens,
and take off every yoke, and let the oppressed go free; which if you do,
both as to civil and spiritual rights, which they promised to do, but did not,
then shall you prosper, and the righteous rejoice in your government:
but if those things continue, for which they were cast out before you,
then shall the indignation of the Lord smoke against you,
and your fall be great and speedy, and that into mischief, and shall rise no more.
O that you had hearts to consider the languishing state
of this nation! that righteousness might be encouraged,
justice promoted, sin and iniquity stopped, and you a terror to the workers thereof.
Let not that be found amongst you,
which was found amongst them that were cast out before you, to advance any sect, party,
or opinion; but let him of every sect, party, or judgment, that fears God,
and works righteousness, find protection from your government:
so shall partiality be shut out, and distributive justice,
and impartial righteousness be administered unto all,
and run down our streets like a stream.
Then shall it be well for you, that the Lord hath so long chastised you,
that you might learn righteousness, and hate iniquity; so shall the nations be healed,
and the distractions thereof composed.

But on the contrary, if iniquity be sheltered under your wing, and unrighteousness,
profaneness, and ungodliness, be countenanced, encouraged, or connived at;
then shall the fury of the Lord smoke against you,
and his righteousness shall be revealed, to throw you down,
and that with an hand more eminent and remarkable, than that which brought you in;
and the sound and report of your destruction and extirpation,
shall exceed and go farther, and strike the nations afar off, with greater astonishment,
and amazement of spirit.
Even their ears shall tingle, and fright shall take hold upon them,
because of the revelation of the righteous judgments of the Lord,
against a rebellious people, whom he would have healed again and again,
but they would not, but insulted and revolted yet more and more,
and abused the patience and long-suffering of the Lord towards them,
and turned their deliverances against the Lord, to puff and swell themselves up,
beyond any that ever was before them: if this be your state, you shall perish suddenly,
and that without remedy; and then shall you know, that the Lord hath spoken by me.

=== To all that fear the Lord, and whose hearts are upright with him, and yet are sensible of the suffering state of the Church that is in God; because of the oppressions, and weights, and burdens, that lie upon the righteous seed.

Fear not, nor be dismayed with any amazement.
For your sakes will the Lord arise, and shake terribly the earth,
and remove that which is shaken, that that which cannot be shaken may remain.
Your heads will he lift up above all your enemies,
and the day of your redemption shall draw nigh,
and Satan shall be trodden under your feet,
and you brought into the mountain of the Lord,
where ye shall feed upon the fat things which he hath prepared upon his holy mountain.
This mountain shall you know to be over, and on top of, all the mountains;
and here you shall abide, and dwell in the dwelling-place that is upon Mount Zion;
and upon all your glory shall be a defence, and none shall be able to make you afraid.
Then shall ye know him that shall stand the last upon the earth,
and ye shall receive dominion from him, whereby ye shall reign with him forevermore.
Therefore watch ye unto prayer, and be you diligent in the work of the Lord,
that you may finish with faithfulness the testimony
that he hath given you to bear for his name`'s sake;
and know assuredly, that nothing can harm you, while you follow that which is good.
Watch ye in the light of Christ, that ye may be kept out of that part, in yourselves,
which appertains to this world, and the things thereof,
in that good part which shall never be taken from you,
in which the god of this world hath no part.
There is your safety forever; there is the faith known, that stops the mouths of lions,
and rebukes the roarings of the sea, and keeps in the calm, as in an ark,
when all the world shall be overwhelmed with the Lord`'s wrath and displeasure.
Then shall you be safe, and plant the earth with righteousness;
and the former things shall be passed away,
and the old heaven and the old earth melted away, and passed as a scroll;
and the new heaven and the new earth, wherein dwelleth righteousness, shall remain,
and the inhabitants therein shall rejoice, and shall sing the songs of Zion,
and the songs of the Lamb, the praise of him that hath saved them.
For your kingdom is not of this world,
but he hath chosen you to be as pilgrims and strangers in and to the world.
Although your bodies be in the world, yet use it and possess it,
as though you used and possessed it not;
that you may be known to be the redeemed of the Lord,
that are seeking a city that hath foundations;
and your conversations may be known to be above the earth, with all its glory,
and you be saved out of all, and raised up over all, by him that throws down,
and exalts at his pleasure.

This is the word of the Lord to you all; you are the Lord`'s host,
and he will go before you, and be your rear-ward; and by you, and through you,
will he bring mighty things to pass, at the sound whereof the nations shall tremble,
and at the hearing whereof the earth shall be astonished,
because of the Lord`'s appearing in his sons and daughters:
unto the brightness of whose arising, many shall come from far,
and at whose feet the riches and the glory of the Gentiles shall be laid down:
and these things, you that are faithful shall know.
Be not inquisitive which way the Lord will bring these things to pass;
for his own arm shall do it; and that not by might nor by power,
but by his Spirit will he remove the mountains, and all that lets, out of the way.

Therefore be not faithless, but believing, and dwell in the patience,
out of that which would limit the Holy One, either to time or means;
so shall yon come to the overcoming and to be more
than conquerors through Christ your life,
who is manifest in your mortal flesh.
And concerning the times and seasons, I need not write unto you.
For you know perfectly in yourselves, that the day of the Lord so cometh,
as a thief in the night; that when they shall cry peace and safety,
then sudden destruction shall come upon them; for now is their hour,
and the power of darkness: but dwell you in the secret place of the Most High,
under the shadow of his wing, and enter into your privy chambers,
and shut the door till the calamity be overpast.
For it shall not be long until the Lord shall visit his seed,
and gather it from off the barren hills and mountains, that they that have gone astray,
through the allurements, pleasures, and vanities of this world,
shall be gathered into the fold; then shall there be one fold, and one shepherd;
and the sons of God shall sing together, and the morning stars shall rejoice,
and clap their hands for joy, because of so great salvation.
They that are faithful shall know and see this, and be glad:
for the Lord will not leave you, nor forsake you; you that are bold, valiant,
and faithful for his name, and love not your lives unto the death,
that you may finish the testimony of Jesus; but are as sheep appointed for the slaughter,
and are like those that are killed all the day long;
yet the Lord my God will arise for your sakes, and will utter his voice from Zion,
and his thunderings from Jerusalem; and you shall be glad with his salvation,
to the praise of his name forever.
Amen.

[.signed-section-signature]
John Crook.
