== Chapter 5

[.blurb]
=== Glad tidings proclaimed to the upright in heart, who walk in the light of life: and judgment pronounced against Babylon and her merchants, whose rewards must be according to her works.

Dear flock of my heavenly Father, whom he hath visited and chosen out of the world,
to be his peculiar treasure; whose tears are bottled up,
and whose groans are in remembrance before him,
that he cannot withhold from doing you good.
Oh ye faithful and valiant ones for his truth upon earth!
He hath seen, he hath seen your afflictions, sufferings, and trials,
and hath weighed them in the balance, and tempered your cups,
that you may say of the bitterest of them,
My God is the portion of this also.
Hath he taken thy valiant men, and removed them hence?
What is it for?
Because of distaste that he hath taken against thee, or to bring thee,
O Zion! to live in this life that never dies?
The former is to be searched into; and according to the discovery from God therein,
the deep sense is to be impressed upon thy spirit; that his will may be done,
and his end answered.
Shall I take up a lamentation, and say, How are thy mighty men fallen,
or removed by death?
And how hast thou been tried,
O daughter of Zion! even since thy coming forth from amongst the pots,
and since thou hast appeared out of the holes?
Though thy days be but young, and thy beauty scarcely discovered;
yet how hast thou been hunted?
Not only when thou wast in the wilderness, and desert land,
but since thou art on thy way to Canaan: how hath Amalek vexed thee,
and the nations everywhere been troubled at thee?
Art thou born unto it?
And must it always be so?
Must war still follow war, and new tempests arise so soon as the calms appear?
What, no time given thee to put on thy beautiful attire,
and to show thyself forth to the alluring of the nations?
Yes surely, thou shalt have a day, and thy glory shall shine,
and thy beauty and comeliness be made manifest, as well as thy blackness and deformity.
He is but emptying thee from vessel to vessel, that thou mayest not taste of thy lees;
but that thy words may be as new wine, to refresh the hearts of the mourners,
and as apples of gold set in pictures of silver, to take the eyes of the beholders;
that it may be known, that thy food is not that which will corrupt,
but upon the tree of life, whose leaves shall heal the nations,
and whose fruit shall not fail, but in every month and change be green.

Oh then! why shouldst thou not be content,
and thoroughly satisfied with all the dealings of thy God towards thee, and say,
"`It is the Lord, let him do what seemeth good in his sight;`" he will bring me forth,
after he hath thoroughly purged me, and I shall shine as the sun in lustre, and triumph,
after the darkest day, and thickest clouds.
Then shalt thou see clearly, and understand the end of the Lord,
as well in taking away thy mighty men, as all the rest of his dealings towards thee;
how that it is not only from the evil to come, but that their blood might cry,
now their bodies are dead, louder, and more powerful than when they were living.
For know, O Zion! to thy comfort, and Babylon! unto thy sorrow,
that though their bodies be dead, their blood speaks,
and the spillers thereof shall not escape in the
day of the inquisition of the mighty God;
for from his hand thou shalt have justice, and the nations shall know it,
and be ashamed and confounded forever.
For the spirit of the Lord is upon me, to proclaim glad tidings in thine ears,
in the authority of his life, and dominion of his name; and to tell them,
that thy warfare is nigh to be accomplished,
and thy redemption out of the hands of all thine enemies, hastens;
that thou shalt worship and serve thy God, in the beauty of holiness,
and land of the living; when Babylon, with all her upholders and adherents,
shall not have whereon to lay their heads, or set their feet;
but as she hath dealt to Jerusalem, so shall it be measured to her again;
"`The word of the Lord hath spoken it.`"

Only wait ye in the shepherd`'s tents, with the flocks of the companions,
and these things you shall see assuredly brought to pass: and the time hastens,
that he that hath wisdom shall read, and he that hath understanding,
shall understand the number of the beast, and of his name; for it is the number of a man:
he that can reckon, let him.
The key to open this mystery, and to unlock this secret,
is the brightness of the coming of the Son of Righteousness, shining unto the soul,
to give the discovery of every motion of the spirit of man in the things of God;
that it may pass no longer for the Spirit of God, but may be ceased from forever,
in praying, in speaking, with all the rest of God`'s worship and service;
that all may be done by the spirit of his mouth, who hath the key of David; and openeth,
and none shutteth; and shutteth, and none openeth.
Then shall be read and distinguished the ministration from the ministrator,
that when he removes, the ministration may not be adored,
but the Lamb followed wherever he goes: so shall there be no more sea,
but the former things shall be passed away, and a sea of glass mingled with fire,
appear in the room thereof, and the followers of the Lamb standing by it,
as with harps in their hands, and praise in their mouths, unto the Most High,
that lives forever.

Oh my dear friends, brethren and companions,
whom my soul greeteth with these salutations of love and good tidings!
What shall I say to you all, that may be as oil to make your faces shine,
and wine to make your hearts glad, in the midst of all your besettings, huntings,
and temptations?
Your God sees, and beholds, and ponders all your trials; leave them all with him,
and cast your care wholly upon him: for by all your care,
not one cubit can be added to your stature.
He will bring to pass his purpose, and your desires.
O ye upright in heart! be faithful unto him, and follow those things that make for peace;
and take heed of this present world, that neither its riches, its frowns, its fears,
its sufferings, nor its pleasures, may move you out of your tents;
but that the signs of the coming of the Son of Man may be always in your eye,
lest either the marrying, or giving in marriage, spoken of,
or the beating of the fellow servants, do overtake any of you;
and then the kingdom of heaven be indeed like unto ten virgins, five wise,
and five foolish.

These things are written, not to upbraid any, but to forewarn all,
that they stir not out of their tents; but dwell continually in the lowly mind,
preferring one another before themselves; cherishing the good in all,
and strengthening the weak hands; dwelling as Saviours upon Mount Zion;
for it is easy to judge and condemn, but hard to save.
So shall ye be known to be children of the Most High,
and as epistles written upon one another`'s hearts, seen and read of all men;
and the blessed presence of your Father will be with you,
and his glory will not cease to rest upon you:
which is the desire of my travailing soul for you all; who am

Your brother and companion, in the faith and patience of Jesus,

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
From visiting my Father`'s children, the 17th of the Twelfth month, 1662.

[.blurb]
=== A true and faithful testimony concerning John Samm, the servant of the Lord, who finished his course, by laying down his life in Northampton jail, for the Truth of Jesus, the 16th of the first month, 1664.

[.salutation]
Dearly beloved of the lord,

Although many of you are not ignorant of the departure of John Samm out of the body,
and for what cause he was in outward bonds,
which was for meeting with the servants of the Lord;
and what his life and conversation was,
together with the ministry committed to him by the Lord,
as well as his faithful discharge thereof, is well known unto you: and I might be silent,
if this were the only end, to tell you of these things;
for is there such a stranger in Israel, among you all, as knows them not?
But notwithstanding, I have a testimony in my heart, from the Lord, on this behalf,
and do desire it may find acceptance with you, to stir up your pure minds,
to be sensible of the Lord`'s dealings with you in his own particulars;
and also of his providences and disposings of those, that are near and dear unto you all,
as I know this servant of the Lord John Samm was, unto all that thoroughly knew him,
and had inward acquaintance with him.

For his education, it is well known in Bedfordshire where he dwelt:
as also his conversation, which was just and honest among men,
before he was convinced of the truth;
for the sake of which he suffered imprisonment five
or six times for bearing testimony to the same truth,
which at last he sealed with his life in Northampton jail,
where he first suffered imprisonment, about the year 1656,
in which prison he ended his days, as he foretold, saying, Northampton was the first,
and will be the last.

For his life and conversation, I can speak to it,
for I was perfectly acquainted with him, both outwardly as a man,
and inwardly as a Christian;
as a man he was endowed with a competent measure of understanding, and did improve it,
unto that end, in the managing of the creation, for which it was given him;
being discreet, sober, and of good report among men,
and his carriage courteous and loving unto all.
Much more might be said of this nature, which I omit.

And as a Christian, he was holy, harmless, patient, meek, valiant and bold,
contending earnestly for the faith which was once delivered to the saints,
and in which he himself, as a saint, did walk, live and die.
Christianity to him, was not a talk, but a life; for rather than he would deny it,
he suffered loss of estate, liberty, and life itself: witness his often imprisonment,
and his laying down his life at last for the same cause.

As a minister, he had a dispensation of the gospel committed unto him,
in which he was a faithful labourer in the work thereof,
with great zeal and fervency of spirit,
taking all opportunities and occasions in the wisdom of the Lord, as moved by him,
to deliver his message unto all people, of all estates and degrees,
that he might be free from the blood of all men.

His gift was large, his utterance plain to be understood, his words savoury and powerful,
not painted with man`'s wisdom, but as given him of the Lord,
being often spoken in much authority,
cutting deep to the wounding of the wicked one in man,
and easing of the poor and needy prisoners,
being often mindful of the captive daughters of Zion,
as of the pure seed in deep captivity, that he might reach it help.
When his words began to reach it, he was as one transported with joy;
and when it was once raised, and come forth of the prison-house, the song of Moses,
and of the Lamb, was in his mouth, with much joy,
and great gladness of heart unto the astonishment of the wicked,
and filling the hearts of the righteous with great joy,
through the overflowings of his cup, and aboundings of God`'s love in his heart:
in which state his face was full of dread, and did speak as one having authority,
and not as the scribes: besides, the melody of his voice,
sometimes sounding out the high praises of the God of Israel;
and at other times the blessed state of the righteous,
as they stood in union with the living God, and one with another.
Oh! how have I seen him make the earth to tremble,
and the hearts of the upright to overflow with joy and gladness,
through that abundance of life that hath run through his vessel,
unto the forcing of water out of the rocks, and tears out of the eyes of the saints,
in great abundance: his hymns and sounds, sometimes were as flames of fire,
consuming the drossy matter, and at other times, as swords and spears, cutting down,
and thrusting through the tall cedars and lofty oaks, and wild beasts of the wilderness:
which did echo to the true seed, and often made sweet melody in their assemblies,
when but few words were spoken by him.

[.blurb]
=== An exhortation unto all the righteous; especially those that were partakers of John Samm`'s ministry.

Did Joseph seek a place where to weep over Benjamin his brother, though yet alive?
And can ye, O ye sons and daughters of Joseph,
refrain from mourning for the loss of a father to many children,
whom he had begotten in the Lord?
And is there a time when the true ambassador of peace may weep bitterly?
Can it be more seasonable at any time, than when the Lord takes away the righteous?
And hath he not done so to many valiants of late, whose trumpets alarmed the world,
and made many dead to arise at the sound thereof?
What was the cause, and wherefore the Lord hath done it,
becomes every one to make inquiry in their own hearts; and the rather,
because there is need, yea, great need, of valiants in this day, the harvest being great,
and the labourers few.
And why the Lord should lessen the number,
seems to challenge a diligent inquiry at every one`'s hand,
to find out the cause thereof: and let me stir you up, all ye that love the Lord,
to search every one his own heart, with the light of Jesus: and for this,
let my harp also be turned to mourning, and into the voice of them that weep:
for indeed I will tell you.
Oh ye children of my Father! my soul hath deeply considered this matter.
And I have this answer; The Lord will do what pleaseth him,
with the instruments of his choosing: and who hath been his counsellor?
He will raise up, and lay aside, at pleasure; for he will have no idols of jealousy,
lest it come to pass, as when he made the brazen serpent at Nehushtan:
neither will he have his work neglected, nor his servants slighted,
whom he sends forth in life and power.
He would have his people to wait upon him in their own measures,
every one as they have received, in it to keep close to him,
that they all may be taught of him, and have the rejoicings in themselves,
and not in another.
And the Lord will yet raise up instruments to fulfill his purpose,
for his work shall prosper.

By these ways and dealings of his,
he would have his children`'s hearts made loose to all things under the sun,
with their lamps burning, and lights shining,
having the loins of their minds girt about with the girdle of truth;
keeping close unto the Lord with a pure heart,
that he may yet further make known unto them his mind and will;
for although you are now become the sons of God, it doth not yet appear what ye shall be;
but this know, the more and oftener ye see him, the more like to him ye shall be:
and let this be your care, that he may be always before you, that you may not be moved.

And my dear friends, keep low in your minds,
and delight to be often in the deeps with God.
Oh watch!
I even beseech you all, as dear brethren,
that by the Lord`'s taking away of his servants of late,
that have been blessed instruments in his hands,
you may come the nearer unto that teacher, and hear his voice daily,
which cannot be removed into a corner; that ye may all say, in truth of heart,
we are come unto that ministry which cannot be taken away by reason of death.
Oh that you may all feel more of this ministry in your assemblies daily,
and keep in that seed of life, where you live with the spirits of those just men,
whose bodies are removed from you.
Indeed I feel the Lord mightily at work in this his day; be but still,
and you will see his wonders as in the days past: let love abound among you,
as at the beginning, and be pure and clean in heart, and you will see,
by all God`'s dealings, what he aims at,
which is certainly to raise up his own life in you all, over all the world,
unto his own praise, and your joy forever.

All you that are sensible of the taking away of dear
J+++.+++ S. as being often refreshed by his life,
and comforted through his ministry,
sink down into the fountain from whence he had all his supplies;
and drink ye of the same blessing the Lord,
that the fountain is in Christ the promised seed, unto whom feel your daily access,
oh ye beloved of the Lord!
Say in your hearts with my soul, O God! it is enough that we have thyself to go unto;
and that we can in thy life, enjoy communion with the spirits of the just ones:
and lift up your heads overall the world, and be not dismayed with any amazement,
either inward or outward, for your Redeemer lives, and your ransomer will not tarry.
And you that are full of sorrow, by reason of your temptations and trials,
which are many, and that your own strength is so small; I say unto you all,
lift up your heads; for you that cannot live without Christ,
but feel your daily need of him, he will not leave you, nor forsake you.
Thou art a true heir of him, that canst not live without him; to thee he will come,
and will not tarry; and in the mean time, as a good soldier, endure the hardship:
it is but yet a little while, and he will appear without sin unto thy soul`'s salvation.
For I feel thee, and do travail for thee.

Oh thou well beloved!
How are my cries unto my God for thee, who laments in thy spirit for want of the Lord,
and can hardly be persuaded of his love to thee, thou art so uncomely in thine own eyes;
and thou lookest upon his dealings, both within, in thy spirit, and without,
in his taking away those instruments whom thou lovest, and by whom thou wast refreshed,
as being in wrath against thee, and for thy sake: well I know thee,
and am to testify unto thee, in mine, and thy Father`'s name, that he doth behold thee,
and his eyes do pity thee, and he is waiting to be gracious unto thee,
that in an acceptable time he may commend his love unto thee, and thy salvation is sure,
oh thou travailing soul!
And I could even put my soul in thy soul`'s stead, to ease thee a little.

Well, my cries are for thee, that thy faith fail not: so unto our God give up,
and when thou art sinking, as to the bottom of sorrow, there is a hand to support thee,
and thou wilt feel it in the lowest dungeon, and darkest deep.
Be thou still, and my God will be thy interpreter, to let thee see, know,
and understand thy state and condition; with whom I leave thee,
in that bosom where Lazarus dwells safely, and at rest, when Dives is tormented,
and hath not one drop of that mercy with which thou art filled,
to the praise of our God forever.
Amen.

[.blurb]
=== Some reasons why the people called Quakers do absent from the public way of worship, and cannot conform thereunto, though they are exposed to great sufferings because thereof.

We are a people that have desired,
and diligently enquired after the true knowledge of God,
and the way in which he is worshipped; in which way we desire to walk:
and after much seeking, and serious consideration, we do find,
and are persuaded in our hearts and consciences.

[.numbered-group]
====

[.numbered]
_First,_ That God is a Spirit, and that his worship is spiritual;
according as Christ hath said, John 4:24. And that none are true worshippers,
but such as worship in the Spirit, and in Truth.

[.numbered]
_Secondly,_ That men must first feel and receive a measure of the Spirit of the Lord,
before they can come to know the true way of worship,
which is only learned in the Spirit, ver. 22, 23.

[.numbered]
_Thirdly,_ That no man upon the earth, can or ought to prescribe how, or after what manner,
God Almighty is to be worshipped, so as to impose any practices upon men;
but is to leave that to him, to direct them by his good Spirit,
in things pertaining to his worship; and he is to persuade them thereunto:
and that they ought not to be compelled or forced to the true worship;
much less to that which is so justly suspected by many people,
not to be the true way of worship.

====

And it doth appear to us, that the public way of worship,
or the worship of the church of England, is very different from this spiritual worship:
for we see, that they have not received the measure of the Spirit of Christ,
which leads into all truth, but they daily rebel and transgress against it,
doing those things that they should not,
and leaving undone those things which they ought to do;
so that they are without spiritual health: and these cannot be the spiritual worshippers;
for they that do worship in the spirit, do feel health and peace in it.
And therefore we have good reason to absent from the public way of worship.

And because that those, who do frequent that worship,
are not born again of the Spirit of Christ, John 3:3.
but are still in an unregenerate state,
following the pleasures and vanities of sin, and living in all manner of wickedness,
as swearing, lying, drunkenness, murder, cozening, and cheating,
and what other evils may be mentioned, which may be found among those worshippers;
and these are the works and fruits of the flesh, and not of the Spirit of God, Gal. 5.
And therefore we do absent from that worship.

Besides, they do not seek to draw and win people by love and tenderness,
and by the example of a good conversation, but labour by violent force and compulsion,
to bring people to their worship; which the true worshippers and Christians never did;
and persecute, and cause such to suffer, who are otherwise minded,
that cannot come to their church and worship, according to their prescriptions;
which the true worshippers never did, but said, "`If any were otherwise minded,
God should reveal the same unto them,`" Phil. 3:15.
and they did not by force impose their religion upon others.
But we do believe, that imposing religion upon people, is of antichrist;
and that all that do so impose, are in the way of antichrist; and we do, and must,
absent from them.

And also,
we find their ministry is much different from the ministry of the true church of Christ,
both in call, maintenance, doctrine, and conversation;
for they were "`ministers of the spirit, and not of the letter,`" 2 Cor. 3.
Neither were they called by man, nor taught by man the things which they did preach;
neither did they "`receive it from man, but by the revelation of Jesus Christ,`" Gal. 1.
and they had "`received his Spirit, by which the deep things of God are revealed,`" 1 Cor. 2.
But these ministers are made at Oxford or Cambridge, by learning natural languages,
and old books and authors, and serve such a time there, before they go forth;
and when they have attained that, then they run, when the Lord never sent them;
and they use their tongues, and say, He saith it, when the Lord never spoke to them,
nor called them forth to preach his word.
They are made ministers by man, and sent out by man,
and two or three hundred pounds a year calls them thither; and there they will stay;
and such the true prophets and servants of the Lord witnessed against, as may be seen,
Isa. 56. Jer. 23. Mic. 3.
The ministers of Christ did give freely, as they had freely received,
according to Christ`'s command. Matt. 10.
But these ministers receive and force tithes from the people,
which Christ came to put an end to, Rom. 10:4. The apostle said,
"`The priesthood being changed,
there is made of necessity a change also of the law;`" by which law, tithes were paid, Heb. 7.
which the ministers of Christ never received, much less to force people to pay them,
but did witness against them;
for they pertained only to the priests of the first covenant:
and so in their maintenance we find them contrary to the ministers of Christ.
And also they differ in their doctrine; for the ministers of Christ did preach,
that people might wait to receive Christ into their hearts,
and that they might know Christ in them, else they were reprobates;
and if Christ was in them, the body was dead because of sin,
and they came to be dead unto sin.

Every particular member of their church was to know the Spirit of Christ in him;
"`and if any man had not the Spirit of Christ, he was none of his,`" etc. Rom. 8.
But these ministers tell the people, that they are Christians, and the church of Christ;
though they know nothing of this in them, but live in sin and unrighteousness,
and are dead to truth, and feel nothing of the operation of the Spirit of Christ in them,
but still sin against it, doing that they should not do,
and leaving undone that which they should do, and are not saved from sin,
nor made free by the truth.
They tell them, they must never expect to be free from sin,
nor to know the revelation of Jesus Christ, as former Christians did,
nor to know the power of God, to work mightily and effectually in them,
to destroy the works of the devil, while they are on this side the grave;
and so keep them in blindness and ignorance, ever learning, but still laden with sin,
and divers lusts, and never able to come to the knowledge of the truth, which makes free,
as we have seen; and therefore we have denied them.
We believe, with the ministers of Christ, that the truth makes free;
and that it is possible to know Christ so made manifest within,
as to destroy the devil`'s works, and to save from sin; and that he that is born of God,
sins not.
We say, we believe that such a state is attainable on this side the grave;
and yet we acknowledge, there is a state the saints knew, and passed through, in which,
if we should say we have no sin, we deceive ourselves, and the truth is not in us;
but if we confess our sins, he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness:
and this was spoken to little children in the truth, that they should not sin, John ii.
But there were fathers, that had known the truth, and young men, that were strong,
in whom the word of God dwelt, that had (take notice) overcome the wicked one.
Many other things might be mentioned, but these may be sufficient to show,
why we deny that ministry, which hath not profited the people at all;
but they are proud and covetous, as thousands do know.

Again, we do absent from the public way of worship,
because of its deadness and formality; because we cannot find,
that the immortal souls of people are refreshed therein,
nor that true and spiritual comfort is received thereby: and we do believe,
and upon true search and examination, do find, and also are persuaded in our consciences,
and that by the Spirit of the Lord, that the most part of their ceremonies and practices,
in their worship, are but vain traditions of men, and no heavenly divine institutions;
and we may say, as the apostle said in another case,
"`They do not make the comers thereunto any whit
the better;`" but they are still miserable and dead,
and want that which only can give life and satisfaction to the soul; to wit,
the knowledge of Christ`'s appearance in themselves, and of his life and virtue.

And having seen these things,
that they want the Spirit of the Lord to exercise them in their worship;
that they are not born of it that they want the fruits of it;
that they force and persecute people,
that cannot for conscience sake conform to their way of worship;
that their ministry differs from the ministry of Christ, in call, maintenance,
conversation and doctrine,
and is the very same with the false prophets and deceivers in the days of old,
being found in their very steps and practices, that their worship is dead, formal,
and carnal, and doth not give satisfaction to the soul; we cannot conform to it,
but have denied it upon just ground, and in conscience to the Lord do absent from it;
and not out of obstinacy, as some would accuse us.

And again, we absent from it, because we have found a better way,
in which we can trust our souls: and find health and peace, and spiritual comfort,
and true satisfaction, in this way in which we now walk with the Lord,
and worship him in spirit and truth;
and we find his living presence in our assemblings together,
in the worship and service of God: for we meet together to wait upon him,
and to perform holy duty to him, and speak as his Spirit moveth in us,
and gives us utterance, and pray in the spirit, and this only is acceptable to him.
This is spiritual worship,
when the Spirit of the Lord exerciseth man in the things he performeth towards God:
and if his spirit doth not stir or move in us, we are silent,
waiting to hear the Lord speaking in our souls;
and this is according to the saints practice.
And because we have found great peace and satisfaction to our souls in this way,
in which we now walk, we cannot deny it, whatever we suffer;
and choose rather to obey the Lord, that we may have and feel his peace in our hearts,
than to obey men, to avoid all sufferings.

And because we would not lose that peace, and make shipwreck of our faith,
we cannot conform to the public way of worship;
and not out of any willfulness or obstinacy.
We desire to spend our days in the fear of God,
to walk in justness and righteousness towards all men,
and to do unto all men as we would they should do unto us;
to love God with all our hearts, and our neighbours as ourselves;
and to avoid the iniquities and abominations that daily
abound among those that are of the public way of worship.
And we dare not riot in the day time, nor spend our precious time in vanity,
nor waste God`'s creatures, and spend them upon our lusts,
which will be cause of God`'s severe judgments upon men and nations.
We cannot go with multitudes to do evil,
but must have respect to the Lord God that made us, to live unto him,
that we may die in his love and favour,
and that we may be heirs of that kingdom which is everlasting;
into which the sayers Lord, Lord, must not enter, but those that do his will.
And this is that we seek, and which is our only end and aim, the Lord knows;
and if for this we must be hated and afflicted, we cannot help it:
for we must not deny the Lord, but will trust in him,
though we perish for our obedience unto him;
and because this is our desire and resolution,
we do absent from the public way of worship,
and cannot have fellowship with the unfruitful workers and works of darkness,
but do rather reprove them.

=== And as for our refusing to swear:

We would have all men to know, that it is not out of obstinacy or willfulness,
that we do refuse, or as though we had any reserve to ourselves,
because we cannot swear allegiance to the king,
as if we would plot or contrive mischief against him.
No, God knows, and his people knows,
and the witness of God in the consciences of our very adversaries,
will one day testify for us, that this is not the cause why we refuse to swear;
but it is only and singly in pure obedience and conscience to the Lord Jesus Christ,
who saith, swear not at all; and this is his command unto his followers:
"`Though it was said by them of old time, thou shalt not forswear thyself,
but shalt perform thine oaths unto the Lord.`"
They might then swear, for it was commanded; but now Christ being come,
who is the end of the law, and fulfiller of it, saith, Swear not at all:
by which it is clear, that all swearing is forbidden;
for the law did forbid and prohibit all vain and frivolous swearing.
If these words of Christ did reach no farther, than to prohibit that,
as some would limit them,
then Christ had only forbid that which before was forbidden by the law;
but it is very plain his words extend farther,
because he repeats what before was forbidden and commanded, and then goes on farther.
But I say unto you.
Swear not at all, etc.
And how he could have spoken more fully, I cannot tell.
Also the apostle James preaches the same doctrine, with the same absolute prohibition;
But above all things, my brethren, swear not;
for it was so positively forbidden by Christ,
that he put that as it were above all things, neither by heaven, nor earth,
(mark) nor any other oath: no oath was to be sworn by the true Christians,
who were brought out of the strife, that was among men, into love, and peace,
and good will towards all men.

And truly it is a token of darkness, and much ignorance,
that any man professing Christianity should have any word to say against such a thing,
which is so clearly forbidden.
And how many Christians have suffered since, for refusing to swear,
appears by several ancient histories:
and upon the same account only do we refuse to swear at this day,
having received the Christian spirit, which in us saith, swear not.
And therefore, upon this general account, we cannot swear allegiance to the king;
but we can and have proffered to promise in faithfulness, and do desire,
that the same punishment may be inflicted upon those that break their word and promise,
as on them that break their oaths; and if this were taken, it would appear,
that we make as much conscience, and more, to keep our promise,
as any men do their oaths, and it is to the full as binding to us:
for it is a common saying among men, those that will swear, will lie;
and many that will now swear allegiance to the king, to save their outward liberty,
would soon swear against him upon occasion.
And if it had been known, that ever we could swear in any case, since we were a people,
and would not now swear allegiance to the king;
then indeed there were great cause of suspicion: but we have always denied to swear,
in any case, since we knew the truth, and had the Spirit of Christ to guide us;
and have suffered upon divers accounts in former days.
Therefore, in reason and justice, we ought not to suffer in this case,
for refusing to swear allegiance to the king; neither ought men to ensnare us,
because of the tenderness of our consciences to the Lord;
for we have always desired the good and happiness of the king, and all men,
in this world, and that which is to come.
And inasmuch as we live in the fear of God, and peaceably,
it is that which brings honour to good government and kings,
when subjects do live in the fear of God.
And such as do live wickedly, in ungodly ways and practices,
dishonour God and good government, and kings too.
We are for peace,
and deny that spirit that would plot or contrive mischief against the king,
or any man`'s person; for our principle is peaceable,
and leads to love and good-will towards all men;
which is the principle of truth and honesty; as will appear,
when all false suspicions will die, and the refuge of lies, and evil reports,
will be swept away.
Thus we have spoken the truth, in simplicity, desiring that it may be for good unto all,
to whom it may come.

We are lovers of truth and righteousness,
and every one that truly desires to walk therein;
in which alone true happiness and everlasting peace are enjoyed,
by all such as believe and walk in the light of righteousness,
which leads out of the evil way, that the sons of men have long run on in,
in the time of great darkness, which hath overshadowed the earth, shall pass away;
and light shall shine more and more in the hearts of men;
in which all that do walk shall know the salvation of God, and partake of his mercies,
and great lovingkindness, and praise and magnify his glorious name forevermore.

[.signed-section-context-close]
Reading Jail, the 22nd day of the Fifth month, 1665.

[.asterism]
'''

[.blurb]
=== +++[+++The following address appears to have been written while the plague was prevailing in London, and designed to bring those who were in affliction to a proper consideration of their own states, and of the administration of the Lord`'s judgments in the earth, that they might profit by them.-- Ed.]

[.blurb]
=== Compassion to all the Sorrowful, Afflicted, Visited, Tempted, Suffering Seed; whether inwardly or outwardly, in the city of London, or elsewhere in England.

Thus saith the Lord, say to them that are of a fearful heart, be strong, fear not;
behold your God will come with vengeance, even God with a recompense;
he will come and save you.

This is spoken unto you, whose consciences are tender,
having the deep sense of God`'s judgments upon your spirits,
which are now upon the city of London, and other parts of this isle;
whether upon your own persons or families, or as yet more remote from you,
who wait upon the Lord in the way of his judgments;
if possibly he may be entreated by you,
to stop his hand from slaying the righteous together with the wicked,
and those who know not their right hand from their left.
Ye know if his anger be kindled but a little,
that blessed are all those that put their trust in him.

I know your griefs, and am well acquainted with your sorrows; which are most of all,
that ye yourselves have not redeemed the time, as ye now see ye might have done,
although ye grieve to see others despise God`'s laws.
In that for your time ye might have been teachers of others,
ye have need to be taught the first principles of the teachings of God;
as repentance from your dead works, it being your daily burden,
that ye can feel no more life stirring in your hearts and services,
nor any more faith towards God, to draw life and virtue from him;
nor any more of the operations of his hand, and openings thereof,
to fill you with his blessings.
This makes you doubt sometimes, whether ye are the sheep of his pasture,
or of the number of the flock of his hands, by reason of your leanness of soul,
and poverty of spirit; concluding in yourselves,
ye have not yet truly learnt the doctrine of baptisms; seeing ye find so much of self,
and the spirit of this world alive in you, and so little of the hay, straw, and stubble,
yet consumed and burnt up in you; that ye question, many times,
whether ye know the foundation of God laid in your hearts.
And ye find daily so many temptations and vain thoughts lodge within you,
to the disquieting and vexing of your righteous souls,
that ye fear the baptism of the Holy Spirit is not yet attained by you;
seeing your sorrows are so many, and your comforts so few and uncertain,
that ye know not certainly, whether there be any such Holy Spirit come into your hearts.

And for the resurrection of the dead and eternal judgment,
ye fear that ye know little of them,
more than ye have received by the hearing of the ear,
and reading of the letter without you;
therefore ye doubt that your faith stands but in word, and not in power:
because it removeth so little out of your hearts that stood there before,
and giveth you no more victory over the world; but as ye were, so ye are still,
too much in bondage to it, which is your grief; although, too long after,
victory is present with you;
but how to attain and perform it continually over all things, both in words, thoughts,
and actions, ye find not.

Yet ye cannot satisfy yourselves with the common faith, viz.,
That such a state or condition is not attainable,
but rather find cause enough in yourselves, to judge your own remissness and negligence,
in not watching in the light, to keep your hearts with all diligence,
experiencing that now your own folly doth correct you,
because ye have often had precious seasons and opportunities, as a daily price,
put into your hands, but ye improved them not as ye might have done.
Nevertheless, ye dare not, like those, whose foolish hearts are darkened,
lay the fault upon God, as if the reason was, because he denied you power;
never intending to make you perfectly holy, lest your salvation should be of yourselves.
But experience hath taught you otherwise,
in that when ye are at any time most holy and sanctified throughout, in body, soul,
and spirit; ye, are then most meek and lowly,
inheriting the presence and kingdom of God in your hearts.

Further, ye know there would be no variance or discord between the Lord and you,
but for your defects in love to him, and watchfulness to his counsel; from which causes,
flow your miscarriages in life and conversation; and such darkness upon you,
that ye cannot see the salvation of God, crying out as undone; saying,
We are cast out of thy sight, O Lord; wilt thou be merciful no more?
And no marvel, because ye know right well, that if the Lord be always before you,
ye cannot be moved.

Thus far I have traced you, by the footsteps of the flocks of the companions;
although to you they seem as untrodden paths, and like the way of an eagle,
and as a ship at sea: yet be it known unto you,
the same steps have been trodden by your brethren that are in the world,
as the way of the Lord, to show them what was in their hearts,
like as he did to Israel of old.

O that I had the tongue of the learned,
so as to show you the causes of your diseased weaknesses,
that a perfect cure might be received.

First of all, I find your minds abroad,
and your eyes gadding too much in the ends of the earth,
where ye find many wandering like yourselves; which so occupies your minds,
as to strengthen your hands in this evil, and thereby to lessen +++[+++the sense of]
it in yourselves.

Also the wicked one so busieth you, in finding fault with others,
as if ye were to keep their vineyards,
whereby he cunningly enticeth you to neglect your own, under pretence of service to them;
or otherwise, to fill your hearts so with prejudice against religion itself,
as if all men were liars.
Which thing lurking so secretly in your bosoms, that when the winter cometh,
and storms arise, it gendereth to fear and bondage, through the mixture of unbelief,
carelessness, and lukewarm indifferency; all which now appears to be a monstrous birth,
although before nursed and dandled as a most beautiful child,
and none so likely to inherit the kingdom as it; but now ye see it is for judgment,
and must not be heir with the son of the free woman.

Again,--as many by talking of what once they did possess and enjoy,
have lost the sense and comfort of what they should have to support them at present;
so others, by speaking so much of suffering, are made unfit to suffer and at this day,
how many are there, who have so spent their precious time,
in often relating the cruel deaths and hardships of others,
that they are neither prepared to die, nor fitted for trial themselves:
and hence also ariseth the multitudes of their fears and troubles.

Another cause of your fear and trouble,
I find to be the falling of many good and righteous people in this common calamity;
as if the Lord had no more respect to them that serve and fear him,
than to the wicked and profane; seeing what befalls the swearer,
befalls him that fears an oath.
But this comes to pass, that none may presume, and that all may fear before him;
yet the accuser of the brethren wounds you so sorely on this account,
that ye daily feel his stinging, by all tidings that come to your ears,
concerning the Lord`'s visiting the righteous with the wicked,
and little children in their innocency, with grown people in their sins.
As this doth much embolden the ungodly in their presumption,
so it doth discourage the weak in the faith, as if they served God for naught;
not remembering that it is written, No man knoweth either love or hatred,
by all that is before him.
And it is meet it should be so,
because the love and hatred are to the two seeds of Jacob and Esau, which are invisible:
therefore, they that keep not to the light,
in the daily watchfulness through believing in it,
but look out at things visible and temporal, such are unstable in all their ways,
and misinterpret all the Lord`'s proceedings:
whence ariseth such discontentedness of mind, and trouble of spirit,
that they are ready to say with Jonas, They do well to be angry,
thinking they have cause enough for it, even unto death.

Thus doth the evil nature deal with the Lord, when it gets loose from the bit and bridle.
But this is the plague, for people to die in their sins, as Christ said to the Jews,
all must die, but ye shall die in your sins.

Yet hear, O Jacob, and hearken, O Israel, that art afflicted, tossed with tempest,
and not comforted; the Lord will lay thy foundation, as with precious stones;
thou shalt be taught of the Lord, and in righteousness shalt thou be established:
thou shalt be far from oppression, for thou shalt not fear.

A further cause of fear and trouble,
may be the natural temper and inclination of your minds and spirits,
not yet knowing the seed of life, so raised into dominion in your hearts,
as to witness it stronger in you, than he that is in the world;
therefore ye lie open to the storms and blasts of fear and distrust;
notwithstanding the root of the matter may be in you,
yet is it but as a seed sown in weakness, and as yet not raised in power.
By reason of your natural temper, ye may labour more with your own hearts,
than some others do,
and yet not be able to attain that victory and courage which they arrive at;
which makes you conclude, the root of the matter is not in you;
and that one day ye shall fall by the hand of Saul; and your fears do so attend you,
upon every approach of danger, as those that can do nothing of your own selves,
and yet are able to do all things, through Christ strengthening of you.
I know you well, that when ye are naked, none so timorous,
ye knowing self to be of no reputation; but when ye have girt on strength,
and sunk down into the armour of light, none so bold and valiant;
although thou be but a little one, thou art as David, not afraid of great Goliath,
when into the name of the Lord thou art gotten.
Feel me, for I would not have you dismayed, because of this kind of fear:
therefore be ye still; when ye feel it arise in you, look not at it,
but keep your minds out of all compliance with it; and the just that live by faith,
will spring in your hearts, suddenly daunting your fears, and driving them back;
whereby you will witness the power of God to arise in you; by which, through faith,
ye will be kept unto salvation.

But in your journey it will fare with you, as sometimes with Ahaz,
unto whom the Lord said, Ask thee a sign, when the enemies conspired against him;
but Ahaz said, "`I will not ask, neither will I tempt the Lord,`" etc.
In like manner will he find your souls compassed about with evils;
some that ye are guilty of through negligence, etc.,
and others laid to your charge by the accuser, as if because he tempted,
ye had consented; and others also by him threatened to come upon you,
as a just reward for the former:
yet in this very condition the Lord bids you believe in his grace,
that shall be sufficient for you in this great strait; but take heed, at such a time,
lest, like Ahaz, you hastily reply, "`I will not, nor I cannot believe;
neither will I tempt the Lord, in presuming to be quiet and still,
through believing in his light and power, that secretly shows me my duty,
and stirs me up unto it in my own breast, in this close besetting.`"

I say unto you, if ye will not now believe, as in hope against hope,
ye shall not be established; but on the contrary, if ye will believe in the light,
this great distress, and sore siege, shall be unto you,
as the death of Lazarus was unto Martha and Mary; concerning which, Christ said,
He was glad, although they were troubled,
in that it should be an advantage to their faith,
whereby they saw the glory of God in Christ, raising him from the dead.

But I know you are so overwhelmed with fears, many times,
that ye cannot hearken or be still,
like the children of Israel that could not hearken unto Moses,
because of the anguish of their spirits:
even so do your fears and unbelief indispose and
unfit you for any service acceptable in God`'s sight,
whereby ye are ready to conclude yourselves to be without,
amongst the fearful and unbelieving, etc. Rev. 21:8.
But I say unto you, that he who came not to call the righteous,
but sinners to repentance, shall not break the bruised reed, nor quench the smoking flax;
he it is that invites you, because ye are weary and heavy laden;
and whoever comes to him, he will in nowise cast off; for he comes to deliver those,
who all their lifetime were subject to bondage, by reason of the fear of death.

Therefore, take heed ye refuse not him that speaks from heaven,
who appears the second time unto them that look for him, without sin unto salvation,
to set them free, through believing in the truth, which God loves in your inward parts.
This freedom, in due time, ye will reap, O ye that have sown in tears, if ye faint not;
and that ye may not faint, he hath provided a cordial for you, and that near you,
even the Spirit itself to help your infirmity,
and to comfort you by bearing witness with your spirits, that ye are the Lord`'s;
which above all things ye desire to know, and to have the full assurance of.
The counsel of the Lord is unto you in this case, to delight yourselves in him,
and hereby will you enjoy the desires of your hearts; and through keeping his sayings,
which ye will hear him daily saying in you, and unto you, as humble and meek,
in his light ye will abide and walk, and ye easily know his voice,
and his words to be spirit and life; and that ye may be fully assured it is he,
the works which he doth in you, and for you, bear witness of him.
And by faith in him, will he become an inhabitant in you;
for we are all the children of God, by faith in Christ Jesus;
and by faith he dwelleth in your hearts; and hereby will ye know that ye know him,
and have the full assurance of him,
because the Son of God is come to give you this understanding,
by virtue of his being in you, and ye in him, who is true God, and eternal life.

I have now something to say to those fearful, that are without amongst the unbelievers,
and abominable, murderers, and sorcerers, and all liars,
who shall have their portion in the lake; who cannot endure the Lamb,
nor the presence of God, when he sits upon the throne,
but fly to the mountains and hills, in which they have trusted,
to hide them in the day of calamity.
These are of Cain`'s generation, that are better at killing than sacrificing;
and as the fruit of their doings, they are always afraid, and that where no fear is,
even of every man, not knowing whom to trust, as Cain was;
and although such hide their sin, as Adam, they shall not prosper.
But of this sort I have something to say, more at large, by themselves,
and so I pass them by at present.

Others there are, who are yet without amongst the dogs,
unto whom I intend not the children`'s bread before spoken of;
and they are such who are always learning,
but never able to come to the knowledge of the truth, to make them free from their fears,
being laden with sin, and led away with divers lusts;
thinking an opinion of truth will save them,
while they are crucifying afresh the Son of God, and putting him to open shame;
flying to scripture sanctuary, as the Jews did, who searched the Scriptures,
but would not come to Christ; and in a wrong zeal, as the disciples did,
when they would have had those consumed that followed not with them, urging to Christ,
the example of Elias.
But let these know,
that their fears flow from the guilt of sin that defiles their consciences;
which all the sacrifices that they offer day by day, can never take away,
nor make the comers thereunto perfect; because they reach not the conscience,
but still there remains a conscience accusing for sin;
because they believe not in the light to walk in it;
that the blood of Jesus might be known, to sprinkle their hearts from an evil conscience;
that they may witness by it perfection, as pertaining to the conscience.
Therefore these are not free from affrighting, terrifying fears,
because their sins remain;
how confident soever they may seem to be of their eternal conditions,
in that they know not the truth, as it is in Jesus; for if they did,
it would make them free.
Unto such I say, they are yet too high and wise for God,
and therefore must come down to know a meek, poor and quiet spirit within them;
which is of price, beyond all their talk, knowledge, and empty profession of Scriptures,
God and Christ without them, while they have not learned to stand still,
to feel the Spirit of Christ to be their strength and leader within them:
these shall likewise perish and die in their sins,
if they bring not forth fruits meet for repentance,
through that faith which is held in a pure conscience.

But unto you whose hearts are tender, and consciences awakened unto righteousness,
shall the Son of Righteousness arise with healing in his wings;
for ye love his present appearance in your hearts,
and wait for the brightness of his coming, to consume whatever is contrary to himself,
that he may be, and none besides him.
Therefore, for your comfort, I have this to assure you of, from my God and your God,
that he will come quickly, and will not tarry, and ye know his reward is with him;
because ye never enjoyed him, but ye were sufficiently rewarded for waiting upon him.

And these clouds of sufferings, whether sickness, bonds, or banishment,
are but as the evening, which must be added to the morning, to make up the last day,
in which God will perfectly raise up his seed, as well as the first day.
O sing, thou barren, and thou that didst not bear;
for now shalt thou be fruitful in children, and they shall sing together,
as the sons of the morning of this blessed holy day, the new song, which none can learn,
but the redeemed out of the earth:
although now in the evening thou mayest be weeping by the rivers of Babylon,
with thy instrument untuned, because in a strange land.
Behold the bridegroom Cometh,
at whose presence thy sorrow shall be turned into rejoicing,
and thy joy shall none take from thee: but the world shall mourn;
and now is the day of their sorrow begun,
even that great and sore distress of nations spoken of, with that inexpressible woe, woe,
woe, upon the inhabitants of the earth;
which hath been often sounded through the Lord`'s witnesses and servants,
that it may be known there have been prophets in England, and sounding in thy streets,
O London!
But who shall live when God doth this, besides the seed that shall serve the Lord!

Feel it already begin to arise in your hearts,
O all ye that fear the Lord! by all the oppositions it meets withal; and saying in you,
if this be to be vile, to rejoice at the return of the glory of Israel,
I will yet be more vile, and all the lookers on, like Michal, shall be ashamed,
when the seed of David shall be exalted over all,
to the praise of the glory of the name of its God forever: therefore, thou royal seed,
it is good for thee to draw near unto him; that when he takes peace from the earth,
both within and without, that then thou mayest encourage thyself in the Lord thy God,
who is over all blessed forevermore.
Amen.

This is from a sufferer with the righteous seed,
and one that prays and waits for its deliverance out of all its troubles,
in all where it yet groans for redemption, a salutation of unfeigned love.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
The fourth of the Seventh month 1665.
