== Chapter 6.

Truth`'s Progress: or,
A Short Relation of its first Appearance and Publication after the Apostacy.

Containing--1. An Epistolary Salutation.
2+++.+++ All Expostulation.
3+++.+++ The Description of the Truth, as it was declared in the beginning, with its Progress,
Operation, and Opposition.
4+++.+++ The Rise and Ground of the true Ministry.
5+++.+++ To all who have at any time, or in any place,
wrested or misapplied my words or writings, as some have done,
to make them suit with their evil intentions; that they may be convinced of their evil,
and do so no more.
6, That all jealousies, and all false judgments grounded thereupon,
may be removed out of the minds of all concerned therein;
and they cautioned for the future of all such dealings and practices.
7+++.+++ The Author`'s Appeal concerning himself.
8+++.+++ An Exhortation to all, to try themselves by the Truth,
as it was received and published in the beginning.
9+++.+++ That all who are fallen may be restored; and the way of their recovery declared.
10+++.+++ A Word of Reproof to all people and professors,
who encourage themselves and one another to hope for the downfall of the Quakers,
so called, and the Truth which they profess,
because of any thing that befalls them in this world.
11+++.+++ The afflicted soul`'s complaint and cure.

1+++.+++ Dear Friends,--From the deep sense of the great care, love, mercy,
and long-suffering of God, which he hath exercised towards us all,
do I at this time write unto you; desiring the Lord so to direct my heart,
that what is here signified,
may fully and effectually reach every conscience and condition;
that they may be as words in season to every state, hitting the mark;
and as nails fastened by the Master of the assembly, in every particular of you.

If Christ loved the young man, as it is recorded in Scripture,
because from his youth upward he had been towardly, affecting the best things,
and observant of God`'s commands; then, in pursuance of Christ`'s example,
ought every one of us, that are his disciples,
to pity and compassionate all those who have been convinced by the everlasting gospel,
of the way to life and salvation, which some of them have been breathing after,
ever since their young years, and yet now may be hindered, by Satan`'s wiles and devices,
from walking in that way and path of peace and happiness; some by one snare,
and others by other stratagems,
which the subtle adversary useth to beguile the simple withal.

Indeed my heart affects mine eye in this matter, and I could say from my very soul,
O that some arrow out of the bow of the Almighty might wound and slay that enemy,
which hath stopped any in the race which once they were running in, to obtain the crown!
What shall I say unto you, or do for you?
For my bowels yearn after you, and my spirit is grieved for you, night and day,
that are hindered; that ye should come so near the good land,
as not only to behold it afar off, but many of you so near the borders thereof,
as to taste the fruit of it; and yet go back again into the wilderness,
amongst the briars and thorns: what pity is this.

2+++.+++ Shall ever length of time, multitude of business, increase of worldly riches,
offences, prejudices, snares, or temptations, or whatever can be named,
be able to blot out the sweet remembrance of the tender mercies of God unto your souls,
showed unto you in the day of your sore and deep distress,
which I am persuaded many of you once felt, and were in measure acquainted withal?
Shall any heighth, length, breadth, or depth, be able to separate you,
that have tasted of the good word of God, and the powers of the world to come,
from the sensible soul engaging feeling of that love and mercy,
so freely bestowed upon you?
Or to stop your mouths from proclaiming, in the assemblies of his people,
what he hath done for you, when you were very low, even like unto dry bones?
O take heed, take heed! lest your continuance in evil be accounted,
by the pure and just God, a despising of the riches of his goodness and forbearance,
and long-suffering; not knowing that the goodness of God leadeth to repentance.

For who can, with Samson, return to view the dead carcases of the strong lions,
which by the grace of God they once overcame,
and that but while young and green in the truth, and not be melted in spirit,
and broken as before the Lord,
through the sense of the sweetness and freeness of that love and goodness,
that so fully gave them the victory, through faith in his name and virtue?

O! can you remember those years of drought and famine, not of bread,
but of hearing the word of the Lord, which passed over your heads,
when the very heavens were as brass, and the earth as iron, and not be astonished,
that the little black cloud should appear in your day,
which must spread until the face of the whole heavens be covered,
and all the earth be watered thereby?

What were ye, or your father`'s house, or any of us,
when we were as the poor shepherds that kept their flocks by night,
that then the day-star should appear, and arise in our hearts,
and not first manifest itself to the doctors and great rabbles of the time,
that first from them might flow the light of life;
but that God`'s free choice in the promised seed might appear,
to the stilling of every enemy and avenger?
And shall any, that have been eye-witnesses of these things in any measure, draw back,
or be found unthankful to him, that found them out, and ordained strength for them;
when otherwise the devourer had at that time destroyed them?

But lest I should seem to any to be like those the apostle speaks of, that said,
"`Be clothed, fed, and warmed;`" but neither gave them clothes, food, nor fuel,
to relieve and succour them; I shall descend into particulars,
for the clearing the truth,
for the relief and better information of all those principally concerned in this testimony,
and for the keeping of my own soul free from the blood of all men: and bear with me,
if I use plainness, and let no man account me his enemy, because I tell him the truth.

It was the practice of the prophets and apostles in their time and day,
to remind the people of the wonders, mercies, and deliverances,
that the Lord had given to them, and to their fathers; as may be seen by Nehemiah, David,
and others; and by the martyr Stephen, and the apostle Paul:
both of God`'s dealings with them, and with their fathers;
and how the truth grew and prospered, and who were the enemies of it;
and how the Lord upheld his witnesses, and scattered his adversaries:
and also by what way and method those were reclaimed and reduced,
that had backslidden and fallen from their steadfastness, and from the gospel-order:
as in general may be seen by the prophets`' exhortations
and messages to backsliding Israel;
and in particular, Samuel towards Saul, and Nathan to David; and others also,
recorded in Scripture.
In like manner I find it recorded in the New Testament,
that it was the apostles`' practice, to restore from mistakes and irregularities,
by bringing them concerned to the beginning; as in the case of divorce by Moses,
for the hardness of people`'s hearts; but it was not so in the beginning, as it is said.
And also to rectify mistakes, and confirm due subjection in the marriage state;
the apostle instanceth God`'s giving the woman to the man; or,
that Adam was first formed, and then Eve; and also, how Sarah called Abraham lord.
And likewise in the abuse of their love feasts, or breaking bread,
Paul brings them to the beginning, or Christ`'s practice of it at first; saying.
In the same night he was betrayed, he took bread, etc.
As if to bring abuses and mistakes to the first, were to see their last.

3+++.+++ In like manner let me mind you a little of the
appearance and publication of truth again,
as in the beginning, and of its progress unto this day: not at large, in all particulars,
lest I should swell the volume beyond my intention; but, as in a map,
to bring the substance pertinent to the occasion, to the reader`'s view,
in as small a compass as I can, with freedom and clearness.

After the long, grieved, retired, solitary state of the church in the wilderness,
it pleased God, in his appointed time, to cause a voice to be heard, crying,
Make strait the way of the Lord: all flesh having corrupted their way,
and their guides being blind,
there was no hope that ever people could find their resting-place,
which they had so long forgotten: their physicians being of no worth or value,
working no perfect cure upon any of their soul-sick patients; pouring brine,
instead of oil, into their wounds; and giving bitter gall and vinegar to dying men,
instead of reviving cordials; mistaking both the disease, its seat, and way of cure:
applying words and promises to the memory and natural understanding,
as if the malady had been in the head, for want of knowledge in the brain.
When as the people, Mephiboshethlike, were all diseased in their feet; not looking,
as they should, unto their walking, to make straight paths for their feet,
and the law of God to be a light unto their feet, and a lantern to their paths.

Now the word of the Lord was precious in those days; for there was no open vision.
And the voice which at first was heard in the wilderness, crying,
Prepare the way of the Lord, came afterward to be heard upon the Mount,
out of the most excellent glory; confirming his appearance, saying,
"`This is my beloved Son, in whom I am well pleased.`"
So mighty was the word of God, that it grew and prospered,
cutting down whatever stood in its way, the strong oaks, as well as the tall cedars;
levelling many high mountains with the low valleys.
It was so quick and powerful,
that it discerned between the thoughts and intents of the heart,
and divided between the flesh and spirit, shell and kernel, form and power,
painted Jezebel and the true Spouse, and between the marrow, and the bone that cased it:
discovering to all men their thoughts, making all flesh to tremble in its progress:
whence, in scorn, came the name Quaker to be given to those that came under its power.

It abased itself and made it of no reputation; and it made the cross to be endured,
and taken up daily, to all excesses and superfluities, whether in meats or drinks,
apparel, or honours and dignities below;
in whatsoever they fashioned themselves to this world, and its glory,
that was not of the Father; and to follow only those things that made for peace,
and whatsoever was of good report; reforming throughout, in body, soul and spirit,
as well as outwardly, in gestures, and postures, and language, and behaviour,
diverse from all people; which made them a gazing-stock to men and angels,
and to be hated of their near relations: yet,
through taking up the cross daily to those things,
they despised the shame that came upon them from the wicked world.
The truth of all these things is known to them that were eye-witnesses from the beginning.

It made many to cast away things of great value, as in the apostles`' days,
their pictures, laces, and other needless attires and superfluities, with which many,
(that the word of eternal life met with in its progress,)
were then adorned after the fashion of this world.
By its authority, it spoiled the image and pomp of this present world,
insomuch that the very visage of many was so marred,
that they became a wonder to their former intimates and acquaintance;
laying low all sorts of people, bringing down the honourable of the earth,
in that day to deny their titles and attendants; some from the judgment seat,
and others from their great gains, in their needless traffic;
making many valiant men of war to put up their swords, and become men of peace,
and to learn war no more.

But what shall I say of the wise and learned, men of all professions, religions,
and opinions, that were gathered from all quarters of the land,
as it took them in its progress; and honourable women, of all persuasions, not a few?
Making some to leave their nets, and others the receipt of custom,
to become followers of truth; though not to disdain their lawful callings,
but to return to them again; as Paul did to his tent-making, and others to their nets,
upon occasion.
An ancient father once said, "`we never read,
that those who were called from the receipt of custom
returned thither any more:`" observing thence,
that some callings, once laid down, ought never to be taken up again.

4+++.+++ What unwearied pains the truth made many take, to run to and fro,
to inform and forewarn their relations and acquaintance,
lest they should neglect the day of their visitation; and, they, knowing the truth,
should become guilty of their blood, because they had not forewarned them;
is known to many witnesses.
How many, like David`'s worthies, brake through an host and camp of dangers,
to bring the water of life to the thirsty souls; and what blows and bruises,
imprisonments and suffering they met withal,
there was scarcely in that day such a stranger in Israel, but knew it right well.
And will it not be charged by the Lord, that sent them,
as great ingratitude in those that received of their water, but now have forgotten it,
so as evilly to requite them for their good?

How tender were the hearts of those made in that day, who received the word of life?
And what was too dear for them to part with, for the advancement of truth,
and its testimony?
Nay, what zeal, what care to preserve those then begotten,
lest they should be turned aside by the enemy?
If but an evil report was occasioned through any indiscretion,
what pains was taken to stop it?
Or if any nakedness appeared in any, what love and pity was used to cover it;
lest the world should know it, and blaspheme the pure name of God thereby,
and the person perish in the snare of the devil,
for want of a little balm and restoring medicine?
I need not mention, except to provoke those that are in a declension in these things,
the love that abounded, and the delight that the sheep of God`'s pasture took,
in being often together, their hearts cleaving to each other,
like the soul of Jonathan and David; many hours seeming but a short time;
and often meeting together, although through great hardships and difficulties,
appeared as nothing,
in comparison of the great joy and comfort they found
in coming together to meet with the Lord,
and to feel the glory of his presence amongst them.

All which is known, and much more,
unto those that were eye and heart witnesses from the beginning.
Let me remind you also of the great care and circumspection
that every sound heart had at that day,
of whispering or backbiting any,
or of letting in any hard or prejudicial thoughts or jealousies,
concerning any that were in the least measure in the truth;
but much more touching the least of those that had the message
of glad-tidings to deliver from the great God;
whose care was, to approve themselves in all things, lest the gospel should be blamed,
either through life or doctrine.
How few and savoury the words of all convinced were,
that had their hearts seasoned with the grace of God,
to the edification of all that conversed with them; being watchful,
lest their hearts should be sown with mingled seed,
or that they should mix spirits with the world; being principally careful,
that their hearts might not be overcharged with the cares of this life:
not at all affecting great things for themselves, nor to get a name in the earth;
but to stand approved in God`'s sight, which they valued beyond the judgment of the wise,
and of the honourable in the earth, or of any of the sons of men;
is also fully known to them that were converted in the beginning.

What the testimony itself was in the beginning, as to doctrine and good manners,
I need not mention in particular;
because it is also known and testified unto by many witnesses,
as it was in the beginning: as also, its form and dress,
in which it first appeared upon the stage of this world.
Only let me remember you of its disguised habit,
that none of the worldly wise could know it, or receive it in reality.

How it did anatomize and dissect men in their inward parts,
whereby they came to see and understand the mystery of iniquity in all its workings,
lineaments, and dependencies, with the man of sin, his seat and government in them,
above all that is called God, and how he was worshipped as God;
which was the cause why those, who thus learned of Christ,
appeared so rough and sharp against hypocrisy in all professions,
of what form or opinion soever they were,
from a true certain sight and knowledge they had
of the slates and conditions of all people,
in their several ways and worships; discerning the insides of others,
by the spirit of truth, which had given them a certain knowledge of themselves.
From whence, as truly learned, and like skilful physicians,
they came to understand both the diseases, and the cause of them,
and also the right way of cure for them; and durst not daub with untempered mortar,
as the unskilful builders had done before them;
nor heal the several hurts and diseases of people slightly; but first removed the cause,
and then the effect ceased.
Thus the Lord blessed the truth, and prospered it from the beginning,
in the hearts and hands of those who continued faithful witnesses of it, and to it,
as it was in the beginning: blessed be his holy name forever.
Amen.

But the way of cure being so sharp and terrible to all flesh,
many that assented to the skill of the physicians, and were convinced of the truth,
after they had tasted a little of judgment, as the sharp medicine,
to eat through all the deadness and darkness within them;
all the passages of life being dammed up,
and the power working strongly to remove all those obstructions, many escaped,
and fled the judgment, not being able to endure the mightiness of its operation,
and therefore never came through the work of regeneration; but got loose,
after a deadly wound, and so became only formal for a time.
Such, although they might come out with us in the beginning, yet went away,
some to the earth, and others to their old courses, according to the proverb,
having opportunity of returning, they returned again with the dog to his vomit;
which manifests, they did not stand by faith, nor were born of the immortal seed.

These, like the star John speaks of in the Revelations, fell from heaven to the earth,
and then became chief factors for the evil one,
being entrusted with the keys of the bottomless pit,
and had power to hurt all but the green thing, for the time suffered,
which will not be long,
beyond those that never attained to a state higher than the earth;
and such revolters are profound to make slaughter; and are like unto Gehazi,
coveting after those things, which that master refused, whom they pretended to serve.
But they have been, and shall be also requited with like plague and punishment;
for the leprosy of Naaman came upon Gehazi.
Let him read that can understand.

Now, friends, it is in my heart, as God shall enable me,
somewhat to let you understand the cunning workings of the enemy,
in his opposition to the truth, and to betray the simple; to this end,
that they who have been beguiled by him, may be delivered out of his snare;
and others prevented by their example, that the truth may prevail in and over all.

The contests about religion hitherto, have not been so much about the trial of spirits,
as between opinion and opinion,
and between interpretation and interpretation of Holy Scripture.
And yet it hath been the complaint of all sides,
that they have not had fair dealings from the adverse party;
especially from those that have had the sword, and outward power on their side; because,
like the Jews against Stephen, when arguments have been wanting,
they have presently run to the heap of stones.
Like dealings the innocent have met withal in this age; when,
as in religious matters men ought to be conquered or silenced,
as the stars in brightness do exceed each other, and the darkness also,
and the moon them all; and as the sun doth both the moon and stars,
by a transcendent and outshining glory, which rather naturally swalloweth them up,
or comprehends them, than forceth them,
or as the vast ocean doth the little brooks and rivers; or,
according to Scripture phrase, as mortality is swallowed up of life;
and in this sense ought every less measure to be subject to the greater;
and so it is not hurt by, but blessed of the greater; as it is written,
the less is blessed of the greater.
And not as beasts do each other, by force and mastership; as it is written,
man being in honour abideth not, but becometh like the beast that perisheth;
and what the master-beast`'s carriage is to all the rest, experience showeth.
But Christ gently leads, not forcibly drives, his lambs into the fold of rest.

But now as the contest comes closer between spirit and spirit, it must needs be hotter,
because the relation is nearer; and differences between near relations,
if one side doth not bear, are more disquieting, than between neighbours,
and worse between neighbours than strangers; for now the enemy, as it were,
hath all at stake at once, knowing his time is but short, and therefore rageth the more;
and the battle must needs be sharp, because he is cast out of many already,
blessed be the Lord, and must be cast out of more daily;
because that everlasting gospel is preached again, and must be, to all nations,
for a sign of his destruction, but their recovery and salvation; that,
as sin hath reigned unto death and darkness,
so righteousness might reign to light and life,
until the knowledge of the Lord covers the earth, as blindness and ignorance have done,
and as the waters cover the sea.

So that now the great business is, for all who are convinced of God`'s everlasting truth,
to examine themselves with the light of Jesus Christ,
that they may know what spirit they are of; and not to conclude,
they are all born of that right spirit, because they once were in measure guided by it,
or because they have it at present convincing them, or striving with them,
to gain obedience from them in all things unto itself And
therefore to father all actions and motions upon it,
as the author of them; is not only an heinous offence against God,
but also dangerously hazardous to that soul which so presumes.

Therefore I shall in short speak something concerning the pure, holy,
sanctifying Spirit of God, that every one may understand what spirit they are of;
as the apostle did,
in order to recover those that were drawn aside amongst the Galatians,
bringing them to the beginning, saying, Ye began well, ye began in the spirit;
and also reminding them of the fruits of it, which while they abode in it, they knew:
and also the fruits of the flesh, which also they might know to abound in them,
so soon as ever they had departed from the Spirit;
and doubtless he instances such particular fruits of the Spirit,
as most abound in those who abide in it, toward those which have departed from it,
as the most effectual means to reclaim them.
On the contrary, the like may be said of the particular fruits of the flesh,
which he instanceth; else he spake but in general,
and so answered not the particular occasion, as most proper to obtain his travail,
which was their recovery.
The particular fruits of the Spirit he instanceth, are love, joy, peace, long-suffering,
gentleness, goodness, faith, meekness, temperance; against such there is no law.

Now the contrary to these, must needs proceed from the flesh;
otherwise they could not try themselves according to his advice.
In like manner do I exhort all to come to the light and Spirit of Christ within them,
to show them their miscarriages,
and whether they hold the truth as it was in the beginning.
For envy, strife, bitterness, fierceness, wrath, watching for evil,
despising those that are good, and such as are employed by the Lord to feed his lambs,
and to preach the everlasting gospel freely, as they have freely received it;
or to lay stumbling blocks in the way of the weak;
or to cause the way of truth to be evil spoken of, because of the miscarriages of some;
these, and the like, doubtless, are evils that the Lord will not suffer to go unpunished;
and are for judgment, and must be repented of, by all that are guilty of them.

Let none that are guilty think to wipe their mouths, and say, these things concern not me.
To the witness in thee thou art brought, from whence there is no appeal;
for if that condemn thee, God is greater.
I am now in all faithfulness endeavouring thy recovery,
and if I may speak it without offence,
I could even desire that my breast were as a window, that every one might see through me,
and within me,
whether my heart and my soul desireth or seeketh
any thing else besides the advancement of truth,
and the liberty of every captive, that in any measure breatheth after the living God;
for I am sure there is a seed that would serve the Lord,
did not a hard heart hinder it within, as Pharaoh did without.

Let me in honesty of heart reason with you a little:
what can you charge against this elect seed?
Who hath it wronged?
And whose name hath it defamed?
Or whom hath it betrayed?
Or whose gold, or silver, or apparel, hath it coveted?
Or what good order hath it broken?
Or did it ever put any upon the forsaking the assemblies of the saints?
Either for fear of suffering, or out of sullenness of mind,
because of prejudice against the persons of any;
or out of slighting contemptuous thoughts, either of those that meet,
or of the worship and service which they perform?
Nay, is it not the hasty peevish spirit that concludes all men are liars,
because some are so, that profess the truth; and therefore slights all in the mind,
how fair soever they may seem to be to any outwardly.
Take heed of it, for indeed the enemy works secretly to thy hurt,
while thou lettest in such thoughts and reasonings;
lam sure these things are not with the consent of the pure seed of life,
but to the grief of it, couldst thou understand its voice,
which at present is stopped from thy hearing, by the multitude of thy thoughts,
prejudices, consultations, and conclusions; all which make thee confident in thyself,
that thou dost well in what thou dost; like Jonah, who replied to God,
he did well to be angry, even unto death.

Oh remember, that when once the light is put out, and darkness takes its place,
how great is that darkness, as Christ said to the Jews.
I have a travail in my spirit at this time for thee; the Lord is my witness, I lie not.
Oh what shall I do for the poor oppressed innocent soul,
that lies under the dust of fleshly rubbish, as in a grave covered with earth in thee?
Shall I say to thee in the fear and name of my God, Arise, and come forth;
for why wilt thou die?
Arise, and shine, for thy light is come, which doth make manifest thy state,
and all the mountains shall melt before thee, and all clouds shall be scattered,
and brightness appear in the face of the whole heavens; and instead of cruel bondage,
that soul in whom life ariseth, shall enjoy a glorious liberty;
and for grief and heaviness, the oil of joy and gladness; and for mourning and sorrow,
the beautiful garments of praise and thanksgiving;
for where the Spirit of the Lord is in rule and authority, there is liberty;
and the Lord is that Spirit, which sets free the soul from death,
by breaking the bands thereof, and snapping the chains in sunder.
All thy straitness is in thy own bowels, by letting in evil thoughts, jealousies,
and surmisings.
But thou wilt be enlarged through thy accepting of judgment upon all these things,
and whatever else is contrary to the holy God;
for I am to preach the everlasting gospel to thee this day,
that thou mayest arise that sittest in the dust, and show thyself forth;
and awake to righteousness, thou that sleepest, and stand up from the dead,
and Christ shall give thee light and life.
For Christ Jesus the Son of Man, is this day held forth, and lifted up unto thee,
that thou mayest see him, and be saved by him,
as the serpent was lifted up in the wilderness,
to cure all the hurts they received in the wilderness; and to heal thy backslidings,
and love thee freely, if yet thou wilt hearken diligently, that thy soul may live;
and look up in the light to him over all thy thoughts, miscarriages, and fears,
and sin no more, lest a worse thing come upon thee.
For the time to come, owe nothing unto any man but love; and when thou art converted,
thou wilt strengthen thy brethren;
as before thou didst weaken them by thy evil example and conversation,
inventing of that which will now be thy shame,
as in the converted estate thou abidest and continuest.

I long and travail in my spirit, to see the day wherein many that have been beguiled,
like Samson, through the cunning craftiness of the wicked one, shall be restored again;
for why may not the long grieved resisted spirit of grace, yet so strive again,
as to give them victory over all that hath captivated;
like the hair of Samson that was shaven, but grew again, whereby his strength returned,
that he slew more through his death, than he did by his life.
Surely those that delight to dwell inwardly in close fellowship and communion with God,
are sensible of the many wiles and devices which the enemy useth,
to draw out their minds to give heed to those vanities which he
on purpose suggesteth to make them forsake their own mercies,
tendered freely to them in the light of Jesus.

What bait more likely to take,
than the resemblance of that which the right innocent spirit loveth?
As may be seen in the serpent`'s beguiling Eve from the simplicity of Christ,
the express likeness and image of God, under a pretence of bringing her more into it;
as it is written.
And ye shall be as God, or like unto God, knowing good and evil; which the apostle calls,
a beguiling through his subtlety.
It is good abiding with God, in the state whereunto man is called by God,
and not to remove, until he is sure the advance and remove is by the same God.

My love to the seed in all, and readiness to lend those my hand that were fallen,
hath procured like judgment from some, as the Jews gave against Christ;
because he kept company, and eat and drank sometimes with publicans and sinners,
to seek the lost amongst them.

But the Jews seeing his readiness to mercy, tried him,
whether he would do justice at all in any case,
by bringing to him the woman taken in the act of uncleanness; which thing,
although it proceeded from an evil intent in the Jews; yet it proved an occasion to him,
to manifest both mercy and justice; mercy upon the woman, and justice upon her accusers,
as being faulty persons themselves, and therefore not competent and true witnesses,
to be taken in the due and right administration of justice;
which method Christ still observed, to meet with forward and malicious prosecutors.

I have longed for an opportunity, a little to express my spirit and soul in this matter.
I have been a man, like Heman, afflicted from '`my youth up, and few, but the Lord,
have been acquainted with my exercises inwardly;
though outwardly also I have had my share.
Indeed, having had much forgiven me, and much love and mercy showed to me,
I cannot but be likeminded; as I am kept to the seed of life in myself,
for the sake of which, I have been upheld in and over all;
and what I have felt and seen the Father do to me, when I have at any time,
in any thing miscarried, that do I, or at least, ought always, and in all things,
and like cases, to do to others; and when I have not done so,
I have felt the Lord rebuking me for it.

I acknowledge from my heart, that in cases wherein I agree with others,
both concerning the disease, and the danger of it, yet in the way of cure,
I somewhat vary; especially if I have laboured under the same temptation myself,
and remember what way I was restored or helped.
Some by corrosives, and sharp medicines, where the case is desperate, may be recovered;
and some others also may be lost and slain, which, by a skilful hand,
through the use of lenitives or cordials, might have been preserved.
And if experience may give her vote, I judge she will direct to love and pity,
as the most excellent way, in the first place, and in ordinary cases.
But wherein I have miscarried in being too mild, and offended any,
I hope they will forgive me that wrong, as they expect to be forgiven,
who have at any time miscarried on the other hand.

5+++.+++ But if any, on the one hand, have taken encouragement,
either from my speaking or writing, to strengthen themselves in evil practices,
contrary to the truth, as it was in the beginning received and held forth,
from the light and Spirit of our Lord Jesus Christ; I declare,
in the holy name of my God, whom I serve with my spirit, in the gospel of his Son,
that I never intended any such encouragement,
but always intended and endeavoured peace and union.
And, whatever might proceed, at any time, either from my pen or tongue,
was only to heal and make up breaches, where any were already made;
and never in the least either to make new ones, or the old ones wider.
And whoever they are, that have wrested my words or writings,
to suit their humours and evil intentions, to hinder the prosperity of truth,
and to make discord among brethren, whether in this isle, or the isles beyond the seas,
they have wronged my words, and the naked intentions of my heart,
and will bring upon themselves misery and destruction, if they continue therein.
This I desire may be prevented by the Spirit of Jesus,
making them sensible of their danger therein, and to bear the indignation of the Lord,
because they have sinned against him,
unto a thorough change and reformation in them for the time to come:
and I can and do freely forgive the wrong done unto my particular.

6+++.+++ On the other hand, if any have conceived jealousies in their minds,
and watched for occasion against the innocent,
and grounded a false judgment upon those misapprehensions,
and then sent it abroad as a certain thing, on purpose to bespatter the guiltless;
such shall bear their judgment, whoever they be.

I have often, in secret,
considered what reason there should be for some men`'s jealousies;
and I could find none more probable, than that of Saul`'s against David, viz.,
because of the voices of others, with this note upon it,
"`And Saul eyed David from that day forward.`"
But whether any thing of like nature or resemblance hath ever been in my heart,
much less endeavoured by me, concerning the least labourer in my Father`'s vineyard,
is known to the Lord.

7+++.+++ And I appeal to all you that have known me in bonds and at liberty,
amongst whom I have laboured, and been conversant these twelve years and upwards,
who have known my doctrine, and manner of life, whether I have sought myself,
or any thing from you, to enrich myself, but have gone a warfare at my own charge?
And whether I have handled the word deceitfully,
but endeavoured always to stand approved in God`'s presence,
and to be manifest to your consciences in his sight?
And whether I have used lightness among you,
to stir up the vain mind to unprofitable discourses?
Or whether, at any time, I suggested jealousies amongst you,
concerning any of the Lord`'s people?
Or to beget a low esteem in your minds,
of those that labour in the word and doctrine of Jesus?
Or, whether I have sought to get entertainment in your affections!
Nay, had it been the will of God, I could have desired often,
that my message might have been delivered, and my face and person have been unknown.
I have often said, and again I do declare,
that those who keep in the feeling love of God,
and honour and respect his Spirit in themselves, let such so kept, if they can,
disrespect the ministers of life and peace.
Bear with me, if I use plainness in this matter, for it is for no other end,
but to answer the good in all,
and that the gospel might have a free passage in all hearts and consciences,
wherever it is published, either through this vessel, or any other,
whom the Lord shall use;
and that an open door may be ministered through all the churches of Christ,
for the word of eternal life to enter into them, from henceforth and forever.

I labour, and am pained in spirit, until all bands be broken,
and all the hearts and minds of those convinced, be opened,
and prepared as a bride for her husband: that none may be found foolish virgins,
contenting themselves with the words and talk of truth, like oil in the lamp only,
which will go out and be consumed, if the seed of truth within be not daily felt,
as oil in the vessels, to keep your lamps burning, and your lights shining,
that men may see your good works, and glorify the God of your salvation.

8+++.+++ I beseech you, friends and brethren,
to suffer the word of exhortation to prevail with you,
unto a thorough examination of your own hearts, with the light of the gospel of Jesus,
whether you have kept to the truth, as declared and practised in the beginning;
or you have suffered loss in your inward man, and find decays of love to God,
and of zeal for his truth upon earth.
I know right well, that a good condition may be easily lost, but hardly recovered.
Examine thyself, whether thou delightest thyself now, as much as at first thou didst,
in communion with God and his people?
Are the assemblies of his children as dear to thee as ever they were?
If not, seek out the cause,
and let no pretence blind thy mind from a diligent attending thereupon;
but keep to the seed in thyself, which thinketh no ill, much less doth any,
and in that thou wilt feel the benefit of communion with God`'s people,
and wilt be bound up together with them, as in the bundle of life:
and a bundle is not easily broken and shattered, as particulars apart are.

Search whether thou hast kept thy garments clean,
from being defiled with the spirit of this world, building again in thyself,
that which once thou destroyedst in others.
If riches increase, set not thy heart on them; which they will easily get,
if thou be not watchful and diligent in keeping thy heart close unto the Lord,
and his truth in the inward parts: for the love of money is the root of all evil,
as it is written.

9+++.+++ Take often a view of the truth, as it was in the beginning,
and what effect and operation it had upon thee, when thou wast first convinced; how low,
how meek, how poor in spirit, and humble in heart and mind;
making thee to esteem every one better than thyself;
seeing and knowing more evil in thyself,
and in that nature by which thou wast a child of wrath, than in all the world beside,
as in thy eye at that day.
And surely experience showeth unto the watchful, that that nature is the same,
and will be bringing forth the same fruits again, if it be not mastered,
and ruled over by the pure and divine +++[+++Spirit]; which made the apostle say,
after his conversion, That in him, that is to say, in his flesh, was no good thing:
which quickened state made the poor disciples cry out as guilty persons,
though clear from the act, Master,
is it I? Is it I? Whilst seared Judas takes no notice
of a particular intimation given by Christ,
concerning himself, who told him plainly,
"`He that dipped his finger with him in the dish,
should betray him;`" of which his hard heart took no notice.
Again, -- art thou as careful to keep the truth without blame, as at the beginning?
and as ready to restore the fallen, and to cover the nakedness of thy brother,
as at first?
Is there no whispering, evil speaking, and backbiting, and watching with an evil eye,
and searching after weaknesses and baitings in some,
accounting them great and heinous miscarriages, being glad of them,
to defame those whom thou hast a mind to defame;
and taking no notice of greater miscarriages in others, whom thou respectest,
and wouldst have thought well of?
Durst thou do thus in the beginning, when thou wast first convinced,
and the lively quickening spirit ruled in thee,
keeping thy spiritual senses always exercised, to discern between good and evil?
Thus let every one try themselves with the measure of truth,
that they may see whether they have kept to it as it was in the beginning.

But you that have kept your habitations with God, and close to the truth,
bless the Lord for his goodness unto you: for if he had not kept you, you had run out,
and miscarried, as well as others; for you do not bear the root, but the root you.
And how know you, but you have been spared for such a time as this, like Queen Esther,
to attend the king`'s presence,
that you may be instruments to divert the evil purposes of the enemy of the holy seed?
And that many, fallen into their snares and temptations,
by the spirit of meekness in you, who stand by faith, might be restored,
to the making of you shine more gloriously in the firmament of God`'s power,
through the converting of many from the evil of their way.
Blessed shall you be of the Lord, who are found diligent in this work.
For this is my testimony for the Lord this day,
that another gospel shall never be preached, to gather men and women to God;
for it is the everlasting gospel:
and those who know it to be the gospel of their salvation, can say,
that there is more than a bare opinion, or different judgment between them and others,
that do not believe in the light within,
that lighteth every one that cometh into the world, to be sufficient to lead to God,
through Christ, from whom it comes: yet it is possible for one,
that once knew the truth in measure, and after departed from it,
to think as slightly of the truth as those that never knew it.
It was not Dives, but Lazarus, in the parable,
that knew the difficulty of the passage into Abraham`'s bosom;
while Dives thought the way passable at pleasure.
Nevertheless, this gospel must more and more spread and shine, in its glory and beauty,
until the man of sin be fully discovered in all minds and hearts,
that the kingdoms of this world may become the Lord`'s, and his Christ`'s.

Whatever hath fallen out, or shall yet be suffered to come to pass,
to obstruct and hinder the work of this gospel,
shall in the conclusion be ordered of God to work together for its advancement,
as if such things had never been: for those flames of fire,
which are and shall be rendered upon those that obey not the gospel, shall make those,
that are sanctified through obedience thereunto, the more to glorify God:
and the perishing of others, through unbelief, shall make those that are saved,
through faith, the more to admire the riches of God`'s love and mercy unto them.

Therefore, arise thou that sittest in the dust; and sing forth the high praises of God;
and come forth of the pit, and out of the prison-house, and show thyself forth;
for the day of God`'s mercy is come, even the set time to pity Zion,
that mourned in the dust, because God had forsaken her.
Thou that shakest thyself, like a man of war, and rejoiceth like a giant to run his race,
notwithstanding the storms and winds, clouds and mist, that may seem to interpose,
thou shalt yet sing in the heights of Zion.
For thy sake am I stirred in spirit, that all bonds may be broken,
and all weights and burdens laid aside, and the yoke of Christ put on every neck;
that with one shoulder we may all draw in the work of the Lord,
until the fallow ground of people`'s hearts, whereon groweth briars and thorns,
be plowed up, and the seed of the kingdom may sprout and grow in them also,
until the nations become like the garden of of Eden,
and the mountain of the house of the Lord be on the top of all mountains,
that the nations may flow unto it forever.
Amen.

Now I have a few words unto you, sons and daughters of men,
into whose hands this testimony may come, of what judgment or per suasion soever you are;
and it is by way of advice,
to take heed that you harden not your hearts against the truth,
because of any miscarriages in those that do profess it.
It is no new thing for a Judas to betray his master,
and a Demas to embrace this present world; nor for all Asia to turn aside for a time.
Remember, thou art doing the same thing daily, and knowest it not,
in thy heart and spirit, against the strivings of God`'s good Spirit in thy own bosom.
Remember that Sarah`'s laughing at the angel`'s message, was rebuked by the angel;
and Hagar was cast out, with her son, for his offence,
who mocked Isaac after he was born, which by the apostle is called persecution; saying,
As he that was born after the flesh (referring to
Ishmael) persecuted him that was born after the Spirit,
(referring to Isaac) so it is now.
I know many are big with expectation, concerning the downfall of the Quakers, so called,
and the truth which they profess, and ignorant of the Quakers`' foundations.
Take heed of speaking evil of things ye know not,
lest ye render yourselves more like beasts than men, in so doing.
Say not, as those mockers did, Where is the promise of his coming?
Where is that perfection you speak of, and that union you glory in?
lest your bands become strong.

The doctrine of perfection doth stand, and shall stand forever,
which the Quakers asserted; for they never assigned any particular man to the world,
as lodging it there; but Christ the promised seed, and those that abide in him; and such,
the Scripture saith, sin not, because in Him is no sin.
The Quakers asserted perfection attainable through God`'s grace,
and that every Christian ought so to believe, in despite of the devil`'s enmity;
which priests and professors opposed: and this was the question between us and them;
and not whether this or that particular man hath attained it.
And so it stands firm and safe; notwithstanding what the evil eye doth,
or can spy out against it.

For the union we speak of with God, and one with another, we never placed it in the name,
or outward form only, but in the light of Christ; not talked of, but walked in.
But if any convinced of the light of Christ, say, They have fellowship with us in him,
and yet walk in darkness, they lie, and do not the truth; for no lie is of the truth:
and their practice is a sufficient evidence to convict them, without any further trial;
for, according to Christ`'s doctrine, the remaining of sin,
is a sufficient conviction of blindness; as he said to the Jews, Because you say you see,
therefore your sin remains, etc.
But all that do walk in the light, as he is in the light,
have fellowship one with another.
We never asserted, that all convinced, must needs be converted;
nor that all converted must needs always keep in that state,
and could never depart from it; but that every one`'s safety was,
in keeping to the grace, whereby they should know how the grace kept them;
as it is written, Hereby we know that we know him, if we keep his commandments:
and it is but our reasonable service, that we should do as much for God,
as we have done for the devil; as it is written, Rom. 6:19,
"`As ye have yielded your members servants to unrighteousness,
even so yield your members servants to righteousness,`" etc.
How this hath been done unto the motions of lust within, may easily be known;
even so may the motions of the good Spirit within, be known and yielded unto,
which is but most just and equal.
So that the union with God, and one with another,
in the light of Jesus Christ, amongst all that abide and walk in it,
stands as firm as ever it did, between the faithful and watchful in spirit:
for we never held out a fellowship and communion between light and darkness,
nor between good and evil; but in the good only.

Therefore your hopes and expectations shall be abortive, and your eyes shall fail,
who look to see your desires accomplished upon the truth, and children of it.
As you love your own souls, cease such thoughts and expectations;
for you will but harden your hearts the more thereby, and be disappointed at last;
but bow your necks unto the yoke of Christ,
which will convey you to the true rest for your souls, and show unto you,
as in the light you believe, the end of all your observations, and carnal ordinances,
and beggarly elements, to the rending the veil off your hearts;
which will remain and continue, until Christ be witnessed,
the sum and substance of all things to you, and in you,
through the application of his Holy Spirit, and not through any imagination,
or traditional credulity, in yourselves.

A few words to you, little children, that are ready to be troubled,
because of the prosperity of the wicked, and your own trials increasing upon you,
and it may be such as you never expected to meet with: saying within yourselves.
Have I forsaken all that is near and dear to me in this world, to embrace the truth?
Have I left all other societies and fellowships, to come into the fellowship of truth;
expecting I should never have found those, professing the same truth with me,
and such as were convinced before me,
to differ among themselves or that any such fruits should
have been brought forth by any that profess the truth?
Nay, saith some weak one, I would have thought hardly of such in time of my profession,
as not fit for the fellowship I then was in, I know the enemy tempts thee sorely,
sometimes by raising doubts in thy mind, whether it be truth or no,
which thou hast received and suffered for;
but after a little combating with him about this, thou shakest him off,
as that liar which from the beginning thou wast troubled with.
But then he comes upon thee, with a new assault, to justify this man,
and to condemn the other; and to take part with this thing, and to condemn the other;
which doth so bewilder thy mind, and darken thy understanding,
that thou art at a stand what to do, sometimes liking, and sometimes disliking,
this and the other thing, the enemy suggesting to thee,
that thou hadst better never have received the truth: and thou seest,
saith the enemy within, what thou hast gotten through all thy hardships and sufferings;
more trouble, vexation, and disquieting of spirit, than ever thou knewest before:
thou resolving at sometimes to sit still, and to meddle no more,
and never to come to meetings with God`'s people again,
but to pass away thy time with as little trouble as thou canst;
thinking sometimes to take this course, and sometimes the other, to get ease to thy mind;
or else to mourn away thy days in sorrow.

I have this to say to thee, thou poor soul; Keep thou thy own habitation with God,
in the measure of his grace committed to thee; and meddle not with other men`'s matters,
neither those that are given to change.
Shut out all that would interrupt thy communion with God,
and with his people that keep their minds out of strife,
and that follow those things which are of good report, and which make for peace;
these things follow.
And keep in love with all those that love the truth, and are tender of it,
and seek its advancement above all; who have no end to self, nor to this world,
nor the things of it; but unto purity and holiness,
and a close walking with God in Spirit; and thy temptations will wear away,
and those broken bones shall be set again unto a firmer union with God,
and his truth and people, than ever thou wast in before.
Then the broken bones shall rejoice, and thou conclude,
that in faithfulness God hath suffered thee to be tried,
that thou mayest learn obedience by all thou hast suffered; and understand,
that it was to make thee abhor thyself more than ever thou couldst have done,
had not these things befallen thee; that, with Job,
thou mayest attain to a knowledge of God beyond the hearing of the ear;
which will reward thee double for all thy sufferings and trials,
and make thee keep close unto the Lord, and to the fellowship of saints forever:
that through thy experiences many wanderers may be converted to God,
and thyself established in his blessed truth forever,
and become a pillar in God`'s house, and go no more forth;
but be found to the praise of the riches of the glory of his grace, whose mercies,
wilt thou say, endure forever.

Thus having finished my testimony at this time, in faithfulness to God,
and his requirings, in what plainness he was pleased to bring things to my remembrance;
desiring to answer the least good in all hearts and consciences,
but not to regard the evil will of any,
nor to please the minds of the unstable multitude, whether professors or profane;
knowing the one sort, like the Jews, will cry Hosanna to day, and crucify him tomorrow;
and the other, like the barbarians, who sometimes concluded the apostle a murderer,
and presently changed their mind, and said, He was a God: for I am more a freeman,
than to sacrifice my just liberty to any man`'s humour; and more a Christian,
than to ask any man leave to perform my duty to God,
or to hold the faith of our Lord Jesus Christ with respect to persons;
but in Christ alone, the author of it, who is God over all, blessed forever.
