== Chapter 7

[.blurb]
=== An epistle to all that are young in the Truth, and lately convinced; who walk in, and assemble amongst, the People of God called Quakers; that they may escape the wiles of Satan, and continue and walk in the way of righteousness.

We call to remembrance the labours, hardships,
and inward travailing pangs and throes of the true gospel ministers in the days of old;
and we know the same in our day, in our measures, the apostle saying.
Of whom I travail in birth again, till Christ be formed in you.

And blessed be the Lord, there are many witnesses in this our day,
not only of instructors, but of such as, through deep travail, have begotten many to God;
and these, being once children themselves,
retain the sense of the childish state of those who are come inwardly
to feel some renewings in the spirit of their minds,
by the gospel power, in order to the overturning of all their old building, that now,
like to Jerusalem of old, for their despising and rejecting the true prophets,
there was not to be one stone left upon another.

The old serpent perceiving his kingdom to be shaken,
by the operation of that divine light, grace, and power of God,
which will admit of no terms any longer to be made with him;
or any subjection or compliance in the least to be yielded to him,
or to any of his works, every plant now being to be plucked up,
that the heavenly Father hath not planted; yea, the fig-tree that bears no fruit,
whereby the hungry may be relieved, must wither by the curse of his displeasure.

Then this crooked serpent, that is more subtle than all the beasts of the field,
twists and turns himself every way, if possible,
to entangle again those that are turning from his thick darkness,
to Christ`'s marvellous light, that hath showed them where they have been,
with whom they have been conversing, and what they have been doing in the dark,
and what path they must walk in, if they will arrive at the land of rest.

And thus we found judgment to begin at the house of God,
in order to the overthrowing and purging out of all that had defiled,
that our bodies might become the temples of the Holy Spirit.

Oh, the many devices that the enemy useth,
that true judgment might not take place! and when it did take place,
how did he transform himself, to make us believe his suggestions, viz.,
That now we had lain long enough in the furnace, and the tin and dross was all gone,
and nothing now was left but pure gold.
But when we at any time lent an ear to these his delusions, we found by experience,
that which he suggested to be gold, was but tin and counterfeit metal;
and that he lied unto us, when he said, we had been long enough in the refining fire:
although the fleshly part was glad of these tidings,
hoping thereby its life would have been spared.

So that we saw, we must go into the furnace again,
and there continue all the appointed time of the Father, till, indeed,
we were changed into the state of the precious sons of Zion,
truly comparable to fine gold.

And this was the way in which we waited, under the great tribulations and sore judgments;
that we might not only be convinced, and take up a rest there,
in that we believed the words of truth, and could dispute for it;
but that we might be converted, and, in the spirit of our minds thoroughly renewed;
that we might be as saviours upon Mount Zion,
and as workers together in the gospel of our Lord Jesus,
to to help and strengthen the weak brethren and sisters,
and speak a word in due season to the weary soul;
which work was not at all wearisome to us,
though our hazards and hardships were great sometimes,
to get a hand to the helpless ones; yet when once we got but a little hold,
and we felt them coming nearer to truth and us, then our hearts rejoiced,
and our souls were right glad.

And they whose beauty was hid as with bullrushes, and smeared as with mire,
then they appeared to be goodly children: these were sweet encouragements unto us,
greatly refreshing to behold these prisoners thus showing themselves forth,
which made us, with many more faithful brethren, not to love our lives unto the death;
but even for the truly good man, dare to die, when called thereunto.

The spirit of that blessed man began so to stir in our bosoms, that we could even,
in a sense, have wished ourselves accursed for our kindred, acquaintance, and countrymen,
that they also might feel what we felt; knowing upon what ground they stood,
and what zeal they as well as we had: but the true knowledge of the truth,
as it is in Jesus, was wanting;
the veil of observations and carnal apprehensions being over the heart,
which nothing can remove but Christ; who is the life and light of men,
and glory of his people Israel.

There are many witnesses yet alive, who can testify to these things,
and much more than we intend at this time to mention;
only some few particulars we may hint at, to the end that no travellers towards Zion,
may turn aside from the footsteps of the flocks of the companions,
nor err from the right way, as it was received and walked in at the beginning.

O! what fear and holy dread was upon our spirits, lest we should think our own thoughts,
or give way in the least to the fleshly motions of our own minds,
or admit any of the cares for the things of this life,
or give way to any inordinate affection to the nearest and dearest relations,
lest thereby we should be hindered in the day of our espousals,
from being chaste virgins unto Christ!

Likewise,
what carefulness of our words! what watchfulness to our ways! what
heedfulness of our company that we might keep our consciences clear;
that our lives and conversations might show unto all men,
that we are under the government of Jesus,
that we might be manifest to God`'s witness in every man`'s bosom;
and in these things the Lord blessed us.

Again, how careful were we, that we might not lose one tittle of our testimony,
by the keeping to the plain language; that we might not lift up the proud spirit in any,
by mincing in that particular.

How did our moderation appear unto all men, in our meats, and drinks, and apparel?
And how inwardly retired did we walk,
fearing to draw out the minds of any into unprofitable discourses;
having a principal regard to the inward exercise of our minds,
lest we should lose our own conditions; which made us prize retired meetings,
in which we were sensible of the teachings of the true prophets from the false,
in ourselves, and others?

Then we were sensible of the living word to take deep root downward,
that from thence we might bring forth fruit upward, to the praise of God:
desiring ye may walk in these steps.

Time would fail to tell of the poverty of spirit, humility of heart, lowliness of mind,
brokenness of soul, contempt of the world, not only of its glory and riches,
but of all its wisdom and knowledge, counting it dross and dung,
in comparison of the excellent knowledge now manifested in us,
through the revelation of our Lord Jesus Christ.

We cannot pass by that godly fear, which at that day was in our hearts,
lest by discoursing, or reading many books,
we should awaken again the old wisdom and understanding,
and again get the notion of things in the carnal comprehension,
and thereby lose our experimental knowledge of the inward work of God in our particulars:
from which expedience we are careful to speak about the things of God;
finding it our safety and preservation, to keep to our own measures;
and not to deck ourselves with the words only, or other men`'s gifts;
nor yet to pride ourselves with our former experiences and knowledge,
though God`'s jewels, according to the prophet`'s words.

These things being witnessed in the beginning, we exhort and advise all,
especially those that are young in the truth, and newly convinced of the everlasting way,
and make profession of the same,
that they be careful to avoid all those things which
the godly fear caused us to avoid at the beginning;
and so much the more,
because our enemies and opposers are waiting for all occasions to asperse the holy truth,
and the true professors of it:
in which practice they follow the steps of the enemies of God in former times,
who not only watched for mischief, to make offenders for a word,
but were ready to fall upon the hindermost and weakest amongst them;
and that when they were but newly convinced of the truth;
even while they were yet in deep exercise of mind.

Then if they could draw them out, to dispute of any thing beyond their own measure,
they will boast of that, and charge any advantage, that they have gotten from the weak,
or newly convinced, upon the whole body; and put us,
either to deny the unlearned words that were spoken, or them that speak them,
though their intentions were right, these men being willingly ignorant of,
as well as envious against the truth, and them that walk therein.

Therefore cast not pearls before swine, lest they turn again and rend you:
so out of our love to, and care for the truth, we desire all such friends,
and convinced people, to keep to their own measures,
trusting more to the simplicity of Christ manifest in themselves, than to any wisdom,
parts, or arguments of their own, in the earthly or natural comprehension.

For we have found by many years experience, that true simplicity,
and inward poverty of spirit, God hath always had regard unto,
beyond all flourishing expressions, and gilded speeches, that may charm,
and take the outward ear, but never deliver the prisoner out of the pit.

Neither hath the work of God thus far prospered by such weapons of war,
or words of man`'s wisdom; but by a secret virtue,
that always attended the truly poor in spirit,
that did appear what they were only by grace, and its work upon the conscience;
and to this day do all the true labourers work with the same means.

And if you that are newly convinced, would be kept lively in your conditions Godward,
your growth must be, only in walking in the light, and keeping in the grace of God;
and then for words and knowledge, they will come fast enough upon you,
as God hath service for you: and by so doing, you will both save yourselves,
and them that hear you; and also, frustrate them that wait for evil.

From which grace of God these things are written,
and in the same commended to your consciences; desiring heartily,
that in your own measures of the same,
you may be preserved amongst the faithful witnesses of Jesus,
till your days be accomplished, and you finish your course with joy.

This from us, who labour and travail in the work of the gospel,
for the advancing of the name of the Lord, your friends in God`'s truth,

[.signed-section-signature]
John Crook, Thomas Green.

[.signed-section-context-close]
London, the 15th of Eleventh month, 1672.

[.blurb]
=== An epistle to all that, profess the light of Jesus Christ (within) to be their guide.

Dear Friends, Brethren, and Sisters,
that believe in the inward and spiritual grace which
is the light of our Lord Jesus Christ,
I salute you all; desiring, that as we received Christ Jesus the Lord,
we may all so walk in him.
In order hereunto let us all watch,
and be mindful how we received the truth at the beginning:
which is the subject-matter upon my heart, by this epistle, to signify unto you.

For you know, many of us, before we received the truth, as it is in Jesus,
felt some stirrings of life;
and therefore separated in our judgments and opinions from the
generality of our neighbours and countrymen where we dwelt,
because of an inward cry from a deep want in our souls,
and hungering after the constant enjoyment of that which we with many others professed;
but could not find in any thing under the sun.

So poor and needy were we, that the dealings of God with our spirits in that day,
in some sense, may be said to resemble God`'s proceedings with Adam,
when he set all the creatures before him, before he gave him a meet-helper;
that when he saw he could find out no fit helper for himself amongst them all,
he might have the more account of the meet-helper that was after given him of God.

So it was inwardly with us, until that trumpet sounded,
which directed our minds to the light of Christ Jesus in our own hearts and consciences,
which when we believed the report, and made trial of its sufficiency,
we soon found the meet-helper for our souls; to wit,
the arm of the Lord to be revealed in it, and made so bare,
that we knew it to be the Lord`'s arm, which brought deliverance to us.

But not from all our enemies at once, yet so that we understood plainly,
by certain experience, that the tendency thereof, and the end of its being made bare,
was to deliver us out of the hands of all our enemies; that being delivered,
we might serve God, without a tormenting, distrustful fear,
in holiness and righteousness before him all the days of our lives.

And the way thereunto was, by the working of this arm of power in our inward parts,
to make a separation within, between the precious and the vile,
and between our own spirits and God`'s Spirit; between our own wills, and God`'s will;
between our own thoughts, and God`'s thoughts; and our own ways, and God`'s ways.

So that we found the great business of regeneration and restoration,
was to be wrought within us; and what sorrow, what trouble, what horror, what distress,
what wars, and rumours of wars, were within us, many know;
and what earthquakes were in divers hearts,
which might occasion the name Quaker to be given to some of us;
those that were eye-witnesses from the beginning are not ignorant of these things.

O what carefulness, what watchfulness, what circumspection, what awfulness of God,
and what dread of his power, was upon our spirits, lest we should speak our own words,
work our own works, walk in our own ways,
or think our own thoughts! so diligently did we keep watching over our hearts,
being conscious to ourselves, that we should give an account for every idle word;
which caused us to learn a bridle for our tongue,
that our words might be few and savoury, ministering grace to the hearers.

How solid were our looks?
How grave were our countenances?
How serious was our carriage?
and how exemplary our behaviour and conversation amongst all that we conversed with,
lest we should give occasion for any to speak evil
of the blessed truth of the living God?

And if any, though but newly convinced thereof, walked disorderly,
or that took up their rest in a bare convincement,
and came not to be converted to the life and power of God in their own particular,
which at the beginning was soon discovered by that spirit of discerning,
which in the light we received from God,
how conscientiously solicitous were we to admonish, instruct, advise, and counsel them,
to take heed of a false rest, or running into,
or doing any thing by bare imitation from others?
Yet how tender were we of bruising, hurting, stopping,
or hindering any stirrings of light and life,
lest the lame should be turned out of the way, and the feeble be left behind.

The spirit of holy David was in our hearts,
who would not consent that the sore and weary ones,
that could not get over the river Bezor, should lose their part of the prey,
because they tarried with the stuff; but made it a law and a statute in Israel forever,
that they should have part alike.

And how did we love and pity those that took pleasure in the stones of Zion,
and favoured the dust thereof?
What carefulness was upon us for them?
And if we found any like the young man in Mark 19:22,
that had been religiously inclined from their youth, how did we love them?
Watching for opportunities to communicate some spiritual advice to them.

As if the new kindred, that Christ speaks of, Matt.
xii. to wit, whosoever shall do my Father`'s will, the same is my mother, sister,
and brother, who was now discovered again,
and the beauties of holiness were now made manifest,
with the many glorious privileges enjoyed thereby, as to see clearly,
and know certainly the living God; for hereby came we to know, that we knew him,
because of the beauties of holiness, in keeping close to his commandments,
whereby our love to God, and one to another, was manifest unto all.

For we durst not let in distrustful thoughts of God,
nor one of another--faith in him then becoming our law:
so that our care was steadfastly and constantly to believe in the light,
by which we had seen him; and to dwell in a holy fear,
lest we should transgress the law of faith;
by which Christ was then kept dwelling in our hearts,
and all boasting of self-righteousness was utterly excluded.

But with how much difficulty we kept that faith, you only know,
who like valiant soldiers have endured hardships in the good fight of faith;
whereby we ourselves were preserved and kept, by the power of God through faith,
that we might in due time receive the end of our faith, to wit,
the salvation of our souls.

And then, because we believed in the power, as we were moved of it, we spake by it,
and such words, like Jonathan`'s bow, never returned empty, but wounded the hypocrites;
like the man that shot the arrow out of simplicity,
which smote disguised Ahab between the harness, so that he died;
according to the word of the Lord by Micaiah.

You may remember also, how like Ephraim, at first, we were as little children,
and spake trembling; saying often in our hearts,
as Jacob did of the mountain where God appeared, to wit, How dreadful is this place?
And how quick and powerful were those words that
proceeded from that dread of God in our hearts!

The great mystery of the false prophet, that rides upon the beast,
being then inwardly discovered, with the mystery of his name, and number thereof, to wit,
the number of a man; which caused us at the beginning to cry down vain, corrupt man,
both in ourselves and others; feeling that God was risen in his power,
to confound his wisdom, and to bring his fleshly prudence and policy to nothing:
therefore we feared the getting up of that man`'s part in ourselves,
being so battered by the inward judgments of God upon ourselves.

That with good Jehoshaphat we said in our hearts, We know not what to do,
but our eyes are towards thee, O God: then in this valley of helplessness, straights,
poverty, lowliness, and humility, God pleaded with our fleshly part;
so that in the day of our distress, although we multiplied our services,
and doubled our offerings and observations, to obtain relief;
yet Christ refused all these our works, that he might freely make himself known unto us,
which in due time he did, as Joseph unto his brethren, and saith that scripture,
"`there stood no man with him,
when he made himself known unto them;`" to the exalting
of the riches of the glory of his grace in us,
whereby sorrow fled away, and our own mournful spirits were now made to rejoice in God,
and our formerly troubled souls began to magnify our Saviour.

Thus former things passed away, till the tempestuous sea was no more;
but joy and gladness was in our dwellings, and the voice of melody in our hearts,
and in the midst of our assemblies.

But before we came hither, you know, fellow travellers,
that Mount Sinai was first in our way, where we tarried a while,
and felt the entertainment of her flames, and heard the voice of words,
and the sound of her trumpets, and were witnesses of her terrible earthquakes,
yet fled not; but with Moses a remnant drew near unto the thick darkness where God was:
but others made this mountain the end of their journey,
escaping with their lives still in their own doings; yet these,
though they might in profession come out with us thus far, they were not of us,
and in time will go out from us, that it may appear,
they came not through all the tribulations that a remnant went through.

For from thence a remnant came unto the ministration of the prophets,
where they met with openings and prophecies of good things yet to come,
before they did come: and here others fled as on the sabbath day,
as if now all labour was at an end; and here they took up their rest,
but God did not sanctify it, and therefore glorying and pride got up in these;
boasting in the sifted man, soon forgetting all dependence upon the opener, viz.,
the Spirit of Truth, to exercise their hearts and tongues in the management of all,
for the glory of God, and refreshment of his own seed in the hearts of his people.

But a remnant still travelled on, through John Baptist`'s cry in the wilderness.
Make straight the way of the Lord,
and come to repentance from all their dead words and works,
that every valley might be filled, and every mountain and hill brought low,
and the crooked made straight, and the rough ways made smooth:
then came we to see the salvation of God, to wit; The Lamb of God,
that takes away the sins of the world, whom then we followed;
leaving John as some of his own disciples did.

Some also came with us as far as John`'s baptism,
that washeth away the filth of the flesh; but not coming to the baptism of Christ,
which washeth away all filthiness both of flesh and spirit; also they left us at John:
such as these may be compared to the king of Israel, who, at the command of the prophet,
smote the ground often; but not smiting it long enough, until the enemy was consumed,
he missed of a perfect victory, and full conquest;
so do all that take up their rest in any thing short of the Lamb of God.

These things being thus witnessed in the spiritual travails of a remnant at the beginning,
let us all search and try our ways,
whether we be still following the ancient footsteps of the flocks of the companions,
by keeping in the pure separation from the fleshly part in ourselves,
ministering only from the ability that God gives; which a remnant,
that have kept to their first love, and their garments clean therein, have done,
to the praise of the Lord God Almighty forever.

My exhortation therefore is unto all,
but more especially to you that are children of believing parents,
and servants to believing masters, with all the younger men, and younger women,
convinced in these latter times,
knowing that a remnant of these also have kept their garments clean,
to examine yourselves, how you came by your profession; Whether you,
that are children and servants, received it by tradition,
only because of your outward relations, etc.,
or from the inward work of God upon your own spirits,
as those did that received the truth, in the love of God, at the beginning.
For many may endure sufferings, and undergo the reproach of a Quaker,
and all for sinister ends; to whom I say, as Jacob did to Simeon and Levi,
You have troubled us, and, as much as in you lies,
have made the truth to stink amongst the inhabitants of the land;
yet a remnant dare not do so, blessed be the Lord.
But to you that are grieved and troubled, because of these, I say to you also,
as the Lord on this occasion said unto troubled Jacob, Arise, and go up to Bethel,
the house of God, and dwell there, Gen.
xxxv.

O the bemoanings of many tender souls at the beginning for the loss of their conditions,
sometimes through their own negligence, and sometimes through the enemy`'s subtlety,
weeping like Rachel for her children, and refusing to be comforted,
because they were not, are fresh in my remembrance.

But of later times many come amongst us, that in outward appearance may seem to be of us,
who as yet never truly knew the meaning of such bemoanings,
nor the bitterness of Rachel`'s tears,
but walk as if the gate of entrance into the truth was grown wider,
and the path and way thereof broader than it was at the beginning;
for how careful were those that came to witness the truth, at the beginning,
to keep low and humble, that they might not be drawn from their own measures,
lest their own words should become their burden,
and they be condemned in themselves for uttering that, as in the name of God,
which came not from the Spirit of the living God!

Therefore it was, that so mightily grew the word of God, and prospered,
bringing all down, to the loathing of their persons, in true humility,
growing up in every honest heart; that the fruits of the spirit were manifest,
as in the apostles`' days, to wit, love, joy, peace, long-suffering, gentleness,
goodness, faith, meekness, temperance; against such there is no law, saith the apostle:
and they that are Christ`'s have crucified the flesh, with the affections and lusts.
If we live in the spirit, let us also walk in the spirit: let us not be desirous,
saith the apostle, of vain-glory, provoking one another, envying one another.
But like brethren, if a man be overtaken in a fault, ye which are spiritual;
restore such an one in the spirit of meekness; considering thyself,
lest thou also be tempted.
Bear ye one another`'s burdens, and so fulfill the law of Christ.

My heart is overcome, when I take a view of God`'s dealings with us,
from the day that he first visited us, unto this present time.
My dear friends and brethren, you know how Christ (our Joseph) knew us,
when we knew not him; and made himself known to us, as Joseph did unto his brethren,
while guilt and fear, distrust and horror, were in their spirits; and then commanded,
that they should do unto, and one for another, as he had done unto and for them all.

Therefore let all come down to the remembrancer, the Spirit of Truth,
which will distinguish between those that are now arrayed
with the beautiful garments of their youthful days,
viz., humility, meekness, righteousness, and the true zeal of the Lord;
and those that have only a show of it:
and there let us behold one another in our comely attire,
with the glorious visions of the Almighty in our hearts;
judging down all stirrings of envyings and evil surmisings against any.
For, can we consider the price we cost at first, and the love, care,
and watchfulness of our God over us unto this day, of whom a remnant can say,
as Jacob did.
He hath fed us all our life long: and not be in the love one with another?

Can we contemplate the miseries we have been delivered from,
and the mercies we have been made partakers of, since we were a people,
and not be humbled before our God, for any unthankfulness and distrust?
Can we view the prisons and dungeons, the banishments, and all outward losses,
and spoiling of our goods, with the reproachful scoffs, and scornful slightings, by such,
that some could say, with holy Job,
They were not worthy to eat with the dogs of their flocks;
and not to be melted before the Lord, and abased,
as unworthy of the least of all his mercies?

And can we remember our blessed support under all those sufferings,
and the sweet presence of the Spirit of Christ in our hearts, saying in us,
under all these trials and exercises, as the disciples did,
when they returned to Christ their Master, after their weary travels, to wit;
We wanted nothing, etc.
We wanted no perfumes to take away the noisome smells;
we wanted nothing to make our hard lodgings easy;
we wanted no pleasant walks to make our straight confinements joyous;
and we wanted not the society of outward relations, and former acquaintance,
to pass away the time;
because the Lord our God turned all our hardships into unspeakable comfort,
and true contentment?

And shall any now say, God`'s arm is shortened, that he cannot save; or his ear is heavy,
that he cannot hear?
God forbid, that all the milk, and wine, and honey, and other fat things,
with which we have been often spiritually feasted at God`'s table,
should be all forgotten, and buried in the wilderness; saying in ourselves,
as rebellious Israel did of old, to wit;
Can he now prepare such a table in the wilderness for us?

But rather let us, with Manoah`'s wife, the mother of Samson, conclude.
If the Lord were pleased to kill us,
he would not have received a burnt-offering and a meat-offering at our hands;
neither would he have showed us all these things, and done so much for us,
as he hath done, from the very beginning that we were a people, unto this day.

Therefore lift up your heads, you valiants of Israel,
that have come through the dark burning mountain,
and through the pleasant and delightful openings and prophecies,
through and beyond all outward washings, unto the Lamb of God,
that your robes may be washed white in his blood; that thereby you may overcome,
and then sit down in that kingdom which cannot be shaken, with weary Abraham,
thoroughly tried Isaac, and wrestling Jacob.

O how glorious are you all in the sight of God, and all his people,
even as an army terrible with banners,
in the sight of all adversaries! therefore keep your ranks,
and march on in your heavenly way, which the Lord of Hosts himself hath set you in,
and Babylon the great shall fall before you more and more;
for the Lord of Hosts hath spoken it; and you, with all the holy martyrs of Jesus,
shall rejoice over her downfall forever.

These few words farther and again, spring up in my heart to you all, dear friends,
brethren and sisters, to wit;
That we may be always mindful how we received the truth at the beginning,
and be careful that we travel on with our feet always shod with the same humility,
and poverty of spirit,
as when we were first shod with the preparation of the gospel of peace; never forgetting,
nor changing the poor man`'s food, to wit, our old water and pulse,
for any portion of the rich man`'s dainties; but still waiting on God,
that in due season gives both milk to babes, and strong meat to them of riper age;
bearing in our remembrance the great execution that was done at the beginning,
by the smooth stones out of the poor shepherd`'s bag.

Now to the pure harmless seed, that cries in our hearts, I commend you all,
that therein as in the cleft of that rock,
against which the gates of hell shall never prevail, we all may dwell and abide forever:
so shall the work of the Lord prosper, to his own glory, and all our comforts forever.
Amen.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
The 17th of the Sixth month, 1678.

[.blurb]
=== An epistle to young people professing the truth.

[.salutation]
Dear Friends,

Knowing that many which fear the Lord, and think upon his name, have had, for some time,
a concern upon their minds for the declining conditions
of many young people that are amongst us;
saying often one to another, What will become of the next generation,
considering the youth of this are so degenerated
from those that received the truth at the beginning?
Whereupon it came into my heart, according to the examples of Christ and his apostles,
who to rectify abuses in marriage, and other things, saith,
but it was not so from the beginning; intimating,
that the best way to amend things amiss, is to bring people to the beginning;
that as they received Christ Jesus the Lord, so to walk in him;
which is the drift and end of this epistle to young people,
and others professing the truth.

Many are yet alive, who from their own knowledge can testify the humility, mortification,
and self-denial of the youth at the beginning,
together with their contempt of all youthful vanities, etc., their words few and savoury,
their countenances grave and serious, in their places diligent and faithful;
being examples of temperance and sobriety to neighbours and acquaintance;
in the worship and service of God attentive and watchful;
carefully improving all opportunities to increase
their communion and acquaintance with God,
in Christ Jesus the light.
All which were as blessed signs of those times of refreshment from God`'s presence,
that the souls of the faithful were then made partakers of.

Let children inquire of their parents, that were eye-witnesses from the beginning,
and they can tell them; let servants ask their faithful masters,
and they can inform them, what manner of people the younger sort of Quakers, so called,
were at the beginning: nay,
there were few such strangers in the places where the truth first took place,
but they could declare these things.
By all which, as in a glass, many now, professing the same truth,
may see themselves bearing another image: therefore ought diligently to make inquiry,
what is the cause, and whence the disparity ariseth;
for if the gospel at the beginning proved itself to be preached again,
by the fore-mentioned,
and many more blessed effects upon all those that received the truth in the love of it;
what is the matter?
Is not the gospel an everlasting gospel, and Christ the way, the truth, and the life,
the same yesterday, today, and forever?
And doth not his works still, in the hearts of the called, chosen, and faithful,
bear witness of him?

Therefore, it is to be feared, those that are thus fallen, have received another gospel,
or the gospel perverted, or turned upside down, as the apostle speaks;
seeing those at the beginning, began in the spirit; but since that, many that began well,
think to be made perfect by the flesh, where too many hold the truth in unrighteousness.
But my design is, not to accuse, but to inform those that are out of the way,
if possible they may be reclaimed, before the evil day overtake them.

I know some of the younger are ready to blame the elder, and some children their parents,
and some servants their masters`' examples: to all which I say,
That such as are guilty thereof shall bear their own burden,
and shall not escape the righteous judgment of God: but you, that make this plea, know,
that the soul that sins shall die; and the witness of God in your consciences,
if hearkened unto, will convince you of the vanity of this fig leaf covering,
and the deceitfulness of your own hearts,
in thinking that the e`'vil example of others will be an excuse for your backsliding.

For those that in their youth received the truth at the beginning,
were surrounded with evil examples on every hand;
so that if examples could have prevailed to continue them in worldly vanities,
they could never have broken through those oppositions
from acquaintance and nearest relations;
for if they had looked outward, all hopes of preferment in this world were wholly gone;
and looking inward, there appeared such strong holds of Satan,
as seemed impossible ever to be overcome;
the truth itself being such a stranger in the earth,
that almost every body was backward to give it entertainment,
especially if they had any thing in this world to lose for harbouring of it.

Whereas the youth and others of later times found the truth both ready proved,
and successfully defended,
against the subtile arguments and wits of those professing times,
in which it at first broke forth; and that not by the might and power of wit,
or outward learning, but by simplicity and godly sincerity,
accompanied with holiness of life and conversation;
which was a great confirmation to the first publishing of it:
together with the meek and patient, yet bold and valiant,
suffering the loss of all for the truth, as it is in Jesus.
By which, in a great measure, the rough way was worn smooth,
and the passage made much more easy to those that followed, than it was at the beginning.
For those that were as gazing-stocks at the beginning
of latter times came to be well known;
and that estrangedness to persons and principles came to vanish away,
and a good esteem of the truth, and of those that professed it,
sprang up in divers persons: so mightily grew the word of God,
and prospered at the beginning.

But alas, of latter times, the wild boar of the forest hath got into the vineyard,
and rooted up many hopeful plants; and others are (alien into the world`'s customs,
ways and fashions, who are become as spots in the true Christian assemblies,
and blemishes to the truth, as it was at the beginning; as if the sins of Sodom,
which were pride, carelessness, excess, and contempt of the poor,
were become the virtues of Zion.
Many young people, and others, getting into those things again, which their parents,
relations, and acquaintance, for good conscience sake, were forced to lay aside;
as if in these latter times the efficacy of truth was not the same as at the beginning;
and as if the cross of Christ, that was so powerful then was now become of none effect.

Little doth the wanton youth of this age think what sighs
and tears their godly parents and friends that love them,
pour out in secret for them, both because of their eternal estates hereafter,
and the dishonour they bring here unto the blessed name and truth of God,
whereby it is become a saying amongst ancient people,
that the Quakers now a-days are not like those at the beginning.

What watchfulness, what carefulness, what diligence therefore ought every one to use,
lest by bad company and examples, they should be ensnared before they are aware,
and so by degrees be drawn to such inconveniences,
as afterward they will find very hard to withstand;
until they are brought to that degree of stupidity, and hardness of heart,
that all exhortations to virtue and godliness find so little entertainment,
that even strangers in our meetings are more serious,
and tenderness of heart sooner procured in them,
than in many who have frequented our assemblies from
their childhood unto men and women`'s estates,
so evil and catching are the bad examples of others
to them whose hearts are not kept tender to God.

Be serious therefore, all you that make profession of the truth, in your tender years,
and examine yourselves, how you came to make profession of it.
Was it for some by ends, and sinister respects, or was it by education from your parents,
or others only?
Not regarding the good intention and end thereof,
so as to come to the root of the matter in yourselves,
nor heeding to be guided by the light in your own consciences;
but from time to time feeding only upon good words from others,
as it is to be feared too many do at this day.
I say unto all such careless ones, I pity your condition;
for all your goodness will prove like the morning dew,
that soon vanisheth when heat ariseth; and your profession will wither,
like the corn upon the house top: therefore let the time past suffice,
that you have spent your precious time to no purpose, and rest no longer in an easy mind,
above the cross; but sink down in deep humility to the oppressed seed of God in you,
which he hath left as a witness for himself, that you might not be as Sodom,
and like unto Gomorrah, if you diligently hearken to it in your own particulars.

Parents and others, that fear the Lord, are bound in duty to God,
to use all means they can to impress the tender minds of
their children and youth with the sense of God`'s power;
and in so doing they shall not lose their reward from God, although their children,
when grown up, turn their backs upon it.
For parents, at the beginning,
looked u)on the truth as the best portion for their children;
not so much heeding their preferment in this world,
if by any means they might have an interest in that which is to come.
And in order thereunto,
they counselled their children to mind the inward and spiritual grace,
that so they might not rely upon any outward and
visible thing for preservation and defence;
because that inward and spiritual grace was commended to us at the beginning,
as the best teacher, to deny ungodliness and worldly lusts, and to live godly,
righteously, and soberly, in this present world.
But if young people will reject the good advice of their parents and others,
and degenerate from their education, their destruction will be of themselves;
and their poor grieving parents, and others, can but mourn in secret for them.

Children and others ought to know, that there is no standing at a stay,
or stop in religion; for not to go forward therein, is to go backward:
hence it is that the scripture saith, Heb.
vi. "`It is impossible for those who were once enlightened,
and have tasted of the heavenly gift, and were partakers of the Holy Ghost,
and have tasted the good word of God, and the powers of the world to come,
if they shall fall away, to renew them again into repentance;
seeing they crucify to themselves the Son of God afresh, and put him to open shame.`"
And being a business of the greatest importance,
the apostle urgeth it from the similitude following; "`For, saith he,
the earth which drinketh in the rain that cometh oft upon it,
and bringeth forth herbs meet for them for whom it is dressed,
receiveth blessings from God; but that which beareth thorns and briars, is rejected,
and is nigh unto cursing, whose end is to be burned.`"

If there be therefore any consolation in Christ the Truth, if any comfort of love,
if any fellowship of the spirit, if any bowels of mercies,
you that live carelessly and wantonly upon the earth, consider your conditions,
and examine yourselves, how far the fore-mentioned scripture affects you;
for I have a deep concern upon my heart for you all, that have forsaken your first love,
and bear another image, than those young people I have mentioned at the beginning.

Suppose by your conformity to the vanities of this present world,
you should gain a large share therein, which but few obtain;
what will it avail when terrifying death looks you in the face?
Have you forgotten Moses`'s choice,
who esteemed it greater riches to suffer afflictions with the people of God,
than to be related to the court of a great monarch?
What shall I say to prevail with you?
Is it not great pity,
that any who in years past bore the frowns of the great ones of the earth patiently,
went through reproaches cheerfully, and many hardships constantly, for some time,
and doubtless such felt a reward from God for their encouragement?
Why then should you lose your crown at last?

Come, let us reason together, and let God`'s witness speak.
Wanted you any thing, while you kept your integrity?
Did you not witness one day in God`'s presence,
better than all the delights that ever you had,
since your minds by looseness and vanities have been estranged from him?
Did your pleasures and companions in folly ever afford you that comfort,
and inward contentment and peace, which sometimes you have felt amongst God`'s people?
Why then do you deprive yourselves, by your negligence, of that sweetness and comfort,
which no created enjoyment can recompense the loss of,
besides that further hope of glory that is laid up for those that walk uprightly?

Many of the youthful people and others amongst us, need not say, What is truth?
Because I know it hath often proved itself to their consciences,
beyond all outward demonstration;
and they cannot be ignorant how divers that have backslidden
have been followed with a secret hand against them,
in all they have gone about.

Come away therefore, and tarry no longer in lying vanities; and let not any say,
they cannot leave them; for that is the language of your soul`'s enemy to discourage you;
wherefore resist him steadfastly in the faith, and he will fly from you;
for he hath no power, but in darkness and unbelief.
Watch therefore to the light of Christ Jesus,
that discovers all the twistings of that crooked serpent,
and take up the daily cross to those evils that so easily beset you; and you will find,
as you have often heard,
the armour of light at hand to defend you against all your youthful lusts: as,
blessed be God, there are yet a cloud of witnesses alive, that can, from good experience,
testify the same.

[.postscript]
====

P+++.+++ S. Let none despise these lines for their plainness;
for we were a plain people at the beginning,
I know some of the younger sort are apt to be taken with fine words,
and fashionable language, as with other things in fashion; but experience shows,
that that which tickles the outward ear, commonly stops there,
very seldom coming so low as to the truth in the inward parts:
therefore this epistle is sent abroad in so plain a dress, on purpose,
answerable to a plain seed in them that are puffed up, but ought rather to have mourned;
which seed being reached, and their souls relieved, my end is answered,

====

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Luton, the 16th of the Sixth month, 1686.

[.blurb]
=== To Friends of Sewel`'s meeting, Bedfordshire.

[.salutation]
Dear friends,

Having this opportunity, I I was willing to signify my remembrance of you,
amongst whom I was conversant in my young years, and now am old; yet I can say,
in all that I have seen, I never saw the righteous forsaken;
and therefore these lines are to encourage you all,
to be faithful to the light of Christ Jesus, in your hearts and consciences,
for that is the true grace of God, in which the faithful do stand,
and shall stand to the end,
notwithstanding all discouragements either from enemies in your own bosoms,
or from without; notwithstanding the wicked one`'s rage,
who goes about every way to discourage and hinder, both the prosperity of truth within,
and without also; yet the truth in which you have believed shall prosper;
and you that are faithful to it, shall hold out to the end.
Therefore love the truth nevertheless, but rather the more,
because it is rejected of men; but it is that which God hath chosen,
to exalt his name in the whole world in his due time,
and at present doth exalt it in the faithful.
It is now near forty-four years, since first myself, and it may be, some others,
that are yet alive in the body among you, heard the joyful sound of truth;
since which time we have seen the wonders of the Lord,
in preserving both the truth and the faithful in it, blessed be our preserver forever.

My exhortation to you all is.
To love the truth, and one another in it,
for it is the best portion you can have in this world;
therefore do your utmost to make it the portion of your children after you;
for godliness hath the promise of this life, and that which is to come.
And, I beseech you, refuse not the chastenings of the Lord; for I can tell you,
by good and long experience, that afflictions are God`'s furnace,
in which he refines his people as gold; then they can tell of his doings,
and that they are miraculous in their eyes, as my soul can do this day,
as a man that hath been afflicted from my youth up.
Now in my old age, being eighty years, in all which the Lord hath tried me,
but never forsaken me; but often instructed me in his secrets,
and confirmed me in his truth,
and given me the benefit of that counsel which I have given to you and others;
so that I have found the virtue of those exhortations
to be a comfort to me in my greatest extremities,
to my unspeakable satisfaction and joy.

This I speak, not to boast, but to confirm you in the truth,
that we may all persevere unto the end, and finish our coarse with joy,
in despite of all opposition whatsoever.
And this shall you do,
that are faithful to the light of Christ Jesus in your own particulars;
for that must be watched unto, and waited in, unto the end; that the light,
as it comes from Christ, so it leads to Christ, and exalts the Father,
through the Spirit, who is God over all, blessed forever.
Amen.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Hertford, the 3rd of the Third mo.
1698.
