== Chapter 9

=== An exhortation to stand fast in the truth, according to our ancient testimony, which you have heard from the beginning.

Dear friends, brethren and sisters,

I cannot forget those ancient days, in which we were refreshed together,
when it was my lot to labour, both by exhortation and sufferings, amongst you:
there being those yet alive, that may remember,
with what success those days were attended;
though many of our ancient friends are gone to their long homes; and others,
as well as myself, are hastening apace after them.

That which I have to write to you, is by way of exhortation, to stand fast in the truth,
according to our ancient testimony, which you have heard from the beginning:
for I am sure we began well, who began in the Spirit, for the fruits of it were manifest,
by our deep humiliation into the death of the selfish man;
it being made of no reputation by many at the beginning, after the example of Jesus,
as also our mortification to this present world, and the friendship of it:
so we were crucified unto it, and it unto us, at the beginning.

And above all, let us not forget those aboundings of unfeigned love one towards another,
by which it was manifest, that we were passed from the death, where the whole world lies,
in hating and being hated, unto the life of Jesus, that died for mankind,
and rose again for their confirmation and justification: and where it is otherwise now,
it is because of the enemy sowing his tares, while the good man slept;
but he that continueth to the end, shall be saved.

We have been confirmed in the truth by many remarkable ways; as,
our God supporting us under all our deep sufferings,
and sometimes by his eminent hand upon those which caused us to suffer,
as also by the heavenly testimonies of many faithful friends at their dying hours;
but above all, by the testimony of the same spirit in our own hearts and souls,
who are yet alive.

All which, with much more of like nature, that might be mentioned,
may be as a cloud of witnesses to the truth of the
testimony which we received at the beginning;
and of the true grace of God, in which the faithful now stand,
through Jesus Christ our Lord, the fulness and foundation,
from whence all our refreshings, and springs of life and comfort proceed:
which makes the sincere soul cry out, "`Spring up, O well;
sing ye unto it;`" and to honour the Son, as we honour the Father, who is, over all,
God blessed forever.

But, dear friends, there are goings out of the truth, as well as goings in;
as into the house the prophet speaks of, Ezek. 43:11.
And Rev. 11:2. John speaks of the altar and temple,
and them that worship therein, how all came under the heavenly measure given from above,
into the hand of the angel.
He also speaks in the same place of the outward court, adjoining to the temple,
in which were such, as should tread under foot the holy city;
being left unto their own measure, as it were,
of opinion and imagination of their own conceivings; which all ought to watch against,
lest, being left to ourselves, we be found, after all, but in the outward court,
that is given to the Gentiles.

Let those that are spiritual, judge what I say,
and they will confirm it by their own experience, that there is flesh, as well as spirit,
in us all; as the apostle saith of himself. Gal. 5:17.
Therefore there is great need of a strict watch
to be kept "`with all keepings`" as the margin hath it,
lest we forget there is going out of the truth, by many unsuspected ways,
as well as going in by Christ the door, both being faithfully told us at the beginning;
as many that remain at this day can testify.

These things I signify in short,
that all may be diligent and careful to keep the word of God`'s patience,
as those Philadelphians did.
Rev. 3:10,12, who by overcoming, shall be as pillars in the temple of God,
and shall go no more out.

But he that will build high, must lay the foundation deep: for this I have observed,
the deeper the humiliation, the deeper the reformation.
As it is said of Christ, Acts viii.
"`That in his humiliation his judgment was taken away;
he was as a lamb dumb before the shearers; he opened not his mouth;
and who can declare his generation?
for his life was taken from the earth:`" who hath
left us an example that we should follow his steps:
for he was both a Saviour, and an example, 1 Pet. 2:21.
And what God hath joined together, let no man put asunder.

For the true and saving knowledge of Christ, is a conforming knowledge;
"`We shall be like him,`" 1 John 3:2. "`for we shall see him as he is;`"
"`and hereby`" saith the same John "`we know that we know him,
if we keep his commandments:`" implying,
that there is no true knowledge of God without holiness: and also,
it is not the bare knowledge,
for "`hereby`" saith he "`we know that we know him:`" which experimental
knowledge puts an end to all disputes about him.

And therefore without controversy,
"`Great`' is the mystery of godliness!`" and where
that mystery is known truly among such,
there is no controversy about it; for both that mystery itself, and that faith,
by which it is known and believed, are fitter for admiration,
than man`'s comprehension is, as the apostle speaks, 2 Thess. 1:10.
"`When God shall be glorified in his saints,
and admired in those that believe.`"

Therefore all that forsake and leave spiritual Egypt, must learn to stand still,
and be quiet, that they may see the salvation of God, and witness the joy of it,
that they shall be of the number of those, who shall sing the song of Moses and the Lamb.

Dear friends, in my afflicted old age, I have found that saying made good unto me,
That they who go down into the deeps, see the wonders of the Lord;
for there is witnessed that spirit which searches to the bottom of things,
and manifests the deep things of God; which the fallen man, with all his searchings,
in his wisdom that is from below, cannot find out.

Therefore I beseech you, dear friends, watch unto the light and Spirit of Jesus,
that you may be preserved, as born of the incorruptible seed and word of God:
for all things else may be corrupted; but that which is born of God,
is that elect which cannot be deceived: unto which light and spirit I commend you,
in the simplicity of the knowledge of Christ Jesus our Lord,
that you may be preserved unto the end.

Amen.
Your friend in the truth.

John Crook.

Hertford, the 6th of the twelfth month, 1698.

Anno AEtalis 81.

The Postscript.

We live in a captious age,
therefore I thought good to explain our ancient testimony
to the light and spirit of Christ within.
I never understood or believed that the testimony was exclusive to Christ,
being without us: or of the validity of his death and suffering without us,
as the price by which we were bought, and reconciled to God:
"`For we were bought with a price,`" saith the scripture, 1 Cor. 6:20. "`For if,
when we were enemies, we were reconciled to God by the death of his Son, much more,
being reconciled, we shall be saved by his life.`" Rom. 5:10.
Who sits at God`'s right hand in heaven, and maketh intercession for us. Heb. 7:25.
And is also by his life, to wit, the life of Jesus,
made manifest in our mortal flesh, as the Scriptures testify. 2 Cor. 4:10-11.
And what God hath joined together, none ought to put asunder.

This I take to be, in short, our ancient testimony, as to the God and man Christ Jesus;
of which I hope we shall never be ashamed.

John Crook.

=== The Design of Christianity.

The name Christian, implies the anointing;
Christ being "`anointed above his fellows,`" Heb.
1:2. importing his fellows to be anointed also.
And the beloved disciple John, 1 John 2:27. saith, Those to whom he writ,
had "`received the anointing from the Holy One,`" etc. to make them holy, no doubt,
their "`heavenly Father being holy,`" Lev it.
xi. 44. Which is the great design of Christianity, as the,
scripture abundantly testifies; see Lev. 19:2,and XX. 7. 1 Pet. 1:15.

Christ was also called Jesus,
"`For he shall save his people from their sins,`" Matt.
1:22. "`By abolishing and destroying them,`" saith Leigh,
on John 1:29. in his Crit.
Sacra.
And Christ saith himself, "`For this end was I born,
and for this end came I into the world,`" John 18:37. "`To bear
witness of the truth:`" by drinking that bitter cup of sufferings, Matt. 26:39,42.
for his sheep and followers, for whom he laid down his life,
and shed his most precious blood, to restore man to the image of God again,
that they might follow his steps, as he had left them an example, 1 Pet. 2:21.
Signifying thereby, that he was both a Saviour and a pattern;
which being joined together, none ought to part, or put asunder,
who "`learned obedience by the things that he suffered,`" Heb.
5:8. "`And made himself of no reputation,`" Phil. 2:7. All
which was not only meritorious for all that should believe in him,
but also exemplary to them, that they should follow his steps,
in all those afflictions and sufferings that should betide them in following him,
in the regeneration, to fill up the sufferings of Christ that are behind,
for his body`'s sake, which is the church. Col. 1:24.

Not that our sufferings, or following of him, did equalize his sufferings,
or were the meritorious cause of salvation, and acceptance with God,
either for ourselves, or others;
but that we might be partakers of "`God`'s holiness,`" Heb. 12:10.
the fulness whereof dwells in Christ;
and that we might show forth of the power and virtue
of that which Christ did and suffered for us,
by that grace we receive of his fulness,
which is "`grace for grace,`" John 1:16. viz. Something, as it were,
of everything that is in him, in whom we are accepted, even in his beloved Son, Eph. 1:6.
So we received perfection of parts, though not of degrees,
as to that fulness that dwelt in Christ.

Therefore, as holiness here, in order to our happiness hereafter,
was a great end of Christ`'s sufferings, while on earth; so now he is in the heavens,
at God`'s right hand, his intercession, and all that he doth,
is in order to perfect his saints in holiness;
waiting henceforth until his and their enemies be made his footstool, Heb. 10:12-14.

Whereby it appears, there were enemies yet to be subdued,
which doubtless were those of a man`'s own house; as the prophet speaks of,
viz. Those lusts and corruptions that still remained to be put under,
in the minds and inward parts of his people, Mic. 7:6.
Matt. 10:21. Christ preached to Nicodemus the necessity of regeneration,
saying, "`Except a man be born again, he cannot see the kingdom of God,`" John 3.
Yet Nicodemus made a good confession to, Christ in words, saying, "`Rabbi,
we know thou art a teacher come from God;
for no man can do those miracles that thou dost,
except God be with him,`" a kind of short creed, as it were.
Christ nevertheless tells him, a man must be born again, etc.
"`For that which is born of the flesh is flesh,
and that which is born of the spirit is spirit.`"
Though Nicodemus understood this birth carnally,
yet he took it to be a real birth Christ spoke of; as appears by his question,
"`Can a man enter the second time into his mother`'s womb, and be born again?`"

Christ`'s words also signify, so much, and no less, as if he had said, "`As that birth,
which is born of the mother, is of the nature of the mother;
so that birth which is born of the Spirit, is spiritual,
and of the divine nature,`" 2 Pet. 1:2-3.
Now, where this birth is witnessed,
the design of Christianity is answered, by keeping the commandments of God, 1 Cor. 7:19.
and that is through walking by the rule of the new creature,
which avails with God, as the apostle speaks, Gal. 5:15-16.
Whereas a bare opinion, and formal performance of the things of God,
avails nothing.

Wherefore, from the want of this experimental knowledge of the new birth,
proceeds formality, strife, and envy, about the things of God; for the new man,
born of the Spirit of God,
is renewed in knowledge after the image of him that created him. Col. 3:10.
Observe, it is said to be renewed in knowledge, etc.
It knows and understands divine things otherwise, and after another manner,
than the fleshly birth doth: "`For whosoever is born of God, doth not commit sin,
for his seed remaineth in him; and he cannot sin,
because he is born of God,`" 1 John 3:10-9.
"`And in this the children of God are manifest,`" saith John.
So that the very end of regeneration is holiness and godliness;
which is to advance the great design of Christianity in the world,
and thereby Christ`'s kingdom is exalted, and himself magnified,
who is the express image, "`of his Father`'s glory,`"
Heb. 1:3.
Jt is no wonder, therefore, that such as answer the design of Christianity,
viz.: by living god-like in Jesus Christ, suffer persecution.

In the next place, holiness of life and conversation in Christ Jesus,
is the end of the afflictions and exercises that befall God`'s people, Isa. 27:8-9,
as trials of their faith; for tribulation works patience, and patience experience.
And the apostle James exhorts, to "`let patience have its perfect work,
that they may be perfect and entire,
wanting nothing,`" James 1:3-4. "`He stayeth his
rough wind in the day of the east wind;
by this shall the iniquity of Jacob be purged; and this is all the fruit,
to take away his sin.
God will render to every man according to his deeds;
to them who by patient continuance in well-doing, seek for glory, and honour,
and immortality, eternal life: but unto them that are contentious,
and do not obey the truth, but obey unrighteousness, indignation,
and wrath,`" Rom. 2:6-8. All which,
with many like sayings and exhortations in scripture, shows,
holiness and righteousness to be the great design of Christianity.
And the apostle, Rom.
xi. saith, "`The kingdom of God is not meat and drink, but righteousness and peace,
and joy in the Holy Ghost:`" adding, "`That he which in these things serveth Christ,
is accepted of God, and approved of men:`" as if this was the only true gospel service,
and the great design of Christianity.

Now I appeal to all impartial and unprejudiced Christians,
whether amongst all the denominations of professors of religion, they know any people,
as a people in general, that more fully answers the end of Christianity,
by holiness and righteousness in their lives and conversations,
than the people of God called Quakers do:
notwithstanding their being misrepresented to the world by some,
as if they were not Christians at all; because, say some, they baptize not with water,
nor use bread and wine as the Lord`'s supper.

To which I answer, in short, for myself and brethren,
we do not disuse them out of contempt, but upon a thorough search,
and serious examination--which ought to be allowed us--we do not find
those outward and visible signs to be required of God at our hands;
which we hope none that do what they do, out of conscience to God, will condemn us for.

Now if the drift of the scriptures,
the end of God`'s sending his Son Jesus Christ to bless people,
not only by his dying for them, as aforesaid,
but by "`turning every one of them from their iniquity,`" Acts 3:26,
and the end of his life and sufferings in the world, his resurrection,
his ascension into heaven, his intercession,
together with his expectation of all his enemies to be made his footstool;
and the end of God`'s afflicting and exercising his people,
be all to advance holiness and righteousness in the world,
as the great design of Christianity, how miserably mistaken are those,
that content themselves with the belief of certain creeds, which are many in the world,
as history informs us according to prevailing parties, etc.,
who commonly maintain this persecuting principle, That an error in judgment,
is worse than an error in practice.

Others contenting themselves with state religions,
and with that Christianity they received at the font;
little minding the necessity of holiness, "`without which none can see,
or know the Lord.`" Heb. 12:14.
And the beloved disciple testifies, "`Hereby we know that we know him,
if we keep his commandments,`" 1 John 2:3. As if he had said,
There is no true and saving knowledge of God, without holiness:
to which is annexed a promise, viz.; "`He that doth God`'s will,
shall know of his doctrine;`" which should rectify
the mistake of those that study to know doctrine,
more than to practise holiness; as also those who believe they cannot,
though assisted by the grace and spirit of God, perfect holiness in the fear of the Lord,
notwithstanding the exhortations of scripture thereunto, which, they say,
are to be understood only to stir up our endeavours,
not to encourage our faith to believe perfection attainable, as aforesaid.

This belief of the necessity of imperfection is not only dangerous, but hurtful; for,
instead of inciting endeavours after holiness, it discourages all attempts thereunto.
For what need a man set forth towards a city, while he believes he shall never come there.

Besides, this belief is grounded upon a great mistake,
as if perfection in holiness lessened the conquest or merits of Christ, while,
indeed it confirms them, by making his people more than conquerors through him.
Which may be called more, because it is a double conquest: First, by himself,
without them, as having spoiled principalities and powers, he made a show of them openly,
triumphing over them in it. Col. 2:15.
And secondly, because he conquers all his people`'s enemies within also;
that they being delivered out of the hands of all their enemies,
"`might serve him without fear, in holiness and righteousness before him,
all the days of their lives.`" Luke 1:74.

So that perfecting holiness in the fear of the Lord,
is so far from lessening or undervaluing the merits or conquest of Christ,
that it manifests him to be "`able to save to the
uttermost all that come to God by him.`" Heb. 7:25.
Not only from the guilt, but from the filth of sin also;
and to sanctify them throughout, both in body, soul, and spirit;
and to make them whole every whit, as he did those he cured outwardly.

This way of holiness was the good old way;
for it was called so in Jeremiah`'s time, Jer. 6:16,
and such as walked in it, found rest for their souls:
therefore it must needs be an old way,
even that old way, in which Enoch walked with God,
and "`Abraham instructed his children,`" Gen. 18:19,
"`and walked in it himself.`" Gen. 26:5.

And as it was the first way described, so it is the last mentioned in scripture,
as appears Rev. 22:14, with a blessing annexed to it, viz.,
"`Blessed are they that do his commandments,
that they may have right to the tree of life,
and may enter through the gates into the city.`"

But this is a narrow way, and to be sought for amongst the paths, as Jeremy speaks, chap,
vi.
16, as if the reason, that it was no more beaten, was, because it was not a common road,
but to be sought for amongst the paths;
as if it was a kind of Shibboleth that few could hit of, that walked in those many ways:
yet, notwithstanding, it was amongst the paths, etc.

A mystery like that which Solomon wondered at, and said,
"`This wisdom seemed great unto him,`" Ecc. 9:13. 15,
that was concerning the poor man delivering the besieged city;
concluding that by which he did it, was better than strength,
and better than weapons of war: notwithstanding the poor wise man was despised then,
as the poor in spirit are now, whom Christ calls blessed,
and begins his sermon upon the mount withal;
as if all other blessings depended upon poverty of spirit.

I shall conclude this discourse with the preacher at the end of Ecclesiastes, saying,
"`Let us hear the conclusion of the whole matter: fear God, and keep his commandments,
for this is the whole duty of man:`" or as Doctor Gell reads it, All the man,
in his Essay, p. 392, "`And,`" saith the Doctor, "`whatever else in man,
contrary unto this, is either the beast or the devil.`"

To this may be added also the saying of Richard Baxter, in his Sheet to the Light,
"`The question at the great day,`" saith he, "`will not be, How righteous Christ was?
but How righteous we were?`"
Thus Baxter.
And saith the preacher, "`God shall bring every work into judgment,
with every secret thing, whether it he good,
or whether it be evil:`" with these words the preacher ends his Ecclesiastes,
after he had seen all to be "`vanity, and vexation of spirit, under the sun.`"

John Crook:

Near entering into the 82d year of my age.

Hertford, the 17th of the 12th month, 1698-9.

=== An Epistle to Friends belonging to Hertford meeting.

Dear Friends,

Being the Lord`'s prisoner, (but I have a merciful keeper,
blessed be his holy name forever),
I was moved to signify my remembrance of you as followeth:
I beseech you be mindful of your reconciliation with God through Jesus Christ,
walking in all well-pleasing before him, that you may be kept unrebukable in his love,
for our God is a jealous God, lest a divided heart cause you to err,
in giving his glory to another.
But if we love him with all our heart, and with all our soul, we shall,
in our reconciliation to him,
be reconciled to all states and conditions that we
meet withal in this present evil world;
"`for fury is not in me,`" saith the Lord,
but against the briars and thorns that muster up themselves in battle against him.
It is our corrupt and fleshly part that God fights against,
that we might walk with him as Enoch did, that was not, for God took him;
he took him out of flesh into spirit,
as he doth all those that walk with God in the light, as he is in the light;
he translates them, in spirit, into the kingdom of his dear Son, as Enoch was, outwardly,
in heaven.

Dear friends, let us not always be dwarfs in Christianity, as it were,
for Christ is a thorough Redeemer to all that the first Adam lost;
as Abraham recovered all for the king of Sodom, that Chedorlaomer had carried away.
Therefore mind your growth, I beseech you, from little children to young men,
that you may overcome the wicked one;
and unto the state of fathers--which for your time divers of you
might be--that you may know him that was from the beginning,
that is, Christ Jesus, yesterday and today, the same forever.
If you are in the spirit, walk in the spirit, that discovers the deep things of God,
that we may, after our long wading, at last learn to swim in those waters,
where all things live, as Ezekiel speaks, etc.

For the barren fig-tree in God`'s orchard is in no
better case than the bramble in the wilderness;
profession without God`'s likeness in Christ Jesus,
will receive no better answer from God, the judge of all,
than "`I know you not,`" if we be found workers of iniquity.

You have had plenty of words outwardly, but to hearken to the word inwardly,
is better than all; for that is both able to comfort at present, and save forever.

Dear friends, the visiting hand of God is in this town,
and none of you know how soon mortality may enter into your dwellings,
therefore I beseech you, live as you would die,
and then death will not be terrible unto you;
but as a messenger of glad tidings to your inward man, though displeasing to the outward.

I rest your friend and brother in the faith and patience of Jesus,

John Crook.

Hertford, the 25th of the 12th month, 1698-9.

=== Advice to my children and grandchildren.

Dear Children,

I must leave you in a wicked age,
but commend you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it,
you will find it a counsellor to instruct you in the way everlasting,
and preserve out of the ways of the ungodly.

I have seen much in my days, and I always observed,
that the fear of the Lord God proved the best portion, and those that walked in it,
were the only happy people,
both in this life (while they continued faithful) and when they come to die,
though they meet with many hardships in their passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to the upright soul,
than the greatest pleasures this world can afford; the former reaches the heart and soul,
while the delights of this world are but a show, and appearance only,
vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities; therefore the apostle, Rom. 6:21,
might boldly put the question to the converted Romans, viz.,
"`What fruit had you then in those things whereof you are now ashamed?
for the end of those things is death.`"

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it; you may find buddings of it, from an holy seed in your hearts;
as you mind the inner man, the light will manifest the stirrings of it after God,
which I felt from my tender years; although I understood them not so plainly,
till I heard the truth declared.

I advise you to keep a pure conscience, both towards God and man; for if that be defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God`'s presence;
and then deadness and dryness will be your miserable portion.

Be careful how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting, and vain talking, are said to grieve the Spirit of God:
read Eph. 4:29-30. But improve your time in prayer and religious exercises, etc.,
and be diligent in your lawful callings,
for "`The desire of the slothful man killeth him.`" Prov. 21:25.

Be careful what company you frequent;
for a man is commonly known by the company he keeps, as much as by any one outward thing;
and of your behaviour in company; for I have found, that a wise and sober deportment,
adds much to a man`'s reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan`'s devices;
so the net will be spread in vain in the sight of the bird;
for watchfulness will make you in love with a retired estate;
and the more truly and perfectly any man knows and understands himself,
the better discerning will such have of other men; as in the beginning,
when deep silence of all flesh was more in use, the spirit of discerning was more common,
and quicker, than since it hath been neglected; therefore be sure you spend some time,
at convenient seasons, in waiting upon God in silence, though it be displeasing to flesh;
for I have had more comfort, and confirmation in the truth,
in my inward retiring in silence, than from all words I have heard from others,
though I have often been refreshed by them also.

Love the Holy Scriptures, preferring them to all other books whatsoever;
and be careful to read them with an holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt;
but exercise faith in the promise of Christ, who hath said,
"`My spirit shall take of mine, and show them unto you.`"

Keep constantly to religious meetings amongst Friends; but look to your affections,
that you respect not persons, but the power and life of truth, from whomsoever it comes;
not minding the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide, when flashes of affections will fade and come to nothing,
after the words are ended.

Love one another truly, manifesting your love by good counsel,
and being helpful to each other upon all occasions;
being good examples to all you converse with, especially to your children,
and those of '`your own families, that pride and vanity may not be countenanced by you,
but rather reproved; remembering, while they are under your government,
you must give an account of the discharge of your duty to God towards them.

Lastly, be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world:
and while you do live in it, despise not the chastenings of the Lord,
whatever they be he is pleased to visit you with.
I have been afflicted from my youth up, both inwardly and outwardly,
but the God whom I served, provided for me, when all my outward relations forsook me,
none of them giving me any portion to begin the world withal.
This I speak, to let you know, I shall leave more outwardly, even to the least of you,
than was left me by all my relations, etc.,
I need not mention this sharp affliction (beyond expression) in my old age, because,
in some measure, you know it; but I could not have been without it,
as the Lord hath showed me, for I have seen his wonders in the deeps:
therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls, though displeasing to the flesh.

These things I commend unto you, out of true love to your souls,
knowing how the vain mind of man little regards such advice as this I leave behind me:
but by this advice I show my true love to you all, desiring God`'s blessing upon it;
to whom I commit you all, my dear children, and end my days.

Your loving father and grandfather,

John Crook.

Hertford, the 1st of the 1st month, 1698-9.
