== Chapter 3.

[.letter-heading]
To Friends in Bedfordshire, Hertfordshire, and thereaways: mercy and peace rest among you.

[.salutation]
Dear friends and brethren,

Many and long have been the days of your sorrow and mourning,
and great also have been the deliverances which you have known:
what people have been saved by the Lord, like unto you?
And who have been carried as upon eagles wings, as you have been?
Who in storms, have known him making a calm; and in a tempest,
have known him rebuking the winds?
And when no rock could be seen, because of the swelling of the mighty waters,
but through the dashing of the waves, the rock has been covered over with water,
and yet in a little time the rock has appeared again, as unmoveable and fixed;
whereby you have learned both how be in need, and how to abound; and to be full,
and to suffer hunger.
Keep fast the word of his patience, and let none take away your crown,
but hold fast what you have received, which has already made you to differ,
not only from what you were in times past, but also from your familiars and acquaintance,
who account it strange to see what you are, considering what you once were.

And now the day is come and coming, wherein the difference must yet more appear,
between those that fear the Lord, and those that fear him not;
and the difference between those that say they are Jews, and are not,
though they may have the praise of men.
But the true Jew shall be now known from the formalist and time-server,
and the upright-hearted from those that were never true in any form or profession.
For it is the truth in the inward parts which many have talked of,
but few have kept unto; such vain talkers shall now be known from the pure innocent seed,
which now can lift up their heads, and not change their countenance,
but are single to God.
Come life, come death, liberty or bonds, their loyalty appears;
for they are not of the earth, and therefore cannot sell their birth right for vanity,
nor their inheritance for that which is changeable.
But however, the God, whom this royal seed serve, deals with them,
either to kill or save alive; yet they will not bow to the world,
but must be faithful in all things, knowing in whom they have believed.

And though none may be tempted like unto these, or none seemingly so desolate as they,
yet they will trust in the hope, against the hope,
and believe for the inheritance beyond all; because of a secret dependency upon,
and a near alliance unto, the God of the whole earth, whose children they are:
and their Father they dare not forsake, whatsoever becomes of them,
for he never did nor will forsake them; and their care is,
that he may not be against them, whatever becomes of them.
O you begotten of the Lord! lift up your heads, and know, in the Word of the Lord,
that whatsoever trials he exercises you withal,
though it be to the offering up of all that is dear unto you, even as Isaac unto Abraham,
your father; yet will he not fail, but provide himself a sacrifice,
to save your hope from perishing, and your faith from failing.

Therefore be strong in the power of his might, and valiant for his name, unto the end;
giving up all that is dear unto you,
that the trial of your faith may appear to be more precious than silver,
seven times tried in the fire, for the perfecting your joy, that it may be unspeakable,
and full of glory; that through the steadfastness of your faith,
you may not fail of deliverance, but by walking in Abraham`'s steps,
you may come to Abraham`'s blessing; and your faith, as it was to Abraham,
shall be imputed unto you for righteousness; and God will be your friend,
and you shall walk with him, and he will not hide from you the things that he does;
but you shall know his secrets, when all the dreamers shall be starved,
as with their dreams, and the despisers shall wonder and perish;
but your hope shall not make you ashamed.

Therefore, my dear Friends, as one that has travailed with you and among you,
I beseech you stand fast in the liberty wherewith Christ has made you free,
and be not entangled again with any yoke of bondage; but give up all freely and wholly,
and keep nothing back, but let the Lord of the whole earth be your possession,
and the mighty God of Jacob your inheritance forever.
For certainly, great is the work our God has in hand,
and glorious shall be the issue of these things, unto all who stand faithful; but sorrow,
horror, judgment, and wrath, unto all hypocrites and dissemblers,
who are now running in the way of Esau,
as before they were running in the way of Cain and Ishmael.
But where can they fly from God`'s presence?
Or where can they hide from his hand?
Surely he will arise in his fury, and his jealousy shall burn as an oven,
against all that are chaff and stubble.
And after he has tried his seed, and made the excellency thereof appear,
beyond all the vain talkers, and has purged his floor, and cleansed his sanctuary;
then will he renown his name forever, and make Zion a praise,
and Jerusalem the beauty of the whole earth.

And therefore now my dear friends and brethren, keep your meetings,
and be not at all affrighted, and take no notice of the boisterous winds; but be still,
and they will pass over; know your dwelling, and abide there with God.
As any are moved, let none keep silence, or withhold from letting the fountain flow;
but build up one another in the holy faith, that God`'s presence, life, and power,
may abide with you and run through you; that you may be a watered garden,
and as beds of spices, that the beloved may blow +++[+++upon],
and cause the scent thereof to ascend; that the Lord, your husband; may walk in you,
and be with you forever.
Thus the fearful and unbelieving may be seen to dwell without,
and you to have no fellowship with them, but rather to reprove them:
that a pure lump you may be, and a holy temple;
that nothing may be heard or seen among you,
but what is becoming so high and holy a calling, as you are made partakers of;
that purity may shine through you, and greenness and freshness may be your condition,
and righteousness and holiness your whole course, at all times,
to the praise of him who has called you forever.
Amen.

My God and Father keep you all, dear friends and brethren, in his arms of love and peace,
and fill your meetings with his power and presence,
that you may be a blessing one to another: and let peace and unity be among you;
let every one keep their place in the body; and whereto you are called, abide faithful;
and none strangle any moving of the life, but all in the innocency and simplicity keep,
which will make you bold and valiant for the truth of our God, in this day of storms,
wherein all the blossom trees, that bear no fruit, shall be cursed,
together with the dry and fruitless; for now shall they be blessed forever,
who stand faithful to the end.
Keep your meetings, as at other times; and take no notice of anything,
but what is pure and holy: and so the God of peace keep you all,
with all the faithful brethren and friends, in his love and peace to the end.
Amen.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
From Huntingdon jail, the 28th of the Eleventh month, 1660.

[.letter-heading]
An epistle for unity to prevent the wiles of the enemy.

Dear lambs of my Father`'s fold, who have been rescued out of the hands of the devourer,
and known the wolves, and the roaring of the lions, and the craft of the foxes,
who made a prey upon you, while you were without a shepherd,
and while you were in the open field, and upon the wide mountains,
without a hedge about you, or a wall to defend you; but every wild beast,
and ravening bird, was ready to prey upon you.
There was no one found either to pity or gather you, until the good Shepherd,
from whose fold you had strayed, sought you out, and brought you home,
some upon his shoulders, and some driven gently, and others,
who would have run away after you were found, being accustomed to wander,
and in love with your wandering, he constrained by his sharpness;
after whom he has had a watchful eye, because of your liableness to go astray again,
to feed by yourselves, and not with the rest of the flock,
whereby you have been liable not only to be torn by the briars and thorns,
but also with the wolf, and other preying beasts, unto your wounding again.

O all you lambs and sheep of my Father`'s fold!
Were you not all torn and wounded by going astray,
and many of you ready to perish of your wounds, and weary with complaining?
And yet could not but complain, but were even tired of that also;
so that you did but add to your own sorrow,
whereby you made your condition worse than the worst, by being your own tormentors;
your sorrow keeping you from rest, and your complaints from feeding,
where others got some relief Your strength being wasted, and your power gone,
so that you could not shift nor flee, but lay open to the spoiler,
to execute his fury upon you; so helpless were you in yourselves in that day.
In this state were many of you found, when the Shepherd of Israel arose to seek his sheep.
Oh! do you not remember these things?
Was not your grief unutterable, and your pain grown to that extremity,
that you had perished immediately, if he had not found you when he did?
How were some of you fled into solitary holes,
and others into the cliffs of the craggy rocks, and were mourning there,
desiring that your eyes were as a fountain of tears,
because of the wickedness of the wicked, and miserable state of mankind,
and there was no helper found?

Others of you like a sparrow chirping alone upon the house top, seeing over the world,
with all its glory; and yet could not tell how to get rid of it,
but still had an eye over it, and yet could not break through it.
This caused you to sigh and mourn,
and you could not meet with a mate or companion among all the sons of Adam;
and so inward sorrow wasted your strength, and outward griefs consumed your flesh;
and when you went to break through, you were torn by the briars and thorns,
that you could not find a way to escape.
And others of you had learned to herd with the beasts of the field,
and could eat of their bread, and drink of their drink,
and lie down in their resting place.
Oh! how did the Shepherd chase you with his judgments,
and hunt you with his crosses and afflictions outward and inward, to bring you home?
And what care has he taken, since your recovery,
to keep you in the fold among the lambs,
that you may no more find out any of your old walks and haunts,
but be kept forever to feed with the lambs, that you all might lie down together,
as sheep of one fold.

My heart and all that is within me, is pained for you, and mourns in secret after you,
and cries day and night unto the Shepherd, to look after you, and take care of yon all,
that none of you be lost, or stray, or be worried, or hunted any more;
but that you may forever lie down together, and neither hurt, grieve,
nor offend one another, nor harden those who yet go astray;
but that all may be kept in the sense of what, and where, once you were, and of the love,
care, and mercy, that pitied you then, and healed and bound you up, and brought you home,
and passed by the remembrance of all your trespasses, and loved you freely.
Oh! let the bowels of the Shepherd to you, beget compassions unto the scattered,
and unto one another, who will again soon be scattered, if he should look not after you!
For you were all once in that nature, by which you were children of wrath,
and in darkness as well as others; and wherein any of you differ,
either from what yourselves once were, or from what others are,
it is by that which you have freely received.

Oh! Are you strong in the Lord?
And have many great things been done by you;
and many mighty men been made to fall before you by his power;
and the host of the Philistines been put to flight; and the power of darkness, and Satan,
the prince thereof, been withstood, and made to turn his back,
and veil to Him your strength; and the dead been raised thereby,
and the graves opened at his word, which went out of your mouth?
And many which were bound, as in fetters of iron, have been loosed by him; and others,
that have been shut up close prisoners, in the pit where they saw no light;
and yet at his rebuke, and lifting up of his voice, the dead have risen,
and those prisoners come forth, and sounded out the praises of that God,
in whose power you did it?
And has the tongue of the learned been in your mouth,
and the weary been refreshed by you,
and the mourners been comforted through hearing of your voice;
so that the evil spirits have fled away, when you have taken up your harp,
and all the minstrels and worldly joys have departed at his appearance;
so terrible was his presence, and dreadful his countenance, that no eye was so quick,
as to abide undazzled before him; nor any craft or deceit so closely couched,
but it startled when he made search; nor any paint so artificial,
but it melted before his dissolving presence, and scorching glory;
so that all spirits were discerned, and tried, and judged with righteous judgments,
in the day of his strength?

O! How did the wise men of Egypt, and the soothsayer, peepers and diviners,
with all the magicians and masters of that crew,
together with all the merchants of Babylon, flee before him,
like the routing of a mighty army, and scattering of all their generals,
and officers of command?
How were you, and your companions, in the strength of the Lord,
like David with all his worthies?
And how have you, like mighty men, by his power,
broken through the whole camp of the uncircumcised, to bring water unto the thirsty?
What service was too hard for you to venture upon, to relieve the captives,
and set free them who were bound, who, like Samson,
have broken all the cords and bindings of the Philistines,
and snapped them asunder like a thread?
With many more achievements that have been done by his arm,
which time would fail to record; but living monuments remain,
as pillars and standards reared up,
to keep in remembrance what has been done by the strength of the God whom you served,
to his praise and eternal glory forever.

For, was it not all by his own arm, and his everlasting strength,
that out of the mouths of babes and sucklings he might ordain strength,
and perfect his praise forever?
Yes, was anything yours in all this work, besides the obedience to his power?
And was it not all his, that no flesh might glory in his presence?
Therefore, all you children of the Lord, without respect of persons,
that have seen his wonders, and mighty goings forth,
and have beheld his marvellous doings, not only as spectators,
but sharers in the victories, and dividers of the spoil with the mighty,
whose souls have been delivered out of captivity, and rescued from the land of darkness;
who have drank of the water of life,
that has been brought unto you by the valiants of Israel,
through the hazard of their lives.
Oh! do not you forget the sweetness of the waters; nor the dangers they ran,
who ventured through the enemies camp to bring it unto you,
with their lives in their hands.
How sweet it was unto you then,
and how did you prize it beyond all the rivers of Damascus?
Let your love never abate unto it, but heighten more and more;
for it is not of a wearing nature, but provokes the appetite,
and stirs up the desire after more of the same forever.
For it is the vitiated palate that blames good diet,
and the full stomach that loathes the honeycomb;
but the true seed drink the wine new continually in the Father`'s kingdom,
and the redeemed sing a new song, and have all things new and fresh,
as the water out of the fountain, springing up into eternal life;
where nothing can remain in the old channel,
but is washed away by the running of the pure water, that proceeds from the fountain.

Hear, O you children of Jacob, what is the advice and counsel of a poor redeemed captive,
once your companion in bonds, and now in freedom!
As we mourned once under the oppression of the oppressor together,
so let us now rejoice in that love, that has pitied and set us free;
let nothing stop our mouths from praising, nor our hearts from rejoicing,
in the ocean of eternal kindness and mercy, that has delivered us.
Let us haste upon the top of Mount Gerizim,
opening our mouths in blessings and thanksgivings unto our God forever,
who has made and chosen us to be a people, that were not a people,
that we may keep his statutes, and delight in his law;
and then let us stand upon Mount Ebal,
that the curses and righteous judgments of the Lord
may come upon the head of the wicked one,
and all that would divide us from God, or one from another;
and whatsoever rejoices in unrighteousness, or delights in false judgment,
and upon that root of bitterness, that brings forth gall and wormwood.
Let nothing escape the righteous stroke of the Almighty that genders to bondage,
or would entangle our hearts and minds, whereby that sweet peace and rest,
and satisfaction in the Lord God, might not be enjoyed, as heretofore it has been:
for the wicked one will be sowing his tares in the night of security and carelessness,
and it will soon spread and grow, that you can not get it rooted out of your heart,
but it will eat, defile and stain, that your very comeliness will be disfigured,
and your beauty which once you had will be marred by it.
You, who sometimes were tender and full of love and meekness, will be so changed,
that nothing but roughness and envyings of Jacob`'s blessings will secretly follow you,
with an evil eye to spy out new faults,
and a memory to call to mind the old infirmities of your brethren;
whereby you will have a large treasury of evil in your heart,
which will be furnishing your mind and thoughts with unprofitable matter,
unto the daily wounding of your life, and clouding of your understanding,
and thickening of the veil and mask over your beauty.
All this may be done by the enemy, under pretence of valour, and witness bearing,
against formality and deceit.
Oh! how easy is it for the simple to be deceived here, and the strong to be betrayed,
as through Delilah`'s flatteries, saying, it is not for lack of love to God,
and zeal for him; if a testimony without delay be not borne, and a dislike showed,
against such and such things; whereby the angry part will soon get up,
and quench the love to the brethren, and drown the mercy,
so that all will be covered besides the hard rocks, and lofty mountains;
and upon these they may see afar into the enemy`'s country,
but cannot behold the holy land, with its inhabitants, on the other side of the sea.
And from hence, if the watch be not kept,
may even the valiants in Israel receive a stroke, and come to a loss,
by this craft and disguise of the evil one.

And then others perceiving it, against whom the offence was taken,
not dwelling always in the love that covers all, but venturing too much to take the air,
and to walk as upon the walls, without the castle, may soon let in the knowledge,
and taking notice of it, which will beget the same in them;
whereby the distance will be increased, and the evil one will gain ground,
and the enemy will soon show himself to the troubling of Israel;
and so will the evil seed be scattered abroad, and gender unto more ungodliness,
for lack of a timely prevention, both in the one and in the other.
Thus may the lambs of my Father`'s fold be disturbed by the little foxes,
who should be taken by the watchmen of Israel, that they might not wander to hurt.

Therefore, O you children, and mighty men, with the leaders of the tribes!
Remember how easy it is for you all to miscarry, if the watch be not diligently kept;
for Satan will be standing at the right hand of Joshua, to resist him.
Call to mind what is recorded in the Scriptures of Truth!
How the man of God, after he had gone forth and finished his message,
in crying against the altar at Bethel,
and after he had withstood the temptation of the king, was slain by the lion,
for going from the word of the Lord in himself,
and hearkening unto the counsel of the old prophet, whereby he was deceived,
and returned not according to the command of the Lord.
And, my dear brethren, Paul, a champion in Israel, and master builder in God`'s work,
who saw need, in the bowels of love and mercy, that the faithful,
without respect of persons, should watch one over another; did, as need required,
say to Archippus, Take heed to the ministry which you have received in the Lord,
that you fulfill it.
And did not Satan present himself among the sons of God, in the days past,
when they were met together; and, O remember, the serpent got into Paradise,
to tempt from the innocency; who is the same that ever he was,
and most busy about those who are chiefest in the work of the Lord;
for who was so tempted as the Son of God?

Therefore let the strong bear the infirmities of the weak, lest they also be tempted;
for we all stand by faith.
He that is most in the life of the Son, is most sensible of the hurts of others,
and most touched with the feeling of their wounds; not slightly passing by,
like the priest and Levite; but mercifully pitying and healing, like the good Samaritan.
For it is a symptom of hardness in him,
that makes slight of the wounds and bruises of his brethren,
thereby pouring brine into their wounds, rather than the oil of love and tenderness.
Such physicians rather help to fester, than cure the hurt; and to increase the pain,
than to stop the spreading of the disease;
whereby a little slip proves a dangerous sprain,
and a small bruise sometimes to the loss of a member and grieving of the whole body;
and all for lack either of skill or sense, or both, in the physician.

Where skill is lacking,
there the physician may administer that which increases the distemper,
and thereby disparage himself, and endanger the patient; and where sense is lacking,
there austerity and rigidness are usually met withal.
So that he who feeds the lambs, and hurts them not,
must himself be conformable to Christ, who is holy and harmless,
and separate from defilement, and touched with the feeling of their infirmities;
having shoulders to carry the lame on, as well as a tongue to direct the ignorant;
and arms to bear up the weary, as well as feet to go before them in example.
One who ought to feed the lambs, as a testimony of his own love to the Father;
and wash their feet, as an example of humility; not seeking honour,
lest he be infected with lordliness thereby; and so by seeking preeminence,
by eldership, or some other outward thing, hurt the lambs, and stop the simplicity,
that otherwise would have had them highly in esteem, for their work`'s sake in the power,
but now will be hindered, because looked for; whereby the enemy will get advantage,
of the one by seeking it, and the other by taking notice of it,
that prejudice will increase, and the life in both be hurt; and all for lack of watching,
to be content with the honour that comes from God only,
and himself to be as one that serves the lowest and weakest babe,
striving rather to be under all, than seeking to be over any;
counting it honour to serve, knowing sensibly, that one is their Father and Master,
even God, and they have all but one Lord and Master; unto which, both he that teaches,
and they that are taught, must be subject,
as the body unto the wisdom and direction of the head; so must all be unto Christ,
the promised seed.
And if any hold not the head, they run into the error, and so out of the sense,
by which only the members can serve one another in love,
the law which God has set to govern the body by.
For he that is most in the seed, is most in the life,
and so in the sense whereby the unity and sympathy in the body is preserved;
and that member most grieves for the hurts and bruises of the rest,
where the sense is quickest, whereby its usefulness in the body is discerned,
and the double esteem and honour is given unto it by all the living members,
which is not sought by him, but given freely by others,
because they are sensible of the usefulness of that member to the body;
and so is the whole edified in, and built up by love.

But if, through any prevalent humour, the health of any be impaired,
whereby the sense is lost or benumbed, that it feels not when others are hurt,
and yet will continue to officiate in the body, whereby the rest are grieved;
in that case it must not be ruggedly fallen upon, lest, through its own unsensibleness,
it hurt the living members, without either mercy or sense,
and so either make them grieve, or wholly unsensible also,
unto the increasing of farther discord in the body.
But rather gentleness and forbearance must be used, as by the application,
not of harshness, and present judging, or standing at a distance, but, of warm clothes,
and suppling oils, used by a gentle hand, with much pains, and often exhortation,
in the stirrings of love, and risings of the life.
Yet feed not the benumbedness, or senselessness, but cherish the life,
and so recover the sense, whereby it is restored to the former office in the body,
and more filled with compassion, usefulness, and diligence, than before.
And the other members are now made more sensible of the benefit of patience and long-suffering,
and see from which that springs, that would limit unto seven times,
and how narrow and short it is of the fulness of mercy itself, that is unlimited,
but binds the limiting spirit,
unto the perfecting of the praises of the God of everlasting goodness and mercy.
And thus will the wiles of the enemy be prevented, and the body preserved in unity,
and edify itself in love: and hereby will the world be convinced,
that you are the disciples of Christ, and have learned of him to love one another;
and in love, as the members of the natural body, to serve one another,
and to minister to its benefit, of the ability which God gives,
and from the rising of the life, and breaking forth of it, as the sun from under a cloud,
and not under a veil or burden.
Wait until the way be clear in your own particular,
and the power has wrought through and scattered all clouds; and then, with open face,
and not from under a veil,
does the word of life go forth to the cherishing of the tender babes and plants,
and so there will be a springing of the life in all.

He that so ministers, saves himself, and those that hear him;
and neither lacks milk to feed himself, nor the word to minister to others;
but will distinguish in himself between the word, and the milk of it,
and also between that which looks at the passing away of the time,
and to answer the expectation of others in words,
or the keeping of its own authority over others,
and that which dwells in the cross unto all these things,
heeding nothing but the rising of the life, and overcoming of the power,
and so knows how to behave himself in the church of God, both when to begin,
and when to make an end; ministering in the life, and reaching to the seed,
and not to the judgment and affections only.
Feeling in himself when the seed is raised, and the power stirs in another;
this sense makes him cease, that the life may speak in whom and when it pleases.
And so nothing will be quenched, nor any burdened, but unity will be preserved,
and all lordship and mastery destroyed, and every member have its liberty,
without being restrained by anything besides the power;
and so every one will prefer others before themselves, keeping no authority over any,
but minding the arising of the power in their own hearts.
For what do you know, but the power may be quiet and still in you, be you ever so strong,
that it may show itself in a weaker vessel,
and perfect its praise out of the mouths of babes and sucklings;
which may be hindered by your negligence, in not minding the power in yourself,
and God`'s end in exercising you in silence, rather than speaking; which may be,
either to speak himself in some weaker babe, or to come forth in you with great power,
after long exercise and silence, and patient waiting, in the cross to your own will,
and all that would be anything out of the power.

Here the simplicity in all will guide, and the several gifts,
given for edification of the whole, will shine; and no candle be under a bushel,
nor any signification of the Spirit resisted, but all will be as servants unto it.
And in this order will there be time for the lambs to feed, in their green pasture,
as well as others to be exhorted, and the world instructed.
And so will your meetings be as a feast,
and the elders judging not so much what words are spoken,
as what life and power is stirring,
all laying down their crowns at the feet of him that sits upon the throne.
So will all take heed how they hear, as well as what they hear; and they that speak,
as well know in what they speak, as what words they utter;
whereby all will be done unto the praise and glory of God in the churches,
and many will rejoice to behold your order.
This is that behaviour in the church of God which all must learn,
that there may be no schism in the body, but all may be preserved in unity forever,
and in the tender bowels of compassion one unto another;
all being sensible what trespasses have been forgiven them by God, the Father of mercies;
and they, his children, will be merciful like him,
knowing their daily dependence is upon him; and they have no strength or ability,
either to stay where they are, or to go on to perfection,
but as it freely flows from him, upon whom they depend every day for fresh springs,
as the babe upon the mother.

Therefore, O you children of the living God, be like-minded unto your Father,
in mercy and love one to another, and in his fear consider these things,
that in his saving health you may be kept, and none be hurt or bruised among you.

Meet in the faith, and in God`'s fear, that your minds may not be allowed to wander,
because of the diligent watch; but mind feeding more than hearing,
every one coming as unto a feast,
and sitting in the pure light of the Sun of righteousness,
that all your souls`' needs may be supplied,
and every one return laden and filled with the milk and honey of the good land;
that it may be known and taken notice of by all that converse with you,
or come among you, that you have been with Jesus, and have received his virtue,
from the touches of his life; whereby you that come to meetings,
bowed down and heavy laden, may go away with your burdens removed,
praising the name of the Lord.

And let him that ministers,
first feel the state and condition of the meeting by the sensible stirrings of life;
not judging according to the sight of the eye, or hearing of the ear,
but with righteous judgment in the life; minding more their state,
as represented in the power, than by any outward intelligence;
that so the word may be divided aright, and not handled deceitfully,
according to any outward guess or judgment,
or corrupted by intermingling the words that man`'s wisdom teaches.
Let the life put on what clothes he pleases, and as it dresses itself,
so let it appear and go forth; you being as the trumpet,
but the breath of life must make the sound, in what order it pleases;
and so will all the babes be refreshed with its melody, and the sound be certain,
that every soldier may be prepared to battle, to the help of the Lord against the mighty,
in their own hearts; and so will the blessings of the Lord be among you.

Let not time limit you, but in the power and wisdom of God,
wait to know when he gives leave to depart in perfect freedom, lest any go away burdened,
by having something stirring in them, and moving to speak, or pray,
or otherwise sound out the goodness of the Lord,
by what signification the Spirit itself pleases;
that so in all things you may stand fast in the liberty
wherewith Christ has made you free,
not being brought under the power of anything; but, every one,
without respect of persons, using your own liberty unto edification,
minding always the preservation of unity in the body,
more than your own particular ease and benefit, avoiding singularity in anything,
except by a positive command, lest division or separation follow.

Let not your ears be open unto every word that is spoken,
lest dislike or prejudice enter; but mind the life more than words,
that your unity may stand in the Spirit that speaks,
and not in the words that are spoken; lest the affections be tickled,
and a love and unity arise from there, whereby a false fellowship will be begotten,
and held in outward observance, like the world,
and so will gifts and persons come to be set up, and death and formality increase.
But the mystery of the fellowship in the Spirit and life will decay,
and so form and power will clash, and discord soon enter; and the wisdom of the brain,
in the abundance of knowledge, will set up a judgment against the tasting palate,
and inward feeling by the power.
So may the power come to be lost, or much abated,
because its way of overcoming is rather by suffering, than open contest;
which hitherto has been the cause that so few have been on its side in ages past,
the greater part going still the other way; but by your keeping in the savory spirit,
you will try and judge all words, and the spirits also from which they proceed,
to the keeping out of all distempers.

Let there be no whisperings among you,
nor that nourished which delights to hear or bear tales;
but every one minding their own measures, which neither does nor thinks any evil,
but judges that as a seed sown to cause the flesh`'s strength to increase.
For as that evil seed is hearkened unto,
it will beget a fellowship in the prejudiced part, unto the cooling of love,
and nourishing of iniquity, whereby it will secretly spread itself,
to the poisoning of the tongue with private smitings,
and also misspending of precious opportunities in unprofitable discourses,
unto the burdening of the true seed.

Let no harshness to, nor judging of one another be found among you; for your mother,
that brought you forth, is free from all these things, swallowing up, and covering all,
as the sea the earth, by infinite depths lower than all,
and unmeasurable heights above all.
So that all is cleansed through it, and compassed round by it on every side,
that nothing but perfect love and purity may appear,
the multitude of evils being covered by it; so that though they be sought for,
yet they shall not be found.
And therefore let it appear you are her children, by passing by,
and covering all with that mantle which yourselves were once swaddled in,
and to this day are kept warm by.
But if anything that is evil spring up in the garden,
let it be soon weeded out by the care of the owner.
But when you see it either in your own, or neighbour`'s garden,
let not anger or fretting boil in you against it,
but wait for skill and power to pluck it up,
without hurt to the walks or pleasant flowers.
Do it not in haste or wrath, lest you nip the top only,
leaving the root in the ground to spread more, and do greater mischief;
and so shall you in wisdom keep the garden clean,
your duty be discharged unto your neighbour,
and your brother saved from the spite of the enemy; and you shall shine,
because you have saved him from the error of his way.

Let anger and distaste be far from you, not having any place in your heart:
"`Let not the sun go down in your wrath;
but when you remember your brother has aught against you, leave your gift at the altar,
and go your way and be first reconciled to your brother,
and then offer your gift upon God`'s altar;`" and
so shall you meet with acceptance from him,
and your soul be preserved in his peace, and you kept in unity with your brethren.

Let not an accusation be received against an elder, without two or three witnesses,
that so it may be established to be true; and then in love,
and bowels of meekness and tender compassion, let him know of it privately,
that he may be reclaimed, and the body preserved pure, unto the praise of God.
So will all things be done decently and in order, and the Lord God of life and power,
will appear among you in power and great glory, setting up his mercy seat over you,
and the cherubims stretching forth their wings, and covering their faces,
because of his presence.
Here will be found the substance of all figures, the pot with manna,
and the ark of the testament, with the rod that budded,
and the monuments of his mercy and goodness will
be brought into remembrance by the Spirit of truth,
and this glory of the latter house far exceed the former,
unto the praise of his everlasting mercy and goodness forever.

For this is the message which I am to signify unto you,
in the name of the Lord God of hosts, and in his fear I deliver it.
Thus says the Lord God of hosts: I have seen,
I have seen the afflictions of the afflicted,
and their cry is come in remembrance before me; and I will awake as a man of war,
and come forth as a giant refreshed with wine, to finish my determinations,
and to execute my own decrees; and in righteousness and judgment will I do it,
says the Lord God.
I will plead with all the rebellious inhabitants of the earth, as with fire and sword,
to make my power known in their destruction, and to the salvation of my own seed,
says the Lord.
I will not leave one lost sheep unfound, nor one lamb unbrought home,
nor prisoner in the pit unset free.
I will give commission to the graves to open, for the dead to arise, and unto the sea,
to cast up her slain.
I will deliver the mourners, and set free all the captives,
because the day of the everlasting jubilee is come,
and the Lord of sabbaths has heard the cry of the elect,
and is risen to plead their cause, and to execute judgment on their behalf,
and to clear their innocency before all people.
For I will not leave one of them under the power of the adversary:
for my decree is to break all bonds, and to snap all chains asunder,
and to permit no bounds or limits to be unto my love; for they shall know the largeness,
sweetness, and everlastingness of it.
Like a sea it shall be unto them, to overflow all banks,
and cover all mountains and hills,
and to fill them with the knowledge of my life and presence, as the waters cover the sea.

I will, says the Lord God, make the nations know, that I have loved them,
and that they are a people saved by the Lord, and the glory of all nations,
and the blessing of all lands.
Therefore let no straitness be upon you, nor gall of bitterness in you:
for this is the message that I am to deliver unto you from the Lord of hosts,
the God of your salvation: That your God has looked upon you with everlasting mercy,
and upon your scattered brethren and sisters, the royal seed of Abraham,
that are hungering and thirsting after righteousness, and will deliver them all,
and rend all mountains that lie in their way,
and cleave all rocks of opposition against me, divide all waters that separate from me,
says the Lord of hosts, that my ransomed may pass;
and this will I do both within and without them.
For what I will do in them,
shall be as an earnest and pledge of what I will do without them.
Within them shall not be any root of bitterness, or other evil thing,
but I will destroy it, says the Lord God: within them, shall lodge no ravenous beast,
nor devouring bird, nor any evil surmising one against another,
nor any envying shall be found among them; but they shall be all righteous,
and the everlasting gates shall open at the word of my command, and they,
the righteous nation, shall enter into my unlimited glory,
and boundless everlasting lovingkindness, in the free covenant of life in Christ Jesus,
that I may rejoice over them to do them good forever.

And without them shall not be an oppressor found to hurt them,
nor any destroyer upon all my holy mount, says the Lord God.
I will rid the earth of the briars and thorns, and burn up the straw and stubble,
and consume all the workers of iniquity,
that my blessings may come upon my people unto the uttermost; that all nations,
bond and free, may hear of my marvellous works, and be astonished,
and all my children comforted together one in another, and in me, says the Lord God,
forever.
I will fill their hearts and their meetings with my glory, that they,
as the sons of the morning, may sing together,
and the voice of melody and gladness may be in them and among them,
to the ravishing of their hearts, and astonishing of all that behold them;
for Jerusalem shall be a praise, and Zion a rejoicing unto the ends of the earth.

Therefore lift up your heads, and put on your strength, O city of the living God:
for your walls shall be salvation, and your gates praise;
no complaining shall be in your streets, nor beggar in all your land;
and strife and debate shall forever be banished out of your dwellings;
and peace and plenty, love and unity, shall be the motto upon your houses;
and the Omnipotent One, the Lord of hosts, your husband, your Lord,
and your God forever.

[.signed-section-signature]
J+++.+++ Crook.

[.signed-section-context-close]
From Aylesbury common jail the 19th day of the Seventh month 1661.

[.letter-heading]
An Epistle to the children of the Lord.

[.salutation]
Dear children of the Lord,

Great has been the love, with which the Father of mercies has visited you,
when you were fallen into the hands of your enemies, who had wounded you,
and bruised you, so that there was no soundness in you; and in that state you lay,
and none was able to comfort you, or to bind up your wounds.
The priest and the Levite passed by, as void of compassion,
and as physicians of no value, until the good Samaritan came,
whose own compassions reached unto you, so that oil was poured into your wounds,
and a place of entertainment provided, and refreshment was received by you,
to the comforting of your souls in your weary and wounded state.
Oh my friends!
Do you not remember it?
And can you not tell what God has done for you, and when he did it?
And how seasonable and suitable it was unto you, in the day of your misery?
And how welcome, and with what acceptance and thankfulness did you receive it?
Was any either able or worthy, in heaven and earth to help you, besides him?
And if he had not freely succoured you in your distress,
had you not perished in your blood?
Oh!
Why should his mercy be forgotten, or his love slip out of remembrance forever?
Surely he did it that he might be feared, and that he might be praised;
and that a birth might be born, that cannot and will not forget his goodness,
nor give the glory of his doings unto another, but unto him forever unto whom it belongs:
and in this birth is your safety, and in this birth is your peace and quietness forever.
Oh! Do not let the false birth be painted with the openings that belong unto the true,
nor the true lack the food that is proper for it.
Let not the earthly selfish birth,
be covered or clothed with the profession of the true and heavenly birth,
while the immortal is covered with rags, and with death and darkness,
and is kept prisoner in the pit, and captive in the dungeon of falsehood,
and fleshly reasonings; locked with chains of fears, and doubts,
and cares for self-safety, while there is a cry for lack of bread,
and a famine in your hearts; and while the earthly and fleshly part is fed with dainties,
and fares deliciously every day,
with the knowledge and remembrance of what was once enjoyed, but now is departed from,
and barrenness and coldness is come over again;
and yet there is a mind that will not take notice of it, nor believe it,
but sits as queen, notwithstanding all that was once honourable is lost and forsaken,
and self and the earthly spirit is gotten up,
and would rule where once the pure and holy Spirit ruled.

Oh! Take heed of this usurper, for it is but one of Babylon`'s children,
and happy shall he be that dashes it against the stones.
For the Lord God is making the house of Jacob to be as a flame,
and the house of Esau to be as stubble,
and Jerusalem to be as a burdensome stone unto all nations.
Therefore all of you that have seen the wonders of the Lord,
and have beheld his marvellous doings;
and have been patients of the true and everlasting physician,
upon whom he has exercised his skill, and manifested his love,
that you forever might sound out his praise,
and procure many to inquire after him who heals without money, and gives all freely,
and expects nothing but returns of praise and obedience
in the strength of what he has given.
Do not so requite the Lord, as to forget his mercies,
or to slight what he has done for you in times past; neither let the ungrateful,
and disingenuous spirit, prevail again over you,
lest your bondage be greater than before, and the enemy come in like a flood,
and like the breaking forth of waters,
and overflow the banks of temperance and moderation, and your excess prove greater,
and your folly more remarkable, than before you knew the Lord, and the power of his word.
The enemy comes not but to steal and to rob, and he begins in craft, and great subtlety,
that so he may not be suspected; and his art is, in covering his bait,
that his intended mischief may not appear,
but that it may be swallowed down without suspicion; that he may have the greater hold,
he begins with a small matter, and ends with a greater.

My dear friends! Believe him not, for he was a liar from the beginning;
and he will beguile you as he did Eve, if you watch not; he will tell you,
that you may take care for your families, and so bring in distrust of God upon you.
He will tell you, that you must be as wise as serpents,
and so will bring in fleshly wisdom and devilish subtlety upon you.
He will tell you, you must not give offence either to Jew or Gentile,
or the church of God, and so will bring in respect of persons,
and sinful compliances upon you.
He will tell you, that you must love your enemies, and so will bring coldness upon you,
to quench your zeal for God, in reproving of iniquity,
and bearing a testimony for God against it.
He will tell you, as he did Eve,
you must feed upon the knowledge of this thing and the other thing,
and by your knowing what is good and what is evil, you shall be like God,
when it is the way to make you like him, who knows God`'s will,
but is out of the power that enables to obey.

And so will he paint over his wiles, that by his beginning with a little,
he may afterwards bring to more; and so will weakness, and coldness, and hardness,
and stiffness, increase and come upon you, like gray hairs here and there,
and you know it not, but will grow most in a secret benumbing and insensibleness.
Other evils will follow, and be pleaded for, and prejudice arise and grow,
against all others who are not in the same, and who testify against them;
and so the love will abate, and evil surmising spring;
and that which should bear reproof and receive information, is pressed and loaded,
and burdens will grow, and the unity with the faithful will be lost,
and the latter end be worse than the beginning.

Therefore watch, my dear friends, against the enemy of your souls,
that you may be preserved out of all his snares, and that the holy seed may grow,
and you, in the love and unity, may be preserved, faithful, bold, and valiant,
in your answering of God`'s requiring in all things, unto his praise and glory forever.
That the blessings of Abraham may be enjoyed, and your peace with God may abound,
and love, one unto another, and with all his children; shining through,
and manifesting itself in your diligent coming together to worship God,
and faithful keeping of your meetings, out of the fear of men, in the fear of God,
unto his praise, and sweet refreshing of one another;
and so will you delight to meet together, and the joy of the Lord will be your strength,
and you thereby encouraged to wait upon him.
His sweet and precious presence will be manifest among you,
unto the building up and strengthening one another in the faith of the gospel,
vanquishing your fears and scattering all your enemies;
so that you will not be bowed down under any of your enemies,
but be delivered out of all their hands,
that you may serve the Lord your God without fear,
in holiness and righteousness before him all the days of your lives,
unto the praise of the glory of his goodness and mercy, that endures forever.

So in the love of God, and peace one with another dwell,
and judge with the light of Jesus Christ, all that genders unto bondage,
or that would lead you unto the self-safety or fleshly ease, out of the daily cross;
but love the cross of Christ, and delight in the yoke,
that all may be slain and crucified, that oppresses the seed of God.
So shall your hearts be kept open unto God, and you sensible of his heavenly dew,
and the showers of his blessings to water your hearts,
that you may be kept green and fresh as a garden,
and the beloved walking in the midst of you,
and you all comforted by his living presence in your hearts,
unto the endless praise of his mercy forever.
My God keep you all in his life, fear, and love, unto the end.
Amen.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
From my outward bonds for the testimony of Jesus, in the common jail,
in Aylesbury the 16th of the Seventh month, 1661.

[.letter-heading]
Another Epistle to the children of the Lord.

[.salutation]
Dear friends and children of the lord,

My dear love is with you, and my life is refreshed,
when you are in my remembrance by the Spirit of my God,
because of your steadfastness in his truth, and valour for his name;
and as I have been often refreshed among you, when I have been present with you,
even so now are my bonds sweetened to me by the remembrance of you in the Lord.
Oh!
I cannot forget how sweet his presence has been unto
us many a time in our meetings together.
Surely it is never to be forgotten; and sooner let our right hands forget their cunning,
and our tongues cleave to the roofs of our mouths,
and the sucking babe forget the breast that nourished it,
than that we should forget the goodness of the Lord our God,
or to suffer the remembrance of his manifold mercies and often deliverances,
which he has wrought for us in the deeps, and the sands and the rocks,
which he has again and again saved us from falling into, and splitting upon,
to be forgotten by us.
Oh! are not the wonders that he has wrought, exceeding admirable?
And his preservations from time to time, inexpressible and innumerable?
Who is a God like unto him!
Or where is he to be found, that can rescue out of his hand?
Is not his salvation as walls and bulwarks,
and his pure and holy name as an invincible castle,
and his mighty arm as a wall of brass about the dwellings of Zion?
For how has he chosen her to be the delight of his heart, and the spouse of his bosom,
from whom he will not withhold the thing that is good,
but will delight her with his riches, and clothe her with his ornaments,
and feed her with the finest of the flour,
and gladden her heart with the wine of the kingdom,
and be with her at her goings out and comings in,
that she may be known to be the beloved of the Lord;
that kings may be in love with her beauty,
and the mighty be astonished because of her glory,
and of the blessings which night and day attend her;
that she may never more be termed desolate or forsaken; for the Lord himself,
the Holy One of Israel, will tabernacle with her throughout all generations,
and the children that are yet unborn, shall call her blessed.

This is that Zion, that has been as a wife of youth forsaken, whom none has regarded,
but has been mourning in the state of her widowhood for lack of her beloved;
for there was none besides him, in whom she could take delight,
during the time of his absence, which she thought long,
being restless in every condition, because he was absent whom her soul loved.
She could not but inquire after him, though she met with stripes from the watchmen,
and frowns from those that wondered what her beloved was more than theirs,
that she was so restless in her inquirings, and eager in her pursuit after him,
as if none among all the sons of Adam were to be compared to him; so inquisitive,
and laborious after him was she, that if possible at last she might find him,
whose presence would make up all.
O you children of the Lord!
Can you not read me here?
Do you not know right well the thing that I say?
Since you have found him, have not your sorrows fled away?
And is not your joy now complete, not repenting of your former pain, hardships,
and difficulties, which you have undergone to find him?
Are not your souls now satisfied in the enjoyment of him?
And whatever your further sufferings may be, because of your following of him,
and love to him, yet all is not to be compared to the sweetness of his presence,
and inestimableness of his worth, whose price is beyond rubies,
and the enjoyment of whose company is beyond the fine gold,
and the sweetness of it far exceeding the honey or honey-comb?
And this I need not tell you, Oh you faithful ones!
For you know it right well; therefore let your delight be in him,
and your whole life streaming into him, that you may be one with him,
never more to be parted.

Whatever would separate or eclipse, either within or without, let it come to judgment,
that he may be an everlasting covenant unto you all,
in whom the strength of the Father`'s love may run towards you,
and may be continually among you,
as the breaking forth of mighty waters drowning all the unbelief of your hearts,
with whatever else may beset you either outwardly or inwardly.
For you may easily know your beloved from all likenesses of him,
either in heaven or earth, because he is without spot or blemish,
neither is there any wrinkle in his face, nor seam in his garment, but he is all lovely;
neither dwells in his breast one thought of evil towards you, or dislike against you,
either because of anything, that in times past you have done against him,
or because of anything that the enemy can lay to your charge,
or beset you on every side withal;
for he will scatter all with the brightness of his glory.
And though the moon should cease to give light, and the sun its shining,
yet shall the covenant of the Father`'s love in him never change, nor come to an end.
Therefore let your souls delight themselves in fulness,
and let no straitness nor barrenness be in you, or upon you, but drink into his life,
and be filled with his virtue: for the good,
which he is determined to do unto and for his people, shall none hinder.
In vain do the heathen rage, and the people imagine,
and the councils of the earth conspire; for Zion must go free, and Babylon must go down,
and her fall must be great, and none shall be able to hinder it.

And this is the word of the Lord God to you, and to all the inhabitants of the earth,
who shall bewail her downfall; but you shall rejoice, with all my Father`'s children,
begotten of his love, and brought forth by the arm of his power,
and by it strengthened to stand in the evil day, and to have your mouths open,
and your hearts be enlarged, to sound out his praise with all the followers of the Lamb,
in whose work and service it is honour enough to be employed.
For where he is, and when he comes, his reward is still with him.

Therefore in his love I leave you all, and commend you to his faithfulness,
who comes to do the Father`'s will, in you all, in which I am found, in my place,
with the rest of my suffering brethren with me, and remain a lover of all your souls,
and a rejoicer in your joy and unity; praying, that it may be perfected daily,
and continue to the end.
Amen.

Your dear friend and brother in the truth of the gospel of our Lord Jesus Christ,
with my dear love to all the faithful in Hertford and Baldock, and thereaway.

[.signed-section-signature]
J+++.+++ Crook.

[.signed-section-context-close]
From Aylesbury common jail, this fourth day of the Tenth month, 1661,
where I remain in outward bonds for the testimony of Jesus.
