== Chapter 4. The Cry of the Innocent for Justice.

[.section-summary-preface]
Being a relation of the trial of John Crook, and others, at the General Sessions,
held in the Old Bailey, London; beginning the 25th day of the Fourth month, called June,
in the year 1662; before the Lord Mayor of the city of London, and Recorder of the same,
Chief Justice Forster, and several other Judges and Justices of the peace, so called.

[quote.scripture, , Eccles. 5:8]
____
If you see the oppression of the poor,
and violent perverting of judgment and justice in a province, marvel not at the matter;
for he that is higher than the highest, regards; and there be higher than they.
____

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle To All Moderate Readers.

Many and great, in all ages unto this day, have been the afflictions, trials,
and oppressions of the righteous, as have been foretold by the holy prophets, Christ,
and his apostles, since the world began; yet God has not left himself without witness,
both in preserving some in all ages to testify against the
idolatries and oppressions of the times in which they lived;
as also of his judicial appearances to punish the
unjust and merciless imposers on men`'s consciences,
because of their worshipping of God.
For about that the first quarrel began;
witness the serpent tempting from the observance of God`'s command,
which he could not do by flat and plain denial,
because of the positiveness of God`'s command to man, saying,
"`You shall not eat of the tree of knowledge,`" etc.
Therefore he did it by expounding that command, saying, "`It is because God knows,
that by eating thereof you shall be like him, knowing good and evil.`"
By this interpretation or meaning of the devil,
who was the first that ever put meanings to God`'s words, man was deceived,
and thus was transgression brought in,
and by the same means has continued unto this day in the world.
For as it was, so it is; God said to man,
"`You shall not;`" but the deceiving spirit says, That is not intended as it was spoken,
for it has a meaning, etc.
And soon after Cain, the devil`'s successor in murder and lying,
falls upon righteous Abel,
for no other cause than the worshipping of God according to his conscience,
in the faith and power of God,
which was not consistent with Cain`'s hypocrisy and formality.
And thus the quarrel first began about religion, whether power or form should bear sway;
and by religion it shall end.
Therefore blessed are they forever who are found faithful unto death,
for they shall have the crown of life: for sincerity shall prevail over hypocrisy,
and the power against all idolatry and formality; for the Lord has spoken it.

And as holy writ furnishes us with examples in this matter,
both as to witnesses that have stood for God, against the imposers on the conscience,
as Daniel, the three children, Christ himself, and his apostles,
with other clouds of witnesses;
and also of his righteous judgments upon the oppressors and imposers,
as the curse upon the serpent, and the plagues upon Pharaoh,
and the brand upon Jeroboam the son of Nebat, who caused Israel to sin by his imposing;
with many more that might be named.

So our histories and laws are not without precedents in this case also;
witness the Book of Martyrs which testifies of the sufferings of the martyrs,
how that they, as the apostles did, suffered for bearing witness against,
not only unrighteous persons, but unrighteous laws also.
For the laws of the kingdoms and nations, in which they suffered,
as well in England under the Christian governors, so called, as in other parts,
did require those things, or some of them, the denial of which,
was the cause of their sufferings then, as it is of us now;
and may be seen at large in those books, from which came the name Protestant,
because they were witnesses against the unrighteousness
and idolatrousness of the times in which they lived,
notwithstanding any laws that were to the contrary.
As tokens of God`'s displeasure against these things,
many eminent judgments fell suddenly upon the persecutors,
as some by sudden death were taken away, others by bursting asunder,
their bowels falling out in a wonderful manner, with like violent deaths,
which for signal testimonies of God`'s wrath and fury, did fall upon many,
to the astonishing of the beholders in those days.

And our law books furnish us with several acts of justice that were executed
upon unjust judges for their not keeping to the laws and rules of justice,
made and appointed both for the people`'s safety, and them to act by;
as may be seen in King Alfred`'s time, mentioned in the Mirror of Justice,
where it is recorded, that forty-four judges, or justices,
were hanged in one year for their injustice, whose crimes may be seen,
as set down in the said book.

And the Lord Coke, so called, Institutes, part 3, cap, 2. p. 23, says thus.
What damnable opinions those were concerning high treason, of Tresilian,
chief justice of the king`'s bench.
Sir Robert Belknap, chief justice of the common bench, and others of their fellows;
and of John Lockton, one of the king`'s Sergeants, etc.
But, says Coke, more detestable were the opinions of the justices in the 21st Rich.
II. and of Hankford and Brinchley, the king`'s Sergeants, etc.
These justices and Sergeants being called in question afterwards in the parliament,
held 1 Hen.
4, for their said opinions, answered, as various lords spiritual and temporal did.
That they dared no otherwise do for fear of death: yet were these two chief justices,
and the rest aforesaid, attainted, for that it was, as the parliament affirmed,
for the great honour and common profit of the realm.

These, with many more examples, are recorded in our law books, and elsewhere,
as monuments of justice against those that caused injustice thus to be acted;
and of terror unto all corrupt judges, for the future to be afraid of the like injustice.
See Walter Rawleigh`'s [.book-title]#History of the World,# lib.
3, chap.
4.

[.signed-section-signature]
J+++.+++ Crook.

--

=== The Cry of the Innocent for Justice.

I have here collected the proceedings of the present chief justice of the king`'s bench,
with his brethren,
occasioned by a late trial before them at the public sessions for the peace and jail-delivery,
held in the Old Bailey, begun the 25th of the fourth month, called June;
the lord Mayor of the city of London and sheriffs,
with several justices and aldermen then present.

Reader, I here give you a brief account of my taking and imprisoning,
that you may the better judge what justice I had from the court aforesaid;
which is as follows:

I being in John`'s Street, London, about the 13th day of the third month, called May,
with some others of the people of God, to wait upon him; as we sat together,
there came in a rude man, called Miller, with a long cane in his hand,
who laid violent hands upon me, with some others, beating some,
commanding the constables who came in after him; but having no warrant,
they were not willing to meddle, but as his threatenings prevailed,
they being afraid of him, joined with him to carry several of us before Justice Powel,
so called, who the next day sent us to the sessions at Hick`'s Hall.

After some discourse several times with them,
manifesting to them the illegality both of our commitment,
and their proceedings thereupon; yet notwithstanding, they committed me and others,
and caused an indictment to be drawn against us,
founded upon the late act against Quakers and others, and then remanded us to New Prison,
where we continued for some days, and then removed us to Newgate,
where we remained until the sessions in the Old Bailey aforesaid:
whereby you may understand what justice I met withal, by what now farther follows.

Silence being made,
the chief judge commanded the crier of the court to call one of the prisoners to the bar,
who was brought there accordingly out of the bail dock from among the felons and murderers.

[.discourse-part]
_Chief Judge:_ What meeting was that you were at?

[.discourse-part]
_Prisoner:_ I desire to be heard: Where is my accuser?
For I expect the issue will be brought forth, having been thus long in prison.

[.discourse-part]
_Chief Judge:_ Your tongue is not your own,
and you must not have liberty to speak what you list.

[.discourse-part]
_Prisoner:_ I speak in the presence and fear of the everlasting God,
that my tongue is not my own, for it is the Lord`'s,
and to be disposed of according to his pleasure, and not to speak my own words;
and therefore I desire to be heard: I have been so long in prison.
+++[+++Then he was interrupted by the judge.]

[.discourse-part]
_Judge:_ Leave your canting.
+++[+++And commanded him to be taken away, which he was accordingly by the jailer.
This was the substance of what the prisoner aforesaid spoke the first time.]

[.discourse-part]
_Chief Judge:_ Call John Crook to the bar; +++[+++which the crier did accordingly,
he being among the felons as aforesaid.]

[.offset]
John Crook being brought to the bar:

[.discourse-part]
_Chief Judge:_ When did you take the oath of allegiance?

[.discourse-part]
_John Crook:_ I desire to be heard.

[.discourse-part]
_Chief Judge:_ Answer to the question, and you shall be heard.

[.discourse-part]
_John Crook:_ I have been about six weeks in prison, and am I now called to accuse myself?
For the answering to this question in the negative, is to accuse myself,
which you ought not to put me upon; for, _nemo debet seipsum prodere._
I am an Englishman, and by the law of England I ought not to be taken, nor imprisoned,
nor disseized of my freehold, nor called in question, nor put to answer,
but according to the law of the land; which I challenge as my birthright,
on my own behalf, and all that hear me this day, +++[+++or words to this purpose.]
I stand here at this bar as a delinquent,
and do desire that my accuser may be brought forth to accuse me for my delinquency,
and then I shall answer to my charge, if any I be guilty of.

[.discourse-part]
_Chief Judge:_ You are here demanded to take the oath of allegiance,
and when you have done that, then you shall be heard about the other;
for we have power to tender it to any man.

[.discourse-part]
_John Crook:_ Not to me upon this occasion, in this place;
for I am brought here as an offender already, and not to be made an offender here,
or to accuse myself.
I am an Englishman, as I have said to you,
and challenge the benefit of the laws of England;
for by them is a better inheritance derived to me as an Englishman,
than that which I receive from my parents; for by the former the latter is preserved;
and this the 29th ch.
of Magna Charta, and the Petition of Right, mentioned in the third of Car, I.
and in other good laws of England;
and therefore I desire the benefit and observance of them.
You that are judges upon the bench, ought to be my counsel, and not my accusers,
but to inform me of the benefit of those laws; and wherein I am ignorant,
you ought to inform me,
that I may not suffer through my own ignorance of those
advantages which the laws of England afford me as an Englishman.

[.discourse-part]
_Chief Judge:_ We sit here to do justice, and are upon our oaths;
and we are to tell you what is law, and not you us: therefore, sirrah, you are too bold.

[.discourse-part]
_John Crook:_ Sirrah is not a word becoming a judge; for I am no felon;
neither ought you to menace the prisoner at the bar:
for I stand here arraigned as for my life and liberty,
and the preservation of my wife and children, and outward state,
they being now at the stake, therefore you ought to hear me to the full,
what I can say in my own defence, according to law, and that in its season,
as it is given me to speak: therefore I hope the court will bear with me,
if I am bold to assert my liberty, as an Englishman, and as a Christian;
and if I speak loud, it is my zeal for the truth, and for the name of the Lord;
and my innocency makes me bold.

[.discourse-part]
_Judge:_ It is an evil zeal; +++[+++interrupting John Crook]

[.discourse-part]
_John Crook:_ No, I am bold in the name of the Lord God Almighty, the everlasting Jehovah,
to assert the truth, and stand as a witness for it: let my accuser be brought forth,
and I am ready to answer any court of justice.
+++[+++Then the judge interrupted me, saying Sirrah, with some other words I do not remember:
but I answered,]
You are not to threaten me, neither are those menaces fit for the mouth of a judge;
for the safety of the prisoner stands upon the indifferency of the court:
and you ought not to behave yourselves as parties,
seeking all advantages against the prisoner,
but not heeding anything that may make for his clearing or advantage.

[.offset]
The judge again interrupted me, saying:

[.discourse-part]
_Judge:_ Sirrah, you are to take the oath, and here we tender it you, +++[+++bidding, read it].

[.discourse-part]
_John Crook_: Let me see my accuser,
that I may know for what cause I have been six weeks imprisoned,
and do not put me to accuse myself by asking me questions;
but either let my accuser come forth, or otherwise let me be discharged by proclamation,
as you ought to do.

[.offset]
+++[+++Here I was interrupted again.]

[.discourse-part]
_Judge Twisden:_ We take no notice of your being here otherwise than a straggler,
or as any other person, or of the people that are here this day;
for we may tender the oath to any man.
+++[+++And another judge spoke to the like purpose.]

[.discourse-part]
_John Crook:_ I am here at your bar as a prisoner restrained of my liberty,
and do question whether you ought in justice to tender me
the oath on the account I am now brought before you,
because I am supposed to be an offender;
or else why have I been six weeks in prison already?
Let me be cleared of my imprisonment,
and then I shall answer to what is charged against me,
and to the question now propounded; for I am a lover of justice with all my soul,
and am well known by my neighbours, where I have lived,
to keep a conscience void of offence, both towards God, and towards man.

[.discourse-part]
_Judge:_ Sirrah, leave your canting.

[.discourse-part]
_John Crook:_ Is this canting, to speak the words of the Scripture?

[.discourse-part]
_Judge:_ It is canting in your mouth, though they are Paul`'s words.

[.discourse-part]
_John Crook:_ I speak the words of the Scripture, and it is not canting,
though I speak them; but they are words of truth and soberness in my mouth,
they being witnessed by me, and fulfilled in me.

[.discourse-part]
_Judge:_ We do ask you again.
Whether you will take the oath of allegiance?
It is but a short question, you may answer it if you will.

[.discourse-part]
_John Crook:_ By what law have you power to tender it?

[.offset]
+++[+++Then, after some consultation together by whispering, they called for the statute book,
and turning over the leaves, they answered.]

[.discourse-part]
_Judge:_ By the third of King James.

[.discourse-part]
_John Crook:_ I desire that statute may be read; for I have consulted it,
and do not understand that you have power by that statute to tender me the oath,
being here before you in this place, upon this occasion, as a delinquent already;
and therefore I desire the judgment of the court in this case,
and that the statute may be read.

[.discourse-part]
_Judge:_ +++[+++Then they took the statute-book, and consulted together upon it, and one said,]
We are the judges of this land, and do better understand our power than you do,
and we do judge we may lawfully do it.

[.discourse-part]
_John Crook:_ Is this the judgment of the court?

[.discourse-part]
_Judge:_ Yes.

[.discourse-part]
_John Crook:_
I desire the statute to be read that empowers you to tender
the oath to me upon this occasion in this place;
for, _Vox audita perit, sed litera scripta manet;_ therefore let me hear it read.

[.discourse-part]
_Judge:_ Hear me.

[.discourse-part]
_John Crook:_ I am as willing to hear as to speak.

[.discourse-part]
_Judge:_ Then hear me: you are here required to take the oath by the court,
and I will inform you what the penalty will be, in case you refuse;
for your first denial shall be recorded,
and then it shall be tendered to you again at the end of the sessions;
and upon the second refusal you run a premunire,
which is the forfeiture of all your estate, if you have any,
and imprisonment during life.

[.discourse-part]
_John Crook:_ It is justice I stand for; let me have justice,
in bringing my accuser face to face, as by law you ought to do,
I standing at your bar as a delinquent; and when that is done,
I will answer to what can be charged against me, as also to the question; until then,
I shall give no other answer than I have already done, at least at present.

[.offset]
+++[+++Then there was a cry in the court,
"`Take him away,`" which occasioned a great interruption;
and John Crook spoke to this purpose, saying.]

[.discourse-part]
_John Crook:_ Mind the fear of the Lord God,
that you may come to the knowledge of his will, and do justice;
and take heed of oppressing the innocent,
for the Lord God of heaven and earth will assuredly plead their cause: and for my part,
I desire not the hurt of one of the hairs of your heads; but let God`'s wisdom guide you.
+++[+++These words he spoke at the bar, and as he was carrying away.]

[.offset]
+++[+++On the sixth-day of the week, in the forenoon following, the court being sat,
John Crook was called to the bar.]

[.discourse-part]
_Chief Judge:_ Friend Crook,
we have given you time to consider of what was said yesterday to you by the court,
hoping you may have better considered of it by this time; therefore,
without any more words, will you take the oath?
And called to the clerk, and bid him read it.

[.discourse-part]
_John Crook:_ I did not, neither do I deny allegiance,
but do desire to know the cause of my so long imprisonment; for, as I said,
I stand at your bar as a delinquent, and am brought here by force, contrary to the law;
therefore let me see my accuser, or else free me by proclamation, as I ought to be,
if none can accuse me; for the law is grounded upon right reason,
and whatsoever is contrary to right reason, is contrary to law;
and therefore if no accuser appear, you ought to acquit me first,
and then I shall answer, as I have said, if any new matter appear;
otherwise it is of force, and that our law abhors,
and you ought not to take notice of my so being before you; for what is not legally so,
is not so; and therefore I am in the condition, as if I were not before you:
and therefore it cannot be supposed, in right reason, that you have now power,
at this time, and in this place, legally to tender me the oath.

[.discourse-part]
_Judge:_ Read the oath to him; +++[+++and so the clerk began to read.]

[.discourse-part]
_John Crook:_ I desire justice, according to the laws of England;
for you ought first to convict me, concerning the cause of my so long imprisonment:
for you are to proceed according to laws already made, and not to make laws;
for you ought to be ministers of the law.

[.discourse-part]
_Judge:_ You are a saucy and impudent fellow:
Will you tell us what is law, or our duties?+++[+++Then said he to the clerk.]
Read on; and when the clerk had done reading,

[.discourse-part]
_John Crook said:_
Read the preface to the act; I say again, read the title and preamble to the act;
for titles to laws are _claves legimi,_ as keys to open the law; for by their titles,
laws are understood and known, as men by their faces.
+++[+++Then the judges would have interrupted me, but I said as follows:]
If you will not hear me, nor do me justice,
I must appeal to the Lord God of heaven and earth, who is judge of quick and dead;
before whom we must all appear, to give an account of the deeds done in the body;
for he will judge between you and me this day, whether you have done me justice or not.
+++[+++These words following, or the like, I spoke as going from the bar, being pulled away:]
Mind the fear of the Lord God, that you may do justice, lest you perish in his wrath.
+++[+++For sometimes the court cried, pull him away, and then said, bring him again;
and thus they did several times, like men in confusion and disorder.

[.offset]
The same day, in the afternoon, silence being made, John Crook was called to the bar,
before the judges and justices aforesaid; the indictment being read, the judge said,

[.discourse-part]
_Judge:_ Mr. Crook, you have heard your indictment, what say you?
Are you guilty, or not guilty?

[.discourse-part]
_John Crook:_ I desire to speak a few words in humility and soberness,
in regard my estate and liberty lies at stake,
and am likely to be a precedent for many more;
therefore I hope the court will not deny me right and benefit of the law,
as being an Englishman: I have some reason, before I speak anything to the indictment,
to demand and tell you, that I desire to know my accusers;
I have been kept this six weeks in prison, and know not, nor have seen the faces of them.

[.discourse-part]
_Judge:_ We shall afford you the right of the law, as an Englishman,
God forbid you should be denied it; but you must answer first guilty, or not guilty,
that so in your trial you may have a fair hearing and pleading;
but if you go on as you do, and will not answer guilty, or not guilty,
you will run yourself into a premunire, and then you lose the benefit of the law,
and expose yourself, body and estate, to great hazards;
and whatever violence is offered to your person or estate,
you are out of the king`'s protection, and lose the benefit of the law;
and all this by your not answering guilty, or not guilty.
If you plead not guilty, you may be heard.

[.discourse-part]
_John Crook:_ It is recorded in the statutes of the 28th
Edw. 3. & 3. and 42nd Edw. 3. & 3. in these words:
"`No man is to be taken, or imprisoned,
or be put to answer without presentment before justices, or matter of record,
or by due process, or writ original, according to the old law of the land;
and if anything from henceforth be done to the contrary, it shall be void in law,
and held for error.`"
And also in the 25th of Edw. 1, 2. and the 3rd Car. 1. and the 29th cap. Mag. Chart.
"`No freeman shall be taken and imprisoned but by the law
of the land:`" These words +++[+++the law of the land]
are explained by the statute of 37th Edw. 3. 8. to be without due process of law;
and if any judgments are given contrary to Mag. Chart, they are void, 25th Edw. 1. 2.

[.discourse-part]
_Judge:_ Mr. Crook, you are out of the way, and do not understand the law;
though you adore the statute law so much, yet you do not understand it.

[.discourse-part]
_John Crook:_ I would have you tell me the right way.

[.discourse-part]
_Judge:_ Mr. Crook, hear me, you must say guilty, or not guilty; if you plead not guilty,
you shall be heard, and know how far the law favours you.
And the next thing is,
there is no circumstance whatsoever that is the cause of your imprisonment,
that you question, but you have, as a subject, your remedies, if you will go this way,
and wave other things, and answer guilty, or not guilty; and what the law affords you,
you shall have, if you do what the law requires you;
or else you will lose the benefit of the law, and be out of the king`'s protection.

[.discourse-part]
_John Crook:_ Observe how the judge would draw me into a snare: By first pleading,
guilty or not guilty, and when I have done so,
he and his brethren intend suddenly to put me, as an out-lawed person,
out of the king`'s protection; and how then can I have remedy for my false imprisonment?
Therefore first clear me, or condemn me, from my false imprisonment,
while I am in a capacity to have the benefit of the law,
and not to out-law me for an offence created by yourselves; and then, to stop my mouth,
you tell me, that if I have been wronged, or false imprisoned,
I may have my remedy afterwards: this is to trapan me,
and contrary to both law and justice, etc.

[.discourse-part]
_Judge:_ You must plead guilty, or not guilty.

[.discourse-part]
_John Crook:_ I do desire in humility and meekness to say, I shall not!
I dare not betray the honesty of my cause, and the honest ones of this nation,
whose liberty I stand for, as well as my own; as I have cause to think I shall,
if I plead to the present indictment, before I see the faces of my accusers: for truly,
I am not satisfied in my judgment and conscience,
that I ought to plead to a created offence by you,
before I be first acquitted of the cause of my being brought prisoner to your bar;
and therefore it sticks with me to urge this farther, namely, that I may see my accusers.
+++[+++Interruption.]

[.discourse-part]
_Judge:_ The most wicked thief may say he is not satisfied in his conscience.

[.discourse-part]
_John Crook:_ My case is not theirs, yet they have their accusers;
and may not I call for mine?
And therefore call for them, for you ought to do so; as Christ said to the woman,
"`Woman, where are your accusers?`"
So you ought to say to me, "`Man, where are your accusers?`"
+++[+++Interrupted.]

[.discourse-part]
_Judge:_ Your indictment is your accuser, and the grand jury have found you guilty,
because you did not swear: what say you, Mr. Crook, are you guilty, or not guilty?
If you will not answer, or what you have said, be taken for your answer,
as I told you before, you lose the benefit of the law; and what I tell you,
is for your good.

[.discourse-part]
_John Crook:_ What is for good, I hope I shall take it so.

[.discourse-part]
_Judge:_ If you will not answer, you run yourself into a premunire,
and you will lose the benefit of the law, and of the king`'s protection,
unless you plead guilty, or not guilty.

[.discourse-part]
_John Crook:_ I stand as brought forcibly and violently here;
neither had I been here but by a violent action,
and that you should take no notice of it, seems strange to me; and not only so,
but that you should hasten me so fast into a course,
that I should not be able any ways to help myself,
by reason of your hasty and fast proceedings against me,
to put me out of the king`'s protection, and the benefit of all law:
was ever the like known, or heard of, in a court of justice?

[.discourse-part]
_Judge:_ Friend, this is not here in question,
whether you are unjustly brought here or not: do you question that by law,
but not disable yourself to take advantage by the law; if brought by a wrong hand,
you have a plea against them; but you must first answer guilty, or not guilty.

[.discourse-part]
_John Crook:_ How can I help myself, when you have outlawed me?
Therefore let proclamation be made in the court, that I was brought by force here,
and let me stand cleared by proclamation, as you ought to do;
for you are _discernere per legem, quid sit justum,_
(to determine by law what is just) and not to do what seems good in your own eyes;
+++[+++here I was interrupted again,
but might have spoken justice Crook`'s words in Hamden`'s case, who said,
That we who are judges speak upon our oaths,
and therefore must deliver our judgments according to our consciences;
and the fault will lie upon us, if it be illegal, and we deliver it for law:
and farther said, We that are judges must not give our judgments according to policy,
or rules of state, nor conveniences, but only according to law.
These were his words, which I might have spoken, but was interrupted.]

[.discourse-part]
_Judge:_ What, though no man tendered the oath to you, when you were committed, as you say,
it being now tendered to you; from the time you refused it,
being tendered to you by a lawful authority, you refusing, are indicted;
we look not upon what you are here for, but here finding you, we tender you the oath;
and you refusing it, your imprisonment is now just, and according to law.

[.offset]
(Something omitted which I spoke afterwards.)

[.discourse-part]
_John Crook:_ How came I here,
if you know not; I have told you it is force and violence,
which our law altogether condemns; and therefore I not being legally before,
am not before you; for what is not legally so, is not so;
and I not being brought to your bar, you ought not to take notice of my being here.

[.discourse-part]
_Judge:_ No, no, you are mistaken; so you may say of all the people gazing here,
they not being legally here, are not here: I tell you, a man being brought by force here,
we may tender him the oath, and if he take it not, he may be committed to prison;
authority has given us the power,
and the statute law has given us authority to tender the oath to any person,
and so have we tendered it to you; and for your not taking of it,
you are indicted by the grand jury: answer the accusation, or confute the indictment,
you must do the one or the other; answer guilty, or not guilty.

[.offset]
+++[+++Here I was interrupted, but might have said, that the people that were spectators,
beholding and hearing the trials, are not to be called gazers, as the judge terms them;
because it is their liberty and privilege, as they are Englishmen,
and the law of England allows the same;
so that they are not to be termed gazers upon this account,
but are legally in that place, to hear trials, and see justice done,
and might have spoken, if occasion had been, anything in the prisoner`'s defence,
tending to clear up the matter in difference, and the court must have heard them or him:
and this as a stander-by, or amicus curice; so says Coke.]

[.discourse-part]
_John Crook:_ The law is built upon right reason, or right reason is the law;
and whatever is contrary to right reason, is contrary to law; the reason of the law,
being the law itself.
I am no lawyer, and my knowledge of it is but little; yet I have had a love to it,
for that reason I have found in it,
and have spent some leisure hours in the reading thereof;
and the law is that which I honour, and is good in its place;
many laws being just and good (not all) but, I say, a great part of it, or much of it;
and that is not my intention in the least to disparage, or derogate from.

[.discourse-part]
_Judge:_ Mr. Crook, you have been told, you must plead guilty, or not guilty,
or else you run yourself into a premunire; be not your own enemy, nor be so obstinate.

[.discourse-part]
_John Crook:_ I would not stand obstinately before you, neither am I so;
if you understand it otherwise, it is a mistake indeed.

[.discourse-part]
_Judge:_ Will you speak to the indictment, and then you may plead;
if you will not answer guilty, or not guilty, we will record it,
and judgment shall go against you.
Clerk, enter him.

[.discourse-part]
_Recorder:_ Mr. Crook, if you will answer, you may plead for yourself;
or will you take the oath?
The court takes no notice how you came here: What say you?
Will you answer?
For a man may be brought out of Smithfield by head and shoulders,
and the oath tendered to him, and may be committed,
without taking notice how he came here.

[.discourse-part]
_John Crook:_ That kind of proceeding is not only unjust,
but unreasonable also--+++[+++here was some interruption]
and against the laws aforesaid, which say, No man shall be taken or imprisoned,
but by warrant, or due process of law:
so that this speech of the recorder`'s favours more of passion, than justice;
and cruelty, than due observance of law:
for every forcible restraint of a man`'s liberty, is an imprisonment in law.
Besides, this kind of practice, to take men by force, and imprison them,
and then ask them questions, the answering of which makes them guilty,
is not only unrighteous in itself, but against law,
and makes one evil act the ground of another; and one injury offered to one,
the foundation of another; and this is my case this day.+++[+++Interruption.]

[.discourse-part]
_Judge:_ Mr. Crook, you must not be your own judge, we are your judges;
but for our parts we will not wrong you: will you answer guilty, or not guilty?
If not, you will run yourself into a premunire unavoidably,
and then you know what I told you would follow; for we take no notice how you came here,
but finding you here, we tender you the oath.

[.discourse-part]
_John Crook:_ Then it seems you make the law a trapan to ensnare me, or as a nose-of-wax,
or what you please: well!
I shall leave my cause with the Lord God, who will plead for me in righteousness.
But suppose I do take the oath now at this time,
you may call me again tomorrow and make a new tender; or others may call me before them.

[.discourse-part]
_Judge:_ Yes, if there be new matter; or, if there fall out any emergent occasion,
whereby you minister on your part new occasion.
Mr. Crook, will you swear?

[.discourse-part]
_John Crook:_ If I do take it today, it may be tendered me again tomorrow, and so next day,
ad infinitum;
whereby a great part of my time may be spent and
taken up in taking the oath and swearing.

[.discourse-part]
_Chief Judge:_ When you have once sworn, you may not be put upon it again,
except you minister occasion on your part.

[.discourse-part]
_John Crook:_ Is this the judgment of the court,
that the oath once taken by me is sufficient, and ought not to be tendered a second time,
without new matter ministered on my part?

[.discourse-part]
_Judge:_ Yes, you making it appear you have once taken it.

[.discourse-part]
_John Crook:_ Is this the judgment of the whole court?
For I would not do anything rashly.

[.discourse-part]
_Judges._
Yes, it is the judgment of the court; +++[+++to which they all standing up, said, Yes.]

[.discourse-part]
_John Crook:_
Then it seems there must be some new occasion ministered by me after I have +++[+++once]
taken it, or it ought not to be tendered to me the second time.

[.discourse-part]
_Judges._
Yes.

[.discourse-part]
_John Crook:_ Then by the judgment of this court,
if I make it appear that I have taken the oath once,
and I have ministered no new matter on my part,
whereby I can be justly charged with the breach of it,
then it ought not to be tendered me the second time;
but I am the man that have taken it once, being a freeman of the city of London,
when I was made free, witness the records in Guildhall, which I may produce,
and no new matter appearing to you on my part, if there do, let me know it; if not,
you ought not, by your own judgment, to tender me it the second time;
for _De non apparentibus,
et non existantihus eadem ratio est._--+++[+++Interrupted by the shout of the court,
when these last words might have been spoken.]

[.discourse-part]
_Judge:_ Mr. Crook, you are mistaken,
you must not think to surprise the court with criticisms,
nor draw false conclusions from our judgments.

[.discourse-part]
_John Crook:_ If this be not a natural conclusion from the judgment of the court,
let right reason judge; and if you recede from your own judgments in the same breath,
as it were given even now, what justice can I expect from you?
For, if you will not be just to yourselves, and your own judgments,
how can I expect you should be just to me?

[.discourse-part]
_Judge:_ Mr. Crook, If you have taken it, if there be a new emergency,
you are to take it again; as for instance, the king has been out of England,
and now is come in again, there be many have taken it twenty, thirty,
or forty years since, yet this new emergency requires it again;
and although you have taken it, yet you must not make it appear before you answer guilty,
or not guilty; therefore do not wrong yourself, and prejudice yourself and family.
Do you think that every fellow that comes here shall argue as you do?
We have no more to do, but to know of you, whether you will answer guilty, or not guilty,
or take the oath, and then you shall be freed from the indictment; if you will not plead,
clerk record it: what say you?
Are you guilty, or not guilty?

[.discourse-part]
_John Crook:_ Will you not stand to your own judgments?
Did you not say even now, that if I had once taken the oath,
it ought not to be tendered to me the second time,
except I administered new matter on my part that I have not kept it,
etc. but no such matter appearing,
you ought not to tender it to me the second time by your own confession,
much less to indict me for refusal.

[.discourse-part]
_Judge:_ If you will not plead, we will record it, and judgment shall be given against you;
therefore say, guilty, or not, or else we will record it.
(The clerk beginning to record it.)

[.discourse-part]
_John Crook:_ Before I answer, I demand a copy of my indictment;
for I have heard it affirmed by counsel learned in the law,
that if I plead before I have a copy, or have made my exceptions,
my exceptions afterwards against the indictment will be made void:
therefore I desire a copy of the indictment.

[.discourse-part]
_Judge:_ He that said so, deserves not the name of a counsel; for the law is,
you must first answer, and then you shall have a copy.
Will you plead, guilty, or not guilty?

[.discourse-part]
_John Crook:_ If my pleading guilty, or not guilty,
will not deprive me of the benefit of quashing the indictment for insufficiency,
or other exceptions that I may make against it, I shall speak to it.

[.discourse-part]
_Judge:_ No, it will not.
Will you answer, guilty, or not guilty?
If you plead not, the indictment will be found against you: will you answer?
We will stay no longer.

[.discourse-part]
_John Crook:_ I am upon the point;
will not my pleading deprive me of the benefit of the law?
For I am tender in that respect, because it is not my own case only,
but may be the case of thousands more:
therefore I would do nothing that might prejudice others or myself as a Christian,
or as an Englishman.

[.discourse-part]
_Judge:_ Understand yourself, but we will not make a bargain with you, +++[+++said another judge,]
you shall have the right done you as an Englishman, the way is to answer, guilty,
or not guilty: if you plead and find the indictment not good, you may have your remedy:
answer, guilty or not guilty?

[.discourse-part]
_John Crook:_ As to the indictment it is very large, and seems to be confused,
and made up of some things true, and some things false; my answer therefore is,
what is true in the indictment I will not deny, because I make conscience of what I say,
and therefore, of what is true, I confess myself guilty, but what is false,
I am not guilty of that.

[.discourse-part]
_Judge:_ That is not sufficient; either answer guilty, or not guilty,
or judgment will be given against you.

[.discourse-part]
_John Crook:_ I will speak the truth as before the Lord,
as all along I have endeavoured to do; I am not guilty of that which is false,
contained in the indictment, which is the substance thereof.

[.discourse-part]
_Judge:_ No more ado, the form is nothing, guilty, or not?

[.discourse-part]
_John Crook:_ I must not wrong my conscience, I am not guilty of what is false,
as I said before what is true, I am guilty of: what is not true, I am not guilty of that;
which is the substance thereof, as I said before.

[.discourse-part]
_Recorder:_ It is enough, and shall serve turn.
Enter that, clerk.

[.offset]
The seventh-day of the week, called Saturday.

Silence being made, John Crook was called to the bar.
The clerk of the sessions read something concerning the jury,
which was empanelled on purpose, as was said,
the jury being discharged who were eye-witnesses of what passed between us and the court:
and this jury, being several of them soldiers,
some of whom did by violence and force pull and hale Friends out of their meetings,
and some of us out of our houses; and these were of the jury by whom we were to be tried.
The clerk reading the indictment (as I remember.)

[.discourse-part]
_John Crook:_ I desire to be heard a few words, which are these,
That we may have liberty till the next quarter sessions to traverse the indictment,
it being long, and in Latin, and like to be a precedent: and I hope I need not press it,
because I understood that you promised, and especially the Recorder, who answered,
when it was desired, "`You shall,`" that we should have counsel also,
the which we cannot be expected to have had the benefit of, as yet,
the time being so short, and we kept prisoners,
that we could not go forth to advise with counsel,
neither could we tell how to get them to us;
we having no copy of the indictment before this morning;
and because so suddenly hurried down to the sessions,
we cannot reasonably be supposed to be provided, as to matter of law,
to make our defence.

[.discourse-part]
_Judge:_ We have given you time enough, and you shall have no more;
for we will try you at this time, therefore swear the jury.

[.discourse-part]
_John Crook:_ I desire we may have justice, and that we may not be surprised in our trial,
but that we may have time till the next quarter sessions, our indictment being in Latin,
and so large as it is; and this is but that which is reasonable,
and is the practice of other courts: for, if it be but an action above forty shillings,
it is not ordinarily ended under two or three terms.
And in the quarter sessions, if one be indicted for a trespass,
if it be but to the value of five shillings, he shall have liberty to enter his traverse;
and, upon security given to prosecute, he shall have liberty till the next sessions,
which is the ordinary practice; which liberty we desire, and we hope it is so reasonable,
it will not be denied, especially upon this occasion,
we being like to be made a precedent:
and courts of justice have used to be especially careful in making of precedents;
for we are not provided, according to law, to make our defence at this time,
and therefore if we be put upon it, it will be a surprisal.

[.discourse-part]
_Judge:_ There is no great matter of law in the case, it is only matter of fact.
Whether you have refused to take the oath or not, that is the point in issue;
and what law can arise here?

[.discourse-part]
_Recorder:_ Mr. Crook, the keeper of the prison was spoken to, to tell you,
that we intended td try you this day,
and therefore ordered him that counsel might come to you if you would;
and also that the clerk should give you a copy of the indictment: this is fair;
therefore we will go on to swear the jury; for the matter is,
whether you refuse the oath, or not?
and that is the single point, and there needs neither law nor counsel in the case;
and therefore we considered of it last night, when we sent you word,
and did determine to try you, and therefore it is in vain to say anything,
for the court is resolved to try you now: therefore swear the jury, crier.

[.discourse-part]
_John Crook:_ I hope you will not surprise us.

[.small-break]
'''

Then the other prisoners, who also were indicted, cried out,
having spoken something before.
"`Let us have justice,
and let not the jury be sworn till we be first heard;`" so there was a great noise,
the court being in a confusion, some crying, "`Take them away;`" others, "`Stay,
let them alone;`" others saying,
"`Go on to swear the jury;`" which the crier in this uproar and confusion did do something,
as if he had done it:
then we all cried out for justice and liberty till the next sessions;
the court being in a confusion, some crying one thing, and some another,
which now cannot be called to mind,
by reason of the great distraction that was in the court; neither what we said to them,
nor they to us, the noise was so great,
and the commands of the court so various to the officers,
some commanding them to take us away; others, to let us alone; others,
to bring us nearer; others cried, "`Put them into the bail-dock;`" others,
to put them within the farthest bar where the felons used to stand;
where we were forced into accordingly:
and in this hurliburly and confusion that was among them,
some men were sworn to testify that we refused to take the oath,
which we never positively did; other officers of the court, whom they would have sworn,
refused to swear, though pressed to it by the chief justice, they desired to be excused.
Then spoke one of the prisoners again pretty much, but could hardly be understood,
by reason of the noise in the court; but the people, to whom he spoke with a loud voice,
by way of exhortation, might hear the substance of what he said,
which cannot now particularly be called to mind;
but it was to express the presence and love of God to himself,
and to exhort others to mind his fear, that they also might be acquainted with God, etc.

[.discourse-part]
_Judge:_ Stop his mouth, executioner; +++[+++which was accordingly done.]

[.discourse-part]
_Prisoners._
Then we cried out.
Will you not give us leave to speak for ourselves?
We except against some of the jury, as being our enemies,
and some of them who by force commanded us to be pulled out of our meetings,
contrary to law, and carried us to prison without warrant, or other due process of law;
and shall these be our judges?
We except against them.

[.discourse-part]
_Judge:_ It is too late now, you should have done it before they had been sworn jurymen.
Jury, go together, that which you have to find, is:
Whether they have refused to take the oath or no,
which has been sworn before you that they did refuse: you need not go from the bar.
+++[+++And like words said the recorder and others,
there being a confusion and noise in the court, many speaking together.]

[.discourse-part]
_Prisoners:_ Then we cried for justice, and that we might be heard, to make our defence,
before the jury gave their verdict; but the judge and recorder said,
we should not be heard, making good by their practice,
what the chief judge had said the day before, namely.
That if we had liberty to speak, we would make ourselves famous, and them odious,
crying again.
"`Stop their mouths, executioner;`" which was done accordingly, with a dirty cloth,
and also endeavoured to have gagged me, John Crook, striving to get hold of my tongue,
having a gag ready in his hand for that purpose; and so we were served several times.
Then I called out with a loud voice, "`Will you condemn us without hearing?
This is to deal worse with us, than Pilate did with Christ, who,
though he condemned him without a cause, yet not without hearing him speak for himself;
but you deny us both.`"

[.discourse-part]
_Judge:_ Let Mr. Grey come to the bar, +++[+++room being made,
he was conveyed to an officer in the inner bar,
where he spoke to the court to this purpose:]
I desire to know whether, according to law, and the practice of this court,
myself and my fellow-prisoners may have liberty to put in bail,
to prosecute our traverse at the next sessions?

[.discourse-part]
_Court:_ No, we will try you presently.

[.discourse-part]
_Judge:_ Stop their mouths, executioner: +++[+++and this was the cry of many upon the bench,
they being still in a continued confusion; some crying to the jury,
"`Give in your verdict, for we will not hear them;`" with other words,
which could not be heard for the noise, the court being in confusion.

[.discourse-part]
_John Crook:_ You might as well have caused us to have been murdered before we came here,
as to bring us here under pretence to try us, and not give us leave to make our defence;
you had as good take away our lives at the bar, as to command us thus to be abused,
and to have our mouths stopped: Was ever the like known?
Let the righteous God judge between us.
Will you hear me?
You have often promised that you would.

[.discourse-part]
_Judge:_ Hear me, and we will hear you: +++[+++then he began to speak,
and some others of the bench interrupted him;
sometimes they speaking two or three at a time,
and a noise among the officers of the court: but the judge said,]
"`We may give you liberty till the next sessions, but we may choose;
and therefore will try you now.`"

[.discourse-part]
_John Crook:_ I bade the people take notice of their promise,
That I should have liberty to speak, saying.
See now you be as good as your words.

[.discourse-part]
_Judge:_ The law of England is not only just, but merciful;
and therefore you shall not be surprised, but shall have what justice the law allows.
+++[+++Interruption.]

[.discourse-part]
_John Crook:_ I remember what the judge said even now.
That the law of England was a merciful law; that the court had said before, They might,
if they would, give us liberty till the next sessions, but they would not;
and the maxim of the law also is, _Summum jus, est summa injuria;_
therefore I hope your practice will make it good, that it is a merciful law;
and not to execute _summun jus,_ etc. upon me,
and thereby condemn yourselves out of your own mouths.

[.discourse-part]
_Judge:_ Jury, give in your verdict.

[.discourse-part]
_John Crook:_ Let me have liberty first to speak, it is but few words,
and I hope I shall do it with what brevity and pertinency
my understanding will give me leave,
and the occasion requires; it is to the point in these two heads, namely: Matter of law,
and matter of conscience.
To matter of law, I have this to say, first, as to the statute itself,
it was made against the papists, occasioned by the gunpowder-plot; and is entitled.
"`For the better discovery and suppressing of Popish recusants:`" but they have liberty,
and we are destroyed, what in you lies.--+++[+++Interrupted by the judges,
and disturbance of the court.]
As to conscience, I have something to say, and that is, It is a tender thing,
and we have known what it is to offend it;
and therefore we dare not break Christ`'s commands, who has said,
"`Swear not at all;`" and the apostle James said, "`Above all things, my brethren,
swear not`"--(interrupted)--the court calling again to the executioner to stop my mouth;
which he did accordingly, with his dirty cloth, as aforesaid, and his gag in his hand.

[.discourse-part]
_Judge:_ Hear the jury; +++[+++who said something to him,
which was supposed to give in the verdict, according to his order;
for they were fit for his purpose, as it seems,
they beginning to lay their heads together, before we had spoken anything to them,
only upon his words.]

[.discourse-part]
_Judge:_ Crier, make silence in the court: +++[+++then the recorder,
taking a paper into his hand, read to this purpose:]
The jury for the king do find, that John Crook, John Bolton, and Isaac Grey,
are guilty of refusing to take the oath of allegiance;
for which you do incur a _premunire,_
which is the forfeiture of all your real estates during life,
and personal estates forever; and you to be out of the king`'s protection,
and to be imprisoned during his pleasure: and this is your sentence.

[.discourse-part]
_John Crook:_ But we are still under God`'s protection.

[.discourse-part]
_Recorder:_ Adjourn the court: +++[+++which was done accordingly, and we remanded to Newgate,
where we remain prisoners.]

[.asterism]
'''

[.blurb]
=== Some animadversions upon the whole matter, showing the severity and unmercifulness, if not cruel injustice, of the late proceedings against us: Leaving it to be judged by God`'s witness in every conscience.

Considering our first taking without warrant by force of arms,
and our commitment thereupon, with the proceedings upon that commitment at Hicks`'s Hall,
Middlesex,
by indictment against John Crook upon the late act of parliament against Quakers, etc.,
and his pleading not guilty thereunto, with the court`'s committing him again to prison,
where he remained until the sessions in the Old Bailey, as aforesaid;
the court`'s often refusal to take any notice of former proceedings,
or any injury or wrong that he had sustained, either in apprehension or proceedings,
or so much as the cause itself, for which he was imprisoned.

The court`'s putting him upon interrogatories, no accuser appearing, to accuse himself,
in tendering him the oath of allegiance, as a snare,
that so his refusal might become a crime for them to punish him for;
carrying themselves rather as parties, than as equal judges between two.

Because we were surprised in our trial, expecting that, according to our court order,
and former proceedings, we should have been tried upon the late act of parliament,
made on purpose against Quakers, etc.
Not in the least expecting any such proceedings as we met withal;
and therefore could not be provided to make our defence according to law;
seeing we were committed upon pretence of one law,
and prosecuted under colour of another; which could not, without force,
cast any face upon us, as persons concerned to be tried by it, namely: 3 Jacob 4,
entitled, An Act for discovering and repressing of Popish Recusants.

It further appears, in that our judges declined the late act, which was made on purpose,
after the imprisoning so many thousand Quakers,
only for refusing to take the same oath of allegiance;
which imprisonment begat so many debates in both the houses of parliament,
that it may be supposed they concluded the penalty of premunire,
according to the former laws, was either too great and severe, or that the Quakers,
so called, were not at all within the intent of those laws; and therefore they enacted,
That for the first refusal to swear, they might be fined, not exceeding five pounds;
for the second refusal, not exceeding ten pounds; and the third refusal,
it might be lawful for the king to cause them to be transported, etc.
But these judges, not liking the parliament`'s act,
nor their judgments expressed in the same, concerning punishing the Quakers,
have found out a way to make them feel their little
finger to be heavier than the parliament`'s loins,
as is manifest by the sentence of premunire lately passed, only for refusing to swear;
whereby they also slight the king`'s declarations, which say,
That no man should be molested, or called in question, for his conscience, etc.,
as they did his late proclamation, when it was given them in court to be read,
which says, That no man shall have his house searched, or be taken, or imprisoned,
under any pretence whatsoever,
except by a warrant first had and obtained from some of the privy council,
or some justice of the peace, etc.
But of these the court would take no notice, when they were urged to them.

Because, when time until the next sessions was desired, for these reasons:

[.numbered-group]
====

[.numbered]
1+++.+++ Because the indictment was in Latin, and so large.

[.numbered]
2+++.+++ There was need of counsel in the case.

[.numbered]
3+++.+++ It was to be a precedent; and therefore, for themselves, as well as us,
there was need of time: judges heretofore being careful in making precedents.
Unto all which we had this answer returned, Stop their mouths, executioner; and.
Take them away: and all this when it was the proper time for us to make our defence.

====

Because the moderate jury, that had served upon several trials at the same sessions,
were dismissed, and a new jury empanelled only for us,
consisting of several persons who had a hand in our illegal apprehensions and commitments.

Their unrighteousness is farther manifest from the recorder`'s answer to us,
when we pressed for time, who said, They could not grant it,
because they must deliver the jail; and yet several persons,
that were taken and imprisoned upon the same account with some of us,
are continued still in prison, there being nothing done unto them in order to any trial:
but as liars have need of good memories,
so have such judges of careless auditors and spectators,
that their words and actions may not be taken notice of Besides, at the same sessions,
the oath was tendered to some persons, and although they refused,
yet was liberty granted them till the next sessions;
which renders such judges guilty either of partiality, or injustice, or both:
and thus they condemn themselves by their own sayings.

Lastly, That which aggravates their severity and cruelty to us,
is farther manifest by these things following:

[.numbered-group]
====

[.numbered]
1+++.+++ That none of the kings of Israel that we read of,
ever required such an oath of the people.

[.numbered]
2+++.+++ Inasmuch as the refusal of the oath, simply considered, does the king no harm,
nor the taking of it any good.

[.numbered]
3+++.+++ If it were an offence to refuse to take it,
yet the punishment is not proportionable to the offence,
which by the just law it ought to be.

[.numbered]
4+++.+++ To conclude, the oath was not duly tendered, according to their own law,
inasmuch as it was not read at all to some of us, only we were asked,
if we would take it; and to others but once, and not quite through neither,
to our hearing and understanding; and none of us in words denied then to take it.
He that deserves punishment, is supposed to have done or said some evil:
Now the law says, _Malum non hahet efficiendam, sed deficiendam causam;_ in English thus,
Evil has not an efficient, but a deficient cause, says Coke, because,
some virtue is lacking.

====

Now what virtue is lacking in him that does speak the truth, without dissimulation,
but dare not swear at all.
These things truly considered,
and duly weighed in the balance of the sanctuary,
it will soon appear which scale goes down,
and over whom this motto deserves to be written, mene TEKEL, etc.
You are weighed in the balance, and are found lacking:
for this is the day for discovering of false weights and measures,
and of the measuring of the temple, and the worshippers therein,
according to John`'s prophecy, in Rev. 11.
And hearken also what the prophet says, Amos 5:7 and 10,
"`You who turn judgment into wormwood, and leave off righteousness in the earth;
and hate him that rebukes in the gate,
and abhor him that speaks uprightly;`" and at verse 27, it is said,
"`Therefore will I cause you to go into captivity,`" etc. says the Lord,
"`whose name is the God of hosts.`"

[.signed-section-signature]
John Crook.

[.blurb]
=== Now follows some collections, that passed at the same Court of Sessions, by Isaac Grey, called Doctor in Medicine, at the Old Bailey, receiving the same sentence of premunire with the other two.

[.offset]
Isaac Grey being called to the bar:

[.discourse-part]
_Judge:_ Will you take the oath of allegiance?

[.discourse-part]
_Grey:_ I have been near five weeks in prison; I desire to know for what.

[.discourse-part]
_Judge:_ We take no notice of your imprisonment, nor how you came here:
will you take the oath?

[.discourse-part]
_Grey:_ I desire to know for what I am imprisoned, and then I am ready to answer:
for no man, in this particular, has received so much wrong as myself,
having received a wound, whereby I was in jeopardy of my life.

[.discourse-part]
_Judge:_ If any have wronged you, take your course in law: will you swear?

[.discourse-part]
_Grey:_ I am a man of a tender conscience, and do desire time to consider.

[.discourse-part]
_Judge:_ Take him away: which was accordingly done.

[.small-break]
'''

The next day Isaac Grey was called to the bar, and asked by the judge,
if he would yet take the oath?
Recorder speaking unto him in this way: "`Mr. Grey, you are a wise understanding man,
and a scholar; be advised what you do, and do not ruin yourself, but take the oath.`"

[.discourse-part]
_Grey:_ I desire time to consider, and to do nothing rashly.

[.small-break]
'''

Then in the afternoon were all three again called to the bar, and the indictment read.

[.discourse-part]
_Judge:_ Mr. Grey, will you take the oath?
Crier, hold him the book.

[.discourse-part]
_Grey:_ I desire to know the cause of my first imprisonment,
and to discharge me of the same, before I give my answer to the oath;
for I do not know myself guilty of any crime.

[.discourse-part]
_Judge:_ The law supposes you to be disaffected to the present government,
and therefore the oath is tendered you.

[.discourse-part]
_Grey:_
I understand that the fundamental law of England allows
no man to be accused or condemned upon supposition:
I do farther affirm, and that in the light of God, That I am not an enemy to the king,
nor to any man living upon the face of the earth.

[.discourse-part]
_Judge:_ Will you answer guilty, or not guilty?

[.discourse-part]
_Grey:_ I desire time to consider of the truth of this matter; the indictment being large,
and having much contained in it, which indeed I do not well understand.

[.discourse-part]
_Judge:_ Will you yet swear, or plead to the indictment?

[.discourse-part]
_Grey:_ I have told you, and that for conscience sake, I dare do nothing rashly.

[.discourse-part]
_Judge:_ What do you talk to us of conscience?
Every fellow may plead conscience.

[.discourse-part]
_Grey:_ Do you use to swear such as make no conscience?

[.discourse-part]
_Judge:_ Guilty, or not guilty?
When you have answered to this, you may plead what you can in your own defence;
but first answer guilty, or not guilty: the rule of the law is, you must first answer.

[.discourse-part]
_Grey:_ Would you have men swear, whether they will or no,
especially when against their conscience?

[.discourse-part]
_Judge:_ We have consciences as well as you: if there be anything,
as to matter of conscience, it is nothing; you must plead guilty, or not guilty,
that we may not spend time any longer.

[.discourse-part]
_Grey:_ Truly,
I desire not that the time should be taken up in
anything that may not advantage the good of the people:
therefore before I plead, give me a copy of the indictment, and then I shall plead.

[.discourse-part]
_Judge:_ Sirrah, guilty, or not guilty?

[.discourse-part]
_Grey:_ I desire first to be heard as a Christian, and then as an Englishman.

[.discourse-part]
_Judge:_ Do not I tell you, sirrah, if you will plead not guilty, you shall be heard;
but if you will not, you will run yourself into a premunire.

[.discourse-part]
_Grey:_ I appeal then to God Almighty, for I shall not wrong my conscience.

[.discourse-part]
_Judge:_ It is no matter of conscience; guilty, or not guilty?

[.discourse-part]
_Grey:_ Not guilty.

[.small-break]
'''

The last day of trial all the three persons aforesaid being called to the bar,
after some discourse between my fellow-prisoners and the court,
myself was forced from there before I was heard,
my fellow-prisoners being violently thrust within the felons`' bar, but myself,
by command from the bench, was not thrust there;
but I desired to be with my fellow-prisoners, and to fare as they fared,
and so was put in with them; but after some time, the court being in a confusion,
and their officers abusing my fellow-prisoners,
by stopping their mouths and the common hangman endeavoured to gag one of them,
that they might not speak in their own defence;
then I desired I might be heard--upon which the court called me nearer to them:
then I approached to their bar, and spoke in this way, "`I desire to know whether,
according to the law of England, and the proceedings of this court,
we may not be allowed to put in bail to prosecute our traverse at the next sessions?`"

[.discourse-part]
_To which they answered:_ We might not.

[.small-break]
'''

Then I desired them to do me and my fellow-prisoners justice: "`for you are to know,
that as we stand arraigned at this bar,
so shall you appear before the great tribunal of God`'s justice,
to give an account of this day`'s work, as also of all the deeds done in the body,
whether they be good or evil; and what measure you mete to us,
shall be measured to you again.`"

[.discourse-part]
_Judge:_ We know that as well as you; +++[+++and then called to swear the jury,
the court being in a confusion, and the officers and hangman abusing my fellow-prisoners,
as aforesaid; then I went my way, the chief justice, so called, being in a rage,
called to me in an abrupt manner, saying.
"`You shall be tried according to the laws.`"

[.discourse-part]
_Grey:_ I do desire to be tried by the laws, and not by passion.

[.small-break]
'''

They then went on, being all in a confusion and disorder, unto sentence,
which was as follows: "`You shall forfeit all your real estate for life,
and your personal estate forever; and be put out of the king`'s protection,
and imprisoned during the king`'s pleasure, according to the statute of premunire.`"
Which sentence was also passed upon my two fellow-prisoners aforesaid.

These things are part of what passed between the court and myself,
many things being omitted by reason of the often interruptions,
and are written to prevent mistakes,
and to inform all moderate inquirers concerning the
severity and injustice that we met withal,
not only to the loss of all my estate and liberty, but of my practice also,
to the damage and detriment of many of my patients, who, through necessity,
are compelled to come to prison to me,
but have been sometimes hindered from coming to speak to me.

But our desires are
to forgive them that trespass against us,
as God has forgiven us our trespasses against him.

[.signed-section-signature]
Isaac Grey.
