== Chapter 8.

[.blurb.centered]
=== Truth`'s Principles: or, those things about doctrine and worship, which are most surely believed and received among the people of God, called Quakers.

[.blurb]
==== _Concerning the man Christ, his sufferings, death, resurrection, faith in his blood, imputation of his righteousness, sanctification, justification, etc. Written to stop the mouth of clamour, and to inform all who desire to know the truth, as it is in Jesus, by the servant of the Lord, John Crook._

[.centered]
=== To the Reader.

It being allowed by some late adversaries,
that we are more sound in the fundamental doctrines of the Christian faith,
than they thought of; yet they persist to object, that we have altered our religion,
and that our ancient Friends held grievous errors:
I am therefore willing in the 81st year of my age,
that this following treatise should be reprinted, that they may see what myself,
with our ancient friends, held in the year 1663.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Hertford, the 10th of the Tenth mo.
1698.

[.centered]
=== Truth`'s Principles.

Many are the reports that are abroad concerning this people,
not only as to their practices and deportments,
but also as to their doctrines and belief.
The former, time having in a great measure resolved and worn it out,
as being the refuge of lies for the ignorant and unrighteous to flee unto;
for that stormy and wintry appearance is well nigh over and gone,
because the sun is so far risen, and the true light so shines, that most begin to see,
that those reports were but lies and scandals,
raised as fig-leaves to cover the nakedness of other professions,
that begun so manifestly to appear,
through the light that shined in these people`'s lives and conduct.
But though the first be gone yet the latter still sticks with many,
as not knowing what they hold,
as to doctrine some saying They deny the scriptures and the resurrection of the body,
and all ordinances,
the man Christ and his death and sufferings and imputation
of his righteousness and faith in his blood etc.
Wherefore for the satisfaction of all that would willingly
be received and know the truth as it is in Jesus,
I have this short account of their faith and belief;
and if it were possible to stop the mouths of clamourous tongues before sentence
be given against them by some signal stroke of the Lord from heaven;
which he will undoubtedly in his appointed time reveal and make manifest to the trembling
of all hearts concerned therein and tingling of all ears that shall hear thereof,
when it shall be said unto them, "`The holy shall be holy still, and he that is filthy,
let him be filthy still.`"
Rev xxii 11.

We believe, that the God of all grace, has given a measure of grace,
or some manifestation of his Spirit, and light thereof, unto all men;
according unto these scriptures, John 1:9; Titus 2:11; 1 Cor. 12:7,
Neh. 9:29; and the experiences of all men,
who at some time or other do feel something in their hearts and consciences,
that does lust against the flesh, and the flesh against it:
and that these two are contrary the one to the other: one lusting after evil,
which is evil; the other spiritual; the one from the earth, the other from heaven, Gal. 5:16-17.

We believe, by this gift, grace, and inspiration of the Almighty,
man only can come to know the true God truly; what he is,
and how he works in the hearts and consciences of people, to regenerate them,
and make them bear his image; according unto 1 Cor. 1:19-21; Luke 10:21,
and experiences of all that ever were regenerate and born again.

We believe that all the errors and mistakes about God,
and the things relating to his kingdom,
sprang and arose from men`'s wandering from this gift of God,
into their own imaginations; whereby, though they though themselves wise,
yet they became fools, and erred, their foolish hearts being darkened,
according to Rom 1,
not knowing the "`Scriptures nor the power of God;`" as it is written, Matt. 12:29.

We believe and know, that this gift and grace of God appears in and unto all men,
that all may be without excuse, accusing for the evil, and excusing for the good,
according to Rom. 2:15-16, showing unto man what is good,
and reproving of him in his own conscience for the evil, whether thoughts, words,
or deeds; and that this "`reproof of instruction is the way of life.`" Prov. 6:23.

We believe, that as the true God, and eternal life,
is known only by the light of this gift and grace, according unto the Scriptures;
from which light and Spirit of God came the Scriptures,
both of the Old and New Testament, as it is written, 2 Pet. 1:21.
So can they only be read, as truly to be believed, fulfilled,
and practised, in the light and power of the same; and all that are out of this spirit,
must needs be ignorant and unlearned, in the apostle`'s sense,
who wrest the Scriptures to their own destruction, as it is written:
for Peter and John were unlearned men outwardly,
but inwardly read in the knowledge of this light and Spirit of God,
and wrest not the Scriptures.
Acts 4:13; 2 Pet. 3:16.

We believe, according to the Scriptures, 2 Cor. 4:3,
that wheresoever the power of God is not known within, there the gospel is hid,
and unknown unto them that are lost,
in whom the god of this world has blinded the minds of them that believe not,
lest the light of the glorious gospel of Christ, who is the image of God,
should shine unto them, and God should heal them.
Because it is only by the light of Christ, the power of God,
that the creature comes truly to see himself in his lost and undone state;
from which sight arises a true sense in the heart of the creature,
that makes him cry out of his wretchedness, by reason of the body of sin and death,
which necessitates him to look out for a Saviour,
whom God manifests in and by the same light, that shines in the heart,
on purpose to give the light of the knowledge of
the glory of God in the face of Jesus Christ,
God`'s image, whereby God heals the soul.
And therefore does the devil, the god of the world,
strive so much by the gifts of the pleasures, profits, vanities,
and lusts that are in the world, which he presents to men and women now,
as he did to Christ, in the days of his flesh, when he showed to him all the world,
with its glory; which glory is, the lust of the flesh, the lust of the eye,
and the pride of life; whatever may make this life happy, as it were,
in the things that may pride it, or lift it up, to sit as queen.
And as men and women take and receive these gifts from the god of this world,
their minds are blinded because they believe not in the light,
which shows them the vanities of all the gifts of the god of this world; which gifts,
the devil knows, if they be received, will so blind the minds of them that receive them,
that they will not come to be sensible in the true light of their lost conditions,
so as to cry unto God from the deep and true sense; for then God,
out of the depth of his love and mercy, could not but heal them.
And therefore, lest the true light should shine into them,
to give them the sensible knowledge of themselves, and God should heal them, the devil,
as god of the world, by the tilings of the world, endeavours to blind the mind,
not the brain-knowledge, but the heart-feeling sense within, in the mind,
lest the light within should so shine, as God should heal them;
and all the bustlings of Satan, with his gifts, are but to blind the mind,
lest God should heal the soul, that complains to him,
from the true sight and sense of his misery, as in himself.

By this grace and gift within, we believe, that to us,
though in the world there be lords many, and gods many, there is but one God,
the Father of our Lord Jesus Christ, witnessed within man, only by the Spirit of truth,
that manifests both the Father and the Son; and these three are one, and agree in one;
and he that honours the Father, honours the Son that proceeds from him;
and he that denies the Spirit, denies both the Father and the Son, and is Antichrist;
but he that believes in the Spirit, and is led by it, is a son of God; Rom. 8:14.
"`As many as are led by the Spirit of God, are the sons of God.`"

We believe, the Scriptures bear witness unto, and testify of Christ; but they say,
the witness of God is greater than them;
the Spirit itself bearing witness with our spirits, that we are the sons of God.
For it is not the scriptures without the Spirit,
nor the Spirit contrary to the scriptures;
but the Spirit`'s discovering the will of God in the heart,
or opening of the scriptures in its own time and way, and not in or by the will of man,
but as itself pleases, who searches all things, even the deep things of God,
and manifests them unto the soul, which gives the perfect, sound, and saving knowledge.
For, said Christ, the Spirit shall take of mine, and show them unto you:
and as holy men gave forth the scriptures, 2 Pet. 1:21, so holy men, and they only,
come truly to understand them; and not proud or ungodly,
because their hearts and lives do not answer the
hearts and lives of those that gave them forth,
as face answers face in a glass.
This we believe to be the reason, why so long preaching, by men of corrupt minds,
who have and do handle the words deceitfully, for selfish ends, and filthy profit sake,
has brought forth so little fruit, and been to so little purpose;
for "`had they believed, and therefore spoken, and stood in God`'s counsel,
they should have profited their hearers,`" Jer. 23:21-23, to the end.

Through this gift we believe, that Christ Jesus, the Son of God,
was manifested in the flesh, in the fulness of time.
And this we know by the same spirit, by which our fathers believed he was come,
and Abraham saw his day; by the same we do believe he is come, and do see his day;
as also by the prophets and apostles`' writings:
which two-fold cord is not easily broken.

We believe also, according to the scriptures of truth,
that this same Jesus has God highly exalted, and given him a name above every name,
that whosoever believes in him, shall not perish, but have everlasting life;
and that there is not another name, whereby man can be saved,
than this name of Jesus Christ;
nor is remission of sins to be preached by any other name.
But as we do not believe that the outward letters and syllables are that name,
that are to be bowed unto by the outward knee,
no more than the letters or syllables in the words God, or Spirit,
seeing the scripture says, "`Unto God, who is a Spirit,
every knee shall bow,`" Isa. 45:23. But that name which saves,
is the power and arm of God, that brings salvation from sin,
and makes every soul that names it, to depart from iniquity.
This is that name which was preached, and which is preached, through faith;
in which name, remission of sins is obtained: therefore was the outward word Jesus,
given him, as his outward name; You shall call his name Jesus,
for he shall save his people from their sins: (mark) for he shall save, etc.
So that which saves, is the name, which is to be believed in,
which is that arm of God that brings salvation, when no eye pities,
neither is there any to help; the power of God that then saves,
is that grace that comes from the fulness of Christ the Saviour: and without this virtue,
Christ and Jesus are but empty names, 1 Cor. 12:3: "`No man can say,
that Jesus is the Lord, but by the Holy Spirit.`"

We believe also, that this Jesus died for, or because of sin,
and rose again for the justification of those that believe in him,
as well as to manifest to all the world, that he was the Son of God,
and that he thereby spoiled principalities and powers, and triumphed over them openly,
and led captivity captive in his own person; yet we believe and know,
by his grace in our hearts, that as his name Jesus, without virtue and power,
is but an empty word; so his dying, without man`'s conformity to his death,
or being planted in the likeness thereof, or being crucified with Christ,
as says the scripture, Rom. 6:2-6; Gal. 2:20, will not profit man,
as to the salvation of his soul,
no more than the naming of his outward name Jesus
does at this day make people to depart from iniquity.
For we believe, and are sure, that man must die inwardly,
as well as Christ died outwardly, and must be put to death in his flesh,
as Christ was in his: for "`he that is in the flesh, cannot please God,`" Rom. 8:8,
"`neither cease from sin;`" but "`he that is dead is freed from sin.`" Rom. 6:7.
And yet man`'s dying unto sin, and the root and principle of it in himself,
is so far from making void Christ`'s death in his own person,
that it establishes it to all those ends and purposes,
for which it was intended of the Father.
As the cures which the physician does, manifest and establish his skill and ability;
so does man`'s dying unto sin and self, and living unto God,
manifest and establish the virtue and power of Christ`'s death.
For as man manifests his being risen with Christ,
by his seeking the things that are above, Col. 3:1-2,
so does he manifest his knowledge of the death of Christ,
by his being crucified with Christ, and bearing about in his body,
the dying of the Lord Jesus.
For as it is not an outward belief, gathered from the letter,
that will change the heart and life, though it may the judgment and opinion,
so is it not a belief from the history, or letter only,
that can give man a saving knowledge of the death of Christ;
but he must have the same glory and power of the Father in measure, working in him there,
to beget faith in his heart,
that he may believe unto salvation from his own filthiness and unrighteousness,
as well as confess with his mouth, Rom.
x., and must have that spirit in him, quickening his mortal body,
as well as to believe that it was in Christ,
"`and raised him up from the dead,`" Rom. 8:11.

And this man, whoever he be, bond or free, that thus believes the death of Christ,
and its satisfaction to God, as well as its usefulness to man, cannot make it void,
nor divide it and its virtue upon the soul that thus knows it.
But he will say, here is a dying man witnessing the death of Christ,
and nevertheless the same man living with Christ, and concluding, if Christ had not died,
man must have perished in his sin; this being the way found out by God to recover him;
whereby he knows Christ, and him crucified,
and what the preaching of the cross of Christ is,
which is foolishness to them that perish, but to them that are saved, the wisdom of God,
and the power of God. 1 Cor. 1:18.

By this gift of God in our hearts, we further believe,
that Christ Jesus rose again from the dead, according to the scriptures,
and sits at God`'s right hand in a glorious body;
and we believe that our low estates and humbled bodies,
shall be made like unto his glorious body, through the working of his mighty power,
whereby he is able to subdue all things unto himself;
and that this mortal shall put on immortality.
For though we believe, that Christ Jesus has lighted every man with his light,
whereby man may come to know himself lost and undone, as before is said;
yet therefore is not every man saved,
though the grace that appears to all men is sufficient in itself;
but some have the grace of God bestowed on them in vain,
not liking to retain God in their knowledge,
though something within them shows them what is good;
"`but they reject the counsel of God within, or against themselves,
to their own destruction,`" Luke 7:30. (see the margin).
And yet it does not follow, that the grace is insufficient itself,
no more than it follows that Christ`'s death is insufficient,
because he tasted death for every man, and yet every man is not saved.
Neither does regeneration, or the believing in the light of Christ within,
make void the death and sufferings of Christ without at Jerusalem,
no more than believing the scripture testimony without, concerning Christ`'s death,
makes void the work of regeneration and mortification within.
But as the apostle says in another case, so say I in this.
For as the man is not without the woman,
neither is the woman without the man in the Lord;
even so is not the death and sufferings of Christ without at Jerusalem,
to be made void and of none effect by anything within;
neither does the light within make that of none effect without,
but both in the Lord answer his will.

For though there is, and may be,
a knowledge and belief of what Christ did and suffered without the gates,
in his own body upon the tree, and yet sin alive in the heart,
and the work of regeneration not known; yet it cannot be so,
where the light within is believed on, and obeyed,
so as to have its perfect work in the heart, to regenerate and make all things new,
and to be of God; this man can never make void what Christ has done and suffered without.
And yet this new birth, or Christ formed within, and dwelling in the heart by faith,
does not limit or confine Christ to be only within, and not without also,
but both within and without, according to the good pleasure of the Father,
to reveal and make him known, for, "`He fills all things,
and the heaven of heavens cannot contain him,`" and yet is he at God`'s right hand,
far above all heavens, in a glorious body.

And we also believe the resurrection of the just and unjust, the one to salvation,
and other to condemnation, according unto the judgment of the great day;
and then shall every seed have its own body, according to 1 Cor. 15:36-38,
which we verily believe: for if the dead arise not, we are, of all men, most miserable.
But because we dare not be so foolishly inquisitive, as to say,
With what bodies shall they arise?
Therefore do some say, We deny both the resurrection of the body of Christ,
and of all that shall or will be dead: but this also is false;
for "`every man shall be raised in his own order;
but Christ the first fruits,`" 1 Cor. 15:23. And we believe,
they shall be raised with the same bodies, so far as a natural and spiritual,
corruptible and incorruptible, terrestrial and celestial, can be the same.

We further believe, according unto the scriptures, concerning faith.
That that faith is only true, which is God`'s gift, and has Christ Jesus,
the power of God, for its author and object, and is distinguished from the dead faith,
by its fruits: for though in description and definition they may carry a resemblance,
yet in nature are as different as a living man is from a dead,
which lacks not form or shape, but life and power.
So says the apostle James, "`As the body without a spirit is dead,
so is faith without works;`" even so is that faith which stands in the wisdom of words,
and not in the power of God.
By the one, man is kept in captivity to the world, and the things of it;
but by the other he has "`victory over the world,`" 1 John 5:4,
and the seal and witness thereof in his own heart, whereby it is purified,
and God is seen; for the pure in heart see God, Matt. 5:8.
This faith differs men now, and their worships, as it did Cain and Abel;
for, "`by faith Abel offered up a more excellent sacrifice than Cain,`" Heb.
xi. By this living faith, Abel saw beyond the sacrifice unto Christ,
the first-born of God; beyond the firstling of the flock, which he offered;
and therefore God had respect unto Abel and his offering;
but God rejected Cain and his offering, though he had faith to believe it to be his duty,
yet sticking in the form,
and not flying on the wing of faith unto Christ the one offering, he missed the mark,
as all have done ever since, that have gone in Cain`'s way of worshipping,
as well as killing men about worship.
But we believe that faith to be only true and saving, that flies over self-righteousness,
as well as filthiness, unto the fountain of life in Christ;
which faith has nothing of man in it, but is as the breath of life,
by which the soul lives;
not a bare assent to the truth of a proposition in the natural understanding,
but the soul`'s cleaving unto God, out of a naturalness between Christ and the soul;
and so lives rather by relation, than bare credit, or desperate adventure and hazard;
not looking at its doing to commend it, but God`'s love and bounty in Christ the light,
to receive it; and yet holiness is its delight, and he can no more live out of it,
than the fish upon the dry land.

We believe, That this faith keeps the mind pure, the heart clean,
through the sprinkling of the heart from an evil conscience, by the blood of Jesus,
which remits the sin, and justifies the soul,
through the virtue of this blood received into the heart by this living faith,
which receives all its power and virtue from Christ,
in whom it abides as its root and object, whereby justification is witnessed "`from sin,
not in sin,`" Rom. 6:22: "`But now being made free from sin,
and become servants unto God, you have your fruit unto holiness,
and the end everlasting life.`"

We believe, That justification and sanctification are distinguished, but not divided:
for as he that sanctifies and justifies is one, so do these go together;
and when the soul has the greatest sense of justification upon if,
through the virtue of the blood of Jesus by the living faith,
then is it most in love with holiness, and at the greatest distance from sin and evil;
and whenever there is a failing in sanctification,
there is also some eclipse of justification in the eye of the soul,
until faith has recovered its strength again, which it lost by sin`'s prevailing.
For as the farthest and clearest sight is in the brightest day, so is it with the soul,
when it is most in the brightness and beauty of holiness,
its justification appears most glorious,
and its union and communion most sweet and lasting; and so, like twins,
as they are much of an age, so they are like one to the other;
and "`what '`God has joined together, let no man put asunder.`"

We also by this light believe, that acceptance with the Father, is only in Christ;
and '`by his righteousness made ours, or imputed unto us; not by the creaturely skill,
but by the applicatory act of God`'s gift of grace,
whereby the soul feels the difference between self-applying by its own faith,
and God applying by his Spirit, and so making Christ unto the soul, wisdom,
righteousness, sanctification, and redemption; so that we believe, and are sure,
that there is great difference between imputation, as it is the act of man`'s spirit,
and as it is the act of free grace, without man`'s forcing.
And so we distinguish between imagination and imputation,
between reckoning or imputing that is real, and reckoning or imputation that is not real,
but a fiction and imagination in the creaturely will and power:
and because we are against the latter, we are clamoured upon,
as if we denied the imputation of Christ`'s righteousness,
when it is only unto those that are not made righteous by it, to walk as he also walked.
For, as the scripture says,
It is not he that says he is righteous by the imputation of Christ`'s righteousness, but,
"`He that does righteousness, is righteous, as Christ is righteous,`" 1 John 3:7;
he that believes otherwise is deceived.
And yet it is not acts of righteousness, as done by us, nor as inherent in us, as acts,
by which we are accepted of God, and justified before him; but by Christ,
the author and worker of those acts in us and for us, whereby we know that we are in him,
and he in us, and we hold him as our head;
into whom all things are gathered together in one, even in him.

We further believe, that God is only to be worshipped,
and not any likeness that man makes unto himself of God, from any view,
sight or knowledge that he has had of him, but in every act and service,
man is to know what substantially, as well as whom speculatively or notionally,
he worships; as it is written, John 4:22, "`You worship you know not what:
we know what we worship; for salvation is of the Jews.`"
And he that thus worships the Father, honours the Son by the same spirit,
which is one with the Father and the Son; in which spirit only God is worshipped,
according to the form of its own choosing, and manifesting of itself in and by,
according unto the good pleasure of the Father, who is a Spirit,
and limits man unto the Spirit`'s form;
but allows not man to limit the Spirit unto his form:
though it be not of his inventing originally, but of the Father;
yet man must no more limit God unto it,
than he could command God to appear in it at first: for as he chose it himself,
so has he reserved liberty to leave it at his pleasure;
who works all things after the counsel of his own will, which he has purposed in himself;
that the gift of the knowledge of the mystery of his will,
might forever be acknowledged to be of his grace,
and from the riches of the glory thereof, according to Eph.
i.,and man be bound, but God free; man bound to wait in the light for God`'s movings;
but God free to move in whom, to what, and when he pleases: then man is to go,
when he says, Go; and come, when he says, Come; and such servants do serve him;
and then there is no more curse, as in the days of will-worship and voluntary humility,
"`but the throne of God, and of the Lamb,`'`"`' Col. 2:18. 23. Rev. 22:3-4,
and "`they shall see his face, and his name shall be on their foreheads.`"

We believe also, that this worship is spiritual, and not carnal,
in all its parts and ordinances; and not to be imposed by any outward force,
but performed by the inward leadings of God`'s Spirit,
according as the holy men of God were led and guided in the days past,
who gave forth the scriptures; all impositions of worship outward,
being only enjoined under the first covenant, that made nothing perfect,
until the time of reformation, spoken of, Heb. 9:10. But Christ being come,
there is an end as well of such impositions, as of the meats and drinks,
and various baptisms, and carnal ordinances; they being all but temporary,
and in order unto an end; but all to veil Christ, the sum and substance of all,
(the first) pointed at by all, and (the last) ending of all, the Amen.
And he that thus worships God in Christ, his ordinances are spiritual, not carnal,
and his faith carries him beyond his works, with righteous Abel; and preserves him,
that he is not drowned in the form, like Cain;
neither falls he short of the glory of God, nor of his assurance of acceptance with him.

We believe there is one baptism necessary unto salvation, Eph.
iv.5, "`One Lord, one faith, one baptism.`"
And this baptism is spiritual, of which John`'s water was but a figure, John 1:31,
"`That he should be made manifest to Israel,
therefore am I come baptizing with water,`" says John: and 1 Pet. 3:21,
"`The like figure whereunto, even baptism, does also now save us,
not the putting away of the filth of the flesh,
but the answer of a good conscience towards God, by the resurrection of Jesus Christ.`"
This one spiritual baptism into the name of Jesus Christ, is that which saves;
the water being but a figure, that Christ might be manifest to Israel,
who had various baptisms imposed on them, until the time of reformation; but Christ,
the substance, being come, the shadows flee away.
And yet,
wherever any believe they are commanded now by the same Spirit
that commanded the believers to be baptized in the days past,
either for the furtherance of the gospel, or trial of their faith, we judge them not:
but this obedience is very rare to be found; and we could heartily desire,
that all would consider seriously, whether literal sayings,
observed only by outward reading, hearing by the ear,
or inward impulses upon the heart by the Divine Power,
are the motives unto obedience in this kind.
And if honesty and uprightness of heart may be heard, we believe and know,
the many dead souls everywhere, notwithstanding their baptisms,
will be as so many witnesses against them, by their grovelling upon the earth,
as so many slain and killed men by the letter;
while the Spirit`'s quickenings have not been in the true baptism into death.
For we find by daily experience, that most men and women live like Pharaoh`'s lean kine,
only to eat up the fat, and to envy those that are not so lean-souled as themselves.

We believe also, that as there is one true saving baptism,
so there is one bread or body of Christ, which all the saints do feed upon;
and though they may be many, as to persons, yet their bread is but one,
and they all in it but one bread.
And this we believe is the "`flesh that came down from heaven,`" John 6:33,
Though the outward Jews now, as then, murmur at him, because he said,
"`I am the bread which came down from heaven,`" verses 41, 42. But Christ, verse 45,
to stop their murmuring, tells them,
that the knowledge of this mystery was only revealed unto them whom God, and not man,
teaches; and no more than are taught of God,
can set seal and subscribe unto (his truth in Jesus: though we believe also,
that Jesus did take outward bread, and broke it, and gave it to the disciples,
as the scripture says; and this was a figure of his body,
that was to be pierced and broken upon the tree, to show forth his death until he came.
And we believe he did arise again, and appear unto his disciples:
"`And all that believed were together, and had all things common,`" etc.
"`And they continuing daily with one accord in the temple,
breaking bread from house to house,
did eat their food with gladness and singleness of heart, praising God,
and having favour with all the people.`" Acts 2:44-47.
And we believe that the apostle, in 1 Cor.
xi 20, says true, where he says, "`When you come together therefore in one place,
this is not to eat the Lord`'s supper.`"
And all that he speaks in that chapter,
is not to perpetuate that outward breaking of bread, otherwise than as the believers did,
that were "`filled with the Holy Spirit,
in singleness of heart:`" and yet we judge not those who break outward bread,
and drink outward wine, being in a belief they are commanded so to do,
to put them in a remembrance of the body and blood of Jesus Christ, by the Remembrancer,
the Spirit of Truth, which is appointed by the Father, to lead into all truth.

But to do it by imitation or tradition only, as most do it, if not all, at this day,
we know it is not an offering unto God in righteousness,
neither do we believe this to be the communion of the body and blood of Christ; and yet,
the eating of the flesh, and drinking of the blood of Christ,
we believe man must know and witness, or he has "`no life in him;`" John 6:53-55.
We believe that many are striving now in their spirits, as the Jews did, verse 52,
saying, "`How can this man give us his flesh to eat?`"
And not only the Jews, but many of his disciples said, "`This is a hard saying,
who can hear it?`" verse 60.
And at verse 63, he tells them, "`It is the Spirit that quickens,
the flesh profits nothing: the words that I speak unto you, they are spirit,
and they are life:`" and he that hears and understands these words,
that are spirit and life,
will not be offended at what I have spoken of the flesh and blood of Christ.

By the same spirit and grace we believe, that prayer is an ordinance of God,
when performed by his Spirit, in its words, and not those which man`'s wisdom teaches,
or without words, by sighs and groans which cannot be uttered;
and these so often as the Spirit itself pleases: but the form without the Spirit,
whether it be by words of other men`'s framing, or words of a man`'s own spirit,
according to his will, time, and manner; this is not the prayer that prevails with God.
And we believe, there is none so weak and infirm,
but this Spirit offers its help at some time, though man regards it not;
and the more man`'s mind is gathered from all visibles,
the more he comes to be sensible of the movings of this Spirit,
in its secret cries to God, answerable to the needs of that man or woman,
in whom it moves.
By due watching thereunto, we believe and know,
the spirit of prayer and of adoption that cries unto God,
comes to be discerned and distinguished from a man`'s own spirit and will.

We believe, by the same gift of grace, that there are several administrations,
and several operations, according to 1 Cor.
xii., and all "`by the same Spirit;`" as before the law, and after the law by Moses;
and after by John the Baptist, and Christ and his apostles;
and in all these the ministration had acceptance with God,
through the management of the Spirit; and its rejection and dislike of God,
for the lack thereof.
And by this Spirit were the Scriptures given forth, and holy men of God did speak,
prophesy, preach, and pray, as they were moved; and for lack of it, the letter did,
and does kill.
And for the further appearance and pouring out of this Spirit,
answerable unto the work and service that God had for them to do, they were to wait,
as Christ commanded his disciples to do at Jerusalem,
to receive the promise of the Father: for, by this Spirit, he that speaks,
speaks as the oracle of God.
And therefore as it was the practice of the people of God in old time,
to wait for the moving and stirring of this Spirit,
that they might speak as it gave them utterance,
in the evidence and demonstration thereof; so do this people, called Quakers, now;
and according to its moving in their hearts they minister,
according to the signification of the Spirit,
whereby they understand both what and when to speak, and when to be silent; as also,
who they are that minister and speak in their own wills, above the cross of Christ,
which the apostle was careful always to be in subjection to, lest he should make it void,
by speaking the words which man`'s wisdom teaches; and therefore as the saints did,
so we do believe, and therefore we speak: and such preaching and speaking in faith,
as well as praying in faith, is acceptable unto God, as his worship, and not otherwise.

And we further believe, by the same Spirit, that the sum of all religion,
according to truth,
and the signification of the word (religion) is man not at liberty in his will,
but bound again unto God, by his having given to him, by the light of Christ within,
the true sight and knowledge of himself, as in himself, as lost and undone forever;
and from this sight, a true sense to arise upon and remain with him,
from which spring unutterable groans and cries unto God,
under the weight of the burden and wretchedness, by reason of the body of sin and death;
and then when there was none to help or pity in this state,
then is mercy showed in Christ the arm of God, which is revealed as a help, neither seen,
nor known, where, how, or when to come at, or meet with it:
and this begets in the heart of that man or woman, in and unto whom it is thus revealed,
thanks and praises unto God, for this gift and revelation of his Son,
in this needful time, whom the soul sees to be the gift of eternal love.

And we believe and know, upon this love and faithfulness of God, is founded, built,
and established, the everlasting covenant,
whereby not only all men may be saved for its ability,
but some shall be saved because of its prevalency,
which is not like to the covenant which he made with our fathers.
And although all mankind is not saved,
yet it is not because either of insufficiency in this covenant,
or of the weakness of the grace that appears in and unto all men;
but because of man`'s will, loving death, and choosing his own delusions,
whereby his destruction is of himself, and God clear of his blood,
in the free tender of his grace, gift, and striving of his spirit within him.
For we know assuredly, according to the scriptures of truth,
and experience of all souls that ever were truly converted to God,
that though by grace man is saved, not of himself, but by the free gift;
yet as the old world did, and those rebellious Jews spoken of, Acts vii.
who, as did their fathers, so did they, always resist the Holy Spirit; so do men now.
And yet in the tender of this grace, and striving of his spirit,
the Lord is a God so hiding himself in the management of this striving,
and ministration of his Spirit,
as if it wholly depended upon man`'s choice and consenting, that man`'s will as to him,
is, as it were, free, in rejecting or accepting, life and death being set before him;
whereby, in the wisdom of God, the propensity of his nature,
as it came out of the hands of his Maker, has an advantage, by this dealing of God,
to put forth itself; so that man is as free in the choice,
as he is in the refusal of the tender of mercy and help,
and that with an equal indifferency, as it appears to him in this state;
notwithstanding afterwards, in the further growth in this grace and knowledge of Christ,
he sees clearly and convincingly, that the grace,
that wrought hiddenly from his sight and knowledge, in the first working, tender,
and ministration of God towards him,
gained his consent through its own prevalency in the love of God;
by which sight and sense, self comes to be abhorred, and the free love so admired,
that he knows from first to last, all was of grace, and that free;
that self is not able to challenge anything, as due from what it had done;
but all of gift; and yet, as before, with such an equal indifferency on man`'s account:
so that God may and will be just, both in condemning and saving,
and the justifier freely of all that believe in Jesus, the light of the world.

Therefore let all take heed how they dislike this ministration of God,
and striving of his Spirit in their hearts and consciences,
under colour and pretence of its insufficiency; and therefore they will not come to him,
because his drawings and strivings are not so strong as they would have them to be,
looking for such an overpowering and irresistibleness,
as they are not able to withstand and gainsay; lest such perish through a wilful neglect,
for lack of stretching out their hand, when the Lord holds out his;
and so they perish in the ditch, with a vain expectation of farther power,
or cry in their mouths, Lord have mercy upon us.
And with the sluggard, while they cry.
Yet a little more slumber, and folding of the hands to sleep,
their garden is overgrown with weeds, and their backs clothed with rags,
and they beg in harvest; while others, that have sown in tears, not fainting,
do in due time reap in joy; and not despising the crumbs that fell from the table,
nor the day of small things, witness the presence of their beloved,
come down into his garden, and walking among the lilies.

Let these things be truly considered, pondered,
and weighed in the true balance of light and righteousness,
lest any soul perish through the false weight and measure; so shall my soul rejoice,
that any have escaped the net of the fowler, through the discovery of the true light,
and God have all the glory, unto whom alone it belongs; and man ashamed, confounded,
his mouth stopped, and he laid in the dust forever:
and then shall my end be answered in writing these things.

[.signed-section-signature]
John Crook.

[.blurb]
=== An epistle to Friends, for union and edification of the church of God in Christ Jesus.

[quote.scripture, , 1 Cor. 1:10]
____

Now I beseech you brethren, by the name of our Lord Jesus Christ,
that you all speak the same thing, and that there be no divisions among you;
but that you be perfectly joined together in the same mind, and in the same judgment.
____

[.salutation]
Dear Friends and Brethren, etc.,

I salute you all in that first love wherewith God loved us,
and we so dearly loved one another.
In my old age I cannot forget those times and seasons of comfortable refreshment
we have enjoyed together in the Holy Spirit of our heavenly Father:
praised be his blessed name forever.

That which is in my heart to you in this epistle, is,
to remind you of that free love of God, that visited us in our low state,
when we were cast out, as it were, in the open field, void of all shelter,
as in a weary land, quite tired, and weary of everything:
then was made known to us the hiding-place from the storms, etc.,
which we found to be as a rock in that weary, wayless, wilderness-state and condition.

My dear friends, you that know and can witness what I write, what remains,
but that we love him that first loved us, and one another in him.
The former will appear by our keeping his commandments,
and the latter by our diligent and tender watchfulness one over another,
for our preservation in the same love unto the end.

Remembering that all miscarriages, both towards God and towards one another,
arise and spring, commonly from the decay of love:
this procured that dreadful threatening to Ephesus,
of having her golden candlestick removed, because she had left her first love, etc.

I doubt not but there are those yet left among us,
who can remember that esteem and good persuasion that many people had of the truth,
and of those that professed it at the beginning, because we loved one another;
and therefore many concluded we were the disciples of Christ.
And it may be observed,
that because Peter knew man`'s heart is not more ready to deceive him in anything,
than concerning true and unfeigned love, he prefers not his own knowledge of his heart,
but appeals to Christ`'s knowledge of it, saying, "`Lord you know I love you.`"

And because true love to the brethren is such an excellent grace and virtue,
the primitive Christians counted it a sign of their regeneration, saying,
"`We know we have passed from death unto life,
because we love the brethren:`" but seeing there is a hypocritical fawning,
that looks like love, the apostle sharply reproves that, saying,
"`Let your love be without dissimulation.`"

Therefore as God`'s free love in Christ Jesus was the cause
of our gathering to be a people at the beginning,
who were not a people, but gathered us, as it were,
out of all sorts of professions of religion, to be a people to his praise; and did,
agreeably to his promise, Jer.
iii, 15, 16, raise up pastors, according to his own heart,
that fed us with divine wisdom and understanding;
which was in some measure the fulfilling of that prophecy,
so that we pursued after the substance, which is Christ Jesus; and left the shadows,
ceremonies, and figures, as ending in him the substance; of which figures,
the ark of the covenant under the old law, was chief; as Jeremiah,
prophetically speaking of the gospel times, saying, "`In those days says the Lord,
they shall say no more the ark of the covenant of the Lord,
neither shall it come upon the heart,`" as the margin has it,
"`neither shall they go after it,`" etc.

Now, dear friends, seeing we began in the substance,
which was the appearance of Christ Jesus in spirit and power, let all watch,
and be careful, that they turn not aside, lest by hearkening to the fleshly wisdom,
and carnal reasoning, any of you fall back again into the naturals,
where the shadows pass for substances; and so become bewildered again,
and at a greater loss than you were in before: for then it may be said,
It had been better for you that you had never known the way of truth;
better not only because it will be harder to return again,
than before your first convincement; but also the fiery furnace,
through which such must pass, will be hotter;
because the state the backslider is fallen into,
is aggravated by his being once enlightened;
which renders that condition near unto impossibility
of returning according to Heb. 6:5-6.

This I speak as a warning to all concerned, that they which stand, or think they stand,
may take heed lest they fall; for,
"`Blessed is the man that fears always;`" because
he that casts away true fear will restrain prayer;
and the restraining of prayer, will discover the irreligious and careless:
and the hypocrite does not truly discern prayer, though he makes long prayers.

Therefore, dear friends, as you would persevere unto the end,
in your spiritual union with God, and communion one with another;
and as you would have such as should be saved added to the church,
and that the number of them may be increased through the world,
until the kingdoms thereof become the kingdoms of the Lord, and his Christ`'s;
which must be accomplished, and the mystery of God finished, Rev. 10:7,
compared with 11, 15; I say, as you desire the accomplishment of all these things,
in their season, what manner of people ought you to be in all godliness of conduct?
which branches out itself into all particulars of religion, and the duties thereof,
as children to parents, subjects to their governors, wives to husbands,
servants to masters, and the younger to the elder, etc., as the apostle writes to Titus:
which exhortation would be to no purpose, did not the grace of God appear to them all;
therefore he says,
"`For the grace of God that brings salvation has appeared to all men,`" etc.,
whereby the apostle exalts the sovereignty of grace,
for the performance of all these duties;
exhorting them to keep the "`unity of the spirit in the bond of peace:`" for
peace must be kept in all the states and conditions God has placed people in;
peace and love being the bond that will preserve in the unity, both with God,
and one with another.

The children of God are bound together, as it were, in the bundle of life;
and as they continue so bound, the gates of hell can never prevail against them:
but if any separate from that bundle of life, and unity in the spirit,
they are soon broken.
Therefore I exhort all, to keep the unity of the spirit in the bond of peace;
and then will you abide in the new covenant, that is ordered in all things, and sure.
For although the great covenant is between the Father and his Son Christ Jesus:
yet that covenant is derived from the Father to all his children in Christ Jesus:
so that every particular, according to their measure, can say, with holy David,
"`You have made with me an everlasting covenant,`" etc.,
as they abide in the unity of the spirit, and bond of peace.

But if this unity of the spirit be departed from, by disorderly walking,
and running greedily after this present world, hasting to be rich, etc.,
such oftentimes miscarry, not only to the loss of their own estates,
and ruin of their families; but also to the wrong of their neighbours;
and above all to the dishonour of their holy profession,
and causing the way of truth to be evil spoken of.

Let not such deceive themselves, by thinking such miscarriages may be salved over,
or covered with an outward and formal profession of the truth;
for God is not so tied to any profession,
that they should be at liberty to walk after the lusts of the flesh,
and to please themselves; but if we break covenant with him,
he is not bound to keep covenant with us; but the breach is always first on man`'s part,
as the prophet Zechariah speaks, ZEcc. 11:10, which was signified by the two staves,
beauty and bands, saying, "`And I took my staff, even beauty, and cut it asunder,
that I might break the covenant that I had made with
all people;`" and it was broken in that day;
and the poor of the flock that waited upon God, knew that it was the word of the Lord.

And when the unity of the Spirit is departed from, and the bond of peace broken,
the other staff`", bands, which signified their outward form or discipline,
could not keep them together; but God soon cut that asunder also,
that he might break the brotherhood between Judah and Israel;
for the brotherhood between Judah and Israel of old did
not stand in the outward form of the same profession only,
as appears Isaiah Ixvi.
3, where it is said, "`He that kills an ox, is as if he slew a man:
he that sacrifices a lamb,
as if he cut off a dog`'s neck;`" even when these things were outwardly required:
but they were departed from the holy Spirit of God; therefore it follows,
"`But to this man will I look, says the Lord, even to him that is poor,
and of a contrite spirit, and trembles at my word.`"

Dear friends,
let us be careful to keep to the laws of the house upon the top of the mount, which is,
"`Holiness round about,`" Ezek. 43:12. If holiness be round about, then God is there,
according to his promise, and Christ is in the midst, be the number never so small;
yet it may be called the house upon the top of the mount, because the Lord is there;
then there is no room for formality, or carnal liberties, nor anything else,
that tends not to holiness and purity;
but whatever advances and promotes holiness round about, even in all our ways, words,
and actions, that the doctrine according to godliness may be maintained,
even that godliness that is in Christ Jesus, although we suffer persecution for it.
The name of this house, THE LORD IS THERE, will end all other names, as it is foretold,
that the time shall come that the Lord shall be One and his name One in all the earth.

His name is his power, and presence of his Spirit and glory,
and as we give up wholly to his disposal and ordering of us,
then it will be with us inwardly in all our meetings,
as it was outwardly at the dedication of the temple;
which God took so kindly at the hands of Solomon, that he would not dwell in it himself,
though it was so much famed in the world, but gave it up to the Lord,
that "`God so filled the house with his glory,
that the priests could not enter in,`" as it is written in 2 Chron.
vii. and not only so, but God provided such plenty of sacrifices,
that there was scarce room to receive them.

As we give up to the divine power of God, as Peter calls it,
that will make us partakers of all things that pertain to life and godliness,
and so fill our meetings with greater glory than at the beginning;
when few words oftentimes did the work of, the ministry, to God`'s praise and glory,
and to the comfort and satisfaction of the souls of his people.

Those pastors which God raised up at the beginning, according to his own heart,
went out to God`'s work, as Abraham did out of his country and father`'s house,
not knowing where; so they not questioning God`'s assistance,
or disposal of them in his service; and like Israel when they left Egypt,
and set forth their three days journey, saying,
"`We know not wherewith we shall serve God until we come there.`"

So poor in spirit were they in that day,
and so closely kept they retired unto the light and
measure of the Spirit of Christ within,
that they dared not, out of a holy fear, open their mouths,
till the word of the Lord came, saying, as the prophet Jeremiah speaks,
and when that stopped saying, they had done speaking until it came again.

This was one great cause, wherefore the truth, at the beginning,
so mightily grew and prospered, together with the holy conduct, answerable thereunto,
of those that received the truth in the love of it, into the good and honest heart,
as it is written.

These things I write unto you by way of remembrance,
to stir up your pure minds to follow these good examples,
that those of latter times may beware of lusting to speak many words,
and of thinking that may do the business of the ministry;
and of lusting to preach or pray, to gratify an itching ear after speaking;
or sometimes to show their gifts and elocution, for applause.
This is not spoken to stop the motion of God`'s Spirit in any,
nor to despise youth truly sanctified and gifted,
but that none may be exalted when they see people affected with their ministry.
Pray observe Christ`'s caution to those early messengers, that came and told him,
that unclean spirits were subject to them, etc., by advising them not to rejoice in that,
but rather that their names were written in heaven, Luke 10:20.
This may be a caution to all those of lower attainments and less authority,
who had need to take heed of popularity, or striving for a name on earth,
but be sure their names are recorded in heaven.

Timothy was a young preacher, but rarely qualified, yet Paul in his epistle to him,
among other counsel that he gives him, he advises him to exhort the younger women,
as sisters, with all purity.
Timothy was a young man, and probably attended with temptations of youth;
therefore Paul advises him to shun youthful lusts;
and instructs him to be careful in his exhortation to young women,
that he do it with all purity, lest any sinister or by-end should creep in to defile,
and so frustrate his exhortation.
A good caution to all young men, that are but young preachers also.

Those pastors after God`'s own heart, at the beginning,
kept much to the word of exhortation, to the light of Christ in the conscience,
as a seed that was sown for the righteous to bring
forth a plentiful crop of holiness to the Lord;
from which also sprang pure living praises to the Almighty,
for bequeathing such a legacy and gift through Jesus Christ,
unto such poor orphans as we were, at that day, when as to religion,
we could call no man father on earth; no, we scarcely dared call God father,
in that state we were then in, at our first convincement.
Yet I can say, with many more at that day, that in God, the fatherless found mercy,
through Jesus Christ.

Let all be careful, how any meddle by way of prophecy of times and seasons,
so as to fix destructions and desolations to be on, or within, such a certain time.
But keep to the form of sound words, and gospel doctrine, used in holy Scripture,
and examples of gospel ministers, and not to be too positive about persons, places,
and things; which if imaginary, presumptuous, or mistaken,
proves to the great dishonour of truth, and stumbling of many,
if not to the ministering an occasion of atheism,
to such as watch for opportunities thereunto,
and also to cause many not to regard true prophets.

The first preachers among us, as all true preachers do,
minded more the goodness and sincerity of those that came among us,
than they did the number of the people: their business and message was,
to gather the poor lost sheep of the house of Israel;
and to call sinners not only to change their opinions, but to change their hearts, lives,
and conduct, that such might be added to the church, as should be saved;
and in all things they showed themselves workmen, that need not be ashamed;
they were experienced in the word and doctrine,
and knew that a bare convincement in the judgment and understanding,
was not sufficient to make disciples of Christ; and that unhewn stones,
as they came out of the quarry, were not fit to build God a house to dwell in;
but would rather prove a disgrace to the workman that uses them,
and a dishonour to the whole building, if made use of;
for such unskilful builders indeed, may well be ashamed of their work,
and give it over till they are better experienced.

Therefore such ought to be remembered, as have spoken unto us the word of God,
whose faith follow; considering the outcome of their conduct, Christ Jesus,
the same yesterday, today, and forever,
as Heb. 13:7-9. And that you be not carried about with diverse and strange doctrines;
for it is a good thing, that the heart be established with grace, and not with meats,
as says the apostle.

Therefore dear friends and brethren, let us all abide with God,
in the calling whereunto he has called us; and none to strive for mastery,
nor to be many masters, and to set up, as it were, for themselves,
but all to serve the full time of silence,
in order to be well experienced in the word and doctrine;
and when you are thoroughly taught of God yourselves, you will understand,
and learn of him, how to instruct others.

But let all, in the first place, learn well the doctrine of self-denial,
submitting ourselves to God in Christ Jesus.
So will every one know their place and service in the house, or church,
of the living God; where none that are really members of it,
but will submit to the laws thereof,
which are "`all holiness round about,`" and God in the midst,
judging out all stubbornness, self-will, and all that wickedness of jealousies,
evil-surmisings, whisperings, and backbitings, etc. which produce discord and divisions:
and all his little children, serving one another in love,
and the younger receiving the counsel and advice of the elder,
embracing it thankfully for God`'s glory, and their own benefit and comfort: so will all,
from the highest to the lowest,
submit one to the other in true love and godly simplicity,
for edification and preservation of the whole.
And then forgiving and forgetting all former distances;
that in the unity of the Spirit you may be all knit together by the bond of peace;
and the gates of hell shall never prevail against you,
but you shall remain a people to God`'s glory, and your own comfort:
and so you will abide in the pure religion, unspotted from the world;
manifesting plainly, that you have received a kingdom that cannot be shaken,
by all that noise and clamour that is made against you.

Which kingdom, as it came not by outward observation,
so it stands not in word or opinion, nor yet in food and drink,
but in righteousness and peace, and joy in the Holy Spirit;
and he "`that is in these things,`" says the apostle, Rom. 14:17-18.
"`serves Christ;`" such a man or woman is accepted of God,
and approved of men; having this evidence fixed to this pure religion, viz. of Father,
Son, and Spirit, and of all good men,
as being that only pure and merciful religion before God and the Father,
that the apostle James has given, as it were a short definition or description of; James 1:27.

So that whoever professes this pure religion, and abides and continues in the same,
bringing forth in his whole life and conduct the pure and holy fruits thereof,
need not be ashamed of it; for to such a one, it is not only given to believe it,
but also to suffer for the same; which has been, and is a great confirmation to many,
by that sweet power and presence of God,
that assisted them in all their afflictions and exercises, both from within and without,
and joyfully, in that needful time of great and sharp trials,
borne up their spirits to their great satisfaction and comfort,
and to the eternal praise of God`'s most holy and blessed name forever.
Amen.

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Hertford, the 26th of the Third month, 1698.

[.postscript]
====

A Postscript.

[.salutation]
Dear Friends,

Let not your outward concerns prevent your religious meetings and service on the week-days,
lest the earthly spirit get up again, and bury you before your time;
but meet in the faith that you shall meet with God,
whether you hear words spoken outwardly or not;
so by retiring into the inward and spiritual grace,
you will avoid the extremes of dead formality, and false liberty,
and witness that pure silence, wherein was felt the breast that inwardly nourished,
and those paps that gave us suck, when we were young.

When Christ ascended, he commanded his disciples to wait for power from on high,
the promise of the Holy Spirit, which, according to his promise,
fell upon them when they were met together with one accord; and the apostle,
2 Thess. 2:2, exhorts them by their gathering together in Christ.
Seeming to use their meeting together, as an argument to keep down that wicked one,
and them from that falling away he speaks of.

Therefore, dear friends and brethren, be diligent in your meetings together,
in God`'s fear and service,
and that will procure his blessing upon your diligence in your particular callings;
therefore I beseech you, stir up and exhort one another thereunto,
by the elder giving good examples to the younger sort,
who are apt to content themselves with going to meetings on the first-days only;
and then, too many, instead of waiting and exercising faith,
to meet with the teachings of the Spirit of God in their inward parts,
only exercise their outward ears in hearing what may be spoken outwardly;
which in tender love and good will to the souls of all,
I desire may be prevented for the future.
Farewell.

[.signed-section-signature]
John Crook.

====
