== Chapter 10. Testimonies of John Crook

[.blurb]
=== Edward Chester`'s Testimony concerning John Crook.

As to my dear and well beloved friend, and elder brother, John Crook, deceased,
whom I loved in the truth, and was intimately acquainted with,
in his middle age and in the beginning of Truth`'s appearance in Bedfordshire, I had,
though but young, the opportunity of often conversing with him.
He was a man of some note in that county,
being formerly justice of the peace in Bedfordshire;
and God gave him a great measure of understanding
in the administration of that part of the government,
which he was entrusted with.

And after he had received the truth, the Lord by his Spirit,
made him an able minister of the gospel;
by which he was made instrumental in turning many to God and his truth.
He had great openings, and was sound in doctrine,
and might be called a skilful marksman in our Israel, hitting the mark.

A man greatly afflicted by infirmities in his body, and also exercises in his mind;
in prison often, likewise loss of his outward estate,
greatly afflicted with the gout and cholic,
insomuch that he would compare his state to Heman`'s, being afflicted from his youth:
and under the sorrow and grief that he had with some of his offspring, he would sometime,
in a tender frame of spirit, comfort himself in the words of David;
"`Although my house be not so with God,
yet you have made with me an everlasting covenant, ordered in all things,
and sure;`" and that the Lord remembered the kindness of his youth.
I am melted in the renewed sense of the unity I had with him in spirit; whose spirit,
I believe, is now among the just ones made perfect.

He was frequent in prayer, praying for the welfare of Zion, and the prosperity of Truth,
the increase of Christ`'s kingdom, rule, and government, over the whole world:
and I do believe, he died in the faith, That truth shall prosper.

These few lines came into my heart to write,
as a testimony or commemoration of my dear and well-beloved friend,
who is recorded in my mind, from the sense that I had of him,
as a minister of the everlasting gospel, and one well accepted of the Lord,
and also of his people; and am persuaded he died a servant of the Lord.
The Lord fit us all for his service, that we may all finish our course in the same!

[.signed-section-signature]
Edward Chester.

[.signed-section-context-close]
The 29th of the Fifth month, 1700.

[.blurb]
=== Richard Thomas`'s Testimony concerning John Crook.

A testimony lives upon my heart, to give for my ancient friend and brother John Crook,
some time since deceased, on the 26th of the second month, 1699,
and near the 82nd year of his age, in the town of Hertford,
where he had lived for several years latterly;
and where he had a frequent conversation for forty years in meetings,
by testimonies to the truth, to the convincing many,
and to the refreshing and building up of others in the faith of Christ Jesus,
in this town, and the adjacent parts of this county,
of whom many are gone unto their graves, and but few of the ancient ones left after him.
And forasmuch as my intimate and familiar acquaintance with him,
has been for forty years or more, in travels sometimes formerly,
and latterly conversant with him in the time of his great affliction of body, by stone,
gout, and cholic, I have often heard him say,
that did he not feel and witness an inward power from the Lord to support him,
he could not subsist under his pains, they were so great,
which continued on him to his end.
And yet I do not remember, that I ever heard him utter an unsavoury word,
or impatiently to cry out; yet after the extremity of the fits were over,
he would express his inward joy and peace that he had from the Lord.

As to his ministry, it was very demonstrative and doctrinal,
he had an excellent gift in opening the mystery of the Holy Scriptures,
that it might be said of him, as it was of Apollos, Acts 18:24-25,
that he was an eloquent man, and mighty in the Scriptures,
and well instructed in the way of the Lord; and being fervent in the spirit,
he spoke and taught diligently the things of the Lord Jesus Christ,
as these his works and writing do in part testify.
And in former years, when he was at liberty, out of prison,
he travelled much in the publishing of the everlasting gospel;
many were convinced of his ministry in several of these adjacent counties;
and many were seals of his ministry,
and continued in the faith unto the end of their race;
though some that have owned their convincement by him, are turned aside,
and gone into the world again.

He came forth in early days,
and may well be said to be one of the ancients in spiritual Israel, in our age,
and had a share and part of the ministry, for the publishing of the blessed truth;
and also a large share of sufferings for his faithful testimony
to the spiritual appearance of Christ in this age;
several times in imprisonments, as in Aylesbury, Huntington, London, and Ipswich:
in all which he was a patient sufferer, until the Lord`'s time of deliverance.
He would sometimes say, with Heman,
"`I have been afflicted from my youth up:`" and declared what conflicts
of spirit he underwent heretofore many days and nights,
for lack of peace with the Lord: and in his youth he was,
as many others of us have been that are ancient now,
seekers of the Lord in large professions; but it was on the barren mountains and hills,
where we lacked life, as he would often say.
But after he and we came to embrace the light of Christ Jesus,
which shined into our dark hearts, we could say, from an inward sense,
that which condemned sin in us, as it was obeyed, became our justification; which,
through death, became life and peace, through Christ Jesus.
In his latter days, some time before his death, he would say,
that the furnace of afflictions was of good use,
to purge away the dross and earthly part in us: and doubtless his and our experience,
did, and can witness the same.
He would many times say unto me,
that "`many of the ancient ones were gone to their long homes,
and we are making haste after them; they step away before me, and leave me behind; and I,
that would go, cannot: well, it will be my turn soon, or quickly.`"
In which he seemed to rejoice.

This was upon my mind, and much more,
that I could say of my dear and well-beloved friend;
but not being willing to enlarge much, knowing right well,
that if there were opportunity, many Friends elsewhere in these parts of the nation,
could, with me, give an ample testimony for him, who is gone to an everlasting rest,
with the faithful, whose works follow them; which everlasting rest, that I,
and all that sincerely follow Christ Jesus, in the regeneration and newness of life,
continuing in well-doing unto the end, may attain unto, is the prayer of,

[.signed-section-signature]
Richard Thomas.

[.signed-section-context-close]
Hertford, the 9th of the Ninth month, 1700.

[.blurb]
=== George Whitehead`'s Account Concerning our Ancient Deceased Friend and Brother, John Crook.

I having had early acquaintance with him,
after his loving and tender reception of the blessed truth, as it is in Christ Jesus,
it being above forty years since we became first acquainted;
I have this account to give of him,
that after he sincerely received Truth`'s testimony of Christ Jesus,
as he is the true light professed by us, he became truly zealous for the same,
both in conduct and doctrine;
and was in times of persecution exposed to great sufferings, by several imprisonments,
for his Christian testimony; being therein freely resigned, in the will of God,
rather to suffer in person and estate, than to decline his testimony,
injure his conscience, or break his inward peace with God,
which he preferred before life, liberty, or external enjoyments.
He had regard to the power of godliness, in life and doctrine, above outward dead forms;
and to the enduring substance, above empty shadows; and to the spirit above the letter:
and yet truly and highly esteemed the Holy Scriptures,
with respect to the sacred doctrine thereof, being well read therein,
and devoted for the faith and practice thereof, as the Lord gave him understanding.

He was both eloquent, allegorical, and mysterious, many times,
in his ministry but did not thereby deny or invalidate the sacred history of things,
as literally recorded in Holy Scripture.
He laboured to promote Christian religion in life and power,
and the sincere practice of piety, above all empty and fruitless professions.

The mystery of Christ in Spirit, and as revealed and formed in true believers,
and their sincere conformity to him, in spirit and conduct, he greatly esteemed;
desiring professors of Christianity might come into the true sense and experience thereof,
by a true, living, and feeling faith in Christ, and sincere obedience to him.

And as for helps and governments in the church of Christ, 1 Cor.
xii. he did not think himself obliged to be so actually
concerned in all the methods thereof among us,
as many other faithful brethren are;
yet retained his love and affection to them who are truly helpful therein,
both faithful men and women: and therefore none ought to conceive, or excuse,
opposition or disunion, from his passiveness therein,
or tenderness toward them who might be otherwise minded in some lesser matters,
or methods relating to good order and discipline: all are not gifted,
nor spirited for government in the church of Christ, nor called thereunto;
every man is required to minister as he has received the gilt.
Nevertheless this good man was zealous against disorderly conduct, divisions,
and backsliding.

His Christianity did show itself in the spirit of meekness and humility,
and in true love to his faithful friends and brethren, their labours of love,
and gospel testimony; and greatly esteemed a sound convincing ministry,
for the turning people`'s minds from darkness to the light,
and strengthening the weak in the faith and power of Christ.

For my own part, I can sincerely say, we did tenderly love each other,
and were kindly affectioned one towards another, as Christian brethren;
and I did in spirit sympathize with him,
when he laboured under a long and sore affliction and weakness of body;
in which the Lord endowed him with much patience, in submission to his blessed will:
and though his affliction and pains were great, the Lord gave him intervals of ease,
refreshment and comfort, from his presence, to support and bear up his spirit,
until his desirable and long waited for change came.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
London, the 21st of the First month, 1701.

[.blurb]
=== Daniel Monro`'s Testimony concerning John Crook.

Having been present at reading several of John Crook`'s writings,
a fresh remembrance came before me, of the saying of Caleb, Josh. 14:11;
"`As yet I am as strong this day, as I was in the day that Moses sent me:
as my strength was then, even so is my strength now, for war, both to go out,
and to come in.`"
And I am comforted in a sense of this faithful friend,
that in his old age he was as strong for the spiritual war as ever.

[.signed-section-signature]
Daniel Monro.

[.blurb]
=== A Short Testimony concerning John Crook.
Containing also a few words spoken by him a little before his death.

It was about the year 1662,
I was first acquainted with this painful labourer in the gospel;
and from the many comfortable opportunities I had in meetings
where he was exercised in preaching the everlasting gospel,
in much tenderness, I could not but dearly love him,
as one of the instruments of God`'s glory, and of good to the souls of men,
in this latter age.

His ministry was lively and demonstrative, and plenteously opening the scriptures,
and the mysteries of life and salvation;
preaching powerfully the power and coming of our Lord Jesus Christ,
in his spiritual appearance, and work of sanctification and regeneration;
the death of the old man, and the raising of the new birth; to serve the Lord,
the Redeemer thereof, in righteousness and true holiness.

About three weeks before his death, I was at Hertford to visit him,
and though he was weak in body, yet did he powerfully declare,
after a prophetical manner, "`Truth must prosper, Truth shall prosper:
but a trying time should first come,
and afterwards the glory of the Lord should more and more appear.`"

Among other his faithful brethren, he had a reverend esteem of the coming of Christ,
and his sufferings, in the days of his flesh;
and knew well how to distinguish his great work of redemption and salvation,
as he died for all men, or was a sacrifice for sin: and also,
as he was a sanctifier and redeemer, out of sin: the fruit and benefit of the one,
being not obtained without the other.

And were our adversaries duly sensible, what great things Christ both does in us,
as well as did for us, surely they would be humbled under his mighty hand,
and leave off their slight esteem of his spiritual work in us,
and not suppose the one to be in opposition to the other.

The apostle Peter says, "`He bore our sins in his own body on the tree,
that we being dead unto sin, should live unto righteousness.`"
And how can we die unto sin, and live unto righteousness,
but by his assistance inwardly manifest in his light, grace, and Holy Spirit?

Our being born again, not of corruptible seed, but of incorruptible, by the Word of God,
which lives and abides forever, does not hinder his being made sin for us,
who knew no sin, that we may be made the righteousness of God in him.

Our owning we are sanctified by the work of his Spirit in our inward parts,
hinders not our having remission of sins in his name.

He having left us an example, that we should follow his steps,
bars him not at all from being our King and Captain of salvation:
though he is a condemner of sin in the flesh,
yet he is also our advocate with the Father, Christ Jesus the righteous.

Our owning him a sacrifice for sin, hinders not at all his being our great High Priest.

Our acknowledging, he was tempted in all points, like as we are,
does not prevent his being able to succour us, when we are tempted.

Thus our preaching him, the true light,
which enlightens every man that comes into the world,
does not divest him of any of his blessed attributes, or offices,
worthily bestowed upon him in Holy Scripture; as the Seed of the woman, the Word,
Emmanuel, Interpreter, One among a thousand, Wonderful, Counsellor, mighty God,
everlasting Father, Prince of peace, Lamb of God, Jesus, Saviour, the very Christ,
the Anointed, and many more: yes, he becomes all these to us, as we walk in his light,
who was given for a light to lighten the Gentiles,
that he might be God`'s salvation to the ends of the earth.

[.signed-section-signature]
Theodore Ecclestone.
